#ifndef BRIGPORT_H
#define BRIGPORT_H

#define MVAR_Made_Car                               (0)
#define MVAR_BPORT_BRAHMIN_LIFE                     (1)
#define MVAR_BPORT_BRAHMIN_LOCATION                 (2)
#define MVAR_BPORT_CITIZEN_LIFE                     (3)
#define MVAR_BPORT_CITIZEN_ENEMY                    (4)
#define MVAR_BPORT_BAIKER_LIFE                      (5)
#define MVAR_BPORT_BAIKER_ENEMY                     (6)
#define MVAR_BPORT_BAIKER_RUN                       (7)
#define MVAR_BPORT_DANTE_TAINIK                     (8)
#define MVAR_BPORT_DANTE_LIFE                       (9)
#define MVAR_BPORT_CITIZENBOSS_LIFE                 (10)
#define MVAR_BPORT_REPAIR_FLAG                      (11)

#endif // BRIGPORT_H