/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef DEPOLVB_H
#define DEPOLVB_H

// Header file for Map vars for Depolvb

#define MVAR_Made_Dobbs                 (0)
#define MVAR_Eyeball_Used_4             (1)
#define MVAR_Security_Level_4           (2)
#define MVAR_Field_4a                   (3)
#define MVAR_Field_4b                   (4)
#define MVAR_Field_4c                   (5)


#define FIELD_ENABLED               (0)
#define FIELD_DISABLED              (1)
#define FIELD_DAMAGED               (2)
#define FIELD_DESTROYED             (3)

#endif // DEPOLVB_H
