/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef KLARATCV_H
#define KLARATCV_H

 // Map vars for Klamath Rat Cave Map

 // Comments -currently does not use mapvars...this just copy of arroyo map vars

//MAP_GLOBAL_VARS:

//GLOBAL                                        NUMBER

// All Map Vars need to start w/ MVAR_

#define MVAR_Stealing_From_Shaman               (0)
#define MVAR_Kill_Evil_Plants                   (1)
#define MVAR_Talked_Villager                    (2)
#define MVAR_Talked_Warrior                     (3)

#endif // KLARATCV_H
