#ifndef NEVADA_REJECT_H
#define NEVADA_REJECT_H

/*****************************************************************
***************     REJECT MVAR PARAMETRS     ***************
******************************************************************/

#define MVAR_Made_Car                   (0)
#define MVAR_REJECT_SeifFlagOpen        (1)
#define MVAR_REJECT_AlcogolInfo         (2)
#define MVAR_REJECT_MutantInfo          (3)
#define MVAR_REJECT_MedicalStatus       (4)
#define MVAR_REJECT_ArsenalStatus       (5)
#define MVAR_REJECT_ArmrestlingStatus   (6)
#define MVAR_REJECT_ArmrestlingDude     (7)
#define MVAR_REJECT_BrahminStatus       (8)
#define MVAR_REJECT_ChinaStatus         (9)
#define MVAR_REJECT_BumBum              (10)
#define MVAR_REJECT_MutantCounter       (11)
#define MVAR_REJECT_BrahminAndBumKnow   (12)
#define MVAR_REJECT_BerchWater          (13)
#define MVAR_REJECT_BERCH_EXIT          (14)
#define MVAR_REJECT_REPAIR_MUZIK        (15)
#define MVAR_REJECT_REPAIR_STANOK       (16)
#define MVAR_REJECT_C4_FLAG             (17)
#define MVAR_REJECT_MutantKillDude      (18)
#define MVAR_REJECT_DYNAMIT_INFO        (19)

#define REJECT_COAST_ZEROA               0 // ничья
#define REJECT_COAST_ZEROB               1 // ничья, получен квест на перепродажу
#define REJECT_COAST_NELSON              2 // нельсона
#define REJECT_COAST_WRITE               3 // райта
#define REJECT_COAST_BERCH               4 // берча

#endif