#ifndef NEVADA_HEADCRVN_H
#define NEVADA_HEADCRVN_H

/*****************************************************************
***************       HEAD CARAVAN  LVAR Param     ***************
******************************************************************/

#define Head_Rino_Vegas                      (0)
#define Head_Salt_Vegas                      (1)
#define Head_Salt_Rino                       (2)
#define Head_Wind                            (3)

#endif