#ifndef NEWR5_H
#define NEWR5_H

#define MVAR_Oliver_Password                (1)
#define MVAR_Oliver_LowDeath                (2)
#define MVAR_Oliver_SlaverKnown             (3)
#define MVAR_Oliver_ConwoiDead              (4)
#define MVAR_Oliver_ConwoiBarter            (5)
#define MVAR_Oliver_ConwoiStart             (6)
#define MVAR_Oliver_RancoRassword           (7)
#define MVAR_Oliver_GrdsLiefCheck           (8)
#define MVAR_Oliver_OsheinikSwich           (9)
#define MVAR_Oliver_AdminUranCity           (10)
#define MVAR_Oliver_ShaiennSlave            (11)

#endif