#ifndef NEWRGO_H
#define NEWRGO_H

#define MVAR_RENO_TEATR_00               (0)
#define MVAR_RENO_LIFE_ZRITEL            (1)
#define MVAR_RENO_LIFE_KILLER            (2)
#define MVAR_RENO_EXIT_FLAG              (3)
#define MVAR_RENO_CINEMA_START           (4)
#define MVAR_RENO_START_ALL_RUN          (5)
#define MVAR_RENO_START_REPLY            (6)
#define MVAR_RENO_EXP_FINAL              (7)
#define MVAR_RENO_TEATR_08               (8)
#define MVAR_RENO_TEATR_09               (9)

#endif // NEWRGO_H