/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef REDDOWN_H
#define REDDOWN_H

#define MVAR_Fannie_Mae             (0)
#define MVAR_Widow_Rooney           (1)
#define MVAR_Made_Car               (2)
#define MVAR_Attecked_Cashier       (3)
#define MVAR_Using_Locked_Door      (4)


#define FANNIE_NONE                 (0)
#define FANNIE_CUSTOMER             (1)
#define FANNIE_MONEY_ASKED          (2)
#define FANNIE_MONEY_GIVEN          (3)
#define FANNIE_SICK                 (4)
#define FANNIE_SICKER               (5)
#define FANNIE_DEAD                 (6)

#define WIDOW_NONE                  (0)
#define WIDOW_JOB_ACCEPTED          (1)
#define WIDOW_KICKED_OUT            (2)
#define WIDOW_PAID                  (3)
#define WIDOW_KILLED                (4)

#endif // REDDOWN_H
