#define SFALL_SC_EVALUATION   (true)  // short - circuit evaluation
#define crit_fid(critter_obj)    (get_proto_data(obj_pid(critter_obj),8))
#define short_crit(critter_obj)  (crit_fid(critter_obj) == 16777313 or crit_fid(critter_obj) == 16777275 or crit_fid(critter_obj) == 16777271 or crit_fid(critter_obj) == 16777240 or crit_fid(critter_obj) == 16777268)
#define medium_crit(critter_obj) (crit_fid(critter_obj) == 16777276 or crit_fid(critter_obj) == 16777232 or crit_fid(critter_obj) == 16777283 or crit_fid(critter_obj) == 16777291 or crit_fid(critter_obj) == 16777243 or crit_fid(critter_obj) == 16777336 or crit_fid(critter_obj) == 16777270)
#define ShootThru(obj)   ((get_flags(obj) bwand FLAG_SHOOTTHRU) or (obj_type(obj) == OBJ_TYPE_CRITTER))
#define CRITICAL_MISS          0
#define MISS                   1
#define HIT                    2
#define CRITICAL_HIT           3

#include "define_extra.h"
#include "DEFINE.H"
#include "sfall.h"
#include "ARTFID.H"


procedure start;
procedure misstohit;
procedure explosiveinjures;
procedure SwingThrust;
procedure LOS_is_blocked(variable watcher_obj , variable target_obj1 );
procedure real_rotation_to_tile(variable begin_tile, variable dest_tile);

variable MissMod;
variable BodyRndHit;
variable CrippleMod;
variable SwingThrustTweak;
variable tardt;
variable tardr;
variable thrusthit;
variable weapon;
variable RLcrip;
variable LLcrip;
variable RAcrip;
variable LAcrip;
variable Icrip;
variable CripDiv;
variable missed;
variable newtarget;
variable first_target_dist;
variable burst;
variable grenade;

export variable exp_drop_wpn;

procedure start begin
   if game_loaded then begin
      MissMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|MissToHit");
      BodyRndHit = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Miss|BodyRndHit");
      CrippleMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|CripplingExplosions");
      SwingThrustTweak = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|SwingThrust");
      if MissMod != 0 or BodyRndHit != 0 or CrippleMod != 0 or SwingThrustTweak != 0 then begin
         RLcrip = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|RLcrip");
         LLcrip = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|LLcrip");
         RAcrip = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|RLcrip");
         LAcrip = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|LLcrip");
         Icrip = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|LLcrip");
         CripDiv = get_ini_setting("mods\\F2MechanicsMiniRework.ini|CripplingExplosions|CripDiv");
         register_hook_proc_spec(HOOK_COMBATDAMAGE, explosiveinjures);
         register_hook_proc_spec(HOOK_AFTERHITROLL, misstohit);
         if SwingThrustTweak then register_hook_proc_spec(HOOK_TOHIT, SwingThrust);
      end
      set_global_script_type(0);
      set_global_script_repeat(0);
   end
end

//Checking Line of Sight is(not) blocked, taking into account the value of ddraw.ini "ObjCanSeeObj_ShootThru_Fix"
procedure LOS_is_blocked(variable watcher_obj ,variable target_obj1 ) begin
   variable blocking_obj;
   variable last_blocking_obj;
   variable count = 0;
   variable ddraw_ShootThru_Fix = 1;
   if obj_type(watcher_obj) == OBJ_TYPE_CRITTER andAlso obj_type(target_obj1) == OBJ_TYPE_CRITTER andAlso get_critter_stat(watcher_obj,STAT_current_hp) > 0 andAlso get_critter_stat(target_obj1,STAT_current_hp) > 0 then begin
      if ddraw_ShootThru_Fix == 0 then begin
         blocking_obj = obj_blocking_line(watcher_obj, tile_num(target_obj1), BLOCKING_TYPE_BLOCK);
      end
      if ddraw_ShootThru_Fix == 1 then begin
         blocking_obj = obj_blocking_line(watcher_obj, tile_num(target_obj1), BLOCKING_TYPE_BLOCK);
      end
      if blocking_obj == target_obj1 then begin
         return false;
      end
      if blocking_obj andAlso not(ShootThru(blocking_obj)) then begin
         return true;
      end
      if ddraw_ShootThru_Fix == 0 andAlso blocking_obj != target_obj1 then begin
         return true;
      end
      if blocking_obj andAlso blocking_obj != target_obj1 andAlso ShootThru(blocking_obj) then begin
         while blocking_obj andAlso blocking_obj != target_obj1 andAlso ShootThru(blocking_obj) do begin
            if watcher_obj == blocking_obj then begin
               return true;
            end
            if ddraw_ShootThru_Fix == 0 then begin
               blocking_obj = obj_blocking_line(blocking_obj, tile_num(target_obj1), BLOCKING_TYPE_BLOCK);
               return true;
            end
            if ddraw_ShootThru_Fix == 1 then begin
               last_blocking_obj = blocking_obj;
               blocking_obj = obj_blocking_line(blocking_obj, tile_num(target_obj1), BLOCKING_TYPE_BLOCK);
               if tile_num(last_blocking_obj) == tile_num(blocking_obj) then begin
                  return true;
               end
               if blocking_obj andAlso not(ShootThru(blocking_obj)) then begin
                  return true;
               end
               if blocking_obj == target_obj1 then begin
                  return false;
               end
            end
            count += 1;
            if count > 24 then begin //exit from loop if it is looped due to the fact that more than 2 NPCs stand in the same tile
               return true;
            end
         end
      end
   end
end

//by JimTheDinosaur https://nma-fallout.com/threads/stuff-for-define_extra-h.202989/page-2
procedure real_rotation_to_tile(variable begin_tile, variable dest_tile) begin
  	variable temp_dist = tile_distance(begin_tile, dest_tile);
  	variable temp_rot = rotation_to_tile(begin_tile, dest_tile);
  	if temp_rot == 4 then begin
  	   if tile_distance(tile_num_in_direction(begin_tile, temp_rot, temp_dist), dest_tile) > tile_distance(tile_num_in_direction(begin_tile, 5, temp_dist), dest_tile) then
  	      temp_rot = 5;
  	   else if tile_distance(tile_num_in_direction(begin_tile, temp_rot, temp_dist), dest_tile) > tile_distance(tile_num_in_direction(begin_tile, 3, temp_dist), dest_tile) then
  	      temp_rot = 3;
  	   end
  	   else if temp_rot == 1 then begin
  	   if tile_distance(tile_num_in_direction(begin_tile, temp_rot, temp_dist), dest_tile) > tile_distance(tile_num_in_direction(begin_tile, 0, temp_dist), dest_tile) then
  	      temp_rot = 0;
  	   else if tile_distance(tile_num_in_direction(begin_tile, temp_rot, temp_dist), dest_tile) > tile_distance(tile_num_in_direction(begin_tile, 2, temp_dist), dest_tile) then
  	      temp_rot = 2;
  	end
  	return temp_rot;
end

procedure SwingThrust begin
   variable hitcap = get_sfall_arg;
   variable atkr = get_sfall_arg;
   variable tar = get_sfall_arg;
   variable bpart = get_sfall_arg;
   variable Sourcetile = get_sfall_arg;
   variable Atktype = get_sfall_arg;
   variable rngflag = get_sfall_arg;
   variable hitch = get_sfall_arg;
   variable wpn_flags;
   variable leftHand_obj = critter_inven_obj(atkr, INVEN_TYPE_LEFT_HAND);
   variable rightHand_obj = critter_inven_obj(atkr, INVEN_TYPE_RIGHT_HAND);
   variable leftHand;
   variable rightHand;
   variable wpn = 0;
   variable wpnanim = 0;
   variable swing = 0;
   variable thrust = 0;
   variable atkrskill = has_skill(atkr, SKILL_MELEE);
   variable tarAg;
   variable Newhitch = 0;
   //if obj_type(tar) == OBJ_TYPE_CRITTER then begin
      tarAg = get_critter_stat(tar, STAT_ag);
   //end
   if leftHand_obj then begin
      leftHand = obj_pid(leftHand_obj);
   end
   if rightHand_obj then begin
      rightHand = obj_pid(rightHand_obj);
   end
   if SwingThrustTweak != 0 andAlso (leftHand_obj or rightHand_obj) then begin
         if Atktype == ATKTYPE_LWEP1 andAlso leftHand_obj then begin // left hand first attack mode
         wpn = leftHand;
         wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
            if (wpn_flags bwand ATKMODE_PRI_SWING) == 3 then begin
               swing = 1;
            end
            if (wpn_flags bwand ATKMODE_PRI_THRUST) == 4 then begin
               thrust = 1;
            end
         end
         if Atktype ==  ATKTYPE_LWEP2 andAlso leftHand_obj  then begin // left hand second attack mode
         wpn = leftHand;
         wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
            if (wpn_flags bwand ATKMODE_SEC_SWING) == 48 then begin
               swing = 1;
            end
            if (wpn_flags bwand ATKMODE_SEC_THRUST) == 64 then begin
               thrust = 1;
            end
         end
         if Atktype ==  ATKTYPE_RWEP1 andAlso rightHand_obj then begin // right hand first attack mode
         wpn = rightHand;
         wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
            if (wpn_flags bwand ATKMODE_PRI_SWING) == 3 then begin
               swing = 1;
            end
            if (wpn_flags bwand ATKMODE_PRI_THRUST) == 4 then begin
               thrust = 1;
            end
         end
         if Atktype ==  ATKTYPE_RWEP2 andAlso rightHand_obj  then begin // right hand second attack mode
         wpn = rightHand;
         wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
            if (wpn_flags bwand ATKMODE_SEC_SWING) == 48 then begin
               swing = 1;
            end
            if (wpn_flags bwand ATKMODE_SEC_THRUST) == 64 then begin
               thrust = 1;
            end
         end
         if wpn > 0 then wpnanim = get_proto_data(wpn, 36);
      //New effect for swing and thust attacks
      if swing == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpn == 522)  then begin // Wakizashi use unique animation so "wpn == 522"
      Newhitch = hitch + tarAg + (atkrskill / 15); // increas hit chance
      if Newhitch > 95 then begin
         Newhitch = 95;
      end
         set_sfall_return(Newhitch);
         set_sfall_arg(0, Newhitch);
      end
      if thrust == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpn == 522) then begin
      end
   end
end

procedure explosiveinjures begin
   variable target = get_sfall_arg;
   variable attacker = get_sfall_arg;
   variable dmgtotar = get_sfall_arg;
   variable dmgtoatkr = get_sfall_arg;
   variable flagfortar = get_sfall_arg;
   variable flagforatkr = get_sfall_arg;
   variable weapon = get_sfall_arg;
   variable bpart = get_sfall_arg;
   variable dmgmult = get_sfall_arg;
   variable bullets = get_sfall_arg;
   variable knockback = get_sfall_arg;
   variable atktype = get_sfall_arg;
   variable c_atk = get_sfall_arg;
   variable wpn_flags;
   variable attacker_melee_dmg = get_critter_stat(attacker, STAT_melee_dmg);
   variable target_type = OBJ_TYPE_CRITTER;
   variable target_pid;
   variable expldmg = 0;
   variable rnd = 0;
   variable wpnpid;
   variable wpnanim = 0;
   variable wpnmaxdmg;
   variable bonusdmg = 0;
   variable newdmg = 0;
   variable swing = 0;
   variable thrust = 0;
   variable wpn_dmg_type = 0;
   variable critter_type;
   variable attaker_type = metarule(METARULE_CRITTER_KILL_TYPE, attacker);
   variable target_curhp = 1;
   variable attacker_curhp = 1;
   variable attacker_en = 0;
   variable attacker_st = 0;
   variable attacker_pe = 0;
   variable target_en = 0;
   variable target_st = 0;
   variable target_pe = 0;
   variable party = party_member_list(0);
   variable target_in_party = is_in_array(target, party);
   variable attacker_in_party = is_in_array(attacker, party);
   variable player_mult = 1;
   variable combat_diff = combat_difficulty;
   variable new_target_dist = -2;
   if weapon > 0 then begin
      wpn_dmg_type = metarule(METARULE_W_DAMAGE_TYPE, weapon);
      wpnpid = obj_pid(weapon);
   end
   if MissMod != 0 then begin
      distance_objs(new_target_dist, target, attacker);
      //disable the original miss mechanic
      rnd = random(0, 5);
      if rnd != 0 andAlso newtarget == 0 andAlso burst == 0 andAlso grenade == 0 andAlso first_target_dist <= new_target_dist andAlso wpn_dmg_type == DMG_normal_dam andAlso missed == MISS then begin
         set_sfall_return(0);
         set_sfall_arg(2, 0);
         set_sfall_return(0);
         set_sfall_arg(3, 0);
         set_sfall_return(0);
         set_sfall_arg(4, 0);
         set_sfall_return(0);
         set_sfall_arg(5, 0);
         missed = -1;
      end
   end
   if target_type == OBJ_TYPE_CRITTER then begin
      critter_type = metarule(METARULE_CRITTER_KILL_TYPE, target);
      target_pid = obj_pid(target);
   end
    //swingThrust
   if SwingThrustTweak != 0 andAlso wpnpid != 0 andAlso target_type == OBJ_TYPE_CRITTER then begin
      wpnmaxdmg = get_proto_data(wpnpid, PROTO_WP_DMG_MAX);
      wpn_flags = get_proto_data(wpnpid, PROTO_FLAG_EXT);
      wpnanim = get_proto_data(wpnpid, PROTO_WP_ANIM);
      if Atktype == ATKTYPE_LWEP1 then begin // left first attack mode
         if (wpn_flags bwand ATKMODE_PRI_SWING  ) == 3 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THRUST  ) == 4 then begin
            thrust = 1;
         end
      end
      if Atktype ==  ATKTYPE_LWEP2 then begin // left second attack mode
         if (wpn_flags bwand ATKMODE_SEC_SWING  ) == 48 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THRUST  ) == 64 then begin
            thrust = 1;
         end
      end
      if Atktype ==  ATKTYPE_RWEP1 then begin // right 1 attack
         if (wpn_flags bwand ATKMODE_PRI_SWING  ) == 3 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THRUST  ) == 4 then begin
            thrust = 1;
         end
      end
      if Atktype ==  ATKTYPE_RWEP2 then begin // right 2 attack
         if (wpn_flags bwand ATKMODE_SEC_SWING  ) == 48 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THRUST  ) == 64 then begin
            thrust = 1;
         end
      end

      //New effect for swing and thust attacks
      if swing == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpnpid == 522) then begin
      tardt = get_proto_data(target_pid, 244);
         if tardt < 2 then begin // more likely to deal maximum damage when attacking lowarmored target
            bonusdmg = (random(23, 30) * 4.0 / 100);
            newdmg = ceil(dmgtotar * bonusdmg + 1);
            if newdmg > (wpnmaxdmg + attacker_melee_dmg) then begin
               newdmg = (wpnmaxdmg + attacker_melee_dmg);
            end
            set_sfall_return(newdmg);
            set_sfall_arg(0, newdmg);
         end
      end
      if thrust == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpnpid == 522) then begin
         if thrusthit == 1 then begin // return norman dr|dt values
            set_proto_data(target_pid, 244, tardt);
            set_proto_data(target_pid, 272, tardr);
         end
      end
   end

//chance to cripple limbs with explosion
   if CrippleMod != 0 then begin // mod activation
   if target_type == OBJ_TYPE_CRITTER then begin
      target_curhp = get_critter_stat(target, STAT_current_hp);
      target_en = get_critter_stat(target, STAT_en);
      target_st = get_critter_stat(target, STAT_st);
      target_pe = get_critter_stat(target, STAT_pe);
   end
   if target_in_party or target == dude_obj then begin
      player_mult = CripDiv;
   if combat_diff == 0 then player_mult = CripDiv * 3;
   end
      attacker_curhp = get_critter_stat(attacker, STAT_current_hp);
      attacker_en = get_critter_stat(attacker, STAT_en);
      attacker_st = get_critter_stat(attacker, STAT_st);
      attacker_pe = get_critter_stat(attacker, STAT_pe);
      exp_drop_wpn = 0;
      if weapon != 0 andAlso target_type == OBJ_TYPE_CRITTER then begin
         // cripple for non robot target

         if player_mult > 0 andAlso dmgtotar > (target_curhp / 6) andAlso (wpn_dmg_type == DMG_explosion or wpnpid == 26) andAlso wpnpid != 159  andAlso critter_type != 10 then begin
            rnd = random(0, ((60 + target_en * 4) * player_mult ));
            if rnd < RLcrip then begin
               critter_injure(target, DAM_CRIP_LEG_RIGHT);
            end
            rnd = random(0, ((60 + target_en * 4) * player_mult ));
            if rnd < LLcrip then begin
               critter_injure(target, DAM_CRIP_LEG_LEFT);
            end
            rnd = random(0, ((60 + target_st * 3) * player_mult ));
            if rnd < RAcrip then begin
               critter_injure(target, DAM_CRIP_ARM_RIGHT);
            exp_drop_wpn = BODY_HIT_RIGHT_ARM;
            end
            rnd = random(0, ((60 + target_st * 4) * player_mult ));
            if rnd < LAcrip then begin
               critter_injure(target, DAM_CRIP_ARM_LEFT);
            exp_drop_wpn = BODY_HIT_LEFT_ARM;
            end
            rnd = random(0, ((60 + target_pe * 4) * player_mult ));
            if rnd < Icrip then begin
               critter_injure(target, DAM_BLIND);
            end
         end
         // criple for robot target
         if ((dmgtotar > (target_curhp / 10) andAlso wpn_dmg_type == DMG_emp) or (dmgtotar > (target_curhp / 3) andAlso (wpn_dmg_type == DMG_explosion))) andAlso critter_type == 10 then begin
            rnd = random(0, ((60 + target_en * 4) * player_mult ));
            if rnd < RLcrip then begin
               critter_injure(target, DAM_CRIP_LEG_RIGHT);
            end
            rnd = random(0, ((60 + target_en * 4) * player_mult ));
            if rnd < LLcrip then begin
               critter_injure(target, DAM_CRIP_LEG_LEFT);
            end
            rnd = random(0, ((60 + target_st * 4) * player_mult ));
            if rnd < RAcrip then begin
               critter_injure(target, DAM_CRIP_ARM_RIGHT);
               exp_drop_wpn = BODY_HIT_RIGHT_ARM;
            end
            rnd = random(0, ((60 + target_st * 4) * player_mult ));
            if rnd < LAcrip then begin
               critter_injure(target, DAM_CRIP_ARM_LEFT);
               exp_drop_wpn = BODY_HIT_LEFT_ARM;
            end
            rnd = random(0, ((60 + target_pe * 4) * player_mult ));
            if rnd < (1 + Icrip)  then begin
               critter_injure(target, DAM_BLIND);
            end
         end
      end
   player_mult = 1;
   if attacker_in_party or attacker == dude_obj then begin
      player_mult = CripDiv;
   if combat_diff == 0 then player_mult = CripDiv * 3;
   end
   // criple for non robot attacker
      if player_mult > 0 andAlso weapon != 0 andAlso (not(attacker_in_party) andAlso attacker != dude_obj or combat_diff > 0 ) then begin
         if dmgtoatkr > (attacker_curhp / 6) andAlso (wpn_dmg_type == DMG_explosion or wpnpid == 26) andAlso wpnpid != 159 andAlso attaker_type != 10 then begin
            rnd = random(0, ((60 + attacker_en * 4) * player_mult ));
            if rnd < RLcrip then begin
               critter_injure(attacker, DAM_CRIP_LEG_RIGHT);
            end
            rnd = random(0, ((60 + attacker_en * 4) * player_mult ));
            if rnd < LLcrip then begin
               critter_injure(attacker, DAM_CRIP_LEG_LEFT);
            end
            rnd = random(0, ((60 + attacker_st * 4) * player_mult ));
            if rnd < RAcrip then begin
               critter_injure(attacker, DAM_CRIP_ARM_RIGHT);
            end
            rnd = random(0, ((60 + attacker_st * 4) * player_mult ));
            if rnd < LAcrip then begin
               critter_injure(attacker, DAM_CRIP_ARM_LEFT);
            end
            rnd = random(0, ((60 + attacker_pe * 4) * player_mult ));
            if rnd < Icrip then begin
               critter_injure(attacker, DAM_BLIND);
            end
         end
   // criple for robot attacker
         if ((dmgtoatkr > (attacker_curhp / 10) andAlso wpn_dmg_type == DMG_emp) or (dmgtoatkr > (attacker_curhp / 3) andAlso (wpn_dmg_type == DMG_explosion))) andAlso attaker_type == 10 then begin
            rnd = random(0, ((60 + attacker_en * 4) * player_mult ));
            if rnd < RLcrip then begin
            critter_injure(attacker, DAM_CRIP_LEG_RIGHT);
            end
            rnd = random(0, ((60 + attacker_en * 4) * player_mult ));
            if rnd < LLcrip then begin
            critter_injure(attacker, DAM_CRIP_LEG_LEFT);
            end
            rnd = random(0, ((60 + attacker_st * 4) * player_mult ));
            if rnd < RAcrip then begin
            critter_injure(attacker, DAM_CRIP_ARM_RIGHT);
            end
            rnd = random(0, ((60 + attacker_st * 4) * player_mult ));
            if rnd < LAcrip then begin
            critter_injure(attacker, DAM_CRIP_ARM_LEFT);
            end
            rnd = random(0, ((60 + attacker_pe * 4) * player_mult ));
            if rnd < (1 + Icrip) then begin
            critter_injure(attacker, DAM_BLIND);
            end
         end
      end
   end
end

procedure misstohit begin
   variable hitmiss = 0;
   variable attacker = 0;
   variable target = 0;
   variable bpart = 0;
   variable hitch = 0;
   variable rnd = 0;
   variable rnd2 = 0;
   variable rnd3 = 0;
   variable rotationatkr = -1;
   variable oldrotationatkr = -1;
   variable rotationtar = -1;
   variable rotationnewtar = -1;
   variable critter = 0;
   variable distance1 = 0;
   variable distance2 = 0;
   variable distance3 = 0;
   variable distance4 = 0;
   variable distance5 = 0;
   variable distance6 = 0;
   variable distance7 = 0;
   variable distance8 = 0;
   variable distance9 = 0;
   variable distance10 = 0;
   variable distance11 = 0;
   variable distance12 = 0;
   variable losblock1 = 0;
   variable losblock2 = 0;
   variable losblock3 = 0;
   variable losblock4 = 0;
   variable losblock5 = 0;
   variable losblock6 = 0;
   variable losblockhit = 0;
   variable leftHand_obj = 0;
   variable rightHand_obj = 0;
   variable leftHand = 0;
   variable rightHand = 0;
   variable wpn = 0;
   variable wpnanim = 0;
   variable wpn_flags = 0;
   variable wpnrng = 0;
   //variable burst = 0;
   //variable grenade = 0;
   variable swing = 0;
   variable thrust = 0;
   variable shortcritfrm = 0;
   variable rndarm = 0;
   variable rndleg = 0;
   variable newtardt = 0;
   variable newtardr = 0;
   variable critter_type = -1;
   variable tar_cur_frm = 0;
   variable attacker_meleedmg = 0;
   variable wpn_maxdmg = 0;
   variable tar_fid = 0;
   variable atk_mode;
   variable combat_diff = combat_difficulty;
   burst = 0;
   grenade = 0;
   if MissMod != 0 or SwingThrustTweak != 0 then begin
      newtarget = 0;
      missed = -1;
      hitmiss = get_sfall_arg;
      attacker = get_sfall_arg;
      target = get_sfall_arg;
      bpart = get_sfall_arg;
      hitch = get_sfall_arg;
      leftHand_obj = critter_inven_obj(attacker, INVEN_TYPE_LEFT_HAND);
      rightHand_obj = critter_inven_obj(attacker, INVEN_TYPE_RIGHT_HAND);
      if leftHand_obj then leftHand = obj_pid(leftHand_obj);
      if rightHand_obj then rightHand = obj_pid(rightHand_obj);
      rotationatkr = real_rotation_to_tile(tile_num(attacker), tile_num(target));
      oldrotationatkr = rotation_to_tile(tile_num(attacker), tile_num(target));
      rotationtar = has_trait(TRAIT_OBJECT, target, OBJECT_CUR_ROT);
      rndarm = random(BODY_HIT_LEFT_ARM, BODY_HIT_RIGHT_ARM);
      rndleg = random(BODY_HIT_RIGHT_LEG, BODY_HIT_LEFT_LEG);
      distance_objs(distance1, target, attacker);
      first_target_dist = distance1;
      critter_type = metarule(METARULE_CRITTER_KILL_TYPE, target);
      tar_cur_frm = get_object_data(target, OBJ_DATA_CUR_FRM);
      tar_fid = crit_fid(target);
      atk_mode = get_object_data(combat_data, C_ATTACK_HIT_MODE);
   //determining the type of attack
      if leftHand_obj andAlso atk_mode == ATKTYPE_LWEP1 then begin // left first attack mode range
      wpnrng = get_proto_data(leftHand, PROTO_WP_RANGE_1);
      wpn = leftHand;
      wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
         if (wpn_flags bwand ATKMODE_PRI_BURST ) == 7 or (wpn_flags bwand ATKMODE_PRI_FLAME ) == 8  then begin
           burst = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THROW  ) == 5 andAlso burst == 0 andAlso (get_proto_data(wpn, PROTO_WP_DMG_TYPE) != DMG_normal_dam) then begin
           grenade = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_SWING  ) == 3 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THRUST  ) == 4 then begin
            thrust = 1;
         end
      end

      if leftHand_obj andAlso atk_mode == ATKTYPE_LWEP2 then begin // left second attack mode range
      wpnrng = get_proto_data(leftHand, PROTO_WP_RANGE_2);
      wpn = leftHand;
      wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
         if (wpn_flags bwand ATKMODE_SEC_BURST ) == 112 or (wpn_flags bwand ATKMODE_SEC_FLAME ) == 128 then begin
           burst = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THROW  ) == 80 andAlso burst == 0 andAlso (get_proto_data(wpn, PROTO_WP_DMG_TYPE) != DMG_normal_dam) then begin
           grenade = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_SWING  ) == 48 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THRUST  ) == 64 then begin
            thrust = 1;
         end
      end

      if rightHand_obj andAlso atk_mode == ATKTYPE_RWEP1 then begin // right 1 attack range
      wpnrng = get_proto_data(rightHand, PROTO_WP_RANGE_1);
      wpn = rightHand;
      wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
         if (wpn_flags bwand ATKMODE_PRI_BURST ) == 7 or (wpn_flags bwand ATKMODE_PRI_FLAME ) == 8  then begin
           burst = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THROW  ) == 5 andAlso burst == 0 andAlso (get_proto_data(wpn, PROTO_WP_DMG_TYPE) != DMG_normal_dam) then begin
           grenade = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_SWING  ) == 3 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_PRI_THRUST  ) == 4 then begin
            thrust = 1;
         end
      end

      if rightHand_obj andAlso atk_mode == ATKTYPE_RWEP2 then begin // right 2 attack range
      wpnrng = get_proto_data(rightHand, PROTO_WP_RANGE_2);
      wpn = rightHand;
      wpn_flags = get_proto_data(wpn, PROTO_FLAG_EXT);
         if (wpn_flags bwand ATKMODE_SEC_BURST ) == 112 or (wpn_flags bwand ATKMODE_SEC_FLAME ) == 128 then begin
           burst = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THROW  ) == 80 andAlso burst == 0 andAlso (get_proto_data(wpn, PROTO_WP_DMG_TYPE) != DMG_normal_dam) then begin
           grenade = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_SWING  ) == 48 then begin
            swing = 1;
         end
         if (wpn_flags bwand ATKMODE_SEC_THRUST  ) == 64 then begin
            thrust = 1;
         end
      end
      if wpn != 0 then wpnanim = get_proto_data(wpn, PROTO_WP_ANIM);
   end

      //New effect for swing and thust attacks
   if SwingThrustTweak != 0 andAlso wpn != 0 then begin
      if swing == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpn == 522) then begin
      end
      if thrust == 1 andAlso (wpnanim == WPN_ANIM_KNIFE or wpn == 522) then begin
         thrusthit = 0;
         if hitmiss > MISS then begin
         wpn_maxdmg = get_proto_data(wpn, PROTO_WP_DMG_MAX);
         thrusthit = 1;
         tardt = get_proto_data(obj_pid(target), 244);
         tardr = get_proto_data(obj_pid(target), 272);
         attacker_meleedmg = get_critter_stat(attacker, STAT_melee_dmg);
         newtardt = tardt - ceil((wpn_maxdmg + attacker_meleedmg) / 8);
         newtardr = tardr - 2 - ceil((wpn_maxdmg + attacker_meleedmg) / 3);
         set_proto_data(obj_pid(target), 244, newtardt);
         set_proto_data(obj_pid(target), 272, newtardr);
            if hitmiss == CRITICAL_HIT andAlso random (0, 98) < (get_critter_stat(attacker, STAT_crit_chance) / 2) then begin
            set_sfall_return(CRITICAL_HIT); //  critical hit
            set_sfall_arg(0, CRITICAL_HIT);
            return;
            end
         end
      end
   end

   if MissMod != 0 then begin
// new targets for missed attacks
      if hitmiss == MISS andAlso wpnrng > 1 andAlso grenade == 0 then begin
         //new targets for miss on low range with spear-like weapons
         if distance1 < 2 and wpnrng < 3 then begin
            foreach (critter in objects_in_radius(tile_num(target),1,elevation(target),OBJ_TYPE_CRITTER)) begin
               if get_critter_stat(critter, STAT_current_hp) > 0 andAlso critter != attacker andalso critter != target then begin
               distance_objs(distance3, critter, attacker);
                  if (oldrotationatkr == rotation_to_tile(tile_num(attacker), tile_num(critter))) andalso distance3 < 2 andAlso (tile_num(critter) == tile_num_in_direction(tile_num(attacker), rotationatkr, 1) or tile_num(critter) == tile_num_in_direction(tile_num(attacker), rotationatkr, 2)) andAlso ( tile_num(critter) == tile_num_in_direction(tile_num(target), rotationatkr, 1) or tile_num(critter) == tile_num_in_direction(tile_num(target), ((rotationatkr + 3) % 6), 1) ) andAlso not(LOS_is_blocked(attacker,critter)) then begin
                     rnd = random(0, 100);
                     if rnd < 20 then begin
                     set_sfall_return(HIT); //  hit
                     set_sfall_arg(0, HIT);
                     set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                     set_sfall_arg(3, BODY_UNCALLED);
                     set_sfall_return(critter); // new target
                     set_sfall_arg(2, critter);
                     newtarget = 1;
                     return;
                     end
                  end
               end
            end
         end
         //new targets for miss with medium and low range
         if wpnrng > 2 then begin
            foreach (critter in list_as_array(0)) begin
               if get_critter_stat(critter, STAT_current_hp) > 0 andAlso critter != attacker andalso critter != target andAlso oldrotationatkr == rotation_to_tile(tile_num(attacker), tile_num(critter))  andAlso not(LOS_is_blocked(attacker,critter))  then begin
               distance_objs(distance2, critter, target);
               distance_objs(distance3, critter, attacker);
               distance4 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 2)));
               distance5 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 4)));
               distance6 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 6)));
               distance7 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 8)));
               distance8 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 10)));
               distance9 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 12)));
               distance10 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 14)));
               distance11 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 16)));
               distance12 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 18)));
               rotationnewtar = real_rotation_to_tile(tile_num(attacker), tile_num(critter));
               losblock1 = obj_blocking_line(attacker, tile_num(target), BLOCKING_TYPE_SHOOT);
               if losblock1 then losblock2 = obj_blocking_line(losblock1, tile_num(target), BLOCKING_TYPE_SHOOT);
               if losblock2 then losblock3 = obj_blocking_line(losblock2, tile_num(target), BLOCKING_TYPE_SHOOT);
               if losblock3 then losblock4 = obj_blocking_line(losblock3, tile_num(target), BLOCKING_TYPE_SHOOT);
               if losblock4 then losblock5 = obj_blocking_line(losblock4, tile_num(target), BLOCKING_TYPE_SHOOT);
               if losblock5 then losblock6 = obj_blocking_line(losblock5, tile_num(target), BLOCKING_TYPE_SHOOT);
               if distance3 > 1 andAlso distance3 < wpnrng + 2 then begin
                     if tile_distance_objs(critter, target) == 1 then begin
                     rnd = random(0, 100);
                     if ((hitch > 4 andAlso rnd < 20) or (hitch < 5 andAlso rnd < 2)) andAlso distance2 < 1  then begin
                     set_sfall_return(HIT); //  hit
                     set_sfall_arg(0, HIT);
                     set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                     set_sfall_arg(3, BODY_UNCALLED);
                     set_sfall_return(critter); // new target
                     set_sfall_arg(2, critter);
                     newtarget = 1;
                     return;
                     end
                  end
               end
               //new targets for missed hit if original target is blocked by critter
               if losblock1 then begin
                  rnd = random(0, 100);
                  if losblock1 == critter andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 15) or (hitch < 17 andAlso rnd < 8)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock1); // new target == blocking critter1
                  set_sfall_arg(2, losblock1);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end

                  rnd = random(0, 100);
                  if losblock2 == critter andAlso losblock1 != losblock2 andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 15) or (hitch < 17 andAlso rnd < 8)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock2); // new target == blocking critter2
                  set_sfall_arg(2, losblock2);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end

                  rnd = random(0, 100);
                  if losblock3 == critter andAlso losblock2 != losblock3 andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 15) or (hitch < 17 andAlso rnd < 8)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock3); // new target == blocking critter3
                  set_sfall_arg(2, losblock3);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end

                  rnd = random(0, 100);
                  if losblock4 == critter andAlso losblock3 != losblock4 andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 15) or (hitch < 17 andAlso rnd < 8)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock4); // new target == blocking critter4
                  set_sfall_arg(2, losblock4);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end

                  rnd = random(0, 100);
                  if losblock5 == critter andAlso losblock4 != losblock5 andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 10) or (hitch < 17 andAlso rnd < 2)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock5); // new target == blocking critter5
                  set_sfall_arg(2, losblock5);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end

                  rnd = random(0, 100);
                  if losblock6 == critter andAlso losblock5 != losblock6 andAlso critter != target andAlso ((hitch > 16 andAlso rnd < 15) or (hitch < 17 andAlso rnd < 8)) andAlso losblockhit != 1 then begin
                  set_sfall_return(HIT); //  hit
                  set_sfall_arg(0, HIT);
                  set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                  set_sfall_arg(3, BODY_UNCALLED);
                  set_sfall_return(losblock6); // new target == blocking critter6
                  set_sfall_arg(2, losblock6);
                  losblockhit = 1;
                  newtarget = 1;
                  return;
                  end
               end
            end
            end
         end
         //new targets for missed hit on medium and long range
         if wpnrng > 2 andAlso newtarget == 0 then begin
            foreach (critter in list_as_array(0)) begin
               if get_critter_stat(critter, STAT_current_hp) > 0 andAlso critter != attacker andalso critter != target andAlso oldrotationatkr == rotation_to_tile(tile_num(attacker), tile_num(critter)) andAlso not(LOS_is_blocked(attacker,critter)) then begin
               distance_objs(distance2, critter, target);
               distance_objs(distance3, critter, attacker);
               distance4 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 2)));
               distance5 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 4)));
               distance6 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 6)));
               distance7 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 8)));
               distance8 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 10)));
               distance9 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 12)));
               distance10 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 14)));
               distance11 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 16)));
               distance12 = tile_distance(tile_num(critter), (tile_num_in_direction(tile_num(target), rotationatkr, 18)));
               rotationnewtar = real_rotation_to_tile(tile_num(attacker), tile_num(critter));
                  if distance1 > 5 andAlso distance3 < wpnrng + 2 then begin
                     if  oldrotationatkr == rotation_to_tile(tile_num(attacker), tile_num(critter))  andAlso (distance3 < wpnrng + 1) andAlso ( ( distance2 > 0 andAlso (distance4 < 3 or distance5 < 3 or distance5 < 3 or distance7 < 3 or distance8 < 4 or distance9 < 4 or distance10 < 5 or distance11 < 5 or distance12 < 5)) )  then begin
                     rnd = random(0, 100);
                        if rnd < 19 andAlso oldrotationatkr == rotation_to_tile(tile_num(attacker), tile_num(critter)) then begin
                           set_sfall_return(HIT); //  hit
                           set_sfall_arg(0, HIT);
                           set_sfall_return(BODY_UNCALLED); // new bodypart 8 - torso_uncalled
                           set_sfall_arg(3, BODY_UNCALLED);
                           set_sfall_return(critter); // new target
                           set_sfall_arg(2, critter);
                           newtarget = 1;
                           return;
                        end
                     end
                  end
               end
            end
         end
         losblockhit = 0;
      end

// humans,ghouls,supermutants/radscop/ Horrigan  conversion of aimed hits in eye/groin in critter's back into head/ torso+legs hits
      if critter_type < 5 or critter_type == 6 or critter_type > 17 then begin // (kill type 0 - 4) = humans, ghouls, supermutants / 6=radscop / > 18= Horrigan and maybe player(38 or 38)
            if hitmiss > MISS andAlso tile_distance_objs(target, attacker) != 0 andAlso ((tar_cur_frm == 4 andAlso tar_fid == FID_BOXER)  or  tar_cur_frm == 6  or  rotationatkr == rotationtar or rotationatkr == ((rotationtar + 5) % 6) or rotationatkr == ((rotationtar + 1) % 6) ) then begin
                 if bpart == BODY_HIT_EYES andAlso (tar_cur_frm != 10 or (tar_cur_frm != 4 andAlso tar_fid == 16777311)) then begin
                     set_sfall_return(hitmiss); // hit or miss
                     set_sfall_arg(0, hitmiss);
                     set_sfall_return(BODY_HIT_HEAD); // new bodypart
                     set_sfall_arg(3, BODY_HIT_HEAD);
                     return;
                  end

         // groin from back and rears convertion to torso or random leg
              if (bpart == BODY_HIT_GROIN  andAlso tar_cur_frm != 10 andAlso tar_cur_frm != 6 or (tar_cur_frm != 4 andAlso tar_fid == 16777311) )  or (bpart == BODY_HIT_GROIN andAlso (tar_cur_frm == 6 or (tar_cur_frm == 4 andAlso tar_fid == FID_BOXER)) andAlso not( rotationatkr == rotationtar))  then begin
                     rnd = random(1, 100);
                     if rnd <= 60 then begin
                        set_sfall_return(hitmiss); // hit or miss
                        set_sfall_arg(0, hitmiss);
                        set_sfall_return(BODY_HIT_TORSO); // new bodypart
                        set_sfall_arg(3, BODY_HIT_TORSO);
                        return;
                     end
                     if rnd > 60 then begin
                        set_sfall_return(hitmiss); // hit or miss
                        set_sfall_arg(0, hitmiss);
                        set_sfall_return(rndleg); //  new bodypart
                        set_sfall_arg(3, rndleg);
                        return;
                     end
               end
            end
      end

   //deathclaw conversion of aimed hits in eye/groin in critter's back into head/ torso+legs hits
      if critter_type == KILL_TYPE_deathclaw_kills andAlso hitmiss > MISS then begin // 13 = deathclaw
         if ( ((tar_cur_frm != 6 andAlso tar_cur_frm != 5) andAlso (rotationatkr == rotationtar or rotationatkr == ((rotationtar + 5) % 6) or rotationatkr == ((rotationtar + 1) % 6) )) or ( tar_cur_frm == 6 andAlso ( rotationatkr == ((rotationtar + 3) % 6)  or rotationatkr == ((rotationtar + 4) % 6)  or rotationatkr == ((rotationtar + 5) % 6) )) or ( tar_cur_frm == 5 andAlso ( rotationatkr == ((rotationtar + 1) % 6)  or rotationatkr == ((rotationtar + 2) % 6)  or rotationatkr == ((rotationtar + 3) % 6) )) ) then begin
              if bpart == BODY_HIT_EYES then begin
                  set_sfall_return(hitmiss); // hit or miss
                  set_sfall_arg(0, hitmiss);
                  set_sfall_return(BODY_HIT_HEAD); // new bodypart
                  set_sfall_arg(3, BODY_HIT_HEAD);
                  return;
               end
         end
      // groin from back and rears convertion to torso or random leg
      if (bpart == BODY_HIT_GROIN andAlso tar_cur_frm == 5 andAlso (((rotationatkr == rotationtar + 1) % 6) or ((rotationatkr == rotationtar + 2) % 6) or ((rotationatkr == rotationtar + 3) % 6)) ) or (bpart == 7 andAlso tar_cur_frm == 6 andAlso ( ((rotationatkr == rotationtar + 1) % 6) or rotationatkr == rotationtar or rotationatkr == ((rotationtar + 5) % 6) ) )  then begin
            rnd = random(1, 100);
            if rnd <= 60 then begin
               set_sfall_return(hitmiss); // hit or miss
               set_sfall_arg(0, hitmiss);
               set_sfall_return(BODY_HIT_TORSO); // new bodypart torso
               set_sfall_arg(3, BODY_HIT_TORSO);
               return;
            end
            if rnd > 60 then begin
               set_sfall_return(hitmiss); // hit or miss
               set_sfall_arg(0, hitmiss);
               set_sfall_return(rndleg); //  new bodypart = rnd leg
               set_sfall_arg(3, rndleg);
               return;
            end
      end
   end
   // brahmins/centaurs/robots/dogs conversion of aimed hits in eye/sensors in critter's back into head/cpu hits // regulator from face into /torso+legs hits
   if critter_type == 5  or critter_type == 7 or critter_type == 9 or critter_type == 10 or critter_type == 11  then begin // 5 = brahmin, 7=rats, 9 == centaurs 10= robots 11= dogs
            if hitmiss > MISS andAlso tile_distance_objs(target, attacker) != 0   andAlso ( tar_cur_frm == 6  or  rotationatkr == rotationtar or rotationatkr == ((rotationtar + 1) % 6)  or rotationatkr == ((rotationtar + 5) % 6) ) then begin
                 // eye(sensor) to head(cpu)
                 if bpart == 6 andAlso tar_cur_frm != 10  then begin
                     set_sfall_return(hitmiss); // hit or miss
                     set_sfall_arg(0, hitmiss);
                     set_sfall_return(BODY_HIT_HEAD); // new bodypart
                     set_sfall_arg(3, BODY_HIT_HEAD);
                     return;
                  end
             end
         // groin(regulator) from face and anterior rears convertion to torso or random leg(motivators)
         if hitmiss > MISS andAlso tile_distance_objs(target, attacker) != 0   andAlso  ( rotationatkr == ((rotationtar + 2) % 6) or rotationatkr == ((rotationtar + 3) % 6) or rotationatkr == ((rotationtar + 4) % 6) )  then begin
              if bpart == 7  andAlso tar_cur_frm != 10 andAlso tar_cur_frm != 6  or (bpart == 7 andAlso tar_cur_frm == 6 andAlso not( rotationatkr == rotationtar))  then begin
                        rnd = random(1, 100);
                        if rnd <= 60 then begin
                           set_sfall_return(hitmiss); // hit or miss
                           set_sfall_arg(0, hitmiss);
                           set_sfall_return(BODY_HIT_TORSO); // new bodypart torso
                           set_sfall_arg(3, BODY_HIT_TORSO);
                           return;
                        end

                        if rnd > 60 then begin
                           set_sfall_return(hitmiss); // hit or miss
                           set_sfall_arg(0, hitmiss);
                           set_sfall_return(rndleg); //  new bodypart  rnd leg
                           set_sfall_arg(3, rndleg);
                           return;
                        end
               end
            end
      end

   // Aliens conversion of aimed hits in eyes(?) in critter's back into head hits
   if critter_type == 16 then begin // 16 == aliens
            // aliens' eyes(?) to head
            if hitmiss > MISS andAlso tile_distance_objs(target, attacker) != 0   andAlso ( tar_cur_frm == 6  or  rotationatkr == rotationtar ) then begin
                if bpart == BODY_HIT_EYES andAlso tar_cur_frm != 10  then begin
                        rnd = random(1, 100);
                        if rnd <= 60 then begin
                           set_sfall_return(hitmiss); // hit or miss
                           set_sfall_arg(0, hitmiss);
                           set_sfall_return(BODY_HIT_HEAD); // new bodypart
                           set_sfall_arg(3, BODY_HIT_HEAD);
                           return;
                        end
                        if rnd > 60 then begin
                           set_sfall_return(hitmiss); // hit or miss
                           set_sfall_arg(0, hitmiss);
                           set_sfall_return(BODY_HIT_TORSO); //  new bodypart
                           set_sfall_arg(3, BODY_HIT_TORSO);
                           return;
                        end
                  end
             end

         // aliens' groin hit if facing the attacker to head or torso hit
         if hitmiss > MISS andAlso tile_distance_objs(target, attacker) != 0   andAlso  rotationatkr == ((rotationtar + 3) % 6)  then begin
              if bpart == BODY_HIT_GROIN  andAlso tar_cur_frm != 10 then begin
                  rnd = random(1, 100);
                  if rnd <= 60 then begin
                     set_sfall_return(hitmiss); // hit or miss
                     set_sfall_arg(0, hitmiss);
                     set_sfall_return(BODY_HIT_TORSO); // new bodypart
                     set_sfall_arg(3, BODY_HIT_TORSO);
                     return;
                  end
                  if rnd > 60 then begin
                     set_sfall_return(hitmiss); // hit or miss
                     set_sfall_arg(0, hitmiss);
                     set_sfall_return(BODY_HIT_HEAD); //  new bodypart
                     set_sfall_arg(3, BODY_HIT_HEAD);
                     return;
                  end
               end
            end
      end

// All critters types
       // chance to convert uncalled_body hit to random aimed hit for all critters if mod is activated
      if (BodyRndHit == 1 or (attacker != dude_obj andAlso BodyRndHit == 2)) andAlso bpart == BODY_UNCALLED andAlso burst == 0 andAlso grenade == 0 andAlso hitmiss > MISS then begin
         //for attackers with small FRM (ant,mantis,small radscorp e.t.) lower chance to hit head/eyes, more chance to hit legs
         if short_crit(attacker) then begin
            rnd = random(0, (1000 - 380 * combat_diff)) ;
            if attacker == dude_obj then rnd = random(0, 100);
            if rnd > 55 then begin // old bodypart 8 - torso uncalled
               set_sfall_return(hitmiss); // hit or miss not changed
               set_sfall_arg(0, hitmiss);
               return;
            end
            // ~1% can hit head/eyes only if target is lying on the floor
            if (rnd <= 10 andAlso tar_cur_frm == 10 andAlso ( rotationatkr == rotationtar or rotationatkr == ((rotationtar + 5) % 6) or rotationatkr == ((rotationtar + 1) % 6)) )
               or (rnd <= 10 andAlso tar_cur_frm == 6 andAlso not( rotationatkr == rotationtar or rotationatkr == ((rotationtar + 5) % 6) or rotationatkr == ((rotationtar + 1) % 6)) ) then begin // ~1 % can hit head / eyes only if target is lying on the floor
               rnd2 = random(0, 100);
                  if rnd2 <= 94 then begin // ~9, 5 % to hit head
                     rnd3 = random(2, 3);
                     set_sfall_return(rnd3); // 50 % critical hit chance
                     set_sfall_arg(0, rnd3);
                     set_sfall_return(BODY_HIT_HEAD); // new bodypart 0 - head
                     set_sfall_arg(3, BODY_HIT_HEAD);
                     set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1)); // return 1 action point because a new attack costs 1 more
                     return;
                  end
                  if rnd2 > 94 andAlso tar_cur_frm == 10 then begin // ~0, 5 % to critical hit eyes
                     set_sfall_return(CRITICAL_HIT); // always critical hit chance
                     set_sfall_arg(0, CRITICAL_HIT);
                     set_sfall_return(BODY_HIT_EYES); // new bodypart 6 - eyes
                     set_sfall_arg(3, BODY_HIT_EYES);
                     set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
                     return;
                  end
            end
            if rnd > 10 andAlso rnd <= 19 then begin // 9 %
                  rnd2 = random(0, (1000 - 400 * combat_diff));
                  if rnd2 <= 10 then begin // 1 -  %
                  set_sfall_return(CRITICAL_HIT); // critical hit
                  set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 10 then begin
                  set_sfall_return(hitmiss); // hit or miss not changed
                  set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(rndarm); // new bodypart 1, 2 - arms
               set_sfall_arg(3, rndarm);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
            if rnd > 19 andAlso rnd <= 45 then begin // 25 %
                  rnd2 = random(0, (1000 - 400 * combat_diff));
                  if rnd2 <= 10 then begin // 10 %
                  set_sfall_return(CRITICAL_HIT); // crit hit
                  set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 10 then begin
                  set_sfall_return(hitmiss); // hit or miss not changed
                  set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(rndleg); // new bodypart 4, 5 - legs
               set_sfall_arg(3, rndleg);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
            if rnd > 45 andAlso rnd <= 55 then begin // 14 %
                  rnd2 = random(0, (1000 - 400 * combat_diff));
                  if rnd2 <= 10 then begin // 10 %
                  set_sfall_return(CRITICAL_HIT); // crit hit
                  set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 10 then begin
                  set_sfall_return(hitmiss); // hit or miss not changed
                  set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(BODY_HIT_GROIN); // new bodypart 7 - groin
               set_sfall_arg(3, BODY_HIT_GROIN);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
         end

         // for attackers with medium FRM or normal human FRM or big FRM
         if not(short_crit(attacker)) then begin
            rnd = random(0, (580 - 215 * combat_diff)) ;
            if attacker == dude_obj then rnd = random(0, 100);
            if rnd > 29 then begin // old bodypart 8 - torso uncalled
               set_sfall_return(hitmiss); // hit or miss not changed
               set_sfall_arg(0, hitmiss);
               return;
            end
            if rnd <= 3 then begin // 3 %
               rnd2 = random(0, 100);
               rnd3 = random(2, 3);
                  if rnd2 <= 95 then begin // ~2, 85 % to hit head
                  set_sfall_return(rnd3); // 50 % critical hit chance
                  set_sfall_arg(0, rnd3);
                  set_sfall_return(BODY_HIT_HEAD); // new bodypart 0 - head
                  set_sfall_arg(3, BODY_HIT_HEAD);
                  set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1)); // return 1 action point because a new attack costs 1 more
                  return;
                  end
                  if (rnd2 > 95 andAlso tar_cur_frm == 10) or
                  (rnd2 > 95 andAlso not( rotationatkr == rotationtar or rotationatkr == ((rotationtar + 1) % 6)  or rotationatkr == ((rotationtar + 5) % 6) )) then begin // ~0,15 % to hit eyes
                  set_sfall_return(CRITICAL_HIT); // always critical hit chance
                  set_sfall_arg(0, CRITICAL_HIT);
                  set_sfall_return(BODY_HIT_EYES); // new bodypart 6 - eyes
                  set_sfall_arg(3, BODY_HIT_EYES);
                  set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
                  return;
                  end
            end
            if rnd > 3 andAlso rnd <= 12 then begin // 9 %
                  rnd2 = random(0, (1000 - 350 * combat_diff));
                  if rnd2 <= 15 then begin // 15 % bonus crit chance
                     rnd3 = random(0, 100);
                     set_sfall_return(CRITICAL_HIT); // crit hit
                     set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 15 then begin
                     rnd3 = random(0, 100);
                     set_sfall_return(hitmiss); // hit or miss not changed
                     set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(rndarm); // new bodypart 1, 2 - arms
               set_sfall_arg(3, rndarm);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
            if rnd > 12 andAlso rnd <= 23 then begin // 11 %
                  rnd2 = random(0, (1000 - 380 * combat_diff));
                  if rnd2 <= 12 then begin // 10 % bonus crit chance
                  set_sfall_return(CRITICAL_HIT); // crit hit
                  set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 12 then begin
                  set_sfall_return(hitmiss); // hit or miss not changed
                  set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(rndleg); // new bodypart 4, 5 - legs
               set_sfall_arg(3, rndleg);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
            if rnd > 23 andAlso rnd <= 30 andAlso (tar_cur_frm == 10 or (not( rotationatkr == rotationtar or rotationatkr == ((rotationtar + 1) % 6)  or rotationatkr == ((rotationtar + 5) % 6)) )
            or (tar_cur_frm == 6 andAlso (rotationatkr == rotationtar or rotationatkr == ((rotationtar + 1) % 6)  or rotationatkr == ((rotationtar + 5) % 6)))) then begin // 7 %
                  rnd2 = random(0, (1000 - 380 * combat_diff));
                  if rnd2 <= 15 then begin // 15 % bonus crit chance
                  set_sfall_return(CRITICAL_HIT); // crit hit
                  set_sfall_arg(0, CRITICAL_HIT);
                  end
                  if rnd2 > 15 then begin
                  set_sfall_return(hitmiss); // hit or miss not changed
                  set_sfall_arg(0, hitmiss);
                  end
               set_sfall_return(BODY_HIT_GROIN); // new bodypart 7 - groin
               set_sfall_arg(3, BODY_HIT_GROIN);
               set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + 1));
               return;
            end
         end
      end

      // chance to convert aimed body miss to random hit for all critters
      if bpart == BODY_HIT_TORSO andAlso hitch > 19 andAlso hitmiss == MISS then begin
         rnd = random(0, 100);
         if rnd < 9 then begin // old bodypart 8 - torso uncalled
            rnd = random(1, 5);
            if rnd != BODY_HIT_TORSO then begin // not a body hit
            set_sfall_return(HIT); // hit instead of miss
            set_sfall_arg(0, HIT);
            set_sfall_return(rnd); // new bodypart
            set_sfall_arg(3, rnd);
            return;
            end
            else begin
            set_sfall_return(hitmiss); // hit instead of miss
            set_sfall_arg(0, hitmiss);
            return;
            end
         end
         if rnd > 98 then begin // 1 - 3 %
            set_sfall_return(HIT); // hit instead of miss
            set_sfall_arg(0, HIT);
            set_sfall_return(BODY_HIT_HEAD); // new bodypart
            set_sfall_arg(3, BODY_HIT_HEAD);
            return;
         end
      end

   // chance to convert head hit to eye hit for all critters
      if bpart == BODY_HIT_HEAD andAlso hitmiss > MISS then begin
         rnd = random(0, 100);
         if rnd < 5 then begin
            if rnd == 4 then begin
            set_sfall_return(hitmiss); // hit or crit
            set_sfall_arg(0, hitmiss);
            end
            if rnd < 4 then begin
            set_sfall_return(CRITICAL_HIT); // hit or crit
            set_sfall_arg(0, CRITICAL_HIT);
            end
            set_sfall_return(BODY_HIT_EYES); // new bodypart 6 - eye
            set_sfall_arg(3, BODY_HIT_EYES);
            return;
         end
      end

   // miss to random hit for all critters

      //eye miss to 1% + (1-5)% head or 3% body hit
      if bpart == BODY_HIT_EYES andAlso hitch > 19 andAlso hitmiss == MISS then begin
         rnd = random(0, 100);
         if rnd < (2 + hitch / 19) then begin
            set_sfall_return(HIT); // hit or miss
            set_sfall_arg(0, HIT);
            set_sfall_return(BODY_HIT_HEAD); // new bodypart
            set_sfall_arg(3, BODY_HIT_HEAD);
            return;
         end
         if rnd > 98 then begin
            set_sfall_return(HIT); // hit or miss
            set_sfall_arg(0, HIT);
            set_sfall_return(BODY_HIT_TORSO); //  new bodypart 3 - aimed_body
            set_sfall_arg(3, BODY_HIT_TORSO);
            return;
         end
      end
      //groin miss to (1-5)% legs or (1-5) body hit
      if bpart == BODY_HIT_GROIN andAlso hitch > 19 andAlso hitmiss == MISS then begin
         rnd = random(0, 100);
         if rnd < (hitch / 19) then begin
            set_sfall_return(HIT); // hit or miss
            set_sfall_arg(0, HIT);
            set_sfall_return(BODY_HIT_TORSO); //  new bodypart 3 - aimed_body
            set_sfall_arg(3, BODY_HIT_TORSO);
            return;
         end
         if rnd > (100 - hitch / 19)  then begin
            set_sfall_return(HIT); // hit or miss
            set_sfall_arg(0, HIT);
            set_sfall_return(rndleg); //  new bodypart 4 - left leg, 5 - right leg
            set_sfall_arg(3, rndleg);
            return;
         end
      end
      // legs&arms miss to body hit (1-5)%
      if (bpart < 6 ) andAlso bpart != BODY_HIT_TORSO  andAlso hitch > 19 andAlso hitmiss == MISS then begin
         rnd = random(0, 100);
         if rnd < (hitch / 19) then begin
            set_sfall_return(HIT); // hit
            set_sfall_arg(0, HIT);
            set_sfall_return(BODY_HIT_TORSO); //  new bodypart
            set_sfall_arg(3, BODY_HIT_TORSO);
            return;
         end
      end
   end
   rnd = 0;
   rnd2 = 0;
   rnd3 = 0;
   //burst = 0;
   //grenade = 0;
   missed = get_sfall_arg_at(0);
end