#define SMALL_FRAME_DODGE 8
#define DODGER_DODGE 5
#define JINXED_MISS 5
#define ONE_HANDER_HIT_BONUS 20
#define ONE_HANDER_CRIT_ROLL_BONUS 5
#define SKILLED_HIT_BONUS 4
#define DRUG_MAX_STATS 18
#define NumEffects 0
#define AddictTimeOff 1

#define base_map_arr_num 1
#define drug_arr_pid_offset 0
#define drug_arr_numeff_offset 1
#define drug_arr_addict_time_offset 2
#define drug_arr_numeff_gvar_id 3
#define drug_arr_addict_text_id 4
#define drug_arr_addict_frm_id 5

#define jinxed_roll_max_value_adress 0x4238BC

#define kamikaze_tohit_penalty 3
#define kamikaze_walk_div 2

#define skilled_perk_level_bonus (4)

#define fast_meta_duration_div (2)
#define skilled_luck_bonus (6)
#define bloody_mess_luck_penalty (-7)
#define ap_bonus_kill_first (2)
//#define ap_bonus_kill_second (2)
#define ap_bonus_kill (1)
#define MAX_TRAITS 16
#define flags_offset 100000

#define timed_hp_regen 1
#define timed_ap_give 5
#define timed_ap_debt 10
#define timed_rad_rm 100
#define timed_rad_rm_get_time            get_array(drug_addict_array, ARRAY_CHEM_RAD_RM_TIME)
#define timed_rad_rm_get_time_next       (game_time() - timed_rad_rm_get_time)
#define timed_rad_rm_set_time(time_ticks) set_array(drug_addict_array, ARRAY_CHEM_RAD_RM_TIME, time_ticks)
#define timed_rad_rm_is_time_set         (timed_rad_rm_get_time != 0)
#define timed_rad_rm_clear_time          set_array(drug_addict_array, ARRAY_CHEM_RAD_RM_TIME, 0)
#define timed_rad_rm_repeat_time         ONE_GAME_HOUR

#define STAT_drug_rnd -2
//#define drug_addict_stats(drug_stat) ((drug_stat >= STAT_st andAlso drug_stat <= STAT_poison_resist andAlso drug_stat != STAT_max_move_points andAlso drug_stat != STAT_heal_rate andAlso drug_stat != STAT_max_hp) orElse drug_stat == STAT_drug_rnd)
#define drug_addict_stats(drug_stat) ((drug_stat >= STAT_st andAlso drug_stat <= STAT_poison_resist andAlso drug_stat != STAT_heal_rate) orElse (RegenMod <= 0 andAlso drug_stat == STAT_heal_rate))

#define drug_resist_stats(drug_stat) ((drug_stat >= STAT_st andAlso drug_stat <= STAT_poison_resist andAlso drug_stat != STAT_heal_rate) orElse (RegenMod <= 0 andAlso drug_stat == STAT_heal_rate))

//#define drug_fast_meta_stats(drug_stat) ((drug_stat == STAT_current_hp orElse drug_stat == STAT_max_hp orElse drug_stat == STAT_max_move_points orElse drug_stat == STAT_heal_rate) andAlso drug_stat != STAT_drug_rnd)
#define drug_fast_meta_stats(drug_stat) ((drug_stat >= STAT_current_hp andAlso drug_stat <= STAT_current_rad) orElse drug_stat == STAT_max_hp orElse drug_stat == STAT_heal_rate)

#define new_msg_file "gl_traits_plus.msg"
#define trait_name_offset 100
#define trait_desc_offset 200

#define one_week_in_min 10080

#define get_combat_free_move sfall_func0("get_combat_free_move")

#define trait_msg(x) message_str_game(traits_plus_msg_file, x)
#define msg_traits_set 1
#define msg_restart_game 2

#define ddraw_perks_ini_path "ddraw.ini|Misc|PerksFile"
#define ddraw_drugs_ini_path "ddraw.ini|Misc|DrugsFile"
#define default_perks_ini_path "mods\\Perks.ini"
#define default_drugs_ini_path "mods\\Drugs.ini"
#define default_perks_ini_name "Perks.ini"
#define default_drugs_ini_name "Drugs.ini"
#define default_perks_ini_name2 "perks.ini"
#define default_drugs_ini_name2 "drugs.ini"

#define power_armor_fid(critter_fid)   (critter_fid == FID_HAPOWR or \
                                       critter_fid == FID_NAPOWR or \
                                       critter_fid == FID_HANPWR or \
                                       critter_fid == FID_MABOSS)
#define crit_is_moving(critter_obj)    ( (art_anim(obj_art_fid(critter_obj)) == ANIM_walk) or (art_anim(obj_art_fid(critter_obj)) == ANIM_running) )
#define get_active_weapon(critter)  critter_inven_obj(critter, (2 - active_hand) if critter == dude_obj else INVEN_TYPE_RIGHT_HAND)
#define signal_close_game                                       sfall_func0("signal_close_game")
#define message_box_flags(text, flags)                          sfall_func2("message_box", text, flags)

#define traits_desc_ver_msg 3

#define gGameMouseCursor read_int(0x518C0C)
#define MOUSE_CURSOR_CROSSHAIR 20

//Nevada drugs
#define PID_MENTATS_NEVADA                  (337)
#define PID_MENTATS_AROM                    (338)
#define PID_NEVADA_FIGHTING_STIM            (164)
#define PID_NEVADA_CARAMEL                  (259)
#define PID_NEVADA_DIESEL_GUM               (525)
#define PID_NEVADA_CADAVER_AMPHET           (718)
#define PID_NEVADA_NUT_SOLUTION             (675)

//ecco drugs
#define PID_ECCO_HERCULES                   (620)

//olympus2207 drugs
#define PID_OLYMP_SURGE                      (223) //"Lazaret"
#define PID_OLYMP_RESISTANOL                 (229)
#define PID_OLYMP_COMBATID                 (230)
#define PID_OLYMP_BRAINNIAC                 (231)
#define PID_OLYMP_STRONGHOLD                (232)
#define PID_OLYMP_DROP                     (233) //"Kaplya"

//sfall 5
#define set_heave_ho_tweak_mod(mod)                             metarule3(202, mod, 0, 0)
#define _combat_turn_running read_int(0x51093C)

#define ARRAY_CHEM_NAME "MMR_DRUG_ADDICT_ARR"
#define ARRAY_CHEM_RAD_RM_TIME -10
#define DA_LAST_PERK 1000000

#define DA_DRUG_MENTATS     11
#define DA_DRUG_BUFFOUT     12
#define DA_DRUG_PSYCHO      13
#define DA_DRUG_JET         14
#define DA_DRUG_NUKACOLA    15
#define DA_DRUG_RADX        16
#define DA_DRUG_RADAWAY     17
#define DA_DRUG_ALCOHOL     18
//Nevada
#define DA_DRUG_NEVADA_AP_DRUGS    19

// Mentats
#define da_mentats_perk_name             trait_msg(300)
#define da_mentats_perk_desc1            trait_msg(301)
#define da_mentats_perk_desc2            trait_msg(302)
#define da_mentats_perk_desc3            trait_msg(303)
#define da_mentats_add_msg               trait_msg(304)

// BUFFOUT
#define da_buffout_perk_name             trait_msg(310)
#define da_buffout_perk_desc1            trait_msg(311)
#define da_buffout_perk_desc2            trait_msg(312)
#define da_buffout_perk_desc3            trait_msg(313)
#define da_buffout_add_msg               trait_msg(314)

// PSYCHO
#define da_psycho_perk_name              trait_msg(320)
#define da_psycho_perk_desc1             trait_msg(321)
#define da_psycho_perk_desc2             trait_msg(322)
#define da_psycho_perk_desc3             trait_msg(323)
#define da_psycho_add_msg                trait_msg(324)

// JEt
#define da_jet_perk_name                 trait_msg(330)
#define da_jet_perk_desc1                trait_msg(331)
#define da_jet_perk_desc2                trait_msg(332)
#define da_jet_perk_desc3                trait_msg(333)
#define da_jet_add_msg                   trait_msg(334)

// COLA
#define is_pid_cola_sonora(drug_pid)      (drug_pid == 107)
#define is_pid_cola_nevada(drug_pid)      (drug_pid == 473 orElse drug_pid == 583 orElse drug_pid == 584)
#define is_pid_cola(drug_pid)             ((drug_pid == PID_NUKA_COLA) orElse (Sonora > 0 andAlso is_pid_cola_sonora(drug_pid)) orElse (Nevada > 0 andAlso is_pid_cola_nevada(drug_pid)))
#define da_nukacola_perk_name             trait_msg(340)
#define da_nukacola_perk_desc1            trait_msg(341)
#define da_nukacola_perk_desc2            trait_msg(342)
#define da_nukacola_perk_desc3            trait_msg(343)
#define da_nukacola_add_msg               trait_msg(344)

// RADX
#define da_radx_perk_name                trait_msg(350)
#define da_radx_perk_desc1               trait_msg(351)
#define da_radx_perk_desc2               trait_msg(352)
#define da_radx_perk_desc3               trait_msg(353)
#define da_radx_add_msg                  trait_msg(354)

// RADAWAY
#define da_radaway_perk_name             trait_msg(360)
#define da_radaway_perk_desc1            trait_msg(361)
#define da_radaway_perk_desc2            trait_msg(362)
#define da_radaway_perk_desc3            trait_msg(363)
#define da_radaway_add_msg               trait_msg(364)

// AL GUL
#define is_pid_alcohol_sonora(drug_pid)  (drug_pid >= 120 andAlso drug_pid <= 125)
#define is_pid_alcohol_nevada(drug_pid)  (drug_pid == 758 orElse drug_pid == 719 orElse drug_pid == 423 orElse drug_pid == 476)
#define is_pid_alcohol_ecco(drug_pid)    (drug_pid == 542) //bottle of wine
#define is_pid_alcohol_oplymp(drug_pid)  (Olympus2207 > 0 andAlso (drug_pid == 234 orElse drug_pid == 235 orElse drug_pid == 236)) //bottle of wine
#define is_pid_alcohol(drug_pid)         ((Sonora <= 0 andAlso (is_pid_alcohol_ecco(drug_pid) orElse drug_pid == PID_BEER orElse drug_pid == PID_BOOZE orElse drug_pid == PID_GAMMA_GULP_BEER orElse drug_pid == PID_ROENTGEN_RUM orElse drug_pid == PID_ROT_GUT orElse (Nevada > 0 andAlso is_pid_alcohol_nevada(drug_pid)))) orElse (Sonora > 0 andAlso is_pid_alcohol_sonora(drug_pid)))
#define da_alcohol_perk_name             trait_msg(370)
#define da_alcohol_perk_desc1            trait_msg(371)
#define da_alcohol_perk_desc2            trait_msg(372)
#define da_alcohol_perk_desc3            trait_msg(373)
#define da_alcohol_add_msg               trait_msg(374)


// NEVADA JEt
#define da_nevada_amph_perk_name                 trait_msg(3330)
#define da_nevada_amph_perk_desc1                trait_msg(3331)
#define da_nevada_amph_add_msg                   trait_msg(3334)


#define COMBAT_TURN_START      (1)
#define COMBAT_TURN_END       (0)
#define COMBAT_END_ABRUPT      (-1) //combat ends abruptly (by script or by pressing Enter during PC turn)
#define COMBAT_END_NORMAL      (-2) //combat ends normally (hook always runs at the end of combat)


#define right_hand_healed_msg    (trait_msg(6))
#define right_leg_healed_msg     (trait_msg(7))
#define left_hand_healed_msg     (trait_msg(8))
#define left_leg_healed_msg      (trait_msg(9))
#define eyes_healed_msg          (trait_msg(10))
#define msg_player_1_hp_healed   (trait_msg(11))
#define msg_player_many_hp_healed   (trait_msg(12))
#define finesse_to_hit_bonus     10


#include "define.h"
#include "define_extra.h"
#include "command.h"
#include "sfall.h"
#include "F2MMR.h"
#include "lib.strings.h"


variable traits_plus_cur_version;
variable traits_plus_version_Sonora = "Sonora";
variable traits_plus_version_et_tu = "et_tu";

variable Nevada;
variable Sonora;
variable et_tu;
variable Olympus2207;
variable TraitsPlus;
variable RegenMod;
variable Lvar_wpn_max_dmg;
variable Lvar_wpn_min_dmg;
variable AimedBurstMod;
variable v1_2_new_install;
variable dude_trait_1;
variable dude_trait_2;
variable in_char_screen;
variable repeat_in_char_screen;


variable traits_plus_msg_file;
variable perks_ini_path;

variable drugs_ini_path;
variable array_drugs_ini;


variable main_attacker;
variable gPyromaniacBonus;
variable gDemolitionExpertBonus;

// TRAIT_fast_metabolism
variable fast_metabolism;
variable fast_metabolism_MMR_regen;
variable fast_metabolism_fast_healing_perk_stat = "FMMRTPFH";
variable gLastRegenTime;
variable gLastGameTime;
variable gPartialTicks;
variable gAccumulatedHealForCrip;
variable gCripHealThreshold;
variable gTotalHealedThisRest;
variable gGlobalMapSpeedMult;
variable timed_hp_regen_global;
variable gFasterHealingPerk;
variable characterEditorSelectedItem;
variable timer_is_up;

// TRAIT_drug_addict
variable drug_addict;
variable drug_addict_array;
variable da_check;
variable drug_addict_stat_check_array;
variable last_xp_mod;

// TRAIT_drug_resistant
variable drug_resistant;

// TRAIT_bruiser
variable bruiser;
variable in_description;
variable scr_repeat;
variable overlay_created;
variable g_HH_target;
variable g_HH_dt_pen;
variable g_HH_dr_pen;
variable g_HH_dmg_type;
variable bruiser_heavy_handed_pid_0;
variable bruiser_heavy_handed_min_0;
variable bruiser_heavy_handed_max_0;
variable bruiser_heavy_handed_pid_1;
variable bruiser_heavy_handed_min_1;
variable bruiser_heavy_handed_max_1;
variable is_unarmed;
variable bruiser_heavy_handed_min_dmg;
variable bruiser_heavy_handed_max_dmg;

// TRAIT_small_frame
variable small_frame;

// TRAIT_one_hander
variable one_hander;
variable one_hander_stat_bonus = "TPOHTBST";
variable one_hander_weapon_pid;
variable one_hander_min_st;

// TRAIT_heavy_handed
variable heavy_handed;

//skilled
variable skilled;
variable skilled_last_perk_level_bonus = -50;
variable skilled_prevent_crit_fail;

variable kamikaze;
variable kamikaze_ap_used;
variable kamikaze_hex_walked_num;
variable kamikaze_last_tile;

//TRAIT_finesse
variable finesse;
variable finesse_hit_to_crit;
variable finesse_hit_to_crit_bonus;
variable finesse_bonus_added;


//TRAIT_bloody_mess
variable bloody_mess;
variable bloody_mess_inj_arr;
variable bloody_mess_ap_debt;
variable bloody_mess_player_death_changed;
variable bloody_mess_bonus_count;
variable bloody_mess_last_ap_attack;
variable bloody_mess_no_ap_end;
variable dude_turn;

//TRAIT_jinxed
variable jinxed;
variable jinxed_removed;
variable jinxed_unsafe_set_max_roll;

variable living_anatomy_bonus;

variable unlucky_attacker;
variable attacker_orig_extra_luck;
variable AF_attack_result = -1;
variable luck_min;
variable luck_max = -1;
variable last_lvl;

variable modded_drug_pid;
variable drug_orig_stats;
variable disabled_traits_arr;

variable ver_major;
variable ver_minor;
variable ver_build;
variable sfall_508;
variable sfall_510;
variable AutoMoveToAttack;
variable AutoMoveToAttack_move_dist;
variable AutoMoveToAttack_start_hex;
variable AutoMoveToAttack_last_ap;
variable AutoMoveToAttack_last_wpn = -10;
variable AutoMoveToAttack_last_target;
variable wpn_is_melee;
variable wpn_range;
variable EXPLOSION_TARGET_COUNT = 6;

procedure weapon_is_two_handed(variable weapon) begin
   variable weapon_flags_ext;
   variable is_two_handed;
   if weapon <= 0 orElse obj_item_subtype(weapon) != item_type_weapon then begin
      return -1;
   end
   if (get_proto_data(obj_pid(weapon),PROTO_FLAG_EXT) bwand WEAPON_2HAND) == WEAPON_2HAND then begin
      is_two_handed = 1;
   end
   return is_two_handed;
end

procedure one_hander_bonus_remove begin
   if get_sfall_global_int(one_hander_stat_bonus) <= 0 then
      return;
   set_critter_extra_stat(real_dude_obj, STAT_better_crit, (get_critter_extra_stat(real_dude_obj, STAT_better_crit) - ONE_HANDER_CRIT_ROLL_BONUS));
   set_sfall_global(one_hander_stat_bonus, 0);
end

procedure one_hander_bonus_add begin
   if get_sfall_global_int(one_hander_stat_bonus) > 0 then
      return;
   set_critter_extra_stat(real_dude_obj, STAT_better_crit, (get_critter_extra_stat(real_dude_obj, STAT_better_crit) + ONE_HANDER_CRIT_ROLL_BONUS));
   set_sfall_global(one_hander_stat_bonus, 1);
end

procedure one_hander_weapon_bonus_remove begin
   if one_hander_weapon_pid <= 0 then begin
      return;
   end
   set_proto_data(one_hander_weapon_pid, PROTO_WP_MIN_ST, one_hander_min_st);
   one_hander_min_st = 0;
   one_hander_weapon_pid = 0;
end

procedure one_hander_weapon_bonus_add(variable weapon) begin
   variable weapon_pid;
   if weapon > 0 then begin
      weapon_pid = obj_pid(weapon);
   end
   if weapon_pid <= 0 orElse weapon_pid == one_hander_weapon_pid then begin
      return;
   end

   call one_hander_weapon_bonus_remove;

   one_hander_weapon_pid = weapon_pid;
   one_hander_min_st = get_proto_data(weapon_pid, PROTO_WP_MIN_ST);
   if one_hander_min_st >= 4 then
      set_proto_data(weapon_pid, PROTO_WP_MIN_ST, (one_hander_min_st - 3));
   else
      set_proto_data(weapon_pid, PROTO_WP_MIN_ST, 1);
end

procedure finess_rm_crit_bonuses begin
   if finesse_hit_to_crit_bonus != 0 then begin
      set_critter_extra_stat(real_dude_obj, STAT_better_crit, get_critter_extra_stat(real_dude_obj, STAT_better_crit) - finesse_hit_to_crit_bonus);
      set_critter_extra_stat(real_dude_obj, STAT_crit_chance, get_critter_extra_stat(real_dude_obj, STAT_crit_chance) - finesse_hit_to_crit_bonus);
      finesse_hit_to_crit_bonus = 0;
      finesse_hit_to_crit = 0;
   end
   finesse_bonus_added = 0;
end

procedure finess_add_crit_bonuses begin
   call finess_rm_crit_bonuses;
   if finesse_bonus_added <= 0 andAlso finesse_hit_to_crit > 0 then begin
      finesse_hit_to_crit_bonus = finesse_hit_to_crit;
      set_critter_extra_stat(real_dude_obj, STAT_better_crit, get_critter_extra_stat(real_dude_obj, STAT_better_crit) + finesse_hit_to_crit_bonus);
      set_critter_extra_stat(real_dude_obj, STAT_crit_chance, get_critter_extra_stat(real_dude_obj, STAT_crit_chance) + finesse_hit_to_crit_bonus);
      finesse_hit_to_crit = 0;
      finesse_bonus_added = 1;
      call finess_rm_crit_bonuses when _combat_turn_running <= 0;
   end
end

procedure TOHIT begin
   variable hit_capped = get_sfall_arg;
   variable attacker  = get_sfall_arg;
   variable target    = get_sfall_arg;
   variable body_part = get_sfall_arg;
   variable atk_type  = get_sfall_arg_at(5);
   variable hit_uncapped = get_sfall_arg_at(7);
   variable dodger;
   variable max_dodge;
   variable max_hit_cap;
   variable new_hit_cap;
   variable new_hit_chance = hit_uncapped;
   variable active_item;

   if target == real_dude_obj then begin
      dodger = has_trait(TRAIT_PERK, target, PERK_dodger);
      if small_frame > 0 then
         max_dodge += SMALL_FRAME_DODGE;
   end

   // get new maximum hit chance if it != 95
   if hit_capped > 95 orElse hit_capped < hit_uncapped then
      max_hit_cap = hit_capped;
   else
      max_hit_cap = 95;

   new_hit_cap = max_hit_cap;

   if attacker == real_dude_obj then begin
      if one_hander > 0 then begin
         active_item = get_active_weapon(attacker);
         if active_item <= 0
            andAlso (atk_type == ATKTYPE_PUNCH
            orElse (atk_type >= ATKTYPE_STRONGPUNCH andAlso atk_type <= ATKTYPE_PIERCINGSTRIKE)) then begin
            new_hit_chance += ONE_HANDER_HIT_BONUS;
         end
         else if active_item > 0 andAlso weapon_is_two_handed(active_item) == 0 then begin
            // penalty if both arms crippled
            if (critter_state(attacker) bwand (DAM_CRIP_ARM_LEFT bwor DAM_CRIP_ARM_RIGHT))
               == (DAM_CRIP_ARM_LEFT bwor DAM_CRIP_ARM_RIGHT) then begin
               new_hit_chance -= ONE_HANDER_HIT_BONUS;
            end
         end
      end

      if finesse then
         new_hit_chance += finesse_to_hit_bonus;

      if skilled > 0 then begin
         new_hit_chance += SKILLED_HIT_BONUS;
         max_hit_cap += SKILLED_HIT_BONUS;
         new_hit_cap = max_hit_cap;
      end
   end

   // Dodge / jinxed
   if (max_dodge > 0 orElse dodger > 0 orElse jinxed > 0) andAlso hit_capped > 0 then begin
      if jinxed > 0 then
         max_dodge += JINXED_MISS;
      max_dodge += DODGER_DODGE * dodger;
      new_hit_cap = max_hit_cap - max_dodge;
   end

   if new_hit_cap < 0 then
      new_hit_cap = 0;
   else if new_hit_cap > 99 then begin
      if body_part == BODY_UNCALLED then
         new_hit_cap = 100;
      else
         new_hit_cap = 99;
   end

   // Kamikaze penalties
   if kamikaze_hex_walked_num > 0 then
      new_hit_chance -= kamikaze_tohit_penalty * kamikaze_hex_walked_num;
   if AutoMoveToAttack_move_dist > 0 then
      new_hit_chance -= kamikaze_tohit_penalty * AutoMoveToAttack_move_dist;

   //PEKR_finesse
   if attacker == real_dude_obj andAlso finesse then begin
      //if body_part == BODY_UNCALLED orElse body_part == BODY_HIT_TORSO then begin
         finesse_hit_to_crit = round((new_hit_chance - new_hit_cap) / 10.0);
      //end
      if finesse_hit_to_crit > 0 andAlso combat_data > 0 andAlso get_object_data(combat_data, C_ATTACK_TARGET) then
         call finess_add_crit_bonuses;
   end

   if new_hit_chance >= new_hit_cap then begin
      if new_hit_cap != hit_capped then begin
         set_sfall_return(new_hit_cap);
         set_sfall_arg(0, new_hit_cap);
         set_sfall_arg(7, new_hit_chance);
      end
   end
   else begin
      if new_hit_chance != hit_uncapped then begin
         hit_uncapped = new_hit_chance;
         if new_hit_chance < -99 then
            new_hit_chance = -99;
         set_sfall_return(new_hit_chance);
         set_sfall_arg(0, new_hit_chance);
         set_sfall_arg(7, hit_uncapped);
      end
   end
end


procedure jinxed_remove_and_get_roll begin
   if jinxed_removed > 0 then
      return;

   if sfall_508 <= 0 andAlso (has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_jinxed) orElse has_trait(TRAIT_PERK, real_dude_obj, PERK_jinxed_perk)) then begin
      jinxed_unsafe_set_max_roll = read_byte(jinxed_roll_max_value_adress);
      write_byte(jinxed_roll_max_value_adress, 0x00);
      jinxed_removed = 1;
   end

   return random(ROLL_CRITICAL_FAILURE, ROLL_FAILURE);
end

procedure jinxed_restore begin
   if jinxed_removed <= 0 then
      return;
   if jinxed_unsafe_set_max_roll != 0 then begin
      write_int(jinxed_roll_max_value_adress, jinxed_unsafe_set_max_roll);//restore random roll
      jinxed_unsafe_set_max_roll = 0;
   end
end


procedure get_luck_min_max begin
   variable dude_extra_luck;
   if luck_max != -1 then
      return;

   dude_extra_luck = get_critter_extra_stat(real_dude_obj, STAT_lu);
   set_critter_extra_stat(real_dude_obj, STAT_lu, -100);
   luck_min = dude_luck;
   set_critter_extra_stat(real_dude_obj, STAT_lu, 100);
   luck_max = dude_luck;
   set_critter_extra_stat(real_dude_obj, STAT_lu, dude_extra_luck);
end

procedure remove_luck_penalty begin
   if unlucky_attacker > 0 then begin
      if luck_max == -1 then
         call get_luck_min_max;

      set_stat_min(STAT_lu, luck_min);
      set_stat_max(STAT_lu, luck_max);
      set_critter_extra_stat(unlucky_attacker, STAT_lu, attacker_orig_extra_luck);
      unlucky_attacker = 0;
      attacker_orig_extra_luck = 0;
      AF_attack_result = -1;
   end
end

// Increases the severity of the critical failure effect by "temporarily" reducing the luck value.
// Formula for calculating the power of a critical miss within the game:
// randomBetween(1, 100) - 5 * (attacker_LUCK - 5); weakest effect at <= 20, strongest effect at > 95
procedure add_luck_penalty(variable attacker,variable has_bloody_mess, variable has_skilled) begin
   variable luck_penalty;
   if attacker <= 0 orELSE obj_type(attacker) != OBJ_TYPE_CRITTER then
      return;
   if unlucky_attacker > 0 andAlso unlucky_attacker != attacker then begin
      call remove_luck_penalty;
   end
   //add heavy handed bonus
   if attacker == real_dude_obj andAlso has_skilled > 0 then begin
      luck_penalty += skilled_luck_bonus;
   end
   //add bloody mess penalty
   if has_bloody_mess > 0 then begin
      luck_penalty += bloody_mess_luck_penalty;
   end
   if luck_penalty != 0 then begin
      set_stat_min(STAT_lu, -20);
      set_stat_max(STAT_lu, 20);
      AF_attack_result = ROLL_CRITICAL_FAILURE;
      unlucky_attacker = attacker;
      attacker_orig_extra_luck = get_critter_extra_stat(attacker, STAT_lu);
      set_critter_extra_stat(attacker, STAT_lu, (attacker_orig_extra_luck + luck_penalty));
   end
end

procedure get_wpn_range(variable weapon,variable attack_type) begin
   variable weapon_range;
   if weapon <= 0 orElse attack_type < ATKTYPE_LWEP1 then begin
      return -1;
   end

   if attack_type % 2 then begin
      weapon_range = get_proto_data(obj_pid(weapon), PROTO_WP_RANGE_2);
   end
   else begin
      weapon_range = get_proto_data(obj_pid(weapon), PROTO_WP_RANGE_1);
   end

   return weapon_range;
end

procedure drug_restore begin
   variable i;
   variable drug_stat_offset;
   variable drug_stat_value;
   variable drug_num_effects;
   if modded_drug_pid <= 0 orElse len_array(drug_orig_stats) <= 0 then begin
      return;
   end

   for (i = 0; i < DRUG_MAX_STATS-1; i++) begin
      drug_stat_offset = (PROTO_DR_STAT_A + (i * 4));
      drug_stat_value = get_array(drug_orig_stats, i);
      set_proto_data(modded_drug_pid, drug_stat_offset,drug_stat_value);
   end
   drug_num_effects = get_array(drug_orig_stats, DRUG_MAX_STATS);
   if drug_num_effects >= 0 then
      set_drugs_data(NumEffects, modded_drug_pid, drug_num_effects);

   modded_drug_pid = 0;
   free_array(drug_orig_stats);
end

procedure CALCAPCOST begin
   variable critter = get_sfall_arg;
   variable is_aimed;
   variable orig_ap_cost;
   variable new_ap_cost;
   variable atk_type;
   variable active_item;
   variable cursor_mode;
   if modded_drug_pid > 0 then begin
      call drug_restore;
   end

   if critter == real_dude_obj andAlso AutoMoveToAttack > 0 then begin
      atk_type = get_sfall_arg_at(1);
      is_aimed = get_sfall_arg_at(2);
      wpn_is_melee = 0;
      if atk_type <= ATKTYPE_RWEP2 then begin
         active_item = get_active_weapon(critter);
         if AutoMoveToAttack_last_wpn > -10 andAlso AutoMoveToAttack_last_wpn != active_item + is_aimed then begin
            AutoMoveToAttack_move_dist = 0;
            AutoMoveToAttack_start_hex = 0;
            AutoMoveToAttack_last_wpn = 0;
            cursor_mode = get_cursor_mode;
            if cursor_mode == CURSOR_TARGETING andAlso gGameMouseCursor == MOUSE_CURSOR_CROSSHAIR then begin
               set_cursor_mode((cursor_mode + 1) % 3);
               set_cursor_mode(CURSOR_TARGETING);
            end
         end
         if active_item > 0 andAlso obj_item_subtype(active_item) == item_type_weapon then begin
            AutoMoveToAttack_last_wpn = active_item + is_aimed;
            wpn_range = get_wpn_range(active_item,atk_type) - 1;

            if wpn_range >= 0 andAlso wpn_range <= 2 then begin
               wpn_is_melee = 1;
            end
            else begin
               wpn_is_melee = 0;
               AutoMoveToAttack_move_dist = 0;
               AutoMoveToAttack_start_hex = 0;
            end
         end
      end
      else if atk_type != ATKTYPE_LWEP_RELOAD andAlso atk_type != ATKTYPE_RWEP_RELOAD then begin
         if AutoMoveToAttack_last_wpn > -10 andAlso AutoMoveToAttack_last_wpn != atk_type + (is_aimed * 100) then begin
            AutoMoveToAttack_move_dist = 0;
            AutoMoveToAttack_start_hex = 0;
            AutoMoveToAttack_last_wpn = 0;
            cursor_mode = get_cursor_mode;
            if cursor_mode == CURSOR_TARGETING andAlso gGameMouseCursor == MOUSE_CURSOR_CROSSHAIR then begin
               set_cursor_mode((cursor_mode + 1) % 3);
               set_cursor_mode(CURSOR_TARGETING);
            end
         end
         AutoMoveToAttack_last_wpn = atk_type + (is_aimed * 100);
         if (get_proto_data(obj_pid(critter), PROTO_CR_FLAGS) bwand CFLG_RANGED) == CFLG_RANGED then
            wpn_range = 1;
         else
            wpn_range = 0;
         wpn_is_melee = 1;
      end
      if AutoMoveToAttack_move_dist > 0 andAlso combat_is_initialized then begin
         if AutoMoveToAttack_start_hex == tile_num(real_dude_obj) then begin
            orig_ap_cost = get_sfall_arg_at(3);
            new_ap_cost = orig_ap_cost - AutoMoveToAttack_move_dist / kamikaze_walk_div - (kamikaze_hex_walked_num / kamikaze_walk_div);
            if kamikaze_hex_walked_num >= kamikaze_walk_div then begin
               new_ap_cost -= (kamikaze_hex_walked_num / kamikaze_walk_div);
            end
            if new_ap_cost < 1 + is_aimed then begin
               new_ap_cost = 1 + is_aimed;
            end
            set_sfall_return(new_ap_cost);
            set_sfall_arg(3, new_ap_cost);
            if new_ap_cost != AutoMoveToAttack_last_ap then begin
               AutoMoveToAttack_last_ap = new_ap_cost;
               intface_redraw;
            end
         end
         else begin
            AutoMoveToAttack_move_dist = 0;
            AutoMoveToAttack_start_hex = 0;
         end
      end
   end
   // restore LUCK
   if AF_attack_result == ROLL_CRITICAL_FAILURE then begin
      call remove_luck_penalty;
   end
   if jinxed_removed > 0 then begin
      call jinxed_restore;
   end
   // kamikaze AP cost reduction
   if kamikaze_hex_walked_num >= kamikaze_walk_div then begin
      atk_type = get_sfall_arg_at(1);
      if atk_type != ATKTYPE_LWEP_RELOAD orElse atk_type != ATKTYPE_RWEP_RELOAD then begin
         active_item = get_active_weapon(critter);
         if active_item == 0 orElse obj_item_subtype(active_item) == item_type_weapon then begin
            is_aimed = get_sfall_arg_at(2);
            orig_ap_cost = get_sfall_arg_at(3);
            new_ap_cost = orig_ap_cost - (kamikaze_hex_walked_num / kamikaze_walk_div);
            if new_ap_cost < 1 + is_aimed then begin
               new_ap_cost = 1 + is_aimed;
            end
            if AutoMoveToAttack_last_ap > 0 andAlso AutoMoveToAttack_last_ap < new_ap_cost then
               new_ap_cost = AutoMoveToAttack_last_ap;

            set_sfall_return(new_ap_cost);
            set_sfall_arg(3, new_ap_cost);
            if kamikaze_ap_used > 0 then begin
               kamikaze_ap_used = 0;
               kamikaze_hex_walked_num = 0;
               AutoMoveToAttack_last_ap = 0;
               intface_redraw;
            end
         end
      end
   end

   if critter == real_dude_obj then begin
      if new_ap_cost > 0 then begin
         orig_ap_cost = new_ap_cost;
      end
      else begin
         orig_ap_cost = get_sfall_arg_at(3);
      end
      //one hander
      if one_hander > 0 then begin
         active_item = get_active_weapon(critter);
         if active_item > 0 then begin
            if weapon_is_two_handed(active_item) == 0 then begin
               call one_hander_weapon_bonus_add(active_item);
               call one_hander_bonus_add;
            end
            else begin
               call one_hander_weapon_bonus_remove;
               call one_hander_bonus_remove;
            end
         end
         else begin
            atk_type = get_sfall_arg_at(1);
            if (atk_type == ATKTYPE_PUNCH orElse (atk_type >= ATKTYPE_STRONGPUNCH andAlso atk_type <= ATKTYPE_PIERCINGSTRIKE)) then begin
               call one_hander_bonus_add;
            end
            else begin
               call one_hander_bonus_remove;
            end
         end
      end
      else begin
         call one_hander_weapon_bonus_remove;
         call one_hander_bonus_remove;
      end
      if bloody_mess > 0 then begin
         if orig_ap_cost > 0 andAlso get_combat_free_move <= 0 andAlso ((get_critter_current_ap(critter) - orig_ap_cost)) <= 0 then
            bloody_mess_last_ap_attack = 1;
         else
            bloody_mess_last_ap_attack = 0;
      end
   end
   else begin
      call one_hander_weapon_bonus_remove;
   end
end


procedure get_crit_mult(variable crit_power_roll, variable target) begin
   variable crit_mult = 2;
   variable crit_flags = (DAM_BYPASS bwor DAM_HIT);
   variable target_kill_type = metarule(METARULE_CRITTER_KILL_TYPE, target);

   if crit_power_roll <= 20 then begin
      crit_mult = 3;
      if random(0,2) then crit_flags = DAM_HIT;
   end
   else if crit_power_roll <= 45 then begin
      crit_mult = 3;
      if not(random(0,3)) then crit_flags = crit_flags bwor DAM_KNOCKED_DOWN;
   end
   else if crit_power_roll <= 75 then begin
      crit_mult = 4;
      if random(0,2) then crit_flags = crit_flags bwor DAM_KNOCKED_DOWN;
   end
   else if crit_power_roll <= 100 then begin
      crit_mult = 5;
      if random(0,5) then
         crit_flags = crit_flags bwor DAM_KNOCKED_DOWN;
      else
         crit_flags = crit_flags bwor DAM_KNOCKED_OUT;
   end
   else begin
      crit_mult = 6;
      crit_flags = crit_flags bwor DAM_KNOCKED_DOWN;
      if crit_power_roll >= 114 andAlso target_kill_type < 18 then begin
         crit_flags = crit_flags bwor DAM_DEAD;
      end
   end

   if target_kill_type > 17 then begin
      if crit_mult > 4 then crit_mult = 4;
      if crit_power_roll >= 100 then begin
         crit_flags = crit_flags bwor DAM_KNOCKED_DOWN;
      end
      if not(random(0,2)) then
         crit_flags = crit_flags bwand (bwnot DAM_BYPASS);
   end

   return crit_mult + (flags_offset * crit_flags);
end

procedure calc_crit_dmg(variable attacker, variable target, variable weapon, variable bullet_count) begin
   variable crit_flags;
   variable bonus_ranged_damage;
   variable bonus_crit_power_roll = get_critter_stat(attacker,STAT_better_crit);
   variable target_dt;
   variable target_dr;
   variable target_kill_type = metarule(METARULE_CRITTER_KILL_TYPE, target);
   variable rnd = random(0, 100);
   variable tar_flags;
   variable crit_mult = 1;
   variable min_dmg = 0;
   variable dmg;
   variable weapon_perk;
   variable crit_power_roll;
   variable weapon_pid;
   variable weapon_dmg;
   variable weapon_anim;
   variable weapon_min_dmg;
   variable weapon_max_dmg;
   variable weapon_damage_type;
   variable weapon_ammo_pid;
   variable ammo_dr_mod;
   variable ammo_dmg_mult = 1;
   variable ammo_dmg_div = 1;
   variable living_anatomy = has_trait(TRAIT_PERK, attacker, PERK_living_anatomy_perk);
   variable pyromaniac;

   if weapon > 0 then begin
      weapon_pid = obj_pid(weapon);
      if weapon_pid == PID_MOLOTOV_COCKTAIL then begin
         weapon_damage_type = DMG_fire;
      end
      else begin
         weapon_damage_type = get_proto_data(weapon_pid, PROTO_WP_DMG_TYPE);
      end
      if Lvar_wpn_min_dmg <= 0 then begin
         weapon_min_dmg = get_proto_data(weapon_pid, PROTO_WP_DMG_MIN);
      end
      else begin
         weapon_min_dmg = Lvar_wpn_min_dmg;
      end
      if Lvar_wpn_max_dmg <= 0 then begin
         weapon_max_dmg = get_proto_data(weapon_pid, PROTO_WP_DMG_MAX);
      end
      else begin
         weapon_max_dmg = Lvar_wpn_max_dmg;
      end
      weapon_perk = get_proto_data(weapon_pid, PROTO_WP_PERK);
      weapon_ammo_pid = get_proto_data(weapon_pid, PROTO_WP_AMMO_PID);
      weapon_anim = get_proto_data(weapon_pid, PROTO_WP_ANIM);
      if weapon_ammo_pid > 0 then begin
         ammo_dr_mod = get_proto_data(weapon_ammo_pid, PROTO_AM_DR_MOD);
         ammo_dmg_mult = get_proto_data(weapon_ammo_pid, PROTO_AM_DMG_MULT);
         ammo_dmg_div = get_proto_data(weapon_ammo_pid, PROTO_AM_DMG_DIV);
      end
      if (weapon_anim >= WPN_ANIM_PISTOL) orElse (weapon_damage_type != DMG_normal_dam andAlso weapon_anim <= 0) then begin
         bonus_ranged_damage = has_trait(TRAIT_PERK, attacker, PERK_bonus_ranged_damage);
      end
   end

   if bullet_count <= 0 then bullet_count = 1;
   weapon_dmg = random(weapon_min_dmg, weapon_max_dmg) * ammo_dmg_mult / ammo_dmg_div + 2 * bonus_ranged_damage;
   weapon_dmg *= bullet_count;

   target_dt = get_critter_stat(target,(STAT_dmg_thresh + weapon_damage_type));
   target_dr = get_critter_stat(target,(STAT_dmg_resist + weapon_damage_type));
   //Increase target_dr if it attacker has TRAIT_finesse
   if finesse > 0 then begin
      target_dr = target_dr + 30;
   end
   if weapon_perk == PERK_weapon_penetrate then begin
      target_dt = target_dt * 0.2;
      if weapon_damage_type != DMG_emp then target_dr = target_dr * 0.8;
   end

   // if YAAM ammo active
   if (ammo_dr_mod > 0 andAlso ammo_dr_mod < 20) or (weapon_ammo_pid == PID_ROCKET_AP andAlso ammo_dr_mod == 20) then begin
      ammo_dr_mod = 0;
      target_dt = target_dt - ammo_dr_mod;
      if target_dt < ammo_dr_mod then begin
         target_dr = target_dr + (10 * (target_dt - ammo_dr_mod) / 100.0);
      end
   end
   target_dr = target_dr + ammo_dr_mod;


   //if crit_roll <= critical_chance then begin
      crit_power_roll = random(1, (100 + bonus_crit_power_roll));
      crit_mult = get_crit_mult(crit_power_roll,target);
      tar_flags = crit_mult / flags_offset;
      crit_mult = (crit_mult % flags_offset) / 2.0;
      if weapon_damage_type != DMG_emp then begin
         if (tar_flags bwand DAM_BYPASS) then begin
            target_dt = target_dt * 0.2;
            target_dr = target_dr * 0.2;
         end
         else begin
            target_dt = target_dt * 0.8;
            target_dr = target_dr * 0.8;
         end
      end
   //end
   if target_dt < 0 then target_dt = 0;
   if target_dr > 90 andAlso weapon_damage_type != DMG_emp then target_dr = 90;
   if target_dr < 0 then target_dr = 0;

   if target_dr < 100 then begin
      dmg = round(((weapon_dmg) - target_dt) * crit_mult * (100 - target_dr) / 100.0);
   end
   if dmg < min_dmg then dmg = min_dmg;

   if target_kill_type != KILL_TYPE_robot_kills orElse target_kill_type != KILL_TYPE_alien_kills then begin
      dmg += living_anatomy_bonus * living_anatomy;
   end
   if weapon_damage_type == DMG_fire orElse weapon_pid == PID_MOLOTOV_COCKTAIL then begin
      pyromaniac = has_trait(TRAIT_PERK, attacker, PERK_pyromaniac_perk);
      dmg += gPyromaniacBonus * pyromaniac;
   end
   tar_flags *= flags_offset;
   return (dmg + tar_flags);

end

procedure ap_hide begin
   variable ap_left;
   variable free_move_ap_left;
   if bloody_mess_ap_debt > 0 then begin
      ap_left = get_critter_current_ap(main_attacker) - bloody_mess_ap_debt;
      free_move_ap_left = get_combat_free_move;
      call_offset_v2(0x45EE0C, ap_left, free_move_ap_left); //intface_update_move_points
   end
end

procedure return_ap_debt2 begin
   if bloody_mess_ap_debt > 0 then begin
      set_critter_current_ap(main_attacker, get_critter_current_ap(main_attacker) - bloody_mess_ap_debt);
      bloody_mess_ap_debt = 0;
   end
end

procedure return_ap_debt begin
   call return_ap_debt2 when _combat_turn_running <= 0;
end


procedure da_radaway_timer begin
   variable current_time;
   variable next_time;
   variable missed_cycles;
   variable delay;
   variable rad_to_remove;

   if not(has_fake_perk_npc(real_dude_obj, da_radaway_perk_name)) then
      return;


   current_time = game_time;
   next_time = timed_rad_rm_get_time;

   if (next_time == 0) then begin
      next_time = current_time + timed_rad_rm_repeat_time;
      timed_rad_rm_set_time(next_time);
      delay = timed_rad_rm_repeat_time;
      add_global_timer_event(delay, timed_rad_rm);
      return;
   end

   if (current_time >= next_time) then begin
      missed_cycles = ((current_time - next_time) / timed_rad_rm_repeat_time) + 1;

      if get_critter_stat(real_dude_obj, STAT_current_rad) > 0 then begin
         rad_to_remove = get_critter_stat(real_dude_obj, STAT_en) / 3 + (2 * has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism));
         if rad_to_remove < 1 then
            rad_to_remove = 1;
         rad_to_remove *= missed_cycles;
         radiation_dec(real_dude_obj, rad_to_remove);
      end
      next_time = next_time + (missed_cycles * timed_rad_rm_repeat_time);
      timed_rad_rm_set_time(next_time);
   end

   delay = next_time - current_time;
   if (delay <= 0) then
      delay = ONE_GAME_HOUR;

   if get_critter_stat(real_dude_obj, STAT_current_rad) > 0 then
      add_global_timer_event(delay, timed_rad_rm);
   else
      timed_rad_rm_set_time(0);
end


procedure ADJUSTRADS begin
   variable critter = get_sfall_arg;
   variable amount = get_sfall_arg;

   if critter == real_dude_obj andAlso amount > 0 andAlso get_critter_stat(real_dude_obj, STAT_current_rad) <= 0 then begin
      call da_radaway_timer;
   end
end

procedure heal_random_injury(variable critter, variable count = 1, variable chance = 100) begin
   variable state;
   variable uninjure;
   variable guaranteed;
   variable remaining_chance;
   variable messages;
   variable injures;
   variable rnd;
   variable roll_chance;
   variable i, key, injury;
   if (chance < 1 orElse count <= 0) then
      return 0;

   state = critter_state(critter);
   if ((state bwand all_injuries) == 0) then
      return 0;

   if chance > 100 then begin
      guaranteed = chance / 100;
      remaining_chance = chance % 100;
   end
   else
      remaining_chance = chance;

   if (critter == dude_obj) then
      messages = [right_hand_healed_msg, left_leg_healed_msg, left_hand_healed_msg, right_leg_healed_msg, eyes_healed_msg];

   injures = [DAM_CRIP_ARM_RIGHT, DAM_CRIP_LEG_LEFT, DAM_CRIP_ARM_LEFT, DAM_CRIP_LEG_RIGHT, DAM_BLIND];
   rnd = random(0, 4);

   while (count > 0) do begin
      for (i = 0; i < 5; i++) begin
         key = ((rnd + i) % 5);
         injury = injures[key];
         if (state bwand injury) then begin
            if (guaranteed > 0) then begin
               roll_chance = 100;
               guaranteed--;
            end
            else begin
               roll_chance = remaining_chance;
            end
            if (roll_chance >= random(1, 100)) then begin
               uninjure = uninjure bwor injury;
               state = state bwand (bwnot(injury));
               if (critter == dude_obj) then
                  display_msg(messages[key]);
               count--;
               if (count <= 0) then
                  break;
            end
         end
      end
      count--;
      rnd = random(0, 4);
      if ((state bwand all_injuries) == 0) then
         break;
   end

   if (uninjure != 0) then
      critter_uninjure(critter, uninjure);

   return uninjure;
end

procedure display_regen_msg(variable critter, variable RegenTickHP) begin
   if (critter == real_dude_obj) then begin
      if (RegenTickHP == 1) then
         display_msg(parse_str_2(msg_player_1_hp_healed, obj_name(critter), RegenTickHP));
      else
         display_msg(parse_str_2(msg_player_many_hp_healed, obj_name(critter), RegenTickHP));
   end
end

procedure apply_regen_tick_simple(variable critter, variable count) begin
   variable critter_max_hp;
   variable critter_cur_hp;
   variable critter_en;
   variable critter_healing_rate;
   variable local_RegenTickHP;
   variable amount;
   variable penalty_percent;

   if count < 1 then
      return 0;

   critter_healing_rate = get_critter_stat(critter, STAT_heal_rate);
   if (critter_healing_rate < 1) then
      return -1;

   critter_max_hp = get_critter_stat(critter, STAT_max_hp);
   critter_cur_hp = get_critter_stat(critter, STAT_current_hp);

   critter_en = get_critter_stat(critter, STAT_en);
   critter_healing_rate = (critter_healing_rate / 10.0 + critter_en);

   amount = get_poison(critter);
   if amount > 0 then begin
      penalty_percent += 5.0 + (amount) * 0.2;
      if penalty_percent > 25.0 then
         penalty_percent = 25.0;
   end

   amount = get_critter_stat(critter, STAT_current_rad);
   if amount > 0 then begin
      penalty_percent += 5.0 + (amount) * 0.05;
   end

   if penalty_percent > 0.0 then begin
      if penalty_percent > 40.0 then
         penalty_percent = 40.0;
      critter_healing_rate *= (100.0 - penalty_percent) / 100.0;
   end

   if (critter_cur_hp < critter_max_hp) then begin
      if gFasterHealingPerk then begin
         if fast_metabolism > 0 then begin
            local_RegenTickHP = ceil((critter_max_hp / 100.0) * 1.0 * critter_healing_rate);
            if (local_RegenTickHP < 2) then
                 local_RegenTickHP = 2;
         end
         else begin
            local_RegenTickHP = ceil((critter_max_hp / 100.0) * 0.3 * critter_healing_rate);
            if (local_RegenTickHP < 1) then
                 local_RegenTickHP = 1;
         end
      end
      else begin
         local_RegenTickHP = ceil((critter_max_hp / 100.0) * 0.5 * critter_healing_rate);
         if (local_RegenTickHP < 1) then
              local_RegenTickHP = 1;
      end

      local_RegenTickHP = count * local_RegenTickHP;

      if (critter_cur_hp + local_RegenTickHP > critter_max_hp) then
         local_RegenTickHP = critter_max_hp - critter_cur_hp;



      if (local_RegenTickHP > 0) then begin
         critter_heal(critter, local_RegenTickHP);
         call display_regen_msg(critter, local_RegenTickHP);
      end
   end
   else begin
      local_RegenTickHP = 0;
   end

   if (critter_is_crippled(critter)) then begin
      call heal_random_injury(critter, count);
   end

   return local_RegenTickHP;
end

procedure dude_timed_hp_regen begin
   variable regen_per_tick;
   variable ticks_passed;
   variable intervals_passed;
   variable remainder_ticks;
   variable total_regen;
   variable next_timer;
   variable on_global_map;
   variable game_time_now;

   if (fast_metabolism <= 0 andAlso gFasterHealingPerk < 2) orElse fast_metabolism_MMR_regen > 0 then begin
      gLastRegenTime = 0;
      timer_is_up = 0;
      return;
   end

   game_time_now = game_time;

   if (gLastRegenTime == 0) then begin
      gLastRegenTime = game_time_now - 50;
   end

   if (combat_is_initialized) then begin
      return;
   end

   ticks_passed = game_time_now - gLastRegenTime;
   intervals_passed = ticks_passed / 50;
   remainder_ticks = ticks_passed % 50;

   regen_per_tick = apply_regen_tick_simple(real_dude_obj, intervals_passed);

   gLastRegenTime = gLastRegenTime + (intervals_passed * 50);

   if (get_game_mode bwand WORLDMAP) then
      on_global_map = 1;

   next_timer = 50 - remainder_ticks;
   if (next_timer <= 0) then begin
      next_timer = 50;
   end

   add_global_timer_event(next_timer + (on_global_map * timed_hp_regen_global), timed_hp_regen);
   timer_is_up = 1;
end

procedure give_ap_for_injures_add_time begin
   add_global_timer_event(0, timed_ap_give);
end

procedure give_ap_for_injures_when begin
   call give_ap_for_injures_add_time when _combat_turn_running <= 0;
end

procedure give_ap_for_bloody_mess(variable attacker) begin
   if bloody_mess_bonus_count <= 0 then begin
      set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + ap_bonus_kill_first - bloody_mess_ap_debt));
      bloody_mess_ap_debt = 0;
   end
   else begin
      set_critter_current_ap(attacker, (get_critter_current_ap(attacker) + ap_bonus_kill - bloody_mess_ap_debt));
      bloody_mess_ap_debt = 0;
   end
   bloody_mess_bonus_count++;
end

procedure give_ap_for_injures begin
   variable critter;
   variable critter_injures;
   if bloody_mess <= 0 andAlso dude_turn <= 0 orElse main_attacker != real_dude_obj then
      return;

   foreach critter in list_as_array(LIST_CRITTERS) begin
      critter_injures = (get_object_data(critter, OBJ_DATA_DAMAGE_FLAGS) bwand all_injuries);
      if critter_injures > get_array(bloody_mess_inj_arr, critter) then begin
         call give_ap_for_bloody_mess(real_dude_obj);
      end
   end
   call return_ap_debt2;
end


procedure Drop_Weapons(variable target,variable hand) begin
   variable weapon;
   variable weapon_pid;
   variable weapon_anim;
   variable weapon_rh_flags_ext;
   variable weapon_lh_flags_ext;
   variable tar_pid;
   variable tar_hex;
   variable tar_critter_type;
   variable tar_critter_flags;
   variable dropped_hex;
   variable blocking_obj;
   variable count;
   variable max_count = 6;
   if target <= 0 then
      return;

   tar_pid = obj_pid(target);
   tar_critter_flags = get_proto_data(tar_pid, PROTO_CR_FLAGS);

   if tar_critter_flags bwand CFLG_NODROP then
      return;

   tar_hex = tile_num(target);
   tar_critter_type = metarule(METARULE_CRITTER_KILL_TYPE, target);

   if critter_inven_obj(target, INVEN_TYPE_RIGHT_HAND) then begin
      weapon = critter_inven_obj(target, INVEN_TYPE_RIGHT_HAND);
      if weapon > 0 then begin
         weapon_pid = obj_pid(weapon);
         weapon_rh_flags_ext = get_proto_data(weapon_pid, PROTO_FLAG_EXT);
         weapon_anim = get_proto_data(weapon_pid, PROTO_WP_ANIM);
      end
      if ((hand == BODY_HIT_RIGHT_ARM) orElse ((weapon_rh_flags_ext bwand WEAPON_2HAND) andAlso (not(tar_critter_type == KILL_TYPE_super_mutant_kills andAlso (weapon_anim == WPN_ANIM_MINIGUN orElse weapon_anim == WPN_ANIM_ROCKET_LAUNCHER))))) then begin
         rm_obj_from_inven(target, weapon);
         dropped_hex = tile_num_in_direction(tar_hex, random(0, 5), random(1, 2));
         blocking_obj = obj_blocking_line(target, dropped_hex, BLOCKING_TYPE_SHOOT);
         if blocking_obj andAlso obj_type(blocking_obj) == OBJ_TYPE_CRITTER then blocking_obj = 0;
         while (tile_contains_obj_pid(dropped_hex, elevation(target), 33554499) != 0) or blocking_obj do begin
            dropped_hex = tile_num_in_direction(tar_hex, random(0, 5), random(1, 2));
            count += 1;
            blocking_obj = obj_blocking_line(target, dropped_hex, BLOCKING_TYPE_BLOCK);
            if blocking_obj andAlso obj_type(blocking_obj) == OBJ_TYPE_CRITTER then blocking_obj = 0;
            if count > max_count then begin
               dropped_hex = tar_hex;
               break;
            end
         end
         move_to(weapon, dropped_hex, elevation(target));
      end
   end
   //all weapons in the game are either right-handed or two-handed, so the player drops weapon only if the shot was in the right hand
   else if critter_inven_obj(target, INVEN_TYPE_LEFT_HAND) then begin
      weapon = critter_inven_obj(target, INVEN_TYPE_LEFT_HAND);
      if weapon > 0 then begin
         weapon_pid = obj_pid(weapon);
         weapon_lh_flags_ext = get_proto_data(weapon_pid, PROTO_FLAG_EXT);
         weapon_anim = get_proto_data(weapon_pid, PROTO_WP_ANIM);
      end
      if ((hand == BODY_HIT_RIGHT_ARM andAlso target == dude_obj) orElse (hand == BODY_HIT_LEFT_ARM andAlso target != dude_obj) orElse (weapon_lh_flags_ext bwand WEAPON_2HAND)) then begin
         rm_obj_from_inven(target, weapon);
         dropped_hex = tile_num_in_direction(tar_hex, random(0, 5), random(1, 2));
         blocking_obj = obj_blocking_line(target, dropped_hex, BLOCKING_TYPE_SHOOT);
         if blocking_obj andAlso obj_type(blocking_obj) == OBJ_TYPE_CRITTER then blocking_obj = 0;
         while (tile_contains_obj_pid(dropped_hex, elevation(target), 33554499) != 0) or blocking_obj do begin
            dropped_hex = tile_num_in_direction(tar_hex, random(0, 5), random(1, 2));
            count += 1;
            blocking_obj = obj_blocking_line(target, dropped_hex, BLOCKING_TYPE_BLOCK);
            if blocking_obj andAlso obj_type(blocking_obj) == OBJ_TYPE_CRITTER then blocking_obj = 0;
            if count > max_count then begin
               dropped_hex = tar_hex;
               break;
            end
         end
         move_to(weapon, dropped_hex, elevation(target));
      end
   end
end

procedure timed_event_p_proc begin
   if fixed_param == timed_hp_regen then begin
      call dude_timed_hp_regen;
   end
   else if fixed_param == timed_ap_give then begin
      call give_ap_for_injures;
   end
   else if fixed_param == timed_ap_debt then begin
      call ap_hide;
   end
   else if fixed_param == timed_rad_rm then begin
      call da_radaway_timer;
   end
end

procedure RestoreHeavyHandedPenalty begin
   if g_HH_target then begin
      set_critter_extra_stat(g_HH_target, STAT_dmg_thresh + g_HH_dmg_type, get_critter_extra_stat(g_HH_target, STAT_dmg_thresh + g_HH_dmg_type) + g_HH_dt_pen);
      set_critter_extra_stat(g_HH_target, STAT_dmg_resist + g_HH_dmg_type, get_critter_extra_stat(g_HH_target, STAT_dmg_resist + g_HH_dmg_type) + g_HH_dr_pen);
      g_HH_target = 0;
   end
end

procedure ApplyHeavyHandedPenalty(variable attacker, variable target, variable weapon) begin
   variable dt_stat, dr_stat, extra_dt, extra_dr;
   variable target_dt, target_dr, dmg_type, penalty;

   call RestoreHeavyHandedPenalty;

   if weapon then
      dmg_type = get_proto_data(obj_pid(weapon), PROTO_WP_DMG_TYPE);
   else
      dmg_type = get_proto_data(obj_pid(attacker), PROTO_CR_DMG_TYPE);

   dt_stat = STAT_dmg_thresh + dmg_type;
   dr_stat = STAT_dmg_resist + dmg_type;

   extra_dt = get_critter_extra_stat(target, dt_stat);
   extra_dr = get_critter_extra_stat(target, dr_stat);
   target_dt = get_critter_base_stat(target, dt_stat) + extra_dt;
   target_dr = get_critter_base_stat(target, dr_stat) + extra_dr;

   penalty = 10 + get_critter_stat(attacker, STAT_st) * 4;
   //if penalty > 50 then penalty = 50;

   g_HH_target = target;
   g_HH_dmg_type = dmg_type;
   g_HH_dt_pen = ceil((target_dt * penalty) / 100.0);
   g_HH_dr_pen = ceil((target_dr * penalty) / 100.0);

   set_critter_extra_stat(target, dt_stat, extra_dt - g_HH_dt_pen);
   set_critter_extra_stat(target, dr_stat, extra_dr - g_HH_dr_pen);
end

procedure get_attack_anim(variable weapon,variable attack_type) begin
   variable attack_anim;
   variable attack_anim_arr;
   variable index;
   if attack_type >= ATKTYPE_LWEP_RELOAD andAlso attack_type <= ATKTYPE_RWEP_RELOAD then begin
      return -1;
   end
   //kick
   if attack_type == ATKTYPE_KICK orElse (attack_type >= ATKTYPE_STRONGKICK andAlso attack_type <= ATKTYPE_PIERCINGKICK) then begin
      return ANIM_kick_leg;
   end
   //punch
   if weapon <= 0 then begin
      return ANIM_throw_punch;
   end
   attack_anim_arr = [ANIM_stand, ANIM_throw_punch, ANIM_kick_leg, ANIM_swing_anim, ANIM_thrust_anim, ANIM_throw_anim, ANIM_fire_single, ANIM_fire_burst, ANIM_fire_continuous];
   if attack_type == ATKTYPE_LWEP1 OrElse attack_type == ATKTYPE_RWEP1 then begin
      index = get_proto_data(obj_pid(weapon), PROTO_FLAG_EXT) bwand 0x0000000F;
   end
   else begin
      index = (get_proto_data(obj_pid(weapon), PROTO_FLAG_EXT) bwand 0x000000F0) / 16;
   end
   attack_anim = attack_anim_arr[index];
   return attack_anim;
end

procedure weapon_is_grenade(variable weapon,variable attack_type) begin
   variable attack_anim;
   variable dmg_type;
   variable is_grenade;
   if weapon <= 0 orElse attack_type < ATKTYPE_LWEP1 orElse obj_item_subtype(weapon) != item_type_weapon then begin
      return -1;
   end

   dmg_type = get_proto_data(obj_pid(weapon), PROTO_WP_DMG_TYPE);
   if dmg_type == DMG_explosion orElse dmg_type ==  DMG_plasma orElse dmg_type == DMG_emp then begin
      attack_anim = get_attack_anim(weapon, attack_type);
      if attack_anim == ANIM_throw_anim then
         is_grenade = 1;
   end

   return is_grenade;
end

procedure get_all_injures begin
   variable critter;
   variable critter_injures;
   if not(array_exists(bloody_mess_inj_arr)) then
      bloody_mess_inj_arr = create_array_map;
   else
      clear_array(bloody_mess_inj_arr);

   foreach critter in list_as_array(LIST_CRITTERS) begin
      critter_injures = (get_object_data(critter, OBJ_DATA_DAMAGE_FLAGS) bwand all_injuries);
      set_array(bloody_mess_inj_arr, critter, critter_injures);
   end
end

procedure AFTERHITROLL begin
   variable attack_result = get_sfall_arg;
   variable attacker = get_sfall_arg;
   variable target = get_sfall_arg;
   variable new_attack_result = -1;
   variable attacker_crit;
   variable attacker_luck;
   variable fail_roll;
   variable sniper;
   variable rnd;
   variable attacker_cur_ap;
   variable weapon;
   variable wpn_anim;
   variable atk_type;
   main_attacker = attacker;
   //kamikaze
   if kamikaze_hex_walked_num >= kamikaze_walk_div then begin
      kamikaze_ap_used = 1;
   end

   if jinxed > 0 then begin
      if attack_result == ROLL_FAILURE then begin
         fail_roll = jinxed_remove_and_get_roll;
         if fail_roll <= ROLL_CRITICAL_FAILURE then begin
            new_attack_result = ROLL_CRITICAL_FAILURE;
            attack_result = new_attack_result;
         end
         else begin
            skilled_prevent_crit_fail = ROLL_FAILURE;
         end
      end
   end
   // set critical miss bonus roll
   if attack_result == ROLL_CRITICAL_FAILURE then begin
      // bloody_mess increases the effect of a critical miss for an attacker by 30
      //skilled reduces chance of a critical miss for an attacker
      if skilled > 0 andAlso attacker == real_dude_obj andAlso random(0,1) then begin
         new_attack_result = ROLL_FAILURE;
      end
      if bloody_mess > 0 orElse (skilled > 0 andAlso attacker == real_dude_obj) then begin
         call add_luck_penalty(attacker,bloody_mess, skilled);
      end
   end

   // check for bloody mess attack with last ap
   if attacker == real_dude_obj andAlso bloody_mess > 0 then begin
      if bloody_mess_last_ap_attack > 0 then begin
         add_global_timer_event(0, timed_ap_debt);
         attacker_cur_ap = get_critter_current_ap(attacker);
         bloody_mess_ap_debt = 1;
         set_object_data(attacker, OBJ_DATA_CUR_ACTION_POINT, attacker_cur_ap + bloody_mess_ap_debt);
      end

      call get_all_injures;
      call give_ap_for_injures_when;
   end

   // heavy_handed reduce target dr dt
   if heavy_handed > 0 andAlso attacker == real_dude_obj andAlso attack_result >= ROLL_SUCCESS then begin
      weapon = get_object_data(combat_data, C_ATTACK_WEAPON);
      if weapon > 0 then begin
         atk_type = get_object_data(combat_data, C_ATTACK_HIT_MODE);
         if weapon_is_grenade(weapon,atk_type) > 0 then
            wpn_anim = 99;
         else begin
            wpn_anim = get_proto_data(obj_pid(weapon), PROTO_WP_ANIM);
         end
      end
      if weapon <= 0 orElse wpn_anim <= WPN_ANIM_SPEAR orElse wpn_anim == 14 orElse wpn_anim == 11 orElse wpn_anim == 12 then
         call ApplyHeavyHandedPenalty(attacker, target, weapon);
   end

   if new_attack_result >= ROLL_CRITICAL_FAILURE then begin
      set_sfall_return(new_attack_result);
      set_sfall_arg(0, new_attack_result);
      new_attack_result = -1;
      return;
   end
end

procedure check_combat_targets_death begin
   variable target = get_object_data(combat_data, C_ATTACK_TARGET);
   variable extra_target;
   variable next_num;
   variable extra_target_num_max = EXPLOSION_TARGET_COUNT * 4;
   variable dmg_value;
   variable flags;
   variable target_cur_hp;
   if target > 0 andAlso obj_type(target) == OBJ_TYPE_CRITTER then begin
      flags = get_object_data(combat_data, C_ATTACK_FLAGS_TARGET);
      if flags bwand DAM_DEAD != 0 then
         return 1;
      target_cur_hp = get_critter_stat(target, STAT_current_hp);
      dmg_value = get_object_data(combat_data, C_ATTACK_DAMAGE_TARGET);
      if target_cur_hp <= dmg_value then
         return 1;
   end
   for (next_num = 0; next_num < extra_target_num_max; next_num += 4) begin
      extra_target = get_object_data(combat_data, (C_ATTACK_TARGET1 + next_num));
      if extra_target == target then
         continue;
      if extra_target <= 0 or obj_type(target) != OBJ_TYPE_CRITTER then
         return 0;

      flags = get_object_data(combat_data, (C_ATTACK_FLAGS_TARGET1 + next_num));
      if flags bwand DAM_DEAD != 0 then
         return 1;
      target_cur_hp = get_critter_stat(target, STAT_current_hp);
      dmg_value = get_object_data(combat_data, (C_ATTACK_DAMAGE_TARGET1 + next_num));
      if target_cur_hp <= dmg_value then
         return 1;
   end
   return 0;
end

procedure COMBATDAMAGE begin
   variable target = get_sfall_arg;
   variable attacker = get_sfall_arg;
   variable dmg_to_tar = get_sfall_arg;
   variable dmg_to_atkr = get_sfall_arg;
   variable tar_flags = get_sfall_arg;
   variable atk_flags = get_sfall_arg;
   variable weapon = get_sfall_arg;
   variable bullets_num = get_sfall_arg_at(9);
   variable atk_type = get_sfall_arg_at(11);
   variable c_atk_data = get_sfall_arg_at(12);
   variable wpn_anim;
   variable new_dmg_to_tar;
   variable new_tar_flags;
   variable weapon_weight;
   variable attacker_ko_score;
   variable attacker_luck;
   variable anti_ko;
   variable target_kill_type;
   variable attacker_crit;
   variable sniper;
   variable rnd;
   variable finesse_arr_key;
   variable is_aoe_crit;
   variable actual_dude_attack;
   variable was_returned;
   variable wpn_is_grenade;
   variable wpn_dmg_type;
   variable wpn_pid;
   if attacker == real_dude_obj then begin
      actual_dude_attack = 1;
   end
   if actual_dude_attack > 0 then begin
      if weapon > 0 then begin
         wpn_pid = obj_pid(weapon);
         wpn_anim = get_proto_data(wpn_pid, PROTO_WP_ANIM);
         wpn_dmg_type = get_proto_data(wpn_pid, PROTO_WP_DMG_TYPE);
         if dmg_to_tar > 0 then
            wpn_is_grenade = weapon_is_grenade(weapon, atk_type);
      end
      //TRAIT_heavy_handed knock down
      if dmg_to_tar > 0 andAlso wpn_is_grenade == 0 then begin
         if weapon <= 0 orElse wpn_anim <= WPN_ANIM_SPEAR orElse wpn_anim == 14 orElse wpn_anim == 11 orElse wpn_anim == 12 then begin
            if not(tar_flags bwand DAM_KNOCKED_DOWN) andAlso not(tar_flags bwand DAM_KNOCKED_OUT) then begin
               if heavy_handed > 0 then begin
                  anti_ko = (get_critter_stat(target, STAT_en) * 3 + get_critter_stat(target, STAT_st) * 2) * 3;
                  target_kill_type = metarule(METARULE_CRITTER_KILL_TYPE, target);
                  if target_kill_type == KILL_TYPE_super_mutant_kills or target_kill_type == KILL_TYPE_deathclaw_kills or target_kill_type == KILL_TYPE_robot_kills or target_kill_type > 17 or power_armor_fid(obj_art_fid(target)) then begin
                     anti_ko *= 2;
                  end

                  attacker_ko_score = dmg_to_tar + (2 * get_critter_stat(attacker, STAT_st) + get_critter_stat(attacker, STAT_melee_dmg)) * 2;
                  if weapon > 0 then begin
                     weapon_weight = get_proto_data(obj_pid(weapon), PROTO_IT_WEIGHT);
                     attacker_ko_score += weapon_weight;
                  end

                  if attacker_ko_score > random(0,anti_ko) then begin
                     tar_flags = (tar_flags bwor DAM_KNOCKED_DOWN);
                     was_returned = 1;
                     set_sfall_return(dmg_to_tar);
                     set_sfall_arg(2, dmg_to_tar);
                     set_sfall_return(dmg_to_atkr);
                     set_sfall_arg(3, dmg_to_atkr);
                     set_sfall_return(tar_flags);
                     set_sfall_arg(4, tar_flags);
                  end
               end
            end
         end
      end
         //aoe attack crit
      if has_trait(TRAIT_PERK, attacker, PERK_weapon_handling_perk) > 0 orElse (has_trait(TRAIT_PERK, attacker, PERK_demolition_expert_perk) > 0 andAlso (wpn_is_grenade > 0 orElse wpn_dmg_type == DMG_explosion)) orElse (has_trait(TRAIT_PERK, attacker, PERK_pyromaniac_perk) > 0 andAlso (wpn_dmg_type == DMG_fire orElse wpn_pid == PID_MOLOTOV_COCKTAIL)) then begin
         //roll for aoe crit
         if target != get_object_data(combat_data,C_ATTACK_TARGET) then begin
            rnd = random(0, 100);
            attacker_crit = get_critter_stat(attacker, STAT_crit_chance);
            if attacker_crit >= rnd then begin
               is_aoe_crit = 1;
            end
            else begin
               if weapon > 0 then begin
                  if (wpn_anim >= WPN_ANIM_PISTOL andAlso wpn_anim <= WPN_ANIM_ROCKET_LAUNCHER) orElse wpn_anim == 13 then begin
                     sniper = has_trait(TRAIT_PERK, attacker, PERK_sniper);
                  end
                  if sniper > 0 then begin
                     rnd = random(0, 10);
                     attacker_luck = get_critter_stat(attacker, STAT_lu);
                     if attacker_luck > rnd then begin
                        is_aoe_crit = 1;
                     end
                  end
               end
            end
         end
         if target != get_object_data(combat_data,C_ATTACK_TARGET) orElse get_object_data(combat_data,C_ATTACK_AROUND_NUMBER) <= 0 andAlso target != attacker then begin
            //set additional targets damage msg from hit to crit
            if was_returned <= 0 andAlso is_aoe_crit > 0 then begin
               new_dmg_to_tar = calc_crit_dmg(attacker, target, weapon, bullets_num);
               new_tar_flags = new_dmg_to_tar / flags_offset;
               new_dmg_to_tar = new_dmg_to_tar % flags_offset;
               if new_dmg_to_tar > 0 then begin
                  tar_flags = new_tar_flags;
                  if new_dmg_to_tar > dmg_to_tar then begin
                     dmg_to_tar = new_dmg_to_tar;
                  end
                  set_sfall_return(dmg_to_tar);
                  set_sfall_arg(2, dmg_to_tar);
                  set_sfall_return(dmg_to_atkr);
                  set_sfall_arg(3, dmg_to_atkr);
                  set_sfall_return(tar_flags);
                  set_sfall_arg(4, tar_flags);
               end
            end
         end
      end
   end
end

procedure ONDEATH begin
   if bloody_mess > 0 andAlso dude_turn > 0 andAlso main_attacker == real_dude_obj then begin
      call give_ap_for_bloody_mess(real_dude_obj);
   end
end

procedure ITEMDAMAGE begin
   variable default_min_wpn_dmg;
   variable default_max_wpn_dmg;
   variable weapon;
   variable attacker = get_sfall_arg_at(3);
   variable atk_type;
   variable wpn_pid;
   variable wpn_anim;
   variable new_max_wpn_dmg;
   variable new_min_wpn_dmg;
   variable melee_dmg;
   variable wpn_max_dmg;
   variable demolition_expert_perk;
   if heavy_handed > 0 then
      call RestoreHeavyHandedPenalty;
   if (bruiser > 0 orElse heavy_handed > 0) andAlso attacker == real_dude_obj then begin
      default_min_wpn_dmg = get_sfall_arg_at(0);
      default_max_wpn_dmg = get_sfall_arg_at(1);
      weapon = get_sfall_arg_at(2);
      atk_type = get_sfall_arg_at(4);
      if weapon > 0 then begin
         wpn_pid = obj_pid(weapon);
         wpn_anim = get_proto_data(wpn_pid, PROTO_WP_ANIM);
         wpn_max_dmg = get_proto_data(wpn_pid, PROTO_WP_DMG_MAX);
      end
      if weapon <= 0 orElse (weapon_is_grenade(weapon, atk_type) == 0 andAlso (wpn_anim <= WPN_ANIM_SPEAR or wpn_anim == 0x0E or wpn_anim == 0x0B or wpn_anim == 0x0C)) then begin
         melee_dmg = get_critter_stat(attacker, STAT_melee_dmg);
         if melee_dmg < 1 then melee_dmg = 1;

         if weapon > 0 andAlso default_max_wpn_dmg < (wpn_max_dmg + melee_dmg) then begin
            default_max_wpn_dmg = (wpn_max_dmg + melee_dmg);
         end
         new_min_wpn_dmg = default_min_wpn_dmg;
         new_max_wpn_dmg = default_max_wpn_dmg;
         //TRAIT_heavy_handed min dmg
         if heavy_handed > 0 then begin
            //new_min_wpn_dmg = default_min_wpn_dmg + (melee_dmg + 1) / 2; // ecco
            new_min_wpn_dmg = default_min_wpn_dmg + melee_dmg;
            new_max_wpn_dmg = default_max_wpn_dmg;
         end
         //TRAIT_bruiser max and min dmg
         if bruiser > 0 then begin
            new_min_wpn_dmg *= 2;
            new_max_wpn_dmg *= 2;
         end

         if new_min_wpn_dmg > new_max_wpn_dmg then begin
            new_min_wpn_dmg = new_max_wpn_dmg;
         end

         default_min_wpn_dmg = new_min_wpn_dmg;
         default_max_wpn_dmg = new_max_wpn_dmg;
         if sfall_508 <= 0 then begin
            if weapon == 0 then
               is_unarmed = 1;
            else
               is_unarmed = 0;
            bruiser_heavy_handed_min_dmg = new_min_wpn_dmg;
            bruiser_heavy_handed_max_dmg = new_max_wpn_dmg - (melee_dmg * (weapon > 0));
         end
         set_sfall_return(new_min_wpn_dmg);
         set_sfall_arg(0, new_min_wpn_dmg);
         set_sfall_return(new_max_wpn_dmg);
         set_sfall_arg(1, new_max_wpn_dmg);
      end
   end
   else begin
      demolition_expert_perk = has_trait(TRAIT_PERK, real_dude_obj, PERK_demolition_expert_perk);
      if demolition_expert_perk then begin
         weapon = get_sfall_arg_at(2);
         atk_type = get_sfall_arg_at(4);
         wpn_pid = obj_pid(weapon);
         if weapon > 0 andAlso (get_proto_data(wpn_pid, PROTO_WP_DMG_TYPE) == DMG_explosion orElse weapon_is_grenade(weapon, atk_type)) then begin
            default_min_wpn_dmg = get_sfall_arg_at(0);
            default_max_wpn_dmg = get_sfall_arg_at(1);

            new_min_wpn_dmg = default_min_wpn_dmg + gDemolitionExpertBonus * demolition_expert_perk;
            new_max_wpn_dmg = default_max_wpn_dmg + gDemolitionExpertBonus * demolition_expert_perk;

            set_sfall_return(new_min_wpn_dmg);
            set_sfall_arg(0, new_min_wpn_dmg);
            set_sfall_return(new_max_wpn_dmg);
            set_sfall_arg(1, new_max_wpn_dmg);
         end
      end
   end
   if has_trait(TRAIT_PERK, real_dude_obj, PERK_weapon_handling_perk) > 0 then begin
      Lvar_wpn_max_dmg = default_max_wpn_dmg;
      Lvar_wpn_min_dmg = default_min_wpn_dmg;
   end
end


procedure get_drugs_num_effects(variable drug_pid) begin
   variable arr_key;
   variable num_effect = -1;
   arr_key = scan_array(array_drugs_ini, drug_pid);
   if arr_key >= 0 then begin
      num_effect = get_array(array_drugs_ini, (arr_key + drug_arr_numeff_offset)) - 1;
      if num_effect >= 0 then begin
         return num_effect;
      end
   end
   return num_effect;
end

procedure get_drugs_addict_time(variable drug_pid) begin
   variable arr_key;
   variable addict_time = -1;
   arr_key = scan_array(array_drugs_ini, drug_pid);
   if arr_key >= 0 then begin
      addict_time = get_array(array_drugs_ini, (arr_key + drug_arr_addict_time_offset)) - 1;
      if addict_time >= 0 then
         return addict_time;
   end
end

procedure drug_save(variable drug_obj) begin
   variable drug_pid;
   variable i;
   variable drug_stat_value;
   variable drug_stat_offset;
   variable drug_num_effects;
   if drug_obj <= 0 orElse obj_item_subtype(drug_obj) != item_type_drug then
      return;

   drug_pid = obj_pid(drug_obj);
   if modded_drug_pid > 0 then begin
      //if modded_drug_pid == drug_pid then begin
//
         //return;
      //end
      //else begin
         call drug_restore;
      //end
   end
   // create array if it doesn't exist
   if not(array_exists(drug_orig_stats)) then begin
      drug_orig_stats = create_array_list((DRUG_MAX_STATS+1));
   end
   // save drug stats
   for (i = 0; i < DRUG_MAX_STATS; i++) begin
      drug_stat_offset = (PROTO_DR_STAT_A + (i * 4));
      drug_stat_value = get_proto_data(drug_pid, drug_stat_offset);
      if drug_pid != 0 then
         set_array(drug_orig_stats, i, drug_stat_value);
   end
   set_array(drug_orig_stats, (DRUG_MAX_STATS - 1), drug_pid);
   drug_num_effects = get_drugs_num_effects(drug_pid);
   set_array(drug_orig_stats, DRUG_MAX_STATS, drug_num_effects);
end



// new drug stats for TRAIT_fast_metaboli
procedure get_new_stat_fm(variable stat_value,variable stat) begin
variable new_value = stat_value;
   if stat_value != 0 then begin
      //stat inc
      if not(stat_value > 0 andAlso (stat == STAT_current_rad orElse stat == STAT_current_poison)) then begin
         // ~33% stat inc
         new_value = 4 * stat_value / 3;
         if stat != STAT_max_move_points orElse drug_addict <= 0 then begin
            if new_value == stat_value then begin
               new_value = stat_value + 1 if stat_value > 0 else stat_value - 1;
            end
         end
      end
      //stat dec
      //else begin
         //nothing
      //end
   end
   return new_value;
end


// new stats for TRAIT_drug_addict
procedure get_new_stat_da(variable stat_value) begin
variable new_value;
   if stat_value != 0 then begin
      // ~50% stat inc
      new_value = 3 * stat_value / 2;
      if new_value == stat_value then begin
         new_value = 2 * stat_value;
      end
   end
   return new_value;
end

// new stats for TRAIT_drug_resistant
procedure get_new_stat_dr(variable stat_value,variable stat) begin
   variable new_value = stat_value;
   if stat <= STAT_poison_resist then begin
      if RegenMod > 0 andAlso stat == STAT_heal_rate then begin
         return new_value;
      end
      new_value = (ceil(stat_value / 2.0));
   end
   return new_value;
end

//all drug stats reduced
procedure drug_modify_drug_resistant(variable drug_pid, variable user) begin
   variable stat_a, stat_b, stat_c;
   variable stat_a_1, stat_a_2, stat_a_3;
   variable stat_b_1, stat_b_2, stat_b_3;
   variable stat_c_1, stat_c_2, stat_c_3;
   variable new_stat_a_1, new_stat_a_2, new_stat_a_3;
   variable new_stat_b_1, new_stat_b_2, new_stat_b_3;
   variable new_stat_c_1, new_stat_c_2, new_stat_c_3;
   variable stat_2_abc, stat_3_abc;
   variable stat_a_modded, stat_b_modded, stat_c_modded;
   variable drug_time_1, drug_time_2;
   variable new_drug_time_1, new_drug_time_2;
   variable drug_num_effects, new_drug_num_effects;
   variable addict_chance, new_addict_chance, new_addict_perk = -1;

   // Check if the drug PID is valid
   if drug_pid <= 0 then return;

   // Modify addiction chance and perk
   addict_chance = get_proto_data(drug_pid, PROTO_DR_ADDICT_CHANCE);
   if addict_chance > 0 then begin
      set_proto_data(drug_pid, PROTO_DR_ADDICT_CHANCE, new_addict_chance);
      set_proto_data(drug_pid, PROTO_DR_ADDICT_PERK, new_addict_perk);
   end
   //set new stats
   //get stat
   stat_a = get_proto_data(drug_pid, PROTO_DR_STAT_A);
   stat_a_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A);
   stat_a_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A);
   if stat_a_2 != 0 then begin
      stat_2_abc += 1;
   end
   stat_a_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A);
   if stat_a_3 != 0 then begin
      stat_3_abc += 1;
   end
   else begin
      stat_a_modded = 1;
   end
   new_stat_a_1 = stat_a_1;
   new_stat_a_2 = stat_a_2;
   new_stat_a_3 = stat_a_3;
   // stat_B
   stat_b = get_proto_data(drug_pid, PROTO_DR_STAT_B);
   //get stat a_1
   stat_b_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B);
   stat_b_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B);
   if stat_b_2 != 0 then begin
      stat_2_abc += 1;
   end
   stat_b_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B);
   if stat_b_3 != 0 then begin
      stat_3_abc += 1;
   end
   else begin
      stat_b_modded = 1;
   end
   new_stat_b_1 = stat_b_1;
   new_stat_b_2 = stat_b_2;
   new_stat_b_3 = stat_b_3;

   if drug_resist_stats(stat_a) orElse (stat_a == STAT_drug_rnd andAlso drug_resist_stats(stat_b))then begin
      // If stat_a_1 is not zero
      if stat_a_1 != 0 then begin
         new_stat_a_1 = get_new_stat_dr(stat_a_1, stat_a);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A, new_stat_a_1);
         if (stat_a_1 + stat_a_2 + stat_a_3) == 0 then begin
            new_stat_a_2 = -new_stat_a_1;
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            if stat_a_3 != 0 then begin
               new_stat_a_3 = 0;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               stat_a_modded = 1;
            end
         end
         // stat will be changed permanently
         else begin
            // check a_2 != 0
            if stat_a_2 != 0 then begin
               new_stat_a_2 = get_new_stat_dr(stat_a_2, stat_a);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
            // check a_3 != 0
            if stat_a_3 != 0 then begin
               new_stat_a_3 = get_new_stat_dr(stat_a_3, stat_a);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
            end
         end
      end
      // If stat_a_1 == 0
      else begin
         if stat_a_2 != 0 then begin
            new_stat_a_2 = get_new_stat_dr(stat_a_2, stat_a);
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            // check if stat return to normal
            if (stat_a_2 + stat_a_3) == 0 then begin
               new_stat_a_3 = -new_stat_a_2;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
            end
            // stat will be changed permanently
            else begin
               // check a_3 != 0
               if stat_a_3 != 0 then begin
                  new_stat_a_3 = get_new_stat_dr(stat_a_3, stat_a);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
            end
         end
         // If stat_a_2 is zero
         else begin
            // check a_3 != 0
            if stat_a_3 != 0 then begin
               new_stat_a_3 = get_new_stat_dr(stat_a_3, stat_a);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
            end
         end
      end
   end

   // check stat_B
   //stat_b = get_proto_data(drug_pid, PROTO_DR_STAT_B);
   if drug_resist_stats(stat_b) then begin

      // If stat_b_1 is not zero
      if stat_b_1 != 0 then begin
         new_stat_b_1 = get_new_stat_dr(stat_b_1, stat_b);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B, new_stat_b_1);
         if (stat_b_1 + stat_b_2 + stat_b_3) == 0 then begin
            new_stat_b_2 = -new_stat_b_1;
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            if stat_b_3 != 0 then begin
               new_stat_b_3 = 0;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               stat_b_modded = 1;
            end
         end
         // stat will be changed permanently
         else begin
            // check a_2 != 0
            if stat_b_2 != 0 then begin
               new_stat_b_2 = get_new_stat_dr(stat_b_2, stat_b);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
            // check a_3 != 0
            if stat_b_3 != 0 then begin
               new_stat_b_3 = get_new_stat_dr(stat_b_3, stat_b);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
            end
         end
      end
      // If stat_b_1 == 0
      else begin
         if stat_b_2 != 0 then begin
            new_stat_b_2 = get_new_stat_dr(stat_b_2, stat_b);
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
               // check if stat return to normal
            if (stat_b_2 + stat_b_3) == 0 then begin
               new_stat_b_3 = -new_stat_b_2;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
            end
            // stat will be changed permanently
            else begin
               // check a_3 != 0
               if stat_b_3 != 0 then begin
                  new_stat_b_3 = get_new_stat_dr(stat_b_3, stat_b);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
            end
         end
         // If stat_b_2 is zero
         else begin
            // check a_3 != 0
            if stat_b_3 != 0 then begin
               new_stat_b_3 = get_new_stat_dr(stat_b_3, stat_b);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
            end
         end
      end
   end
   // stat_C
   //get stat a_1
   stat_c_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C);
   stat_c_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C);
   if stat_c_2 != 0 then begin
      stat_2_abc += 1;
   end
   stat_c_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C);
   if stat_c_3 != 0 then begin
      stat_3_abc += 1;
   end
   else begin
      stat_c_modded = 1;
   end
   new_stat_c_1 = stat_c_1;
   new_stat_c_2 = stat_c_2;
   new_stat_c_3 = stat_c_3;

   stat_c = get_proto_data(drug_pid, PROTO_DR_STAT_C);
   if drug_resist_stats(stat_c) then begin

      // If stat_c_1 is not zero
      if stat_c_1 != 0 then begin
         new_stat_c_1 = get_new_stat_dr(stat_c_1, stat_c);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C, new_stat_c_1);
         if (stat_c_1 + stat_c_2 + stat_c_3) == 0 then begin
            new_stat_c_2 = -new_stat_c_1;
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            if stat_c_3 != 0 then begin
               new_stat_c_3 = 0;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               stat_c_modded = 1;
            end
         end
         // stat will be changed permanently
         else begin
            // check a_2 != 0
            if stat_c_2 != 0 then begin
               new_stat_c_2 = get_new_stat_dr(stat_c_2, stat_c);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
            // check a_3 != 0
            if stat_c_3 != 0 then begin
               new_stat_c_3 = get_new_stat_dr(stat_c_3, stat_c);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
            end
         end
      end
      // If stat_c_1 == 0
      else begin
         if stat_c_2 != 0 then begin
            new_stat_c_2 = get_new_stat_dr(stat_c_2, stat_c);
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
               // check if stat return to normal
            if (stat_c_2 + stat_c_3) == 0 then begin
               new_stat_c_3 = -new_stat_c_2;
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
            end
            // stat will be changed permanently
            else begin
               // check a_3 != 0
               if stat_c_3 != 0 then begin
                  new_stat_c_3 = get_new_stat_dr(stat_c_3, stat_c);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
            end
         end
         // If stat_c_2 is zero
         else begin
            // check a_3 != 0
            if stat_c_3 != 0 then begin
               new_stat_c_3 = get_new_stat_dr(stat_c_3, stat_c);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
            end
         end
      end
   end

   drug_num_effects = get_drugs_num_effects(drug_pid);
   if drug_num_effects > 0 then begin
      drug_num_effects += (drug_num_effects + 1) / 2;
      set_drugs_data(NumEffects, drug_pid, drug_num_effects);
   end

   if ((stat_a_modded > 0 or stat_a == -1) andAlso (stat_b_modded > 0 or stat_b == -1) andAlso (stat_c_modded > 0 or stat_c == -1)) orElse (stat_3_abc > 0 andAlso (stat_a_modded + stat_b_modded + stat_c_modded > 0)) then begin
      drug_time_1 = get_proto_data(drug_pid, PROTO_DR_DURATION_1);
      drug_time_2 = get_proto_data(drug_pid, PROTO_DR_DURATION_2);
      //drug_num_effects = get_drugs_num_effects(drug_pid);
      //remove 3rd effect
      if drug_time_2 > 0 then begin
         // reduce NumEffects if 3rd effect is erased
         if new_stat_a_3 == 0 andAlso new_stat_b_3 == 0 andAlso new_stat_c_3 == 0 then begin
            if stat_2_abc <= 0 andAlso drug_time_1 < drug_time_2 then begin
               new_drug_time_1 = drug_time_2;
               set_proto_data(drug_pid, PROTO_DR_DURATION_1, new_drug_time_1);
            end

            new_drug_time_2 = 0;
            set_proto_data(drug_pid, PROTO_DR_DURATION_2, new_drug_time_2);
            if drug_num_effects > 2 then begin
               new_drug_num_effects = drug_num_effects / 2;
               if new_drug_num_effects < 1 then
                  new_drug_num_effects = 1;

               drug_num_effects = new_drug_num_effects;
               set_drugs_data(NumEffects, drug_pid, drug_num_effects);
            end
         end
         else begin
            if drug_num_effects > 0 then begin
               drug_num_effects += (drug_num_effects + 1) / 2;
               set_drugs_data(NumEffects, drug_pid, drug_num_effects);
               if drug_time_2 > drug_time_1 * 2 then begin
                  new_drug_time_2 = drug_time_1 * 2;
                  set_proto_data(drug_pid, PROTO_DR_DURATION_2, new_drug_time_2);
               end
            end
         end
      end
   end
end

procedure drug_modify_fast_meta(variable drug_pid) begin
   variable stat_a, stat_b, stat_c;
   variable stat_a_1, stat_a_2, stat_a_3;
   variable stat_b_1, stat_b_2, stat_b_3;
   variable stat_c_1, stat_c_2, stat_c_3;
   variable new_stat_a_1, new_stat_a_2, new_stat_a_3;
   variable new_stat_b_1, new_stat_b_2, new_stat_b_3;
   variable new_stat_c_1, new_stat_c_2, new_stat_c_3;
   variable drug_time_1, drug_time_2;
   variable new_drug_time_1, new_drug_time_2;
   variable addict_chance, drug_addict_delay, drug_addict_time;
   variable new_drug_addict_time, new_drug_addict_delay;
   if drug_pid <= 0 orElse (RegenMod > 0 andAlso (drug_pid == PID_SUPER_STIMPAK orElse drug_pid == PID_HEALING_POWDER orElse drug_pid == PID_STIMPAK)) then
      return;
   //set new stats
   //check addiction and reduce it duration
   addict_chance = get_proto_data(drug_pid, PROTO_DR_ADDICT_CHANCE);
   if addict_chance > 0 then begin
      drug_addict_time = get_drugs_addict_time(drug_pid);
      if drug_addict_time <= 0 then drug_addict_time = one_week_in_min;
      new_drug_addict_time = drug_addict_time / fast_meta_duration_div;
      if new_drug_addict_time <= 0 then new_drug_addict_time = 1;
      set_drugs_data(AddictTimeOff, drug_pid, new_drug_addict_time);
      // addictin emerge faster
       drug_addict_delay = get_proto_data(drug_pid, PROTO_DR_ADDICT_DELAY);
      if drug_addict_delay > 1 then begin
         new_drug_addict_delay = drug_addict_delay / 2;
         if new_drug_addict_delay <= 0 then new_drug_addict_delay = 1;
         set_proto_data(drug_pid, PROTO_DR_ADDICT_DELAY, new_drug_addict_delay);
      end
   end
   //duration drug duration 1
   drug_time_1 = get_proto_data(drug_pid, PROTO_DR_DURATION_1);
   drug_time_2 = get_proto_data(drug_pid, PROTO_DR_DURATION_2);
   //reduce duration 1
   if drug_time_1 >= fast_meta_duration_div then begin
      new_drug_time_1 = drug_time_1 / fast_meta_duration_div;
      set_proto_data(drug_pid, PROTO_DR_DURATION_1, new_drug_time_1);
   end
   //reduce duration 1 2
   if drug_time_2 >= new_drug_time_1 + fast_meta_duration_div * 2 then begin
      new_drug_time_2 = drug_time_2 / fast_meta_duration_div;
      set_proto_data(drug_pid, PROTO_DR_DURATION_2, new_drug_time_2);
   end

   //DRUG STAT A
   stat_a = get_proto_data(drug_pid, PROTO_DR_STAT_A);
   //DRUG STAT B
   stat_b = get_proto_data(drug_pid, PROTO_DR_STAT_B);
   // Check if the drug has stats for fast_meta
   if drug_fast_meta_stats(stat_a) orElse (stat_a == STAT_drug_rnd andAlso drug_fast_meta_stats(stat_b)) then begin
      // Get stat_a_1
      stat_a_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A);
      new_stat_a_1 = stat_a_1;

      // Update stat_a_1 if it's not zero
      if stat_a_1 != 0 then begin
         new_stat_a_1 = get_new_stat_fm(stat_a_1,stat_a);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A, new_stat_a_1);
      end
      //get stat a_2 & a_3
      stat_a_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A);
      stat_a_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A);
      new_stat_a_2 = stat_a_2;
      new_stat_a_3 = stat_a_3;


      // Check if stat_a_3 is not zero so drug has all 3 timed effects
      if stat_a_3 != 0 then begin
         // Check if stat_a_2 is not zero
         if stat_a_2 != 0 then begin
            // Check if both stat_a_1 and stat_a_2 have the same sign OR stat_a_1 == 0
            if (stat_a_1 * stat_a_2) >= 0 then begin
               new_stat_a_2 = get_new_stat_fm(stat_a_2,stat_a);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
               // Check if all three stats have the same sign
               if (stat_a_1 >= 0 andAlso stat_a_2 >= 0 andAlso stat_a_3 >= 0) or (stat_a_1 <= 0 andAlso stat_a_2 <= 0 andAlso stat_a_3 <= 0) then begin
                  new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
               // If stat_a_3 does not have the same sign as stat_a_1 and stat_a_2
               else begin
                  if stat_a >= STAT_current_hp andAlso stat_a <= STAT_current_rad then begin
                     new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                  end
                  else begin
                     if stat_a_1 + stat_a_2 + stat_a_3 == 0 then begin
                        new_stat_a_3 = stat_a_3 + (stat_a_1 - new_stat_a_1) + (stat_a_2 - new_stat_a_2);
                     end
                     else begin
                        new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
            end
            // If stat_a_2 does not have the same sign as stat_a_1, adjust it
            else begin
              // set stat_a_2 and change stat_a_3
               if stat_a >= STAT_current_hp andAlso stat_a <= STAT_current_rad then begin
                  new_stat_a_2 = get_new_stat_fm(stat_a_2,stat_a);
                  new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
               // Adjust only stat_a_2
               else begin
                  if stat_a_1 + stat_a_2 + stat_a_3 == 0 then begin
                     new_stat_a_2 = stat_a_2 + (stat_a_1 - new_stat_a_1);
                  end
                  else begin
                     new_stat_a_2 = get_new_stat_fm(stat_a_2,stat_a);
                     new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                     set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
                  end
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
         end
         // If stat_a_2 is zero, adjust only stat_a_3
         else begin
            if stat_a_3 != 0 then begin
               // Check if both stat_a_1 and stat_a_3 have the same sign or stat_a_1 == 0
               if (stat_a_1 * stat_a_3) >= 0 then begin
                  new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
               // If stat_a_3 does not have the same sign as stat_a_1, adjust it
               else begin
                  if stat_a >= STAT_current_hp andAlso stat_a <= STAT_current_rad then begin
                     new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                  end
                  else begin
                     if stat_a_1 + stat_a_2 + stat_a_3 == 0 then begin
                        new_stat_a_3 = stat_a_3 + (stat_a_1 - new_stat_a_1);
                     end
                     else begin
                        new_stat_a_3 = get_new_stat_fm(stat_a_3,stat_a);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
            end
         end
      end
      // If stat_a_3 is zero, adjust stat_a_2
      else begin
         if stat_a_2 != 0 then begin
            // Check if both stat_a_1 and stat_a_2 have the same sign OR! stat_a_1 == 0
            if (stat_a_1 * stat_a_2) >= 0 then begin
               new_stat_a_2 = get_new_stat_fm(stat_a_2,stat_a);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
            // If stat_a_2 does not have the same sign as stat_a_1, adjust it
            else begin
               if stat_a >= STAT_current_hp andAlso stat_a <= STAT_current_rad then begin
                  new_stat_a_2 = get_new_stat_fm(stat_a_2,stat_a);
               end
               else begin
                  new_stat_a_2 = stat_a_2 + (stat_a_1 - new_stat_a_1);
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
         end
      end
   end

    //DRUG STAT B
   //stat_b = get_proto_data(drug_pid, PROTO_DR_STAT_B);
   // Check if the drug has stats for fast_meta
   if drug_fast_meta_stats(stat_b) then begin
      // Get stat_b_1
      stat_b_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B);
      new_stat_b_1 = stat_b_1;

      // Update stat_b_1 if it's not zero
      if stat_b_1 != 0 then begin
         new_stat_b_1 = get_new_stat_fm(stat_b_1,stat_b);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B, new_stat_b_1);
      end
      //get stat a_2 & a_3
      stat_b_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B);
      stat_b_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B);
      new_stat_b_2 = stat_b_2;
      new_stat_b_3 = stat_b_3;

      // Check if stat_b_3 is not zero so drug has all 3 timed effects
      if stat_b_3 != 0 then begin
         // Check if stat_b_2 is not zero
         if stat_b_2 != 0 then begin
            // Check if both stat_b_1 and stat_b_2 have the same sign OR stat_b_1 == 0
            if (stat_b_1 * stat_b_2) >= 0 then begin
               new_stat_b_2 = get_new_stat_fm(stat_b_2,stat_b);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
               // Check if all three stats have the same sign
               if (stat_b_1 >= 0 andAlso stat_b_2 >= 0 andAlso stat_b_3 >= 0) or (stat_b_1 <= 0 andAlso stat_b_2 <= 0 andAlso stat_b_3 <= 0) then begin
                  new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
               // If stat_b_3 does not have the same sign as stat_b_1 and stat_b_2
               else begin
                  if stat_b >= STAT_current_hp andAlso stat_b <= STAT_current_rad then begin
                     new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                  end
                  else begin
                     if stat_b_1 + stat_b_2 + stat_b_3 == 0 then begin
                        new_stat_b_3 = stat_b_3 + (stat_b_1 - new_stat_b_1) + (stat_b_2 - new_stat_b_2);
                     end
                     else begin
                        new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
            end
            // If stat_b_2 does not have the same sign as stat_b_1, adjust it
            else begin
              // set stat_b_2 and change stat_b_3
               if stat_b >= STAT_current_hp andAlso stat_b <= STAT_current_rad then begin
                  new_stat_b_2 = get_new_stat_fm(stat_b_2,stat_b);
                  new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
               // Adjust only stat_b_2
               else begin
                  if stat_b_1 + stat_b_2 + stat_b_3 == 0 then begin
                     new_stat_b_2 = stat_b_2 + (stat_b_1 - new_stat_b_1);
                  end
                  else begin
                     new_stat_b_2 = get_new_stat_fm(stat_b_2,stat_b);
                     new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                     set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
                  end
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
         end
         // If stat_b_2 is zero, adjust only stat_b_3
         else begin
            if stat_b_3 != 0 then begin
               // Check if both stat_b_1 and stat_b_3 have the same sign or stat_b_1 == 0
               if (stat_b_1 * stat_b_3) >= 0 then begin
                  new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
               // If stat_b_3 does not have the same sign as stat_b_1, adjust it
               else begin
                  if stat_b >= STAT_current_hp andAlso stat_b <= STAT_current_rad then begin
                     new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                  end
                  else begin
                     if stat_b_1 + stat_b_2 + stat_b_3 == 0 then begin
                        new_stat_b_3 = stat_b_3 + (stat_b_1 - new_stat_b_1);
                     end
                     else begin
                        new_stat_b_3 = get_new_stat_fm(stat_b_3,stat_b);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
            end
         end
      end
      // If stat_b_3 is zero, adjust stat_b_2
      else begin
         if stat_b_2 != 0 then begin
            // Check if both stat_b_1 and stat_b_2 have the same sign OR! stat_b_1 == 0
            if (stat_b_1 * stat_b_2) >= 0 then begin
               new_stat_b_2 = get_new_stat_fm(stat_b_2,stat_b);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
            // If stat_b_2 does not have the same sign as stat_b_1, adjust it
            else begin
               if stat_b >= STAT_current_hp andAlso stat_b <= STAT_current_rad then begin
                  new_stat_b_2 = get_new_stat_fm(stat_b_2,stat_b);
               end
               else begin
                  new_stat_b_2 = stat_b_2 + (stat_b_1 - new_stat_b_1);
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
         end
      end
   end


   //DRUG STAT C
   stat_c = get_proto_data(drug_pid, PROTO_DR_STAT_C);
   // Check if the drug has stats for fast_meta
   if drug_fast_meta_stats(stat_c) then begin
      // Get stat_c_1
      stat_c_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C);
      new_stat_c_1 = stat_c_1;

      // Update stat_c_1 if it's not zero
      if stat_c_1 != 0 then begin
         new_stat_c_1 = get_new_stat_fm(stat_c_1,stat_c);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C, new_stat_c_1);
      end
      //get stat a_2 & a_3
      stat_c_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C);
      stat_c_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C);
      new_stat_c_2 = stat_c_2;
      new_stat_c_3 = stat_c_3;


      // Check if stat_c_3 is not zero so drug has all 3 timed effects
      if stat_c_3 != 0 then begin
         // Check if stat_c_2 is not zero
         if stat_c_2 != 0 then begin
            // Check if both stat_c_1 and stat_c_2 have the same sign OR stat_c_1 == 0
            if (stat_c_1 * stat_c_2) >= 0 then begin
               new_stat_c_2 = get_new_stat_fm(stat_c_2,stat_c);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
               // Check if all three stats have the same sign
               if (stat_c_1 >= 0 andAlso stat_c_2 >= 0 andAlso stat_c_3 >= 0) or (stat_c_1 <= 0 andAlso stat_c_2 <= 0 andAlso stat_c_3 <= 0) then begin
                  new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
               // If stat_c_3 does not have the same sign as stat_c_1 and stat_c_2
               else begin
                  if stat_c >= STAT_current_hp andAlso stat_c <= STAT_current_rad then begin
                     new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                  end
                  else begin
                     if stat_c_1 + stat_c_2 + stat_c_3 == 0 then begin
                        new_stat_c_3 = stat_c_3 + (stat_c_1 - new_stat_c_1) + (stat_c_2 - new_stat_c_2);
                     end
                     else begin
                        new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
            end
            // If stat_c_2 does not have the same sign as stat_c_1, adjust it
            else begin
              // set stat_c_2 and change stat_c_3
               if stat_c >= STAT_current_hp andAlso stat_c <= STAT_current_rad then begin
                  new_stat_c_2 = get_new_stat_fm(stat_c_2,stat_c);
                  new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
               // Adjust only stat_c_2
               else begin
                  if stat_c_1 + stat_c_2 + stat_c_3 == 0 then begin
                     new_stat_c_2 = stat_c_2 + (stat_c_1 - new_stat_c_1);
                  end
                  else begin
                     new_stat_c_2 = get_new_stat_fm(stat_c_2,stat_c);
                     new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                     set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
                  end
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
         end
         // If stat_c_2 is zero, adjust only stat_c_3
         else begin
            if stat_c_3 != 0 then begin
               // Check if both stat_c_1 and stat_c_3 have the same sign or stat_c_1 == 0
               if (stat_c_1 * stat_c_3) >= 0 then begin
                  new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
               // If stat_c_3 does not have the same sign as stat_c_1, adjust it
               else begin
                  if stat_c >= STAT_current_hp andAlso stat_c <= STAT_current_rad then begin
                     new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                  end
                  else begin
                     if stat_c_1 + stat_c_2 + stat_c_3 == 0 then begin
                        new_stat_c_3 = stat_c_3 + (stat_c_1 - new_stat_c_1);
                     end
                     else begin
                        new_stat_c_3 = get_new_stat_fm(stat_c_3,stat_c);
                     end
                  end
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
            end
         end
      end
      // If stat_c_3 is zero, adjust stat_c_2
      else begin
         if stat_c_2 != 0 then begin
            // Check if both stat_c_1 and stat_c_2 have the same sign OR! stat_c_1 == 0
            if (stat_c_1 * stat_c_2) >= 0 then begin
               new_stat_c_2 = get_new_stat_fm(stat_c_2,stat_c);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
            // If stat_c_2 does not have the same sign as stat_c_1, adjust it
            else begin
               if stat_c >= STAT_current_hp andAlso stat_c <= STAT_current_rad then begin
                  new_stat_c_2 = get_new_stat_fm(stat_c_2,stat_c);
               end
               else begin
                  new_stat_c_2 = stat_c_2 + (stat_c_1 - new_stat_c_1);
               end
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
         end
      end
   end
end



procedure drug_modify_drug_addict(variable drug_pid) begin
   variable stat_a, stat_b, stat_c;
   variable stat_a_1, stat_a_2, stat_a_3;
   variable stat_b_1, stat_b_2, stat_b_3;
   variable stat_c_1, stat_c_2, stat_c_3;
   variable new_stat_a_1, new_stat_a_2, new_stat_a_3;
   variable new_stat_b_1, new_stat_b_2, new_stat_b_3;
   variable new_stat_c_1, new_stat_c_2, new_stat_c_3;
   variable drug_time_1, drug_time_2;
   variable new_drug_time_1, new_drug_time_2;
   if drug_pid <= 0 then
      return;
   //set new stats
   //stat A
   stat_a = get_proto_data(drug_pid, PROTO_DR_STAT_A);
   stat_b = get_proto_data(drug_pid, PROTO_DR_STAT_B);
   if drug_addict_stats(stat_a) orElse (stat_a == STAT_drug_rnd andAlso drug_addict_stats(stat_b)) then begin
      //get stat a_1
      stat_a_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A);
      new_stat_a_1 = stat_a_1;
      if stat_a_1 != 0 then begin
         new_stat_a_1 = get_new_stat_da(stat_a_1);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A, new_stat_a_1);
      end
      //get stat a_2 & a_3
      stat_a_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A);
      stat_a_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A);
      new_stat_a_2 = stat_a_2;
      new_stat_a_3 = stat_a_3;
      // Check if stat_a_3 is not zero so drug has all 3 timed effects
      if stat_a_3 != 0 then begin
         // Check if stat_a_2 is not zero
         if stat_a_2 != 0 then begin
            // Check if both stat_a_1 and stat_a_2 have the same sign OR stat_a_1 == 0
            if (stat_a_1 * stat_a_2) >= 0 then begin
               new_stat_a_2 = get_new_stat_da(stat_a_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
               // Check if all three stats have the same sign
               if (stat_a_1 >= 0 andAlso stat_a_2 >= 0 andAlso stat_a_3 >= 0) or (stat_a_1 <= 0 andAlso stat_a_2 <= 0 andAlso stat_a_3 <= 0) then begin
                  new_stat_a_3 = get_new_stat_da(stat_a_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
               // If stat_a_3 does not have the same sign as stat_a_1 and stat_a_2, adjust it to break even
               else begin
                  new_stat_a_3 = stat_a_3 + (stat_a_1 - new_stat_a_1) + (stat_a_2 - new_stat_a_2);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
            end
            // If stat_a_2 does not have the same sign as stat_a_1, adjust it
            else begin
              // Adjust only stat_a_2 without affecting stat_a_3
              new_stat_a_2 = stat_a_2 + (stat_a_1 - new_stat_a_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
         end
         // If stat_a_2 is zero, adjust only stat_a_3
         else begin
            if stat_a_3 != 0 then begin
               // Check if both stat_a_1 and stat_a_3 have the same sign or stat_a_1 == 0
               if (stat_a_1 * stat_a_3) >= 0 then begin
                  new_stat_a_3 = get_new_stat_da(stat_a_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
               // If stat_a_3 does not have the same sign as stat_a_1, adjust it
               else begin
                  new_stat_a_3 = stat_a_3 + (stat_a_1 - new_stat_a_1);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, new_stat_a_3);
               end
            end
         end
      end
      // If stat_a_3 is zero, adjust stat_a_2
      else begin
         if stat_a_2 != 0 then begin
            // Check if both stat_a_1 and stat_a_2 have the same sign OR! stat_a_1 == 0
            if (stat_a_1 * stat_a_2) >= 0 then begin
               new_stat_a_2 = get_new_stat_da(stat_a_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
            // If stat_a_2 does not have the same sign as stat_a_1, adjust it
            else begin
              new_stat_a_2 = stat_a_2 + (stat_a_1 - new_stat_a_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, new_stat_a_2);
            end
         end
      end
   end

   //stat B
    if drug_addict_stats(stat_b) then begin
      //get stat a_1
      stat_b_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B);
      new_stat_b_1 = stat_b_1;
      if stat_b_1 != 0 then begin
         new_stat_b_1 = get_new_stat_da(stat_b_1);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_B, new_stat_b_1);
      end
      //get stat a_2 & a_3
      stat_b_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B);
      stat_b_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B);
      new_stat_b_2 = stat_b_2;
      new_stat_b_3 = stat_b_3;
      // Check if stat_b_3 is not zero so drug has all 3 timed effects
      if stat_b_3 != 0 then begin
         // Check if stat_b_2 is not zero
         if stat_b_2 != 0 then begin
            // Check if both stat_b_1 and stat_b_2 have the same sign OR stat_b_1 == 0
            if (stat_b_1 * stat_b_2) >= 0 then begin
               new_stat_b_2 = get_new_stat_da(stat_b_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
               // Check if all three stats have the same sign
               if (stat_b_1 >= 0 andAlso stat_b_2 >= 0 andAlso stat_b_3 >= 0) or (stat_b_1 <= 0 andAlso stat_b_2 <= 0 andAlso stat_b_3 <= 0) then begin
                  new_stat_b_3 = get_new_stat_da(stat_b_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
               // If stat_b_3 does not have the same sign as stat_b_1 and stat_b_2, adjust it to break even
               else begin
                  new_stat_b_3 = stat_b_3 + (stat_b_1 - new_stat_b_1) + (stat_b_2 - new_stat_b_2);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
            end
            // If stat_b_2 does not have the same sign as stat_b_1, adjust it
            else begin
              // Adjust only stat_b_2 without affecting stat_b_3
              new_stat_b_2 = stat_b_2 + (stat_b_1 - new_stat_b_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
         end
         // If stat_b_2 is zero, adjust only stat_b_3
         else begin
            if stat_b_3 != 0 then begin
               // Check if both stat_b_1 and stat_b_3 have the same sign or stat_b_1 == 0
               if (stat_b_1 * stat_b_3) >= 0 then begin
                  new_stat_b_3 = get_new_stat_da(stat_b_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
               // If stat_b_3 does not have the same sign as stat_b_1, adjust it
               else begin
                  new_stat_b_3 = stat_b_3 + (stat_b_1 - new_stat_b_1);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_B, new_stat_b_3);
               end
            end
         end
      end
      // If stat_b_3 is zero, adjust stat_b_2
      else begin
         if stat_b_2 != 0 then begin
            // Check if both stat_b_1 and stat_b_2 have the same sign OR! stat_b_1 == 0
            if (stat_b_1 * stat_b_2) >= 0 then begin
               new_stat_b_2 = get_new_stat_da(stat_b_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
            // If stat_b_2 does not have the same sign as stat_b_1, adjust it
            else begin
              new_stat_b_2 = stat_b_2 + (stat_b_1 - new_stat_b_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_B, new_stat_b_2);
            end
         end
      end
   end

   //stat C
   stat_c = get_proto_data(drug_pid, PROTO_DR_STAT_C);
   if drug_addict_stats(stat_c) then begin
      //get stat a_1
      stat_c_1 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C);
      new_stat_c_1 = stat_c_1;
      if stat_c_1 != 0 then begin
         new_stat_c_1 = get_new_stat_da(stat_c_1);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_C, new_stat_c_1);
      end
      //get stat a_2 & a_3
      stat_c_2 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C);
      stat_c_3 = get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C);
      new_stat_c_2 = stat_c_2;
      new_stat_c_3 = stat_c_3;
      // Check if stat_c_3 is not zero so drug has all 3 timed effects
      if stat_c_3 != 0 then begin
         // Check if stat_c_2 is not zero
         if stat_c_2 != 0 then begin
            // Check if both stat_c_1 and stat_c_2 have the same sign OR stat_c_1 == 0
            if (stat_c_1 * stat_c_2) >= 0 then begin
               new_stat_c_2 = get_new_stat_da(stat_c_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
               // Check if all three stats have the same sign
               if (stat_c_1 >= 0 andAlso stat_c_2 >= 0 andAlso stat_c_3 >= 0) or (stat_c_1 <= 0 andAlso stat_c_2 <= 0 andAlso stat_c_3 <= 0) then begin
                  new_stat_c_3 = get_new_stat_da(stat_c_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
               // If stat_c_3 does not have the same sign as stat_c_1 and stat_c_2, adjust it to break even
               else begin
                  new_stat_c_3 = stat_c_3 + (stat_c_1 - new_stat_c_1) + (stat_c_2 - new_stat_c_2);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
            end
            // If stat_c_2 does not have the same sign as stat_c_1, adjust it
            else begin
              // Adjust only stat_c_2 without affecting stat_c_3
              new_stat_c_2 = stat_c_2 + (stat_c_1 - new_stat_c_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
         end
         // If stat_c_2 is zero, adjust only stat_c_3
         else begin
            if stat_c_3 != 0 then begin
               // Check if both stat_c_1 and stat_c_3 have the same sign or stat_c_1 == 0
               if (stat_c_1 * stat_c_3) >= 0 then begin
                  new_stat_c_3 = get_new_stat_da(stat_c_3);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
               // If stat_c_3 does not have the same sign as stat_c_1, adjust it
               else begin
                  new_stat_c_3 = stat_c_3 + (stat_c_1 - new_stat_c_1);
                  set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_C, new_stat_c_3);
               end
            end
         end
      end
      // If stat_c_3 is zero, adjust stat_c_2
      else begin
         if stat_c_2 != 0 then begin
            // Check if both stat_c_1 and stat_c_2 have the same sign OR! stat_c_1 == 0
            if (stat_c_1 * stat_c_2) >= 0 then begin
               new_stat_c_2 = get_new_stat_da(stat_c_2);
               set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
            // If stat_c_2 does not have the same sign as stat_c_1, adjust it
            else begin
              new_stat_c_2 = stat_c_2 + (stat_c_1 - new_stat_c_1);
              set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_C, new_stat_c_2);
            end
         end
      end
   end
   // inc duration
   if RegenMod <= 0 orElse (drug_pid != PID_HEALING_POWDER andAlso drug_pid != PID_SUPER_STIMPAK) then begin
      drug_time_1 = get_proto_data(drug_pid, PROTO_DR_DURATION_1);
      drug_time_2 = get_proto_data(drug_pid, PROTO_DR_DURATION_2);
      if drug_time_1 > 0 then begin
         new_drug_time_1 = get_new_stat_da(drug_time_1);
         set_proto_data(drug_pid, PROTO_DR_DURATION_1, new_drug_time_1);
      end
      if drug_time_2 > 0 then begin
         new_drug_time_2 = get_new_stat_da(drug_time_2);
         set_proto_data(drug_pid, PROTO_DR_DURATION_2, new_drug_time_2);
      end
   end
end

procedure dude_traits_changed(variable trait_1, variable trait_2) begin
   variable traits_have_changed;
   if dude_trait_1 != trait_1 then begin
      dude_trait_1 = trait_1;
      traits_have_changed = 1;
   end
   if dude_trait_2 != trait_2 then begin
      dude_trait_2 = trait_2;
      traits_have_changed = 1;
   end
   if traits_have_changed > 0 then begin
      call drug_restore;
   end
   return traits_have_changed;
end

procedure sfall_4_set_unarmed_dmg_bytes begin
   if read_byte(0x47253A) == 0xEB then
      return;

   write_byte(0x47253A, 0xEB);
end

procedure sfall_4_unset_unarmed_dmg_bytes begin
   if read_byte(0x47253A) == 0x75 then
      return;

   write_byte(0x47253A, 0x75);
end

procedure get_real_dude_traits begin
   variable trait_1 = read_int(0x66BE40);
   variable trait_2 = read_int(0x66BE44);
   variable traits_have_changed = dude_traits_changed(trait_1, trait_2);

   if traits_have_changed > 0 then begin
      if fast_metabolism >= 0 andAlso fast_metabolism < 2 then begin
         if ((trait_1 == TRAIT_fast_metabolism) orElse (trait_2 == TRAIT_fast_metabolism)) then begin
            fast_metabolism = 1;
            if fast_metabolism_MMR_regen <= 0 andAlso timer_is_up <= 0 then begin
               add_global_timer_event(50, timed_hp_regen);
               timer_is_up = 1;
            end
         end else begin
            fast_metabolism = 0;
         end
      end

      if bruiser >= 0 andAlso bruiser < 2 then begin
         if ((trait_1 == TRAIT_bruiser) orElse (trait_2 == TRAIT_bruiser)) then begin
            bruiser = 1;
         end else begin
            bruiser = 0;
         end
      end

     if small_frame >= 0 andAlso small_frame < 2 then begin
         if ((trait_1 == TRAIT_small_frame) orElse (trait_2 == TRAIT_small_frame)) then begin
            small_frame = 1;
         end else begin
            small_frame = 0;
         end
      end

      if one_hander >= 0 andAlso one_hander < 2 then begin
         if ((trait_1 == TRAIT_one_hander) orElse (trait_2 == TRAIT_one_hander)) then begin
            one_hander = 1;
            //call one_hander_uncripple;
         end
         else begin
            //call one_hander_cripple;
            call one_hander_bonus_remove;
            one_hander = 0;
         end
      end

      if finesse >= 0 andAlso finesse < 2 then begin
         if ((trait_1 == TRAIT_finesse) orElse (trait_2 == TRAIT_finesse)) then begin
            finesse = 1;
         end else begin
            finesse = 0;
         end
      end

      if kamikaze >= 0 andAlso kamikaze < 2 then begin
         if ((trait_1 == TRAIT_kamikaze) orElse (trait_2 == TRAIT_kamikaze)) then begin
            kamikaze = 1;
         end else begin
            kamikaze = 0;
         end
      end

      if heavy_handed >= 0 andAlso heavy_handed < 2 then begin
         if ((trait_1 == TRAIT_heavy_handed) orElse (trait_2 == TRAIT_heavy_handed)) then begin
            heavy_handed = 1;
         end else begin
            heavy_handed = 0;
         end
      end

      if bloody_mess >= 0 andAlso bloody_mess < 2 then begin
         if (trait_1 == TRAIT_bloody_mess) orElse (trait_2 == TRAIT_bloody_mess) then begin
            bloody_mess = 1;
            // allow bloody mess to affect player death
            if sfall_508 <= 0 andAlso bloody_mess_player_death_changed <= 0 then begin
               write_byte(0x410700, 0x31);
               write_byte(0x410701, 0xC0);
               bloody_mess_player_death_changed = 1;
            end
         end else begin
            if bloody_mess_player_death_changed > 0 then begin
               write_byte(0x410700, 0x75);
               write_byte(0x410701, 0x16);
               bloody_mess_player_death_changed = 0;
            end
            bloody_mess = 0;
         end
      end

      if jinxed >= 0 andAlso jinxed < 2 then begin
         if (trait_1 == TRAIT_jinxed) orElse (trait_2 == TRAIT_jinxed) then begin
            jinxed = 1;
         end else begin
            jinxed = 0;
         end
      end

      if drug_addict >= 0 andAlso drug_addict < 2 then begin
         if ((trait_1 == TRAIT_drug_addict) orElse (trait_2 == TRAIT_drug_addict)) then begin
            drug_addict = 1;
            drug_addict_stat_check_array = create_array_map;
            call da_radaway_timer;
         end else begin
            drug_addict = 0;
         end
      end

      if drug_resistant >= 0 andAlso drug_resistant < 2 then begin
         if ((trait_1 == TRAIT_drug_resistant) orElse (trait_2 == TRAIT_drug_resistant)) then begin
            drug_resistant = 1;
         end else begin
            drug_resistant = 0;
         end
      end

      if skilled >= 0 andAlso skilled < 2 then begin
         if ((trait_1 == TRAIT_skilled) orElse (trait_2 == TRAIT_skilled)) then begin
            skilled = 1;
         end else begin
            skilled = 0;
         end
      end
      if heavy_handed > 0 orElse bruiser > 0 then begin
         call sfall_4_set_unarmed_dmg_bytes;
      end
      else begin
         call sfall_4_unset_unarmed_dmg_bytes;
      end
   end

   gFasterHealingPerk = has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing);
   if timer_is_up <= 0 andAlso fast_metabolism_MMR_regen <= 0 andAlso gFasterHealingPerk >= 2 then begin
      add_global_timer_event(50, timed_hp_regen);
      timer_is_up = 1;
   end

   return traits_have_changed;
end

procedure can_mod_drugs(variable drug_pid) begin
   variable prohibed_drugs;
   variable can_mod = 1;
   if RegenMod > 0 andAlso drug_pid == PID_STIMPAK then
      return;

   if Nevada > 0 then begin
      prohibed_drugs = [90, 295, 472, 480, 481, 724, 732, 750, 764];
   end
   else begin
      prohibed_drugs = [PID_JET_ANTIDOTE, 480, 481, 480, 482];
   end

   if is_in_array(drug_pid, prohibed_drugs) then
      can_mod = 0;

   return can_mod;
end

procedure get_xp_mod begin
   variable lvl = get_pc_stat(PCSTAT_level);
   variable old_xp = get_pc_stat(PCSTAT_experience);
   variable new_xp;
   variable test_amount = 100;
   //set xp to 0
   write_int(0x6681B4, 0);
   // set lvl to 100
   write_int(0x6681B0, 100);

   give_exp_points(test_amount);
   new_xp = get_pc_stat(PCSTAT_experience);

   write_int(0x6681B4, old_xp);
   write_int(0x6681B0, lvl);

   if (new_xp != 0) then
      return ((new_xp * 100) / test_amount);
   else
      return 0;
end

procedure get_da_mentats_bonus begin
   variable current;
   current = get_array(drug_addict_array, DA_DRUG_MENTATS);
   if (current == 0) then
      return 0;
   else begin
      current = 4 + (current % 100000) / 1000;
      if current > 15 then
         current = 15;
      return current;
   end
end

procedure set_da_mentats_bonus(variable new_bonus) begin
   variable current;
   variable doses;
   variable perk_level;
   variable flag;
   variable new_value;

   current = get_array(drug_addict_array, DA_DRUG_MENTATS);

   doses = current % 1000;
   perk_level = (current / 1000) % 100;
   flag = current / 1000000;

   new_value = doses + (perk_level * 1000) + (new_bonus * 100000) + (flag * 1000000);

   set_array(drug_addict_array, DA_DRUG_MENTATS, new_value);
end

procedure da_set_xp_mod() begin
   variable cur_xp_mod;
   variable da_cur_bonus = get_da_mentats_bonus();
   if (da_cur_bonus == 0) then
      return;

   cur_xp_mod = get_xp_mod();
   last_xp_mod = cur_xp_mod + da_cur_bonus;
   set_xp_mod(last_xp_mod);
end

procedure add_da_xp_mod(variable da_full_bonus, variable bonus_to_add) begin
   variable cur_xp_mod = get_xp_mod;
   variable new_total_mod;
   if cur_xp_mod != last_xp_mod then begin
      if cur_xp_mod < last_xp_mod orElse cur_xp_mod > 130 then
         new_total_mod = cur_xp_mod + da_full_bonus + bonus_to_add;
      else
         new_total_mod = cur_xp_mod + bonus_to_add;
   end
   else
      new_total_mod = cur_xp_mod + bonus_to_add;

   last_xp_mod = new_total_mod;

   set_xp_mod(new_total_mod);
end

procedure inc_all_dmg_res(variable target, variable bonus_to_add) begin
   variable i;

   if bonus_to_add == 0 then
      return;

   for (i := STAT_dmg_resist; i <= STAT_dmg_resist_explosion; i++) begin
      set_critter_extra_stat(target, i, get_critter_extra_stat(target, i) + bonus_to_add);
   end
end

procedure drug_addict_add_perk(variable normalized_pid, variable perk_lvl) begin
   variable bonus;
   variable dr_bonus;
   variable crit_bonus;
   variable cur_xp_mod;

   // PID_MENTATS
   if normalized_pid == DA_DRUG_MENTATS then begin
      bonus = 4 + perk_lvl;
      if (perk_lvl == 1) then begin
         set_fake_perk(da_mentats_perk_name, 1, 140, sprintf(da_mentats_perk_desc1, bonus));
         call add_da_xp_mod(0, bonus);
      end
      else if (perk_lvl >= 2 and perk_lvl <= 11) then begin
         if bonus <= 7 then
            set_fake_perk(da_mentats_perk_name, 1, 140, sprintf(da_mentats_perk_desc1, bonus));
         else begin
            set_fake_perk(da_mentats_perk_name, 1, 140, sprintf(da_mentats_perk_desc2, bonus));
         end

         call add_da_xp_mod(bonus, 1);
      end
      else if (perk_lvl >= 12) then begin
         set_critter_base_stat(real_dude_obj, STAT_iq, get_critter_base_stat(real_dude_obj, STAT_iq) + 1);
         set_fake_perk(da_mentats_perk_name, 1, 140, sprintf(da_mentats_perk_desc3, bonus-1));
         display_msg(da_mentats_add_msg);
         return DA_LAST_PERK;
      end
      display_msg(da_mentats_add_msg);
   end
   //PID_BUFFOUT
   else if (normalized_pid == DA_DRUG_BUFFOUT) then begin
      bonus = 3 + perk_lvl * 2;
      if (perk_lvl == 1) then begin
         set_critter_extra_stat(real_dude_obj, STAT_carry_amt, get_critter_extra_stat(real_dude_obj, STAT_carry_amt) + bonus);
         set_fake_perk(da_buffout_perk_name, 1, 126, sprintf(da_buffout_perk_desc1, bonus));
      end
      else if (perk_lvl >= 2 and perk_lvl <= 10) then begin
         if perk_lvl <= 5 then
            set_fake_perk(da_buffout_perk_name, 1, 126, sprintf(da_buffout_perk_desc1, bonus));
         else begin
            set_fake_perk(da_buffout_perk_name, 1, 126, sprintf(da_buffout_perk_desc2, bonus));
            set_critter_base_stat(real_dude_obj, STAT_st, get_critter_base_stat(real_dude_obj, STAT_st) + 1);
         end
         set_critter_extra_stat(real_dude_obj, STAT_carry_amt, get_critter_extra_stat(real_dude_obj, STAT_carry_amt) + 2);
      end
      else if (perk_lvl >= 11) then begin
         set_critter_extra_stat(real_dude_obj, STAT_carry_amt, get_critter_extra_stat(real_dude_obj, STAT_carry_amt) + 2);
         set_critter_base_stat(real_dude_obj, STAT_en, get_critter_base_stat(real_dude_obj, STAT_en) + 1);
         set_fake_perk(da_buffout_perk_name, 1, 155, sprintf(da_buffout_perk_desc3, bonus));
         display_msg(da_buffout_add_msg);
         return DA_LAST_PERK;
      end
      display_msg(da_buffout_add_msg);
   end
    //PID_PSYCHO
   else if (normalized_pid == DA_DRUG_PSYCHO) then begin
      if (perk_lvl == 1) then begin
         dr_bonus = 1;
         crit_bonus = 1;
         call inc_all_dmg_res(real_dude_obj, dr_bonus);
         set_critter_extra_stat(real_dude_obj, STAT_crit_chance, get_critter_extra_stat(real_dude_obj, STAT_crit_chance) + crit_bonus);
         set_fake_perk(da_psycho_perk_name, 1, 144, sprintf2(da_psycho_perk_desc1, dr_bonus, crit_bonus));
         display_msg(da_psycho_add_msg);
      end
      else if (perk_lvl >= 2 and perk_lvl <= 9) then begin
         if (perk_lvl % 2 == 0) then begin
             call inc_all_dmg_res(real_dude_obj, 1);
         end else begin
             set_critter_extra_stat(real_dude_obj, STAT_crit_chance, get_critter_extra_stat(real_dude_obj, STAT_crit_chance) + 1);
         end

         dr_bonus = (perk_lvl / 2) + 1;
         crit_bonus = ((perk_lvl + 1) / 2);

         if (perk_lvl <= 5) then
             set_fake_perk(da_psycho_perk_name, 1, 144, sprintf2(da_psycho_perk_desc1, dr_bonus, crit_bonus));
         else
             set_fake_perk(da_psycho_perk_name, 1, 144, sprintf2(da_psycho_perk_desc2, dr_bonus, crit_bonus));

         display_msg(da_psycho_add_msg);
      end
      else if (perk_lvl >= 10) then begin
         dr_bonus = ((perk_lvl - 1) / 2) + 1;
         crit_bonus = (perk_lvl) / 2;
         set_critter_base_stat(real_dude_obj, STAT_ag, get_critter_base_stat(real_dude_obj, STAT_ag) + 1);
         set_fake_perk(da_psycho_perk_name, 1, 144, sprintf2(da_psycho_perk_desc3, dr_bonus, crit_bonus));
         display_msg(da_psycho_add_msg);
         return DA_LAST_PERK;
      end
   end
   // PID_JET
   else if (normalized_pid == DA_DRUG_JET) then begin
      if (perk_lvl == 1) then begin
         bonus = 2;
         set_critter_extra_stat(real_dude_obj, STAT_sequence, get_critter_extra_stat(real_dude_obj, STAT_sequence) + bonus);
         set_fake_perk(da_jet_perk_name, 1, 24, sprintf(da_jet_perk_desc1, bonus));
      end
      else if (perk_lvl == 5 orElse perk_lvl == 10) then begin
         bonus = 3;
         if (perk_lvl == 5) then begin
            set_critter_extra_stat(real_dude_obj, STAT_sequence, get_critter_extra_stat(real_dude_obj, STAT_sequence) + 1);
            set_fake_perk(da_jet_perk_name, 1, 24, sprintf(da_jet_perk_desc1, bonus));
         end
         else if perk_lvl == 10 then begin
            set_fake_perk(da_jet_perk_name, 1, 24, sprintf(da_jet_perk_desc2, bonus));
            set_critter_base_stat(real_dude_obj, STAT_pe, get_critter_base_stat(real_dude_obj, STAT_pe) + 1);
         end
      end
      else if (perk_lvl >= 15) then begin
         bonus = 3;
         set_critter_extra_stat(real_dude_obj, STAT_max_move_points, get_critter_extra_stat(real_dude_obj, STAT_max_move_points) + 1);
         set_fake_perk(da_jet_perk_name, 1, 136, sprintf(da_jet_perk_desc3, bonus));
         display_msg(da_jet_add_msg);
         return DA_LAST_PERK;
      end
      if perk_lvl == 1 orElse perk_lvl == 5 orElse perk_lvl == 10 then
         display_msg(da_jet_add_msg);
   end
   // Cadaveric amphetamine
   else if normalized_pid == DA_DRUG_NEVADA_AP_DRUGS then begin
      if (perk_lvl == 1) then begin
         set_critter_extra_stat(real_dude_obj, STAT_max_move_points, get_critter_extra_stat(real_dude_obj, STAT_max_move_points) + 1);
         set_fake_perk(da_nevada_amph_perk_name, 1, 24, sprintf(da_nevada_amph_perk_desc1, bonus));
         display_msg(da_nevada_amph_add_msg);
         return DA_LAST_PERK;
      end
   end
   // PID_NUKA_COLA
   else if normalized_pid == DA_DRUG_NUKACOLA then begin
      if (perk_lvl == 4 orElse perk_lvl == 10 orElse perk_lvl == 16 orElse perk_lvl == 22 orElse perk_lvl == 29) then begin
         bonus = 1 + perk_lvl / 6;
         set_critter_extra_stat(real_dude_obj, STAT_ac, get_critter_extra_stat(real_dude_obj, STAT_ac) + 1);
         set_critter_extra_stat(real_dude_obj, STAT_sequence, get_critter_extra_stat(real_dude_obj, STAT_sequence) + 1);
         if perk_lvl < 12 then
            set_fake_perk(da_nukacola_perk_name, 1, 101, sprintf(da_nukacola_perk_desc1, bonus));
         else if perk_lvl < 25 then
            set_fake_perk(da_nukacola_perk_name, 1, 101, sprintf(da_nukacola_perk_desc2, bonus));
         else begin
            set_fake_perk(da_nukacola_perk_name, 1, 101, sprintf(da_nukacola_perk_desc3, 5));
            display_msg(da_nukacola_add_msg);
            return DA_LAST_PERK;
         end
         display_msg(da_nukacola_add_msg);
      end
   end
   // PID_RADAWAY
   else if normalized_pid == DA_DRUG_RADAWAY then begin
      if (perk_lvl == 6) then begin
         register_hook_proc(HOOK_ADJUSTRADS, ADJUSTRADS);
         set_fake_perk(da_radaway_perk_name, 1, 12, sprintf(da_radaway_perk_desc1, 0));
         display_msg(da_radaway_add_msg);
         call da_radaway_timer;
         return DA_LAST_PERK;
      end
   end
   //ALCOHOL
   else if normalized_pid == DA_DRUG_ALCOHOL then begin
      if (perk_lvl >= 30) then begin
         set_critter_base_stat(real_dude_obj, STAT_ch, get_critter_base_stat(real_dude_obj, STAT_ch) + 1);
         set_fake_perk(da_alcohol_perk_name, 1, 3, sprintf(da_alcohol_perk_desc1, 0));
         display_msg(da_alcohol_add_msg);
         return DA_LAST_PERK;
      end
   end
end

procedure get_min_doses_for_level(variable perk_lvl, variable luck) begin
   variable multiplier = (100.0 + (8 - luck) * 8);
   variable min_doses = ceil((perk_lvl * multiplier) / 100.0);
   if min_doses < 1 then
      min_doses = 1;

   return min_doses;
end

procedure get_perk_chance(variable luck) begin
   variable chance = (50 + (luck * 5));
   return chance;
end

procedure get_guarantee_threshold(variable luck) begin
   if luck >= 9 then
      return 0;

   return 3 - (luck / 3);
end

procedure da_normalize_pid(variable drug_pid) begin
   if (Nevada <= 0 andAlso drug_pid == PID_MENTATS) orElse (Nevada andAlso (drug_pid == PID_MENTATS_NEVADA orElse drug_pid == PID_MENTATS_AROM)) orElse (Olympus2207 andAlso (drug_pid == PID_OLYMP_BRAINNIAC orElse drug_pid == PID_OLYMP_DROP)) then begin
      return DA_DRUG_MENTATS;
   end
   else if drug_pid == PID_BUFFOUT orElse (drug_pid == PID_ECCO_HERCULES) orElse (Olympus2207 andAlso (drug_pid == PID_OLYMP_STRONGHOLD orElse drug_pid == PID_OLYMP_DROP)) then begin
      return DA_DRUG_BUFFOUT;
   end
   else if (drug_pid == PID_PSYCHO orElse (Nevada andAlso drug_pid == PID_NEVADA_FIGHTING_STIM)) orElse (Olympus2207 andAlso drug_pid == PID_OLYMP_RESISTANOL) then begin
      return DA_DRUG_PSYCHO;
   end
   else if (Nevada <= 0 andAlso drug_pid == PID_JET) orElse (Olympus2207 andAlso drug_pid == PID_OLYMP_COMBATID) then begin
      return DA_DRUG_JET;
   end
   else if (Nevada andAlso (drug_pid == PID_NEVADA_CADAVER_AMPHET orElse drug_pid == PID_NEVADA_DIESEL_GUM)) then begin
      return DA_DRUG_NEVADA_AP_DRUGS;
   end
   else if (is_pid_cola(drug_pid)) then begin
      return DA_DRUG_NUKACOLA;
   end
   else if (drug_pid == PID_RAD_X) then begin
      return DA_DRUG_RADX;
   end
   else if (drug_pid == PID_RADAWAY orElse (Nevada andAlso drug_pid == PID_NEVADA_NUT_SOLUTION)) then begin
      return DA_DRUG_RADAWAY;
   end
   else if (is_pid_alcohol(drug_pid) orElse (Nevada andAlso drug_pid == PID_NEVADA_CARAMEL)) then begin
      return DA_DRUG_ALCOHOL;
   end

   return 0;
end

procedure drug_addict_add_dose(variable drug_pid) begin
   variable current;
   variable doses;
   variable perk_level;
   variable bad_luck_counter;
   variable luck;
   variable chance;
   variable guarantee;
   variable roll;
   variable is_last_perk_lvl;
   variable normalized_pid = da_normalize_pid(drug_pid);
   variable is_gifted;
   variable min_doses;

   if (normalized_pid == 0) then
      return;

   current = get_array(drug_addict_array, normalized_pid);
   if (current / DA_LAST_PERK) > 0 then
      return;

   doses = current % 1000;
   perk_level = (current / 1000) % 100;
   bad_luck_counter = (current / 100000) % 1000;
   is_last_perk_lvl = (current / DA_LAST_PERK) * DA_LAST_PERK;

   luck = get_critter_stat(dude_obj, STAT_lu);
   doses += 1;
   is_gifted = has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_gifted);

   min_doses = get_min_doses_for_level(perk_level + 1, luck);
   // gifted nerf
   if is_gifted then
      min_doses = (min_doses * 3) / 2;

   if (doses >= min_doses) then begin
      if (perk_level == 0) then begin
         perk_level += 1;
         bad_luck_counter = 0;
         is_last_perk_lvl = drug_addict_add_perk(normalized_pid, perk_level);
      end
      else begin
         roll = random(1, 100);
         chance = get_perk_chance(luck) - 20 * is_gifted;
         guarantee = get_guarantee_threshold(luck);

         if (roll <= chance orElse bad_luck_counter >= guarantee) then begin
            perk_level += 1;
            bad_luck_counter = 0;
            is_last_perk_lvl = drug_addict_add_perk(normalized_pid, perk_level);
         end
         else begin
            bad_luck_counter += 1;
         end
      end
   end

   if (doses > 999) then
      doses = 999;

   if (perk_level > 99) then
      perk_level = 99;

   drug_addict_array[normalized_pid] = doses + (perk_level * 1000) + (bad_luck_counter * 100000) + is_last_perk_lvl;
end

procedure drug_addict_stat_check begin
   variable target = get_array(drug_addict_stat_check_array, -3);
   variable drug_pid = get_array(drug_addict_stat_check_array, -2);
   variable stat;
   variable value;

   if drug_pid <= 0 orElse target <= 0 then
      return;

   foreach stat:value in drug_addict_stat_check_array begin
      if stat >= STAT_st andAlso stat <= STAT_current_rad andAlso get_critter_stat(target, stat) != value then begin
         da_check = 0;
         call drug_addict_add_dose(drug_pid);
         return;
      end
   end
   da_check = 0;
end

procedure drug_addict_stat_check_set(variable target, variable drug_pid) begin
   variable stat;
   variable value;
   variable i;
   clear_array(drug_addict_stat_check_array);

   set_array(drug_addict_stat_check_array, -3, target);
   set_array(drug_addict_stat_check_array, -2, drug_pid);
   for (i := 0; i <= 2; i++) begin
      stat = get_proto_data(drug_pid, PROTO_DR_STAT_A + (4 * i));
      if stat >= STAT_st andAlso stat <= STAT_current_rad then
         set_array(drug_addict_stat_check_array, stat, get_critter_stat(target, stat));
   end
   da_check = 1;
end

procedure NUKA_COLA_MODIFY(variable drug_obj) begin
   variable drug_pid = obj_pid(drug_obj);
   variable stat;
   variable value;
   variable i;
   variable has_immediate_effect;
   variable stat_is_cur_hp = -1;
   variable total_effect;

   if not(is_pid_cola(drug_pid)) then
      return;

   for (i = 0; i <= 2; i++) begin
      stat = get_proto_data(drug_pid, PROTO_DR_STAT_A + (4 * i));
      value = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A + (4 * i));

      if stat >= STAT_st andAlso value != 0 then
         has_immediate_effect = 1;
      else if stat == STAT_current_hp then
         stat_is_cur_hp = i;
   end

   if has_immediate_effect == 0 then begin
      if stat_is_cur_hp != -1 then begin
         i = stat_is_cur_hp;
         total_effect = get_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A + (4 * i))
                      + get_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A + (4 * i))
                      + get_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A + (4 * i));

         if total_effect >= 0 then
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A + (4 * i), 1);
         else
            set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A + (4 * i), -1);
      end
      else begin
         set_proto_data(drug_pid, PROTO_DR_STAT_A, STAT_current_hp);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_1_A, 1);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_2_A, 0);
         set_proto_data(drug_pid, PROTO_DR_AMOUNT_3_A, 0);
      end
   end
end


procedure drug_modify(variable drug_obj, variable target) begin
   variable drug_pid;
   if target <= 0 orElse drug_obj <= 0 orElse obj_item_subtype(drug_obj) != item_type_drug then
      return;

   drug_pid = obj_pid(drug_obj);

   call NUKA_COLA_MODIFY(drug_obj);

   if drug_addict > 0 andAlso target == real_dude_obj then
      call drug_addict_stat_check_set(real_dude_obj, drug_pid);

   if can_mod_drugs(drug_pid) <= 0 then
      return;

   if target == real_dude_obj then begin
      call get_real_dude_traits;

      call drug_save(drug_obj);
      modded_drug_pid = drug_pid;
      if drug_resistant > 0 then begin
         call drug_modify_drug_resistant(drug_pid, target);//should be first
      end
      if drug_addict > 0 then begin
         call drug_modify_drug_addict(drug_pid);
      end
      if fast_metabolism > 0 then begin
         call drug_modify_fast_meta(drug_pid);
      end
   end
   else begin
      if modded_drug_pid > 0 then begin
         call drug_restore;
      end
   end
end

procedure USEOBJON begin
   variable target;
   variable obj;
   if fast_metabolism > 0 orElse drug_resistant > 0 orElse drug_addict > 0 then begin
      target = get_sfall_arg_at(0);
      obj = get_sfall_arg_at(2);
      call drug_modify(obj,target);
   end
end

//checking and installing the perks.ini file with changing trait descriptions
procedure set_traits_desc begin
   variable trait_desc;
   variable new_trait_desc;
   variable trait_num;
   variable trait_ini_path_desc;
   variable trait_stat_mod;
   variable traits_to_ignore = [TRAIT_fast_shot, TRAIT_good_natured, TRAIT_sex_appeal, TRAIT_gifted];
   variable trait_plus_desc;
   variable trait_ini_path_desc_plus;
   variable ini_was_set;

   variable version = get_ini_string(perks_ini_path + "|Traits|Traits_plus_version");
   if version != traits_plus_cur_version then begin
      set_ini_setting(perks_ini_path+"|Traits|Traits_plus_version",traits_plus_cur_version);
      ini_was_set = 1;
   end
   for (trait_num = 0; trait_num < MAX_TRAITS; trait_num++) begin
      if is_in_array(trait_num,traits_to_ignore) then begin
         continue;
      end
      trait_ini_path_desc = perks_ini_path+"|t" + trait_num + "|Desc";
      new_trait_desc = trait_msg(trait_desc_offset + trait_num);
      if Sonora > 0 andAlso trait_num == TRAIT_bloody_mess then begin
         new_trait_desc = trait_msg((trait_desc_offset*10) + trait_num);
      end
      else if et_tu > 0 andAlso trait_num == TRAIT_skilled then begin
         new_trait_desc = trait_msg((trait_desc_offset*10) + trait_num);
      end
      trait_desc = get_ini_string(trait_ini_path_desc);
      //if new_version <= 0 then begin
         trait_ini_path_desc_plus = perks_ini_path + "|t" + trait_num + "|Traits_plus_desc_is_set";
         trait_plus_desc = get_ini_setting(trait_ini_path_desc_plus);
      //end
      //if trait_desc != new_trait_desc then begin
      if get_array(disabled_traits_arr,trait_num) != trait_num + 1 then begin
         if trait_plus_desc <= 0 orElse ini_was_set > 0 then begin
            set_ini_setting(trait_ini_path_desc, new_trait_desc);
            set_ini_setting(trait_ini_path_desc_plus, 1);
            ini_was_set = 1;
         end

         if trait_num == TRAIT_fast_metabolism then begin
            // TRAIT_fast_metabolism + 4 heal_rate
            trait_stat_mod = get_ini_string(perks_ini_path+"|t0|StatMod");
            if trait_stat_mod == "" orElse trait_stat_mod <= 0 then begin
               set_ini_setting(perks_ini_path+"|t0|StatMod","14|4");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_bruiser then begin
            // TRAIT_bruiser + 10 HP
            trait_stat_mod = get_ini_string(perks_ini_path+"|t1|StatMod");
            if trait_stat_mod == "" orElse trait_stat_mod <= 0 then begin
               set_ini_setting(perks_ini_path+"|t1|StatMod","7|10");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_finesse then begin
            // TRAIT_finesse +10 crit roll
            trait_stat_mod = get_ini_string(perks_ini_path+"|t4|StatMod");
            if trait_stat_mod == "" orElse trait_stat_mod <= 0 then begin
               set_ini_setting(perks_ini_path+"|t4|StatMod","16|10");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_kamikaze then begin
            // TRAIT_kamikaze + 5 seq
            trait_stat_mod = get_ini_string(perks_ini_path+"|t5|StatMod");
            if trait_stat_mod == "" orElse trait_stat_mod <= 0 then begin
               set_ini_setting(perks_ini_path+"|t5|StatMod","13|5");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_drug_resistant then begin
            // TRAIT_drug_resistant + 1 en
            trait_stat_mod = get_ini_string(perks_ini_path+"|t12|StatMod");
            if trait_stat_mod == "" orElse trait_stat_mod <= 0 then begin
               set_ini_setting(perks_ini_path+"|t12|StatMod","2|1");
               ini_was_set = 1;
            end
         end
      end
      else begin
         if trait_desc != "" andAlso trait_desc == new_trait_desc then begin
            set_ini_setting(trait_ini_path_desc, "");
            set_ini_setting(trait_ini_path_desc_plus, 0);
            ini_was_set = 1;
         end
         if trait_num == TRAIT_bruiser then begin
            // TRAIT_bruiser - 10 HP
            trait_stat_mod = get_ini_string(perks_ini_path+"|t1|StatMod");
            if trait_stat_mod == "7|10" then begin
               set_ini_setting(perks_ini_path+"|t1|StatMod","");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_finesse then begin
            // TRAIT_finesse -10 crit roll
             trait_stat_mod = get_ini_string(perks_ini_path+"|t4|StatMod");
             if trait_stat_mod == "16|10" then begin
                 set_ini_setting(perks_ini_path+"|t4|StatMod","");
                 ini_was_set = 1;
             end
         end
         else if trait_num == TRAIT_kamikaze then begin
            // TRAIT_kamikaze - 5 seq
            trait_stat_mod = get_ini_string(perks_ini_path+"|t5|StatMod");
            if trait_stat_mod == "13|5" then begin
               set_ini_setting(perks_ini_path+"|t5|StatMod","");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_drug_resistant then begin
            // TRAIT_drug_resistant - 1 en
            trait_stat_mod = get_ini_string(perks_ini_path+"|t12|StatMod");
            if trait_stat_mod == "2|1" then begin
               set_ini_setting(perks_ini_path+"|t12|StatMod","");
               ini_was_set = 1;
            end
         end
         else if trait_num == TRAIT_fast_metabolism then begin
            // TRAIT_fast_metabolism - 4 heal_rate
            trait_stat_mod = get_ini_string(perks_ini_path+"|t0|StatMod");
            if trait_stat_mod == "14|4" then begin
               set_ini_setting(perks_ini_path+"|t0|StatMod","");
               ini_was_set = 1;
            end
         end
      end
   end
   return ini_was_set;
end



procedure check_traits_desc begin
   variable traits_enabled = get_ini_setting(perks_ini_path+"|Traits|Enable");
   variable ini_was_set;
   if traits_enabled <= 0 then begin
      set_ini_setting(perks_ini_path+"|Traits|Enable", 1);
      ini_was_set = 1;
   end
   ini_was_set = ini_was_set + set_traits_desc;
   return ini_was_set;
end


procedure check_drugs_pid begin
   variable drug_count = get_ini_setting(drugs_ini_path+"|main|Count");
   variable drug_pid;
   variable drug_num;
   variable drug_num_effects;
   variable drug_addict_time_ini;
   variable new_drug_count;
   variable new_drug_count_num;
   variable drug_array_key;
   variable drug_ini_array_key;
   variable drugs_ini_path_drug_num;
   variable drugs_array;
   variable ini_was_set;
   if Nevada > 0 then begin
      drugs_array = [PID_MENTATS_NEVADA, PID_PSYCHO, PID_JET, PID_BUFFOUT, PID_NEVADA_FIGHTING_STIM, PID_MENTATS_AROM];
   end
   else begin
      drugs_array = [PID_MENTATS, PID_PSYCHO, PID_JET, PID_BUFFOUT];
   end
   array_drugs_ini = create_array_map;
   if drug_count < 0 then drug_count = 0;
   // Loop through drugs in ini
   for (drug_num = 1; drug_num <= drug_count; drug_num++) begin
      drugs_ini_path_drug_num = drugs_ini_path + "|" + drug_num;
      drug_pid = get_ini_setting(drugs_ini_path_drug_num + "|PID");
      if drug_pid <= 0 then
         continue;

         drug_ini_array_key = (drug_num - 1) * 3;
         set_array(array_drugs_ini, drug_ini_array_key + drug_arr_pid_offset, drug_pid);
         set_array(array_drugs_ini, drug_ini_array_key + drug_arr_numeff_offset, base_map_arr_num);
         set_array(array_drugs_ini, drug_ini_array_key + drug_arr_addict_time_offset, base_map_arr_num);
         drug_num_effects = 1 + get_ini_setting(drugs_ini_path_drug_num + "|NumEffects");
         drug_array_key = scan_array(drugs_array, drug_pid);
         if drug_array_key >= 0 then begin
            set_array(drugs_array, drug_array_key, 0);
            if drug_num_effects <= 0 then
               drug_num_effects = 5;
         end
         set_array(array_drugs_ini, drug_ini_array_key + drug_arr_numeff_offset, drug_num_effects);

         drug_addict_time_ini = 1 + get_ini_setting(drugs_ini_path_drug_num + "|AddictTime");
         if drug_addict_time_ini > 0 then begin
            set_array(array_drugs_ini, drug_ini_array_key + drug_arr_addict_time_offset, drug_addict_time_ini);
         end
         else begin
            drug_addict_time_ini = one_week_in_min;
            set_array(array_drugs_ini, drug_ini_array_key + drug_arr_addict_time_offset, (drug_addict_time_ini + 1) );
         end

   end
   // Update drug count in INI if new drugs were added
   foreach drug_pid in drugs_array begin
      if drug_pid > 0 then begin
         new_drug_count += 1;
      end
   end
   if new_drug_count > 0 then begin
      ini_was_set = 1;
      set_ini_setting(drugs_ini_path + "|main|Count", (drug_count + new_drug_count));
      // Add base drugs
      new_drug_count = 0;
      drug_num = 0;
      foreach drug_pid in drugs_array begin
         drug_num += 1;
         if drug_pid > 0 then begin
            new_drug_count += 1;
            new_drug_count_num = drug_count + new_drug_count;
            drugs_ini_path_drug_num = drugs_ini_path + "|" + new_drug_count_num;
            set_ini_setting(drugs_ini_path_drug_num + "|PID",drug_pid);
            if Nevada > 0 andAlso (drug_pid == PID_NEVADA_FIGHTING_STIM orElse drug_pid == PID_PSYCHO) then begin
               set_ini_setting(drugs_ini_path_drug_num + "|NumEffects", 1);
            end
            else if Nevada > 0 andAlso drug_pid == PID_JET then begin
               if get_proto_data(PID_JET,PROTO_DR_STAT_A) != STAT_max_move_points andAlso get_proto_data(PID_JET,PROTO_DR_STAT_B) != STAT_max_move_points andAlso get_proto_data(PID_JET,PROTO_DR_STAT_C) != STAT_max_move_points then begin
                  set_ini_setting(drugs_ini_path_drug_num + "|NumEffects", 0);
               end
               else begin
                  set_ini_setting(drugs_ini_path_drug_num + "|NumEffects",4);
                  set_ini_setting(drugs_ini_path_drug_num + "|AddictTime",one_week_in_min);
               end
            end
            else begin
               set_ini_setting(drugs_ini_path_drug_num + "|NumEffects",4);
               set_ini_setting(drugs_ini_path_drug_num + "|AddictTime",one_week_in_min);
            end
            set_array(array_drugs_ini, (new_drug_count_num) + drug_arr_pid_offset, drug_pid);
            set_array(array_drugs_ini, (new_drug_count_num) + drug_arr_numeff_offset, 4);
            set_array(array_drugs_ini, (new_drug_count_num) + drug_arr_addict_time_offset, one_week_in_min);
         end
      end
   end
   free_array(drugs_array);
   return ini_was_set;
end

procedure game_close begin
   variable msg = trait_msg(msg_traits_set)+"\n"+trait_msg(msg_restart_game);
   game_ui_enable;
   message_box_flags(msg, MSGBOX_NORMAL);
   display_msg(msg);
   write_byte(0x481B2A, 0xB8);
   write_int(0x481B2B, 27);
   sfall_func0("signal_close_game");
end

procedure set_ddraw_ini begin
   if get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|PoisonMod") > 0 orElse get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|RegenMod") > 0 orElse get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|SecondaryAttackMod") > 0 orElse get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|StealRebalance") > 0  then begin
      if get_ini_setting("ddraw.ini|Misc|SpeedInterfaceCounterAnims") != 2 then
         set_ini_setting("ddraw.ini|Misc|SpeedInterfaceCounterAnims", 2);
   end
end

procedure check_ini_path begin
   variable perks_ini_not_set;
   variable drugs_ini_not_set;
   variable common_ini_path = -1;
   variable ini_was_set;
   variable common_ini_path_arr;
   perks_ini_path = get_ini_string(ddraw_perks_ini_path);
   drugs_ini_path = get_ini_string(ddraw_drugs_ini_path);
   if perks_ini_path == "" orElse perks_ini_path < 0 then begin
      perks_ini_not_set = 1;
   end
   else begin
      if len_array(get_ini_sections(perks_ini_path)) <= 0 then
         perks_ini_not_set = 1;
      else begin
         common_ini_path_arr = string_split(perks_ini_path, default_perks_ini_name);
         if len_array(common_ini_path_arr) <= 1 then
            common_ini_path_arr = string_split(perks_ini_path, default_perks_ini_name2);

         if len_array(common_ini_path_arr) > 1 then
            common_ini_path = get_array(common_ini_path_arr, 0);
      end
   end

   if drugs_ini_path == "" orElse drugs_ini_path < 0 then begin
      drugs_ini_not_set = 1;
   end
   else begin
      if len_array(get_ini_sections(drugs_ini_path)) <= 0 then
         drugs_ini_not_set = 1;
      else begin
         if common_ini_path == "" orElse common_ini_path < 0 then begin
            common_ini_path_arr = string_split(drugs_ini_path, default_drugs_ini_name);
            if len_array(common_ini_path_arr) <= 1 then
               common_ini_path_arr = string_split(drugs_ini_path, default_drugs_ini_name2);

            if len_array(common_ini_path_arr) > 1 then
               common_ini_path = get_array(common_ini_path_arr, 0);
         end
      end
   end

   if perks_ini_not_set > 0 then begin
      if common_ini_path == "" orElse common_ini_path < 0 then begin
         perks_ini_path = default_perks_ini_path;
      end
      else begin
         perks_ini_path = common_ini_path+default_perks_ini_name;
      end
      set_ini_setting(ddraw_perks_ini_path,  perks_ini_path);
      perks_ini_not_set = 0;
      ini_was_set = 1;
   end
   if drugs_ini_not_set > 0 then begin
      if common_ini_path == "" orElse common_ini_path < 0 then begin
         drugs_ini_path = default_drugs_ini_path;
      end
      else begin
         drugs_ini_path = common_ini_path+default_drugs_ini_name;
      end
      set_ini_setting(ddraw_drugs_ini_path, drugs_ini_path);
      drugs_ini_not_set = 0;
      ini_was_set = 1;
   end
   if get_ini_setting("ddraw.ini|Debugging|AllowUnsafeScripting") <= 0 then begin
      set_ini_setting("ddraw.ini|Debugging|AllowUnsafeScripting", 2 - (ver_major != 4));
      ini_was_set = 1;
   end
   ini_was_set += check_traits_desc + check_drugs_pid;
   if ini_was_set > 0 then begin
      call set_ddraw_ini;
      call game_close in 1;
   end
end

procedure COMBATTURN begin
   variable turn_status = get_sfall_arg;
   variable critter = get_sfall_arg;
   variable remaining;

   if turn_status >= 1 andAlso critter == dude_obj then begin
      main_attacker = dude_obj;
      dude_turn = 1;
   end
   else
      dude_turn = 0;

   bloody_mess_bonus_count = 0;
   if kamikaze_hex_walked_num > 0 then begin
      kamikaze_hex_walked_num = 0;
      intface_redraw;
   end

   if (fast_metabolism orElse gFasterHealingPerk >= 2) andAlso fast_metabolism_MMR_regen <= 0 andAlso critter == real_dude_obj andAlso turn_status == COMBAT_TURN_END then begin
      remaining = 50 - ((game_time - gLastRegenTime) % 50);
      if (remaining <= 0) then
         remaining = 50;

      remove_timer_event(timed_hp_regen);
      call apply_regen_tick_simple(real_dude_obj, 1);
      gLastRegenTime = game_time + 50;
      add_global_timer_event(remaining + 50, timed_hp_regen);
      timer_is_up = 1;
   end
end

procedure set_dude_traits_from_ini begin
   disabled_traits_arr = create_array_map;

   fast_metabolism = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Fast_Metabolism");
   if fast_metabolism <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_fast_metabolism, (TRAIT_fast_metabolism + 1));
      fast_metabolism = -1;
   end
   else if get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|RegenMod") > 0 then
      fast_metabolism_MMR_regen = 1;

   bruiser = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Bruiser");
   if bruiser <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_bruiser, (TRAIT_bruiser + 1));
      bruiser = -1;
   end

   small_frame = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Small_Frame");
   if small_frame <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_small_frame, (TRAIT_small_frame + 1));
      small_frame = -1;
   end
   else begin
      set_ini_setting("ddraw.ini|Misc|SmallFrameFix", 1);
   end

   one_hander = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|One_Hander");
   if one_hander <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_one_hander, (TRAIT_one_hander + 1));
      one_hander = -1;
      call one_hander_bonus_remove;
   end
   //else begin
      //if one_hander >= 2 then begin
         //call one_hander_uncripple;
      //end
   //end

   finesse = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Finesse");
   if finesse <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_finesse, (TRAIT_finesse + 1));
      finesse = -1;
   end

   kamikaze = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Kamikaze");
   if kamikaze <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_kamikaze, (TRAIT_kamikaze + 1));
      kamikaze = -1;
   end

   heavy_handed = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Heavy_Handed");
   if heavy_handed <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_heavy_handed, (TRAIT_heavy_handed + 1));
      heavy_handed = -1;
   end

   bloody_mess = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Bloody_Mess");
   if bloody_mess <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_bloody_mess, (TRAIT_bloody_mess + 1));
      bloody_mess = -1;
   end

   jinxed = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Jinxed");
   if jinxed <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_jinxed, (TRAIT_jinxed + 1));
      jinxed = -1;
   end

   drug_addict = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Chem_Reliant");
   if drug_addict <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_drug_addict, (TRAIT_drug_addict + 1));
      drug_addict = -1;
   end
   else begin
      drug_addict_array = load_array(ARRAY_CHEM_NAME);
      if (drug_addict_array == 0) then begin
         v1_2_new_install = 1;
         drug_addict_array = create_array_map;
         save_array(ARRAY_CHEM_NAME, drug_addict_array);
      end
   end

   drug_resistant = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Chem_Resistant");
   if drug_resistant <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_drug_resistant, (TRAIT_drug_resistant + 1));
      drug_resistant = -1;
   end

   skilled = get_ini_setting("mods\\F2MechanicsMiniRework.ini|TraitsPlus|Skilled");
   if skilled <= 0 then begin
      set_array(disabled_traits_arr, TRAIT_skilled, (TRAIT_skilled + 1));
      skilled = -1;
   end
end

procedure rm_traits_desc begin
   variable trait_num;
   variable new_trait_desc;
   variable trait_ini_path_desc;
   variable trait_desc;
   variable trait_stat_mod;
   variable perks_ini_path = get_ini_string(ddraw_perks_ini_path);
   variable traits_to_ignore = [TRAIT_fast_shot, TRAIT_good_natured, TRAIT_sex_appeal, TRAIT_gifted];
   variable traits_plus_enabled = get_ini_string(perks_ini_path+"|Traits|Traits_plus_version");
   variable trait_ini_path_desc_plus;
   variable trait_plus_desc;
   variable ini_was_set;
   if traits_plus_enabled != "" andAlso traits_plus_enabled != "0" andAlso traits_plus_enabled != 0 then begin
      for (trait_num = 0; trait_num < MAX_TRAITS; trait_num++) begin
         trait_ini_path_desc_plus = perks_ini_path + "|t" + trait_num + "|Traits_plus_desc_is_set";
         trait_plus_desc = get_ini_setting(trait_ini_path_desc_plus);
         if trait_plus_desc <= 0 then begin
            continue;
         end
         trait_ini_path_desc = perks_ini_path+"|t" + trait_num + "|Desc";
         new_trait_desc = trait_msg(trait_desc_offset + trait_num);
      if Sonora > 0 andAlso trait_num == TRAIT_bloody_mess then begin
         new_trait_desc = trait_msg((trait_desc_offset*10) + trait_num);
      end
         trait_desc = get_ini_string(trait_ini_path_desc);
         if trait_desc == new_trait_desc then begin
            set_ini_setting(trait_ini_path_desc, "");
            ini_was_set = 1;
         end
         set_ini_setting(trait_ini_path_desc_plus,0);
      end

      trait_stat_mod = get_ini_string(perks_ini_path+"|t0|StatMod");
      if trait_stat_mod == "14|4" then begin
         set_ini_setting(perks_ini_path+"|t0|StatMod","");
         ini_was_set = 1;
      end
      trait_stat_mod = get_ini_string(perks_ini_path+"|t1|StatMod");
      if trait_stat_mod == "7|10" then begin
         set_ini_setting(perks_ini_path+"|t1|StatMod","");
         ini_was_set = 1;
      end
      trait_stat_mod = get_ini_string(perks_ini_path+"|t4|StatMod");
      if trait_stat_mod == "16|10" then begin
         set_ini_setting(perks_ini_path+"|t4|StatMod","");
         ini_was_set = 1;
      end
      trait_stat_mod = get_ini_string(perks_ini_path+"|t5|StatMod");
      if trait_stat_mod == "13|5" then begin
         set_ini_setting(perks_ini_path+"|t5|StatMod","");
         ini_was_set = 1;
      end
      trait_stat_mod = get_ini_string(perks_ini_path+"|t12|StatMod");
      if trait_stat_mod == "2|1" then begin
         set_ini_setting(perks_ini_path+"|t12|StatMod","");
         ini_was_set = 1;
      end


      set_ini_setting(perks_ini_path+"|Traits|Traits_plus_version",0);
      if ini_was_set > 0 then begin
         call game_close in 1;
      end
   end
   return ini_was_set;
end

procedure get_and_set_perk_level_mod begin
   variable dude_lvl = dude_level;
   variable test_perk = PERK_here_and_now_perk;
   variable test_perk_rank;
   variable i;
   variable perk_lvl_mod;
   if last_lvl == dude_level then
      return;
   last_lvl = dude_level;
   set_perk_level(test_perk, dude_lvl);
   if has_trait(TRAIT_PERK, real_dude_obj,PERK_here_and_now_perk) then begin
      if get_perk_available(test_perk) <= 0 then
         test_perk_rank = 1;
         set_perk_ranks(test_perk, 2);
   end


   if get_perk_available(test_perk) then begin
      for (i := 1; i <= 25; i++) begin
         set_perk_level(test_perk, (dude_lvl + i));
         if get_perk_available(test_perk) <= 0 then
            break;
      end
      perk_lvl_mod = i-1;
   end
   else begin
      for (i := 1; i >= -25; i--) begin
         set_dude_level(dude_lvl - i);
         if get_perk_available(test_perk) > 0 then
            break;
      end
      perk_lvl_mod = i;
      set_dude_level(dude_lvl);
   end

   if skilled_last_perk_level_bonus != perk_lvl_mod then begin
      perk_lvl_mod += skilled_perk_level_bonus;
      set_perk_level_mod(perk_lvl_mod);
      skilled_last_perk_level_bonus = perk_lvl_mod;
   end
   if test_perk_rank > 0 then
      set_perk_ranks(test_perk, test_perk_rank);
   set_perk_level(test_perk, 3);
   if skilled_last_perk_level_bonus != perk_lvl_mod then begin
      set_perk_level_mod(perk_lvl_mod);
      skilled_last_perk_level_bonus = perk_lvl_mod;
   end
   return perk_lvl_mod;
end

procedure get_atk_mode(variable cur_active_hand) begin
   variable hand = (0x5970F8 + (cur_active_hand * 0x18));
   variable current_mode_adr = hand + 0x10;
   variable current_mode = read_int(current_mode_adr);
   variable current_attack_type;
   if current_mode >= 1 andAlso current_mode <= 2 then
      current_attack_type = read_int(hand + 0x8);
   else if current_mode >= 3 andAlso current_mode <= 4 then
      current_attack_type = read_int(hand + 0xC);

   return current_attack_type;
end

inline procedure restore_proto_dmg begin
   if bruiser_heavy_handed_pid_0 > 0 then begin
      set_proto_data(bruiser_heavy_handed_pid_0, PROTO_WP_DMG_MIN, bruiser_heavy_handed_min_0);
      set_proto_data(bruiser_heavy_handed_pid_0, PROTO_WP_DMG_MAX, bruiser_heavy_handed_max_0);
      bruiser_heavy_handed_pid_0 = 0;
   end
   if bruiser_heavy_handed_pid_1 > 0 then begin
      set_proto_data(bruiser_heavy_handed_pid_1, PROTO_WP_DMG_MIN, bruiser_heavy_handed_min_1);
      set_proto_data(bruiser_heavy_handed_pid_1, PROTO_WP_DMG_MAX, bruiser_heavy_handed_max_1);
      bruiser_heavy_handed_pid_1 = 0;
   end
end

inline procedure set_proto_dmg(variable wpn_pid, variable new_min_dmg, variable new_max_dmg) begin
   if bruiser_heavy_handed_pid_0 != wpn_pid andAlso bruiser_heavy_handed_pid_1 != wpn_pid then begin
      if bruiser_heavy_handed_pid_0 <= 0 then begin
         bruiser_heavy_handed_pid_0 = wpn_pid;
         bruiser_heavy_handed_min_0 = get_proto_data(bruiser_heavy_handed_pid_0, PROTO_WP_DMG_MIN);
         bruiser_heavy_handed_max_0 = get_proto_data(bruiser_heavy_handed_pid_0, PROTO_WP_DMG_MAX);
      end
      else if bruiser_heavy_handed_pid_1 <= 0 then begin
         bruiser_heavy_handed_pid_1 = wpn_pid;
         bruiser_heavy_handed_min_1 = get_proto_data(bruiser_heavy_handed_pid_1, PROTO_WP_DMG_MIN);
         bruiser_heavy_handed_max_1 = get_proto_data(bruiser_heavy_handed_pid_1, PROTO_WP_DMG_MAX);
      end
      set_proto_data(wpn_pid, PROTO_WP_DMG_MIN, new_min_dmg);
      set_proto_data(wpn_pid, PROTO_WP_DMG_MAX, new_max_dmg);
   end
end

procedure show_dude_new_dmg begin
   variable item;
   variable wpn_pid;
   variable ATKTYPE;
   variable new_min_dmg;
   variable new_max_dmg;
   variable display_dmg_msg;
   variable i;
   call restore_proto_dmg;
   if ((get_game_mode bwand INVENTORY) != 0) andAlso loot_obj <= 0 then begin
      intface_redraw;
      for (i= 0; i < 2; i++) begin
         item = critter_inven_obj2(real_dude_obj, INVEN_TYPE_LEFT_HAND - i);
         if item == 0 orElse (item > 0 andAlso obj_item_subtype(item) == item_type_weapon) then begin
            ATKTYPE = get_atk_mode(i);
            call_offset_v2(0x478448, real_dude_obj, ATKTYPE);
            new_min_dmg = bruiser_heavy_handed_min_dmg;
            new_max_dmg = bruiser_heavy_handed_max_dmg;
            if item <= 0 andAlso is_unarmed > 0 then begin
               display_dmg_msg = message_str_game(GAME_MSG_INVENTRY, 24);
               SetTextColor(0.0, 1.0, 0.0);
               SetFont(101);
               sfall_func2("interface_overlay", WINTYPE_INVENTORY, 1);
               overlay_created = 1;
               interface_print(display_dmg_msg+" "+new_min_dmg+"-"+new_max_dmg, WINTYPE_INVENTORY, 297, 154 + 40 * i, 0);
            end
            else if new_min_dmg != 0 andAlso new_max_dmg != 0 then begin
               wpn_pid = obj_pid(item);
               call set_proto_dmg(wpn_pid, new_min_dmg, new_max_dmg);
            end
            bruiser_heavy_handed_min_dmg = 0;
            bruiser_heavy_handed_max_dmg = 0;
         end
      end
   end
end

procedure refresh begin
   in_description = 0;
end

procedure ADJUSTFID begin
   if sfall_508 <= 0 andAlso (heavy_handed > 0 orElse bruiser > 0) then begin
      if loot_obj <= 0 andAlso in_description <= 0 andAlso (get_game_mode bwand INVENTORY) == INVENTORY then begin
         sfall_func2("interface_overlay", WINTYPE_INVENTORY, 0);
         overlay_created = 0;
         display_stats;
      end
      if in_description <= 0 then
         call show_dude_new_dmg;
   end
end

procedure DESCRIPTIONOBJ begin
   if overlay_created > 0 then begin
      sfall_func2("interface_overlay", WINTYPE_INVENTORY, 0);
      overlay_created = 0;
      set_global_script_type(1);
      set_global_script_repeat(1);
      scr_repeat = 1;
   end
   if in_description <= 0 then begin
      in_description = 1;
      call refresh in 0;
   end
end

procedure is_perk_window_open begin
   variable pid;
   variable idx;

   if not(get_game_mode bwand CHARSCREEN) then
      return 0;

   pid = read_int(0x5705E0);

   if (pid <= 0 orElse pid > 50) then begin
      return 0;
   end

   idx = read_int(0x6ADD90 + pid * 4);
   return (idx != -1 andAlso idx < read_int(0x6ADF24));
end

procedure set_repeat_perk_desc begin
   if (repeat_in_char_screen == 1) then
       return;

   set_global_script_type(1);
   set_global_script_repeat(1);
   repeat_in_char_screen = 1;
end

procedure restore_characterEditorSelectedItem begin
   write_int(0x5707D0, characterEditorSelectedItem);
   if (get_game_mode bwand CHARSCREEN) then
      call_offset_v1(0x4D6F5C, read_int(0x57060C));
end

procedure set_faster_healing_desc begin
   variable current_state;
   variable prev_state;
   variable cur_gvar;
   variable add;
   if in_char_screen then begin
      cancel (restore_characterEditorSelectedItem);
      cancel (set_repeat_perk_desc);
      gFasterHealingPerk = has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing);
      if fast_metabolism == 0 orElse fast_metabolism == 1 then begin
         if has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism) then begin
            fast_metabolism = 1;
         end else begin
            fast_metabolism = 0;
         end

         call set_repeat_perk_desc when ((has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism) != fast_metabolism) orElse gFasterHealingPerk != (has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing)));
      end
      else
         call set_repeat_perk_desc when (gFasterHealingPerk != (has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing)));
   end

   if (fast_metabolism > 0) then begin
      current_state = 1 + (fast_metabolism_MMR_regen <= 0);
   end
   else begin
      if in_char_screen then begin
         characterEditorSelectedItem = read_int(0x5707D0);
         write_int(0x5707D0, -1);
      end
      if gFasterHealingPerk > 1 orElse ((gFasterHealingPerk > 0) andAlso is_perk_window_open) then begin
         current_state = 3 + (fast_metabolism_MMR_regen <= 0);
         if in_char_screen then
            call set_repeat_perk_desc when ((has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism) != fast_metabolism) orElse (gFasterHealingPerk < 2 andAlso is_perk_window_open != 1));
      end
      else begin
         current_state = 5;
      end
      if in_char_screen then
         call restore_characterEditorSelectedItem when (is_perk_window_open == 0);
   end

   cur_gvar = get_sfall_global_int(fast_metabolism_fast_healing_perk_stat);
   if (cur_gvar == current_state) then
      return;

   prev_state = cur_gvar;
   if (gFasterHealingPerk > 0) then begin
      if (prev_state != 0) then begin
         if ((prev_state <= 2) != (current_state <= 2)) then begin
            if (gFasterHealingPerk > 0) then begin
               set_perk_owed(get_perk_owed + (gFasterHealingPerk - 1));
               set_perk_stat(PERK_faster_healing, STAT_heal_rate);
               if gFasterHealingPerk == 2 andAlso v1_2_new_install <= 0 then
                  set_perk_stat_mag(PERK_faster_healing, 3);
               else
                  set_perk_stat_mag(PERK_faster_healing, 2);
            end
            critter_rm_trait(real_dude_obj, TRAIT_PERK, PERK_faster_healing, gFasterHealingPerk);
            add = 1;
         end
         else if ((prev_state == 1) != (current_state == 1)) andAlso ((prev_state == 3) != (current_state == 3)) then begin
            if (gFasterHealingPerk > 0) then begin
               set_perk_owed(get_perk_owed + (gFasterHealingPerk - 1));
               set_perk_stat(PERK_faster_healing, STAT_heal_rate);
               if gFasterHealingPerk == 2 andAlso v1_2_new_install <= 0 then
                  set_perk_stat_mag(PERK_faster_healing, 3);
               else
                  set_perk_stat_mag(PERK_faster_healing, 2);

            end
            critter_rm_trait(real_dude_obj, TRAIT_PERK, PERK_faster_healing, gFasterHealingPerk);
            add = 1;
         end
      end
      else if v1_2_new_install > 0 then begin
         set_perk_owed(get_perk_owed + (gFasterHealingPerk - 1));
         critter_rm_trait(real_dude_obj, TRAIT_PERK, PERK_faster_healing, gFasterHealingPerk);
      end
   end

   if (current_state == 1) then begin
      set_perk_desc(PERK_faster_healing, trait_msg(31101 + PERK_faster_healing));
      set_perk_ranks(PERK_faster_healing, 1);
      set_perk_stat(PERK_faster_healing, STAT_heal_rate);
      set_perk_stat_mag(PERK_faster_healing, 8);
   end
   else if (current_state == 2) then begin
      set_perk_desc(PERK_faster_healing, trait_msg(21101 + PERK_faster_healing));
      set_perk_ranks(PERK_faster_healing, 1);
      set_perk_stat(PERK_faster_healing, STAT_heal_rate);
      set_perk_stat_mag(PERK_faster_healing, 0);
   end
   else if (current_state == 3) then begin
      set_perk_desc(PERK_faster_healing, trait_msg(11101 + PERK_faster_healing));
      set_perk_ranks(PERK_faster_healing, 2);
      set_perk_stat(PERK_faster_healing, STAT_heal_rate);
      set_perk_stat_mag(PERK_faster_healing, 4 - v1_2_new_install);
   end
   else if (current_state == 4) then begin
      set_perk_desc(PERK_faster_healing, trait_msg(11101 + PERK_faster_healing));
      set_perk_ranks(PERK_faster_healing, 2);
      set_perk_stat(PERK_faster_healing, STAT_heal_rate);
      set_perk_stat_mag(PERK_faster_healing, 4 - v1_2_new_install);
   end
   else begin
      set_perk_desc(PERK_faster_healing, trait_msg(1101 + PERK_faster_healing));
      set_perk_ranks(PERK_faster_healing, 2);
      set_perk_stat(PERK_faster_healing, STAT_heal_rate);
      set_perk_stat_mag(PERK_faster_healing, 2);
      if (get_game_mode bwand CHARSCREEN) then begin
         //set_and_refresh;
         //call_offset_v0(0x4365AC); //characterEditorDrawCard()
          //write_int(0x5707D0, -1);
      end
   end

   if (add) then
      critter_add_trait(real_dude_obj, TRAIT_PERK, PERK_faster_healing, add);

   set_sfall_global(fast_metabolism_fast_healing_perk_stat, current_state);
   v1_2_new_install = 0;
end

procedure GAMEMODECHANGE begin
   variable game_exit = get_sfall_arg;
   variable last_game_mode = get_sfall_arg;
   variable game_mode = get_game_mode;
   if in_char_screen > 0 then begin
      cancel (restore_characterEditorSelectedItem);
      cancel (set_repeat_perk_desc);
      in_char_screen = 0;
   end
   if (repeat_in_char_screen == 1) then begin
      set_global_script_type(3);
      set_global_script_repeat(0);
      repeat_in_char_screen = 0;
   end

   if game_mode == 0 orElse (game_mode bwand COMBAT) then begin
      call get_real_dude_traits;
   end
   else if (game_mode bwand CHARSCREEN) then begin
      if skilled > 0 then
         call get_and_set_perk_level_mod;

      in_char_screen = 1;
      call set_repeat_perk_desc;
   end

   if sfall_508 <= 0 andAlso (heavy_handed > 0 orElse bruiser > 0) then begin
      if (game_mode bwand INVENTORY) andAlso not(last_game_mode bwand INVENTORY) then begin
         if (heavy_handed > 0 orElse bruiser > 0) andAlso loot_obj <= 0 then begin
            call show_dude_new_dmg;
            display_stats;
            inventory_redraw(-1);
         end
      end
      else if not(game_mode bwand INVENTORY) andAlso (last_game_mode bwand INVENTORY) then begin
         if overlay_created > 0 then begin
            sfall_func2("interface_overlay", WINTYPE_INVENTORY, 0);
            overlay_created = 0;
         end
         call restore_proto_dmg;
      end
   end
   if game_exit > 0 then begin
      if bloody_mess_player_death_changed > 0 then begin
         write_byte(0x410700, 0x75);
         write_byte(0x410701, 0x16);
      end
   end
end

procedure MOVECOST begin
   variable critter = get_sfall_arg;
   variable hex_moved;
   variable critter_cur_tile;
   if kamikaze > 0 andAlso critter == real_dude_obj then begin
      critter_cur_tile = tile_num(critter);
      if kamikaze_last_tile <= 0 then begin
         kamikaze_last_tile = critter_cur_tile;
      end
      if kamikaze_last_tile != critter_cur_tile then begin
         hex_moved = get_sfall_arg_at(1);
         if crit_is_moving(real_dude_obj) then kamikaze_hex_walked_num += hex_moved;
         if critter == real_dude_obj andAlso kamikaze_hex_walked_num % kamikaze_walk_div == 0 then begin
            intface_redraw;
         end
         kamikaze_last_tile = critter_cur_tile;
      end
   end
end

procedure REMOVEINVENOBJ begin
   variable RMOBJ_reason = get_sfall_arg_at(3);

   if da_check then
      call drug_addict_stat_check;

   if modded_drug_pid > 0 then begin
      call drug_restore;
   end
   if kamikaze_hex_walked_num > 0 andAlso (RMOBJ_reason != RMOBJ_ARMOR_EQUIPED andAlso RMOBJ_reason != RMOBJ_LEFT_HAND_EQUIPED andAlso RMOBJ_reason != RMOBJ_RIGHT_HAND_EQUIPED andAlso RMOBJ_reason != RMOBJ_ITEM_REMOVED_INVEN) then begin
      kamikaze_hex_walked_num = 0;
      intface_redraw;
   end
   if (in_description > 0 orElse scr_repeat > 0) andAlso (heavy_handed > 0 orElse bruiser > 0) then begin
      if scr_repeat > 0 andAlso loot_obj <= 0 andAlso (get_game_mode bwand INVENTORY) == INVENTORY then begin
         display_stats;
         set_global_script_type(3);
         set_global_script_repeat(0);
         call show_dude_new_dmg;
         in_description = 0;
         scr_repeat = 0;
      end
      in_description = 0;
   end
end

procedure DISPLAYDAMAGE begin
   variable critter = get_sfall_arg;
   variable weapon;
   variable atk_type;
   variable default_min_wpn_dmg;
   variable default_max_wpn_dmg;
   variable wpn_anim = -1;
   variable wpn_pid;
   variable melee_dmg;
   variable new_min_wpn_dmg;
   variable new_max_wpn_dmg;
   variable wpn_max_dmg;
   if (bruiser > 0 orElse heavy_handed > 0) andAlso critter == real_dude_obj then begin
      weapon = get_sfall_arg;
      atk_type = get_sfall_arg;
      default_min_wpn_dmg = get_sfall_arg;
      default_max_wpn_dmg = get_sfall_arg;

      if weapon > 0 then begin
         wpn_pid = obj_pid(weapon);
         wpn_anim = get_proto_data(wpn_pid, PROTO_WP_ANIM);
         wpn_max_dmg = get_proto_data(wpn_pid, PROTO_WP_DMG_MAX);
      end
      if weapon <= 0 orElse (weapon_is_grenade(weapon, atk_type) == 0 andAlso (wpn_anim <= WPN_ANIM_SPEAR or wpn_anim == 0x0E or wpn_anim == 0x0B or wpn_anim == 0x0C)) then begin
         melee_dmg = get_critter_stat(critter, STAT_melee_dmg);
         if melee_dmg < 1 then melee_dmg = 1;

         if default_max_wpn_dmg < (wpn_max_dmg + melee_dmg) then begin
            default_max_wpn_dmg = (wpn_max_dmg + melee_dmg);
         end
         new_min_wpn_dmg = default_min_wpn_dmg;
         new_max_wpn_dmg = default_max_wpn_dmg;
         //TRAIT_heavy_handed min dmg
         //TRAIT_heavy_handed min dmg
         if heavy_handed > 0 then begin
            //new_min_wpn_dmg = default_min_wpn_dmg + (melee_dmg + 1) / 2; // ecco
            new_min_wpn_dmg = default_min_wpn_dmg + melee_dmg;
            new_max_wpn_dmg = default_max_wpn_dmg;
         end
         //TRAIT_bruiser max and min dmg
         if bruiser > 0 then begin
            new_min_wpn_dmg *= 2;
            new_max_wpn_dmg *= 2;
         end

         if new_min_wpn_dmg > new_max_wpn_dmg then begin
            new_min_wpn_dmg = new_max_wpn_dmg;
         end

         set_sfall_return(new_min_wpn_dmg);
         set_sfall_arg(3, new_min_wpn_dmg);
         set_sfall_return(new_max_wpn_dmg);
         set_sfall_arg(4, new_max_wpn_dmg);
      end
   end
end


procedure ATTACKHITROLL begin
   if skilled_prevent_crit_fail > 0 then begin
      set_sfall_return(skilled_prevent_crit_fail);
      set_sfall_arg(3, skilled_prevent_crit_fail);
      skilled_prevent_crit_fail = 0;
   end
end

procedure cripple_arm_dude begin
   critter_injure(real_dude_obj, DAM_CRIP_ARM_RIGHT);
end

procedure AutoMoveToAttack_target_check begin
   if AutoMoveToAttack_last_ap > 0 then begin
      AutoMoveToAttack_last_target = 0;
      AutoMoveToAttack_move_dist = 0;
      AutoMoveToAttack_start_hex = 0;
      AutoMoveToAttack_last_ap = 0;
      intface_redraw;
   end
end

procedure TARGETOBJECT begin
   variable is_attacking = get_sfall_arg;
   variable can_be_attacked = get_sfall_arg;
   variable target = get_sfall_arg;
   variable distance;
   variable wpn;
   variable wpn_dist;
   if one_hander > 0 andAlso critter_state(real_dude_obj) bwand (DAM_CRIP_ARM_LEFT bwor DAM_CRIP_ARM_RIGHT) == 48 then begin
      wpn = get_active_weapon(real_dude_obj);
      if weapon_is_two_handed(wpn) == 0 then begin
         critter_uninjure(real_dude_obj, DAM_CRIP_ARM_RIGHT);
         call cripple_arm_dude in 0;
      end
   end

   if AutoMoveToAttack > 0 andAlso kamikaze > 0 then begin
      if wpn_is_melee > 0 andAlso can_be_attacked > 0 then begin
         distance_objs(distance, real_dude_obj, target);
         AutoMoveToAttack_move_dist = distance - wpn_range;
         AutoMoveToAttack_start_hex = tile_num(real_dude_obj);
         if AutoMoveToAttack_last_target != target then begin
            AutoMoveToAttack_last_target = target;
            call AutoMoveToAttack_target_check when obj_under_cursor(-1,1) != AutoMoveToAttack_last_target;
         end
      end
      else begin
         AutoMoveToAttack_move_dist = 0;
         AutoMoveToAttack_start_hex = 0;
         if AutoMoveToAttack_last_ap > 0 then begin
            AutoMoveToAttack_last_target = 0;
            AutoMoveToAttack_last_ap = 0;
            intface_redraw;
         end
      end
   end
end

procedure CANUSEWEAPON begin
   variable critter = get_sfall_arg;
   variable wpn;
   if one_hander > 0 andAlso critter == real_dude_obj then begin
      if (critter_state(critter) bwand (DAM_CRIP_ARM_LEFT bwor DAM_CRIP_ARM_RIGHT)) == 48 then begin
         wpn = get_sfall_arg_at(1);
         if weapon_is_two_handed(wpn) == 0 then begin
            set_sfall_return(1);
         end
      end
   end
end


procedure set_last_xp_mod begin
   last_xp_mod = get_xp_mod;
end

procedure RESTTIMER begin
   variable game_time_current;
   variable rest_event_type;
   variable rest_hours;
   variable rest_minutes;
   variable max_hp;
   variable current_hp;
   variable heal_amount;
   variable ticks_passed;
   variable total_ticks;
   variable min_heal;
   variable crip_chance;
   variable crip_count;
   if gFasterHealingPerk != 1 then
      return;

   if get_critter_stat(real_dude_obj, STAT_heal_rate) <= 0 then
      return;

   game_time_current = get_sfall_arg;
   rest_event_type = get_sfall_arg;
   rest_hours = get_sfall_arg;
   rest_minutes = get_sfall_arg;

   if (gLastGameTime == 0) then begin
      gLastGameTime = game_time_current;
      gAccumulatedHealForCrip = 0;
      gTotalHealedThisRest = 0;
      max_hp = get_critter_stat(real_dude_obj, STAT_max_hp);
      gCripHealThreshold = max_hp / 5;
      if (gCripHealThreshold < 1) then begin
         gCripHealThreshold = 1;
      end
      return;
   end

   ticks_passed = game_time_current - gLastGameTime;

   if (ticks_passed <= 0) then begin
      gLastGameTime = game_time_current;
      return;
   end

   if (ticks_passed > 864000) then begin
      gLastGameTime = game_time_current;
      gPartialTicks = 0;
      gAccumulatedHealForCrip = 0;
      gTotalHealedThisRest = 0;
      return;
   end

   gLastGameTime = game_time_current;

   total_ticks = ticks_passed + gPartialTicks;
   max_hp = get_critter_stat(real_dude_obj, STAT_max_hp);
   heal_amount = (max_hp * total_ticks) / 864000;

   min_heal = total_ticks / 6000;
   if (min_heal < 0) then begin
      min_heal = 0;
   end

   if (heal_amount < min_heal) then begin
      heal_amount = min_heal;
   end

   gPartialTicks = total_ticks % 6000;

   if (heal_amount > 0) then begin
      critter_heal(real_dude_obj, heal_amount);
      gTotalHealedThisRest = gTotalHealedThisRest + heal_amount;
   end

   gAccumulatedHealForCrip = gAccumulatedHealForCrip + heal_amount;

   crip_count = gAccumulatedHealForCrip / gCripHealThreshold;
   if (crip_count > 0) then begin
      call heal_random_injury(real_dude_obj, crip_count, 100);
      gAccumulatedHealForCrip = gAccumulatedHealForCrip % gCripHealThreshold;
   end

   if (rest_event_type == 1 or rest_event_type == -1) then begin
      current_hp = get_critter_stat(real_dude_obj, STAT_current_hp);
      if (current_hp >= max_hp) then begin
         critter_uninjure(real_dude_obj,  all_injuries);
      end
      else if (gAccumulatedHealForCrip > 0 and gCripHealThreshold > 0) then begin
         crip_chance = (gAccumulatedHealForCrip * 100) / gCripHealThreshold;
         call heal_random_injury(real_dude_obj, 1, crip_chance);
      end

      gLastGameTime = 0;
      gPartialTicks = 0;
      gAccumulatedHealForCrip = 0;
      gTotalHealedThisRest = 0;
   end
end

procedure set_new_perk_stats begin

   gPyromaniacBonus = get_ini_setting("sfall\\Perks.ini|PerksTweak|PyromaniacBonus");
   if gPyromaniacBonus < 0 then
      gPyromaniacBonus = 5;

   gDemolitionExpertBonus = get_ini_setting("sfall\\Perks.ini|PerksTweak|DemolitionExpertBonus");
   if gDemolitionExpertBonus < 0 then
      gDemolitionExpertBonus = 10;

   //PERK_dodger
   set_perk_desc(PERK_dodger, trait_msg(1101 + PERK_dodger));
   set_perk_ranks(PERK_dodger, 1);
   //PERK_pyromaniac_perk
   set_perk_desc(PERK_pyromaniac_perk, sprintf(trait_msg(10000 * RegenMod + 1101 + PERK_pyromaniac_perk), gPyromaniacBonus));
   set_perk_ranks(PERK_pyromaniac_perk, 1);
   //PERK_weapon_handling_perk
   set_perk_desc(PERK_weapon_handling_perk, trait_msg(10000 * AimedBurstMod + 1101 + PERK_weapon_handling_perk));
   set_perk_str(PERK_weapon_handling_perk, 0);
   set_perk_ranks(PERK_weapon_handling_perk, 1);

   //PERK_demolition_expert_perk
   set_perk_desc(PERK_demolition_expert_perk, sprintf(trait_msg(1101 + PERK_demolition_expert_perk), gDemolitionExpertBonus));
   set_perk_ranks(PERK_demolition_expert_perk, 1);

   //PERK_faster_healing
   call set_faster_healing_desc;
end

procedure start begin
   if (game_loaded) then begin
      TraitsPlus = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|TraitsPlus");
      traits_plus_msg_file = add_extra_msg_file(new_msg_file);
      traits_plus_cur_version = trait_msg(traits_desc_ver_msg);
      ver_major = sfall_ver_major;
      ver_minor = sfall_ver_minor;
      ver_build = sfall_ver_build;

      if ver_major >= 5 then begin
         AutoMoveToAttack = get_ini_setting("ddraw.ini|Misc|AutoMoveToAttack");

         if ver_build >= 8 orElse ver_major > 5 orElse ver_minor > 0 then begin
            sfall_508 = 1;
            if ver_minor > 0 then begin
               sfall_510 = 1;
               unsafe_script;
            end
         end
      end
      if TraitsPlus <= 0 then begin
         call one_hander_bonus_remove;

         //if ver_major <= 4 then
            //call sfall_4_unset_unarmed_dmg_bytes;

         if rm_traits_desc then
            return;
         else
            exit;
      end
      Nevada = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|Nevada");
      Sonora = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|Sonora");
      et_tu = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|et_tu");
      if Sonora > 0 then begin
         traits_plus_cur_version = traits_plus_version_Sonora + traits_plus_cur_version;
      end
      else if et_tu  > 0 then begin
         traits_plus_cur_version = traits_plus_version_et_tu + traits_plus_cur_version;
      end

      if Nevada <= 0 andAlso Sonora <= 0 andAlso et_tu <= 0 then begin
         //Fallout_2 = 1;
         //if get_proto_data(542, PROTO_FID) == 197 then begin
            //Megamod = 1;
         //end
         if get_proto_data(595, PROTO_FID) == 171 then begin
            Olympus2207 = 1;
         end
      end

      call set_dude_traits_from_ini;


      set_global_script_type(3);
      set_global_script_repeat(0);

      if kamikaze >= 0 then begin
         register_hook_proc(HOOK_MOVECOST, MOVECOST);

      end
      //if heavy_handed >= 0 orElse bruiser >= 0 orElse finesse >= 0 then begin
         register_hook_proc(HOOK_ITEMDAMAGE, ITEMDAMAGE);
         if sfall_508 > 0 then begin
            register_hook_proc(54, DISPLAYDAMAGE); //HOOK_DISPLAYDAMAGE
         end
         else begin
            register_hook_proc(HOOK_ADJUSTFID, ADJUSTFID);
            register_hook_proc(HOOK_DESCRIPTIONOBJ, DESCRIPTIONOBJ);
         end
      //end
      if skilled >= 0 andAlso sfall_508 > 0 then begin
         register_hook_proc(56, ATTACKHITROLL); //HOOK_ATTACKHITROLL
      end

      register_hook_proc_spec(HOOK_COMBATTURN, COMBATTURN);
      register_hook_proc(HOOK_CALCAPCOST, CALCAPCOST);
      register_hook_proc_spec(HOOK_ONDEATH, ONDEATH);
      register_hook_proc(HOOK_AFTERHITROLL, AFTERHITROLL);
      register_hook_proc_spec(HOOK_COMBATDAMAGE, COMBATDAMAGE);
      register_hook_proc_spec(HOOK_TOHIT, TOHIT);
      if fast_metabolism >= 0 orElse drug_resistant >= 0 orElse drug_addict >= 0 then begin
         register_hook_proc_spec(HOOK_USEOBJON, USEOBJON);
         register_hook_proc(HOOK_REMOVEINVENOBJ, REMOVEINVENOBJ);
      end
      register_hook_proc(HOOK_GAMEMODECHANGE, GAMEMODECHANGE);

      if one_hander >= 0 orElse kamikaze >= 0 then begin
         register_hook_proc(HOOK_TARGETOBJECT, TARGETOBJECT);
      end
      register_hook_proc(HOOK_RESTTIMER, RESTTIMER);
      if one_hander >= 0 then begin
         register_hook_proc_spec(HOOK_CANUSEWEAPON, CANUSEWEAPON);
         intface_redraw;
      end
      traits_plus_msg_file = add_extra_msg_file(new_msg_file);
      RegenMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Main|RegenMod");
      if RegenMod > 0 then
         RegenMod = 1;
      else
         RegenMod = 0;

      call check_ini_path;
      call get_real_dude_traits;

      if has_fake_perk_npc(real_dude_obj, da_radaway_perk_name) then begin
         register_hook_proc(HOOK_ADJUSTRADS, ADJUSTRADS);
      end

      if get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|SecondaryAttackMod") > 0 then begin
         AimedBurstMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|SecondaryAttack|AimedBurstSecondaryAttackMod");
         if AimedBurstMod > 0 then
            AimedBurstMod = 1;
         else
            AimedBurstMod = 0;

      end
      call da_set_xp_mod in 0;
      call set_new_perk_stats;

      if (fast_metabolism >= 0 orElse gFasterHealingPerk >= 2) andAlso fast_metabolism_MMR_regen <= 0 then begin
         gLastRegenTime = game_time - random(10,30);
         add_global_timer_event(gLastRegenTime + 50, timed_hp_regen);
         timer_is_up = 1;
         gGlobalMapSpeedMult = get_ini_setting("ddraw.ini|Misc|WorldMapTimeMod");
         if gGlobalMapSpeedMult > 0 then begin
            if gGlobalMapSpeedMult > 100 then
               gGlobalMapSpeedMult = 100;
            timed_hp_regen_global = 6000 / (101 - gGlobalMapSpeedMult);
            if timed_hp_regen_global < 600 then
               timed_hp_regen_global = 600;
         end
      end
   end
   else begin
      if repeat_in_char_screen then begin
         set_global_script_type(3);
         set_global_script_repeat(0);
         call set_faster_healing_desc;
         repeat_in_char_screen = 0;
      end
      else if (heavy_handed > 0 orElse bruiser > 0) andAlso read_int(0x59E940) == 0 andAlso loot_obj <= 0 then begin
         set_global_script_type(3);
         set_global_script_repeat(0);
         display_stats;
         call show_dude_new_dmg;
         in_description = 0;
         scr_repeat = 0;
      end
   end
end
