#define SFALL_SC_EVALUATION  (true) // short - circuit evaluation
#define critcrippled(crit)          (critter_state(crit) BWAND (DAM_CRIP_LEG_LEFT BWOR DAM_CRIP_LEG_RIGHT BWOR DAM_CRIP_ARM_LEFT BWOR DAM_CRIP_ARM_RIGHT BWOR DAM_BLIND))
#define is_dead(critter_obj) (critter_state(critter_obj) == CRITTER_IS_DEAD)
#define is_prone(critter_obj) (critter_state(critter_obj) == CRITTER_IS_PRONE)
//#define critter_art_fid(critter_obj)    (get_proto_data(obj_pid(critter_obj),PROTO_FID))
#define critter_art_fid(critter_obj)   (obj_art_fid(critter_obj) bwand 0xFFFF0FFF)
#define military_fid(critter_obj)   (critter_art_fid(critter_obj) == 16777217 or critter_art_fid(critter_obj) == 16777226 or critter_art_fid(critter_obj) == 16777219 or critter_art_fid(critter_obj) == 16777309 or critter_art_fid(critter_obj) == 16777287)
#define high_tec_fid(critter_obj)   (critter_art_fid(critter_obj) == 16777287 or critter_art_fid(critter_obj) == 16777301 or critter_art_fid(critter_obj) == 16777217)
#define msg_file "gl_RegPoisMod.msg"
#define msg_perk_regen 1
#define msg_perk_poison_mastery_name 2
#define msg_perk_regen_acquired 3
#define msg_perk_regen_description 4
#define msg_perk_poison_mastery_description 5
#define msg_right_hand_healed 6
#define msg_right_leg_healed 7
#define msg_left_hand_healed 8
#define msg_left_leg_healed 9
#define msg_eyes_healed 10
#define msg_envenomed 11
#define msg_envenomed_description 12
#define msg_pois_appl_npc 13
#define msg_pois_appl_player 14
#define msg_gland_gone 15
#define msg_wpn_poison_full 16
#define msg_gland_gone_npc 17
#define msg_failed_poison_sneak 18
#define msg_player_1_hp_healed 19
#define msg_player_many_hp_healed 20
#define msg_npc_1_hp_healed 21
#define msg_npc_many_hp_healed 22
#define msg_player_poison_dmg 23
#define msg_npc_poison_dmg 24
#define msg_npc_poison_dmg_deadly 25
#define msg_npc_reach_poison_lethal_value 26
#define msg_player_after_poison_effect 27
#define msg_UnsafeScripting 28
#define msg_failedPoisoning1 29
#define msg_failedPoisoning2 30
#define msg_failedPoisoning3 31
#define msg_failedPoisoning4 32
#define msg_npc_use_item 33
#define modmsg(x) message_str_game(new_regpois_msg, x)
#define Poison_amt 50
#define OUTLINE_NEW_RED  0x8500
#define stim_min_hp  2
#define stim_min_hp_fast_meta  3
#define stim_max_hp  4
#define stim_max_hp_fast_meta  5
#define stim_hr_increase  20
#define stim_hr_increase_fast_meta  25
#define stim_hr_decrease  25
#define stim_hr_decrease_fast_meta  30
#define stim_duration  1
#define stim_duration_fast_meta  1
#define stim_penalty_duration  4
#define stim_penalty_duration_fast_meta  3
#define PID_SMALL_TAIL  591
#define CRITTER_PROTO_DT PROTO_CR_BONUS_PLASMA_DT
#define CRITTER_PROTO_DR PROTO_CR_BONUS_PLASMA_DR
#define min_poison_dmg 1
#define min_poison_decay 2
#define reg_anim_animate_and_move(object, tile, animID, delay)                 sfall_func4("reg_anim_animate_and_move", object, tile, animID, delay)
#define set_obj_script_fixed_value(obj_sid, value) call_offset_v2(0x4A3B34, obj_sid, value)
#define set_obj_script_objects(obj_sid, source, target) call_offset_v3(0x4A3B0C, obj_sid, source, target)
#define exec_obj_script_proc(obj_sid, script_proc_type) call_offset_v2(0x4A4810, obj_sid, script_proc_type)
#define get_combat_exp read_int(0x56D398)
#define set_combat_exp(value) write_int(0x56D398,value)
#define inc_kill_count(kill_type) call_offset_v1(0x42D878, kill_type)
#define set_who_hit_me(critter,obj,attacker_critter_obj) call_offset_v2(0x42E4C0,critter,obj,attacker_critter_obj)
#define get_critter_xp(critter_obj) (get_proto_data(obj_pid(critter_obj), PROTO_CR_EXP_VAL))
#define critter_art_fid(critter_obj)   (obj_art_fid(critter_obj) bwand 0xFFFF0FFF)
#define art_exists_death_anim(critter_obj,ANIM_num)  (art_exists((obj_art_fid(critter_obj) bwand 0xFF00FFFF) bwor (ANIM_num * 0x10000 + 0x10000000))) // knockdown and death   20-35
#define art_exists_basic_anim(critter_obj,ANIM_num)  (art_exists((obj_art_fid(critter_obj) bwand 0xFF00FFFF) bwor (ANIM_num * 0x10000)))
#define game_ui_disable2 call_offset_v1(0x443BFC,1)
#define reg_anim_set_priority call_offset_v1(0x413C20, 1)
#define days_since_visited_in_ticks read_int(0x00631D8C)
#define set_cursor_animated_watch call_offset_v1(0x44C840,26)

#include "sfall.h"
#include "DEFINE.H"
#include "define_extra.h"
#include "lib.math.h"
#include "lib.strings.h"
#include "COMMAND.H"

   procedure start;
   procedure poisonInRealTime;
   procedure regenInRealTime;
   procedure ModInTurnBased;
   procedure ADJUSTPOISON;
   procedure map_enter_p_proc;
   procedure rest;
   procedure USESKIL;
   procedure COMBATDAMAGE;
   procedure USEOBJ;
   procedure USEOBJON;
   procedure worldMapTravel;
   procedure map_exit_p_proc;
   procedure stimtoburn;
   procedure stimrestore;
   procedure newperks;
   procedure cripheal;
   procedure death;
   procedure map_enter_p_proc_handler;

   variable new_regpois_msg;
   variable RegenMod;
   variable RegenMaxHPpercentMult;
   variable HealingRateMult;
   variable HealingRateDiv;
   variable PoisonMod;
   variable ShowModMSG;
   variable ShowFloatMSG;
   variable PoisonMaxHPpercentMult;
   variable PoisonMaxHPpercentMult2;
   variable PoisonLevelMult;
   variable PoisonLevelDiv;
   variable PoisonDecayDiv;
   variable RegenTickHP;
   variable RegenTickHP2;
   variable DudeRegenTickHP;
   variable PoisonTickDmg;
   variable Nevada;
   variable Sonora;
   variable Resurrection;
   variable ET_TU;
   variable dudehrexitmap;
   variable dudehrcount;
   variable dudehrcount2;
   variable stimtimer;
   variable stimusetimer;
   variable gamemode;
   variable healfromskill;
   variable dudeishealing;
   variable combatendtime;
   variable hasregenperk;
   variable poisondeath;
   variable deadtarget;
   variable UnsafeRegenModScripting;
   variable stimburn;
   variable regen_perk_name;
   variable regen_perk_description;
   variable perk_poison_mastery_name;
   variable perk_poison_mastery_description;
   variable regen_perk_acquired_msg;
   variable right_hand_healed_msg;
   variable right_leg_healed_msg;
   variable left_hand_healed_msg;
   variable left_leg_healed_msg;
   variable eyes_healed_msg;
   variable envenomed_msg;
   variable envenomed_description_msg;
   variable gland_gone_msg;
   variable failed_sneak_use_msg;
   variable sfall_unsafescripting;
   variable sfall_unsafescripting_msg;
   variable HR_fog_of_war;
   variable StimUninjure;
   variable NPCsUsePoisonTails;
   variable scr_repeat;
   variable PID_SMALL_SCORPION_TAIL = -5;
   variable combat_diff;
   variable EnemyPoisonMult;
   variable sfall_mods_config;
   variable combat_direct_controll;
   variable death_array;
   variable new_death;
   variable map_exit;
   variable mode_change_death;
   variable party_member_remove_arr;
   variable party_member_remove;
   variable dude_must_die;
   variable dude_turn;
   variable dude_turn_critter_dies;
   variable critter_poison_overdose;

   export variable tail_used;

   import variable combat_med_tool_used;

procedure start begin
   if (game_loaded) then begin
      RegenMod = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|RegenMod");
      PoisonMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|PoisonMod");
      if RegenMod > 0 or PoisonMod > 0 then begin
         UnsafeRegenModScripting = 1;
         new_regpois_msg = add_extra_msg_file("gl_RegPoisMod.msg");
         sfall_unsafescripting = get_ini_setting ("ddraw.ini|Debugging|AllowUnsafeScripting");
         if UnsafeRegenModScripting > 0 then begin
         //warning if sfall_unsafescripting is disabled while UnsafeRegenModScripting enabled
            if sfall_unsafescripting < 1 then begin
               sfall_unsafescripting_msg = modmsg(msg_UnsafeScripting);
               display_msg(sfall_unsafescripting_msg);
               exit;
            end
            else begin
               set_stat_max(STAT_heal_rate, 40);
            end
         end
         combat_diff = (combat_difficulty + 1);
         register_hook_proc(HOOK_COMBATTURN, ModInTurnBased);
         register_hook_proc_spec(HOOK_ADJUSTPOISON, ADJUSTPOISON);
         register_hook_proc(HOOK_RESTTIMER, rest);
         register_hook_proc(HOOK_USESKILL, USESKIL);
         register_hook_proc(HOOK_COMBATDAMAGE, COMBATDAMAGE);
         register_hook_proc(HOOK_USEOBJ, USEOBJ);
         register_hook_proc(HOOK_USEOBJON, USEOBJON);
         register_hook_proc(HOOK_GAMEMODECHANGE, worldMapTravel);
         //register_hook_proc_spec(HOOK_DEATHANIM2, death);
         register_hook_proc(HOOK_STDPROCEDURE, map_enter_p_proc_handler);
         set_global_script_type(3);
         set_global_script_repeat(100);
         if get_proto_data(PID_SMALL_TAIL, PROTO_IT_INV_FID) == 117440914 then PID_SMALL_SCORPION_TAIL = PID_SMALL_TAIL;
         Nevada = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|Nevada");
         Sonora = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|Sonora");
         Resurrection = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|Resurrection");
         ET_TU = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|et_tu");
         RegenMod = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Main|RegenMod");
         sfall_mods_config = get_ini_string("ddraw.ini|Scripts|IniConfigFolder");
         if sfall_mods_config <= 0 then sfall_mods_config = "";
         combat_direct_controll = get_ini_setting(sfall_mods_config+"\\sfall-mods.ini|CombatControl|Mode");
         if RegenMod > 0 then begin
            RegenMaxHPpercentMult = atof(get_ini_string ("mods\\F2MechanicsMiniRework.ini|Regeneration|RegenMaxHPpercentMult"));
            if RegenMaxHPpercentMult <= 0 then RegenMaxHPpercentMult = 1.0;
            HealingRateMult = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Regeneration|HealingRateMult");
            if HealingRateMult <= 0 then HealingRateMult = 7;
            HealingRateDiv = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Regeneration|HealingRateDiv");
            if HealingRateDiv <= 0 then HealingRateDiv = 10;
            StimUninjure = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Regeneration|StimUninjure");
            //UnsafeRegenModScripting = get_ini_setting ("mods\\F2MechanicsMiniRework.ini|Regeneration|UnsafeRegenModScripting");
         end
         PoisonMod = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|PoisonMod");
         ShowModMSG = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|ShowMSG");
         ShowFloatMSG = get_ini_setting("mods\\F2MechanicsMiniRework.ini|MAIN|ShowFloatMSG");
         if PoisonMod > 0 then begin
            PoisonMaxHPpercentMult2 = atof(get_ini_string("mods\\F2MechanicsMiniRework.ini|Poison|PoisonMaxHPpercentMult"));
            if (PoisonMaxHPpercentMult2 <= 0) then PoisonMaxHPpercentMult2 = 1.5;
            if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
            if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
            EnemyPoisonMult = atof(get_ini_string("mods\\F2MechanicsMiniRework.ini|Poison|EnemyPoisonMult"));
            if EnemyPoisonMult <= 0 then EnemyPoisonMult = 1.5;
            PoisonLevelMult = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Poison|PoisonLevelMult");
            if PoisonLevelMult <= 0 then PoisonLevelMult = 1;
            PoisonLevelDiv = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Poison|PoisonLevelDiv");
            if PoisonLevelDiv <= 0 then PoisonLevelDiv = 2;
            PoisonDecayDiv = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Poison|PoisonDecayDiv");
            if PoisonDecayDiv <= 0 then PoisonDecayDiv = 10;
         end
         NPCsUsePoisonTails = get_ini_setting("mods\\F2MechanicsMiniRework.ini|Poison|NPCsUsePoisonTails");
         HR_fog_of_war = get_ini_setting("f2_res.ini|MAPS|FOG_OF_WAR");
         regen_perk_name = modmsg(msg_perk_regen);
         perk_poison_mastery_name = modmsg(msg_perk_poison_mastery_name);
         perk_poison_mastery_description = modmsg(msg_perk_poison_mastery_description);
         regen_perk_acquired_msg = modmsg(msg_perk_regen_acquired);
         regen_perk_description = modmsg(msg_perk_regen_description);
         right_hand_healed_msg = modmsg(msg_right_hand_healed);
         right_leg_healed_msg = modmsg(msg_right_leg_healed);
         left_hand_healed_msg = modmsg(msg_left_hand_healed);
         left_leg_healed_msg = modmsg(msg_left_leg_healed);
         eyes_healed_msg = modmsg(msg_eyes_healed);
         envenomed_msg = modmsg(msg_envenomed);
         envenomed_description_msg = modmsg(msg_envenomed_description);
         gland_gone_msg = modmsg(msg_gland_gone);
         failed_sneak_use_msg = modmsg(msg_failed_poison_sneak);
         call map_enter_p_proc();
         scr_repeat = game_time;
         intface_redraw;
         stimtimer = (scr_repeat + 500);
         gamemode = get_game_mode;
         combatendtime = scr_repeat;
         //regenperk activation
            if RegenMod > 0 andAlso has_fake_perk(regen_perk_name) == 0 andAlso get_pc_base_stat(STAT_heal_rate) + (2 * has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism)) + (2 * (has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing) - ET_TU)) >= 6 then begin
               call newperks();
            end
      end
   end
      //after load
   else begin
      if (dude_must_die > 0 or dude_turn_critter_dies > 0) andAlso not(game_ui_is_disabled) then begin
         game_ui_disable2;
         if dude_turn_critter_dies > 0 then
            set_cursor_animated_watch;
      end
      //(repeat ~50 game ticks with no FPS dependency)
      if not(combat_is_initialized) andAlso scr_repeat <= game_time then begin
         scr_repeat = game_time + game_ticks(5);
         call regenInRealTime();
         call poisonInRealTime();
      end
   end
end

procedure callback_ui_disable begin
   game_ui_disable2;
end

//procedure callback_ui_enable begin
   //game_ui_enable;
//end

procedure show_poison_dmg_combat_msg(variable target,variable dmg_value) begin
   variable target_gender;
   variable target_name;
   variable combat_msg_num;
   variable target_cur_hp;
   //return if no target
   if target <= 0 then return;
   target_cur_hp = get_critter_stat(target, STAT_current_hp);
    //npc msg
   if target != dude_obj then begin
      target_name = obj_name(target);
      // not dead
      if target_cur_hp > dmg_value then begin
         display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), target_name, dmg_value));
      end
      //dead
      else begin
         display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), target_name, dmg_value));
      end
   end
   //dude msg
   else begin
      if target_cur_hp > dmg_value then begin
         display_msg(parse_str_2(modmsg(msg_player_poison_dmg), -1,dmg_value));
      end
      else begin

      end
   end
end

procedure kill_dude begin
   dude_must_die = 0;
   game_ui_enable;
   critter_heal(dude_obj, -(get_critter_stat(dude_obj, STAT_current_hp)));
end

procedure show_death_msg begin
   variable target;
   variable dmg_value;
   variable target_sid;
   variable target_frm;
   foreach (target : dmg_value in death_array) begin
      target_frm = art_anim(obj_art_fid(target));
      if map_exit > 0 or mode_change_death > 0 or (target_frm >= ANIM_bad_landing_sf andAlso target_frm <= ANIM_fall_front_blood_sf) then begin
         set_array(death_array, target, 0);
         target_sid = get_object_data(target, OBJ_DATA_SID);
         call show_poison_dmg_combat_msg(target, dmg_value);
         poison(target, -999);
         if target_sid > 0 then begin
            //set_obj_script_fixed_value(target_sid, dmg_value);
            //exec_obj_script_proc(target_sid, damage_proc);
            exec_obj_script_proc(target_sid, destroy_proc);
         end
         set_outline(target,  OUTLINE_NONE);
         //critter_heal(target,-dmg_value);
         //party_remove(target);
         if target != dude_obj then begin
            if map_exit > 0 or mode_change_death > 0 then begin
               if art_exists_death_anim(target,ANIM_fall_front_blood_sf) orElse art_exists_basic_anim(target,ANIM_fall_front_blood_sf) then begin
                  kill_critter(target, ANIM_fall_front_blood_sf);
               end
               else begin
                  kill_critter(target, ANIM_fall_back_blood_sf);
               end
            end
            else begin
               kill_critter(target, target_frm);
            end
         end
         else begin
            call kill_dude;
            //critter_heal(target,-dmg_value);
         end
      end
   end
   if (dude_must_die > 0 or dude_turn_critter_dies > 0) andAlso not(game_ui_is_disabled) then begin
      game_ui_disable2;
      if dude_turn_critter_dies > 0 then
         set_cursor_animated_watch;
   end
   if len_array(death_array) <= 0 then begin
      if dude_turn_critter_dies > 0 then begin
         dude_turn_critter_dies = 0;
         set_global_script_type(3);
         set_global_script_repeat(100);
      end
      if (dude_turn > 0 or not(combat_is_initialized)) andAlso mode_change_death <= 0 then begin
         game_ui_enable;
      end
      mode_change_death = 0;
      new_death = 0;
      free_array(death_array);
   end
end

procedure get_death_anim_poison(variable target, variable dmg_value) begin
   variable death_anim = ANIM_fall_back;
   variable target_cur_anim = art_anim(obj_art_fid(target));
   variable death_anim_sf;
   variable is_front_hit = random(0,1);
   variable dmg_type = DMG_normal_dam;
   //add target to array of creatures that will die. critter_PTR as key, dmg as value
   if not(array_exists(death_array)) then begin
      death_array = create_array_map;
      set_array(death_array, target, dmg_value);
   end
   else begin
      set_array(death_array, target, dmg_value);
   end
   //Death animation for Horrigan
   if target > 0 andAlso obj_pid(target) == PID_END_BOSS then begin
      death_anim = ANIM_exploded_to_nothing;
      return death_anim;
   end
   //Death animation for a knocked out target
   if target_cur_anim == ANIM_fall_back then begin
      death_anim = ANIM_fall_back_blood;
      return death_anim;
   end
   else if target_cur_anim == ANIM_fall_front then begin
      death_anim = ANIM_fall_front_blood;
      return death_anim;
   end
   //Death animation for a standing target
   else begin
      //standard death_anim
      if dmg_type == DMG_normal_dam then begin
         death_anim = ANIM_fall_front - is_front_hit;
      end
      death_anim_sf = death_anim + 28;
      //if death_anim exist then return it
      if art_exists_death_anim(target,death_anim) orElse art_exists_basic_anim(target,death_anim) orElse art_exists_death_anim(target,death_anim_sf) orElse art_exists_basic_anim(target,death_anim_sf) then begin
         return death_anim;
      end
      //else return standard death_anim
      else begin
         if is_front_hit or (not(art_exists_death_anim(target,ANIM_fall_front)) andAlso not(art_exists_basic_anim(target,ANIM_fall_front)) andAlso not(art_exists_death_anim(target,ANIM_fall_front_sf)) andAlso not(art_exists_basic_anim(target,ANIM_fall_front_sf))) then begin
            return ANIM_fall_back;
         end
         else begin
            return ANIM_fall_front;
         end
      end
   end
end

procedure critter_inflict_poison_dmg(variable target,variable dmg_value, variable animate) begin
   variable target_cur_hp;
   //variable target_cur_anim;
   //variable target_sid;
   variable target_team = -1;
   variable who_hit_target;
   variable death_anim;
   variable death_anim_part2;
   variable death_anim_sf;
   variable combat_xp_bonus;
   variable dead_attacker;
   //check if the target exists and is a creature
   if target <= 0 orElse obj_type(target) != OBJ_TYPE_CRITTER orElse get_array(death_array,target) > 0 then begin
      return;
   end
   target_cur_hp = get_critter_stat(target, STAT_current_hp);
   target_team = has_trait(TRAIT_OBJECT, target, OBJECT_TEAM_NUM);
   //target_cur_anim = art_anim(obj_art_fid(target));
   //target_sid = get_object_data(target, OBJ_DATA_SID);

   //cause non-lethal damage
   if target_cur_hp > dmg_value then begin

   end
   //cause lethal POISON damage
   else begin
      if target == dude_obj then begin
         if dude_must_die <= 0 then begin
            //anim(dead_attacker, ANIMETE_FR, has_trait(TRAIT_OBJECT, target, OBJECT_CUR_ROT));
            //set_obj_visibility(target, 1);
            set_global_script_type(3);
            set_global_script_repeat(1);
            scr_repeat *= 2;
            dude_must_die = 1;
            scr_repeat = 0;
            //dead_attacker = create_object_sid(obj_pid(target), tile_num(target), elevation(target), -1);
            //anim(dead_attacker, ANIMATE_ROTATION, has_trait(TRAIT_OBJECT, target, OBJECT_CUR_ROT));
            //set_object_data(dead_attacker, OBJ_DATA_FID, obj_art_fid(target));
            //critter_heal(dead_attacker, -(get_critter_stat(dead_attacker, STAT_current_hp)-1));
            //call critter_inflict_poison_dmg(dead_attacker,dmg_value,1);
         end
      end
      //else begin
         new_death = 1;
         poisondeath = 0;
         //poison(target, -999);
         //party_remove(target);
         //if animate > 0 then begin
         if 1 then begin
            if get_game_mode bwand WORLDMAP then begin
               map_exit = 1;
               death_anim = get_death_anim_poison(target,dmg_value);
               call show_death_msg;
            end
            else begin
               if target != dude_obj then begin
                  critter_heal(target, -(target_cur_hp - 1));
               end
               death_anim = get_death_anim_poison(target,dmg_value);
               reg_anim_combat_check(0);
               reg_anim_clear(target);
               reg_anim_func(REG_ANIM_BEGIN, RB_RESERVED);
               reg_anim_set_priority;
               reg_anim_callback(callback_ui_disable);
               reg_anim_animate(target, ANIM_stand, -1);
               //standardt death anim
               if death_anim == ANIM_fall_back or death_anim == ANIM_fall_front then begin
                  death_anim_part2 = death_anim + 14;
                  death_anim_sf = death_anim_part2 + 28;
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim,snd_knock_down),1);
                  reg_anim_animate(target, death_anim, 0);
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim_part2,snd_knock_down),-1);
                  reg_anim_animate(target, death_anim_part2, 0);
               end
               //KO target death
               else if death_anim == ANIM_fall_back_blood or death_anim == ANIM_fall_back_blood then begin
                  death_anim_sf = death_anim + 28;
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim,snd_knock_down),1);
                  reg_anim_animate(target, death_anim, 0);
               end
               //brutal fire_dance death
               else if death_anim == ANIM_fire_dance then begin
                  death_anim_part2 = death_anim - 4;
                  death_anim_sf = death_anim_part2 + 28;
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim,snd_knock_down),1);
                  reg_anim_animate(target, death_anim, 0);
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim_part2,snd_knock_down),-1);
                  reg_anim_animate(target, death_anim_part2, 0);
               end
               //brutal death
               else begin
                  death_anim_sf = death_anim + 28;
                  reg_anim_play_sfx(target,sfx_build_char_name(target,death_anim,snd_knock_down),1);
                  reg_anim_animate(target, death_anim, 0);
               end
               reg_anim_animate(target, death_anim_sf, -1);
               reg_anim_callback(show_death_msg);
               //if dude_must_die > 0 then begin
                  //reg_anim_callback(kill_dude);
               //end
               reg_anim_end();
            end
         end
         //increase combat_xp and increase kill_count
         if combat_is_initialized then begin
            if target_team != TEAM_PLAYER then begin
               //inc combat exp
               if Sonora <= 0 then begin
                  combat_xp_bonus = get_combat_exp + get_critter_xp(target);
                  set_combat_exp(combat_xp_bonus);
               end
               inc_kill_count(critter_kill_type(target));
            end
            else begin
               inc_kill_count(critter_kill_type(target));
            end
         end
         else begin
            if Sonora <= 0 andAlso target_team != TEAM_PLAYER then begin
               give_exp_points(get_critter_xp(target));
            end
         end
      //end
   end
end

procedure map_enter_p_proc_handler begin
   variable stdnum = get_sfall_arg;
   variable self = get_sfall_arg;
   variable source = get_sfall_arg;
   variable critwaspoisoned = 0;
   variable tardt = 0;
   variable tardr = 0;
   variable critter_fid = 0;
   variable crit_pid = 0;
   variable critter;
   variable party = party_member_list(0);
   variable critter_in_party;
   variable critter_sid;
   if stdnum == map_enter_proc then begin
   //game_time_advance(ONE_GAME_SECOND * 5);
   dudehrexitmap = get_critter_stat(real_dude_obj, STAT_heal_rate);
   if get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
   RegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
   DudeRegenTickHP = RegenTickHP;
   end
   foreach critter in list_as_array(0) begin
     critter_in_party = is_in_array(critter, party);
     poisondeath = 0;
     // if poisoned (exept dude and party)
     if PoisonMod > 0 andAlso get_poison(Critter) > 0 andAlso critter != real_dude_obj andAlso not(critter_in_party) andAlso get_critter_stat(critter, STAT_current_hp ) > 0 then begin
      critwaspoisoned = 1;
      poisondeath = 0;
      // regen while poisoned
      if RegenMod > 0  andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 then begin
        if (RegenMaxHPpercentMult < 1) then begin
        RegenMaxHPpercentMult = 1;
        end
        RegenTickHP = round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * random(0, 1) * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
        if (RegenTickHP < 1) then begin
        RegenTickHP = 1;
        end
        critter_heal(critter, RegenTickHP);
      end
      // Poison dmg
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
      PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
      if PoisonTickDmg < min_poison_dmg then begin
        PoisonTickDmg = min_poison_dmg;
      end
      if PoisonTickDmg > 0 andAlso Critter != real_dude_obj then begin
         if get_critter_stat(critter, STAT_current_hp ) <= PoisonTickDmg then begin
            //critter_fid = critter_art_fid(Critter);
            //crit_pid = obj_pid(critter);
            //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
            //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);


            //set_target_knockback(critter, 0, 0);
            //if HR_fog_of_war then set_outline(critter, OUTLINE_NEW_RED);
            //poison(critter, -999);
            //set_proto_data(crit_pid, CRITTER_PROTO_DT, 0);
            //set_proto_data(crit_pid, CRITTER_PROTO_DR, 0);
            //critter_dmg(critter, PoisonTickDmg, DMG_plasma);
            //display_msg(game_time+"ERE!="+days_since_visited_in_ticks);
            if days_since_visited_in_ticks < game_time - game_ticks(90) then begin
               critter_sid = get_object_data(critter, OBJ_DATA_SID);
               party_remove(critter);
               if critter_sid > 0 then begin
                  //set_obj_script_fixed_value(critter_sid, PoisonTickDmg);
                  //exec_obj_script_proc(critter_sid, damage_proc);
                  exec_obj_script_proc(critter_sid, destroy_proc);
               end
               critter_heal(critter, -PoisonTickDmg);
            end
            else begin
               call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
            end
            poisondeath = 1;
            //set_proto_data(crit_pid, CRITTER_PROTO_DT, tardt);
            //set_proto_data(crit_pid, CRITTER_PROTO_DR, tardr);
            //if not(critter_in_party) andAlso critter_fid != 16777322 andAlso crit_pid != 16777508 then begin
            //give_xp((get_proto_data(crit_pid, PROTO_CR_KILL_EXP)));
            //end
         end
      end
   end
     // heal after poison is cleared (exept dude and party)
      if RegenMod > 0  andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp) andAlso get_poison(Critter) < 1 andAlso critter != real_dude_obj andAlso not(critter_in_party) then begin
         if (RegenMaxHPpercentMult < 1) then begin
         RegenMaxHPpercentMult = 1;
         end
         RegenTickHP = (round(get_critter_stat(critter, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * random(4, 8) * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
         if (RegenTickHP < 1) then begin
         RegenTickHP = 1;
         end
         critter_heal(critter, RegenTickHP);
         end
      end
   end
   if poisondeath != 0 andAlso critwaspoisoned != 0 then begin
      call map_enter_p_proc_handler();
   end
end

//procedure death begin
   //variable wpnpid = get_sfall_arg;
   //variable attacker = get_sfall_arg;
   //variable target = get_sfall_arg;
   //variable dmgtotar = get_sfall_arg;
   //variable deathanim = get_sfall_arg;
   //variable tardt = 0;
   //variable tardr = 0;
   //variable crit_pid;
   //variable crit_fid;
   //if poisondeath then begin
      //display_msg("NO DEATH");
      //if target > 0 then begin
         //crit_pid = obj_pid(target);
         //crit_fid = critter_art_fid(target);
      //end
      //if crit_pid != PID_END_BOSS then begin
         //set_sfall_arg(4, ANIM_fall_back);
         //set_sfall_return(ANIM_fall_back);
      //end
      //else begin
         //set_sfall_arg(4, ANIM_exploded_to_nothing);
         //set_sfall_return(ANIM_exploded_to_nothing);
      //end
      // OUTLINE for fix death animation if fog of war is enabled
      //if HR_fog_of_war then set_outline(target, OUTLINE_NEW_RED);
      //poison(target, - 999);
      //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
      //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);
      //if crit_fid(target) == FID_MAPLNT then begin
         //reg_anim_animate_reverse(target, ANIM_fall_back, -1);
      //end
      //if crit_fid(target) != FID_MAPLNT then begin
         //reg_anim_animate_reverse(target, ANIM_fall_back_sf, -1);
      //end
      //poisondeath = 0;
   //end
//end

procedure newperks begin
  variable Tox = has_fake_perk(perk_poison_mastery_name);
  if RegenMod > 0 andAlso has_fake_perk(regen_perk_name) == 0 andAlso ((get_pc_base_stat(STAT_heal_rate) + (2 * has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism)) + (2 * (has_trait(TRAIT_PERK, real_dude_obj, PERK_faster_healing)  - ET_TU)) > 5) or (get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 andAlso stimtimer < game_time - 800) )then begin
		display_msg(regen_perk_acquired_msg);
		set_fake_perk(regen_perk_name, 1, 79, regen_perk_description);
	end
  if get_game_mode bwor CHARSCREEN then begin
  	if PoisonMod > 0 andAlso get_pc_stat(PCSTAT_level) >= 6 andAlso Tox == 0 andAlso (has_skill(real_dude_obj, SKILL_SCIENCE) > 49 or has_skill(real_dude_obj, SKILL_OUTDOORSMAN) > 69) then begin
  		set_selectable_perk(perk_poison_mastery_name, 1, 102, perk_poison_mastery_description);
  	end
  	if Tox > 0 then begin
  	  set_selectable_perk(perk_poison_mastery_name, 0, 102, perk_poison_mastery_description);
  	  if Tox > 1 then begin
      set_perk_owed(get_perk_owed + 1);
      set_fake_perk(perk_poison_mastery_name, Tox - 1, 102, perk_poison_mastery_description);
  	  end
  	end
	end
end

procedure cripheal begin
  variable healed = 0;
  variable dudeHR = get_critter_stat(real_dude_obj, STAT_heal_rate);
  variable rnd = 0;
  if has_fake_perk(regen_perk_name) > 0 then begin
   if critter_state(real_dude_obj) BWAND DAM_CRIP_ARM_RIGHT then begin
    rnd = random(0, 100);
    if rnd < ((4 * dudeHR) - (25 * healed) )then begin
     critter_uninjure(real_dude_obj, DAM_CRIP_ARM_RIGHT);
     display_msg(right_hand_healed_msg);
     healed += 2;
     end
   end
   if critter_state(real_dude_obj) BWAND DAM_CRIP_LEG_LEFT then begin
     rnd = random(0, 100);
     if rnd < ((4 * dudeHR) - (25 * healed) )then begin
     critter_uninjure(real_dude_obj, DAM_CRIP_LEG_LEFT);
     display_msg(left_leg_healed_msg);
     healed += 2;
     end
   end
   if critter_state(real_dude_obj) BWAND DAM_CRIP_ARM_LEFT then begin
     rnd = random(0, 100);
     if rnd < ((4 * dudeHR) - (25 * healed) )then begin
     critter_uninjure(real_dude_obj, DAM_CRIP_ARM_LEFT);
     display_msg(left_hand_healed_msg);
     healed += 2;
     end
   end
   if critter_state(real_dude_obj) BWAND DAM_CRIP_LEG_RIGHT then begin
     rnd = random(0, 100);
    if rnd < ((4 * dudeHR) - (25 * healed) )then begin
     critter_uninjure(real_dude_obj, DAM_CRIP_LEG_RIGHT);
     display_msg(right_leg_healed_msg);
     healed += 2;
     end
   end
   if critter_state(real_dude_obj) BWAND DAM_BLIND then begin
     rnd = random(0, 100);
    if rnd < ((4 * dudeHR) - (20 * healed) )then begin
     critter_uninjure(real_dude_obj, DAM_BLIND);
     display_msg(eyes_healed_msg);
     healed += 2;
     end
   end
  end
end

procedure COMBATDAMAGE begin
   variable target = get_sfall_arg;
   variable attacker = get_sfall_arg;
   variable dmgtotar = get_sfall_arg;
   variable dmgtoatkr = get_sfall_arg;
   variable flagfortar = get_sfall_arg;
   variable flagforatkr = get_sfall_arg;
   variable weapon = get_sfall_arg;
   variable leftHand;
   variable rightHand;
   variable pyromaniac;
   variable wpnpid;
   variable wpnanim;
   variable wpndmgtype;
   variable tarhr;
   variable atkrhr;
   variable burncount;
   variable burn;
   variable Tox;
   variable lhname;
   variable rhname;
   variable lhpoison;
   variable rhpoison;
   variable acthnd;
   variable caliber;
   variable has_small_scorp_tail;
   variable has_scorp_tail;
   variable player_level = get_pc_stat(PCSTAT_level);
   variable atkr_fid = critter_art_fid(attacker);
   variable tar_kill_type;
   variable atk_kill_type;
   variable party = party_member_list(0);
   variable attacker_in_party = is_in_array(attacker, party);
   if PID_SMALL_SCORPION_TAIL > 0 then has_small_scorp_tail = obj_is_carrying_obj_pid(attacker, PID_SMALL_SCORPION_TAIL);
   tar_kill_type = critter_kill_type(target);
   if critter_inven_obj2(attacker, INVEN_TYPE_LEFT_HAND) then begin
      leftHand  = obj_pid(critter_inven_obj2(attacker, INVEN_TYPE_LEFT_HAND));
      lhname = proto_data(leftHand, 1);
   end
   if critter_inven_obj2(attacker, INVEN_TYPE_RIGHT_HAND) then begin
      rightHand = obj_pid(critter_inven_obj2(attacker, INVEN_TYPE_RIGHT_HAND));
      rhname = proto_data(rightHand, 1);
   end
   if attacker_in_party or attacker == real_dude_obj then begin
      if attacker == real_dude_obj then pyromaniac = has_trait(TRAIT_PERK, attacker, PERK_pyromaniac_perk);
      Tox = has_fake_perk_npc(attacker, perk_poison_mastery_name);
      lhpoison = has_fake_perk_npc(attacker, (envenomed_msg + lhname));
      rhpoison = has_fake_perk_npc(attacker, (envenomed_msg + rhname));
   end
   if player_level > 30 then player_level = 30;
   if weapon > 0 then begin
      wpnpid = obj_pid(weapon);
      wpnanim = get_proto_data(wpnpid, PROTO_WP_ANIM);
      wpndmgtype = metarule(METARULE_W_DAMAGE_TYPE, weapon);
      caliber = get_proto_data(wpnpid, PROTO_WP_CALIBER);
   end
   if dmgtotar > 0 then begin
      atk_kill_type = critter_kill_type(attacker);
      // all centaurs and floaters
      if (ET_TU or Resurrection or Nevada or Sonora or target != real_dude_obj) andAlso (atk_kill_type == KILL_TYPE_floater_kills or atk_kill_type == KILL_TYPE_centaur_kills) andAlso random(0,2) then begin
         if target != real_dude_obj then begin
            poison(target, random(1,7));
         end
         else begin
            poison(target, random(3,6) + player_level / 9);
         end
      end
      // poison atk for plant npc-attacker
      if tar_kill_type != KILL_TYPE_robot_kills andAlso atk_kill_type == KILL_TYPE_plant_kills andAlso random(0,1) then poison(target, random(1,3));
   end
   if dmgtotar > 0 andAlso weapon > 0 andAlso tar_kill_type != KILL_TYPE_robot_kills  then begin
      // needler poison dmg
      if Tox > 0 andAlso caliber == CALIBER_HN_NEEDLER then begin
         poison(target, 14);
      end
      // poison atk for npc-attacker
      if attacker != dude_obj then begin
         // all non-companion npc attackers with Needler pistol
         if caliber == CALIBER_HN_NEEDLER andAlso (not(attacker_in_party) or has_skill(attacker,SKILL_SCIENCE) > 72) then begin
            poison(target, 2 + player_level / 3);
         end
         // all non-companion npc attackers who carry radscorp tails
         has_scorp_tail = obj_is_carrying_obj_pid(attacker, PID_SCORPION_TAIL);
         if (has_scorp_tail > 0 or has_small_scorp_tail > 0) andAlso not(attacker_in_party) andAlso (wpnanim == 1 or wpnanim == 4) andAlso wpndmgtype == DMG_normal_dam then begin
            poison(target, random(1,5) + player_level / 3);
         end
         // poison atk for companion npc-attacker
         if rhpoison > 0 then begin
         poison(target, (rhpoison + random(1, 4)));
            if random(0, 4) == 0 then begin
               set_fake_perk_npc(attacker, (envenomed_msg + rhname), (rhpoison - 1), 23, envenomed_description_msg);
            end
         end
      end
      // poison atk for player
      if attacker == dude_obj then begin
         acthnd = active_hand;
         if acthnd == 0 andAlso lhpoison > 0 then begin
         poison(target, ((lhpoison / 3) + random(2, 5) + (Tox * 4)));
            if random(0, 2 + (5 * Tox)) == 0 then begin
               set_fake_perk_npc(attacker, (envenomed_msg + lhname), (lhpoison - 1), 23, envenomed_description_msg);
            end
         end
         else if acthnd == 1 andAlso rhpoison > 0 then begin
         poison(target, ((rhpoison / 3) + random(2, 5) + (Tox * 4)));
            if random(0, 2 + (5 * Tox)) == 0 then begin
               set_fake_perk_npc(attacker, (envenomed_msg + rhname), (rhpoison - 1), 23, envenomed_description_msg);
            end
         end
      end
   end
   // scorch effect from fire dmg ( reduce healing rate )
   if RegenMod > 0 andAlso weapon > 0 andAlso (wpndmgtype == DMG_fire or wpnpid == 159) then begin
     tarhr = get_critter_stat(target, STAT_heal_rate);
     atkrhr = get_critter_stat(attacker, STAT_heal_rate);
     //scorch effect for target(s)
     if dmgtotar > 2 then begin
      for (burncount = -1; burncount < (dmgtotar / 8) ; burncount++) begin
        if tarhr > 5 then begin
         call stimtoburn();
         burn = create_object_sid(40, 0, 0, -1);
         add_mult_objs_to_inven(target, burn, 1);
         set_self(target);
         set_self(target);
         use_obj_on_obj(burn, target);
         set_self(0);
         if (pyromaniac > 0 or wpnpid == 159) andAlso attacker == real_dude_obj then begin
           burn = create_object_sid(40, 0, 0, -1);
           add_mult_objs_to_inven(target, burn, 1);
           set_self(target);
           set_self(target);
           use_obj_on_obj(burn, target);
           set_self(0);
         end
        end
      end
     end
   //scorch effect for attacker
   if dmgtoatkr > 8 then begin
   call stimtoburn();
      if pyromaniac > 0 then begin
      //nothing :-)
      end
        else begin
         if atkrhr > 5 then begin
         burn = create_object_sid(40, 0, 0, -1);
         add_mult_objs_to_inven(attacker, burn, 1);
         set_self(attacker);
         set_self(attacker);
         use_obj_on_obj(burn, attacker);
         set_self(0);
         end
        end
      end
   call stimrestore();
   end
   // scorch effect from plasma dmg
   if RegenMod > 0 andAlso wpndmgtype == DMG_plasma then begin
     tarhr = get_critter_stat(target, STAT_heal_rate);
     atkrhr = get_critter_stat(attacker, STAT_heal_rate);
     //scorch effect for target(s)
     if dmgtotar > 16 andAlso tarhr > 5 then begin
      for (burncount = 0; burncount < (dmgtotar / 16) ; burncount++) begin
        if tarhr > 5 then begin
         call stimtoburn();
         burn = create_object_sid(40, 0, 0, -1);
         add_mult_objs_to_inven(target, burn, 1);
         set_self(target);
         set_self(target);
         use_obj_on_obj(burn, target);
         set_self(0);
         if pyromaniac > 0 andAlso attacker == real_dude_obj then begin
           burn = create_object_sid(40, 0, 0, -1);
           add_mult_objs_to_inven(target, burn, 1);
           set_self(target);
           set_self(target);
           use_obj_on_obj(burn, target);
           set_self(0);
         end

        end
      end
     end
   //scorch effect for attacker
   if dmgtoatkr > 20 then begin
      if pyromaniac > 0 then begin
      //nothing :-)
      end
        else begin
         if atkrhr > 5 then begin
         call stimtoburn();
         burn = create_object_sid(40, 0, 0, -1);
         add_mult_objs_to_inven(attacker, burn, 1);
         set_self(attacker);
         set_self(attacker);
         use_obj_on_obj(burn, attacker);
         set_self(0);
         end
        end
      end
   call stimrestore();
   end
end

procedure stimtoburn begin // turning stimpak to burn debuff
variable rnd = 0;
rnd = random(1, 4);
   stimburn = 1;
   if UnsafeRegenModScripting > 0 andAlso sfall_unsafescripting > 0 then begin
     rnd = rnd + 3;
   set_proto_data(40, PROTO_DR_STAT_A, 0);
   set_proto_data(40, PROTO_DR_STAT_B, 0);
   set_proto_data(40, PROTO_DR_STAT_C, 14);
   set_proto_data(40, PROTO_DR_AMOUNT_1_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_1_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_1_C, - rnd);
   set_proto_data(40, PROTO_DR_DURATION_1, 2);
   set_proto_data(40, PROTO_DR_AMOUNT_2_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_C, rnd);
   set_proto_data(40, PROTO_DR_DURATION_2, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_C, 0);
   end
   if UnsafeRegenModScripting <= 0 then begin
   set_proto_data(40, PROTO_DR_STAT_A, 0);
   set_proto_data(40, PROTO_DR_STAT_B, 0);
   set_proto_data(40, PROTO_DR_STAT_C, 14);
   set_proto_data(40, PROTO_DR_AMOUNT_1_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_1_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_1_C, - rnd);
   set_proto_data(40, PROTO_DR_DURATION_1, 1);
   set_proto_data(40, PROTO_DR_AMOUNT_2_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_C, rnd);
   set_proto_data(40, PROTO_DR_DURATION_2, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_C, 0);
  end
end

procedure stimrestore begin
  if UnsafeRegenModScripting > 0 andAlso sfall_unsafescripting > 0 then begin
      set_proto_data(40, PROTO_DR_STAT_A, -2);
      set_proto_data(40, PROTO_DR_STAT_B, STAT_current_hp);
      set_proto_data(40, PROTO_DR_STAT_C, STAT_heal_rate);
      set_proto_data(40, PROTO_DR_AMOUNT_1_A, stim_min_hp);
      set_proto_data(40, PROTO_DR_AMOUNT_1_B, stim_max_hp);
      set_proto_data(40, PROTO_DR_AMOUNT_1_C, stim_hr_increase);
      set_proto_data(40, PROTO_DR_DURATION_1, stim_duration);
      set_proto_data(40, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(40, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(40, PROTO_DR_AMOUNT_2_C, -stim_hr_decrease);
      set_proto_data(40, PROTO_DR_DURATION_2, stim_penalty_duration);
      set_proto_data(40, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(40, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(40, PROTO_DR_AMOUNT_3_C, (stim_hr_decrease - stim_hr_increase));
  end
  if UnsafeRegenModScripting <= 0 then begin
   set_proto_data(40, PROTO_DR_STAT_A, -2);
   set_proto_data(40, PROTO_DR_STAT_B, 35);
   set_proto_data(40, PROTO_DR_STAT_C, 14);
   set_proto_data(40, PROTO_DR_AMOUNT_1_A, 2);
   set_proto_data(40, PROTO_DR_AMOUNT_1_B, 4);
   set_proto_data(40, PROTO_DR_AMOUNT_1_C, 6);
   set_proto_data(40, PROTO_DR_DURATION_1, 1);
   set_proto_data(40, PROTO_DR_AMOUNT_2_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_2_C, -8);
   set_proto_data(40, PROTO_DR_DURATION_2, 60);
   set_proto_data(40, PROTO_DR_AMOUNT_3_A, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_B, 0);
   set_proto_data(40, PROTO_DR_AMOUNT_3_C, 2);
  end
   stimburn = 0;
end

procedure USEOBJ begin
  variable user = get_sfall_arg;
  variable obj = get_sfall_arg;
  variable leftHand_obj = critter_inven_obj2(user, INVEN_TYPE_LEFT_HAND);
  variable rightHand_obj = critter_inven_obj2(user, INVEN_TYPE_RIGHT_HAND);
  variable party = party_member_list(0);
  variable user_in_party = is_in_array(user, party);
  variable objpid = obj_pid(obj);
  variable leftHand;
  variable rightHand;
  variable leftHanddmgtype;
  variable rightHanddmgtype;
  variable leftHandanim;
  variable rightHandanim;
  variable LHpois = 0;
  variable RHpois = 0;
  variable Tox;
  variable acthnd = active_hand;
  variable lhname;
  variable rhname;
  variable lhpoison;
  variable rhpoison;
  variable user_name = obj_name(user);
  if user == dude_obj then Tox = has_fake_perk(perk_poison_mastery_name);
  if leftHand_obj then begin
     leftHand  = obj_pid(critter_inven_obj2(user, INVEN_TYPE_LEFT_HAND));
     leftHanddmgtype = get_proto_data(leftHand, PROTO_WP_DMG_TYPE);
     leftHandanim = get_proto_data(leftHand, PROTO_WP_ANIM);
     lhname = proto_data(leftHand, 1);
     if (user_in_party or user == dude_obj) then lhpoison = has_fake_perk_npc(user, (envenomed_msg + lhname));
  end
  if rightHand_obj then begin
     rightHand = obj_pid(critter_inven_obj2(user, INVEN_TYPE_RIGHT_HAND));
     rightHanddmgtype = get_proto_data(rightHand, PROTO_WP_DMG_TYPE);
     rightHandanim = get_proto_data(rightHand, PROTO_WP_ANIM);
     rhname = proto_data(rightHand, 1);
     if (user_in_party or user == dude_obj) then rhpoison = has_fake_perk_npc(user, (envenomed_msg + rhname));
  end
  // small radscorp tail
  if PoisonMod > 0 andAlso objpid == PID_SMALL_SCORPION_TAIL then begin
   //left hand act and wpn
   if acthnd == 0 andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + lhname), (lhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   LHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
   end
   end
   //left hand act and right hand wpn
   if acthnd == 0 andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (leftHandanim != 1 or leftHanddmgtype != DMG_normal_dam) andAlso (leftHandanim != 4 or leftHand == 180 or leftHanddmgtype != DMG_normal_dam) andAlso leftHand != 522 andAlso leftHand != 234 andAlso leftHand != 190 andAlso leftHand != 128 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + rhname), (rhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   RHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
   end
   end
   //right hand act and wpn
   if acthnd == 1 andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + rhname), (rhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   RHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
   end
   end
   //right hand act and left hand wpn
   if acthnd == 1 andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (rightHandanim != 1 or rightHanddmgtype != DMG_normal_dam )andAlso (rightHandanim != 4 or rightHand == 180 or rightHanddmgtype != DMG_normal_dam) andAlso rightHand != 522 andAlso rightHand != 234 andAlso rightHand != 190 andAlso rightHand != 128 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + lhname), (lhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   LHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
   end
   end
   if random(0, 6) == (0 - tox) andAlso (((leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 )or ((rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128 ) andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 ) )then begin set_sfall_return(1);
     if user == dude_obj then display_msg(gland_gone_msg);
   end
   else begin set_sfall_return(0);
     if LHpois > 0 then begin
      display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,lhname));
     end
     if RHpois > 0 then begin
      display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,rhname));
     end
   end
  end
  // original radscorp tail
  if PoisonMod > 0 andAlso objpid == 92 then begin
   //left hand act and wpn
   if acthnd == 0 andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + lhname), (lhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   LHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
   end
   end
   //left hand act and right hand wpn
   if acthnd == 0 andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (leftHandanim != 1 or leftHanddmgtype != DMG_normal_dam) andAlso (leftHandanim != 4 or leftHand == 180 or leftHanddmgtype != DMG_normal_dam) andAlso leftHand != 522 andAlso leftHand != 234 andAlso leftHand != 190 andAlso leftHand != 128 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + rhname), (rhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   RHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
   end
   end
   //right hand act and wpn
   if acthnd == 1 andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + rhname), (rhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   RHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
   end
   end
   //right hand act and left hand wpn
   if acthnd == 1 andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (rightHandanim != 1 or rightHanddmgtype != DMG_normal_dam )andAlso (rightHandanim != 4 or rightHand == 180 or rightHanddmgtype != DMG_normal_dam) andAlso rightHand != 522 andAlso rightHand != 234 andAlso rightHand != 190 andAlso rightHand != 128 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
   set_fake_perk_npc(user, (envenomed_msg + lhname), (lhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
   if user == dude_obj then begin
   LHpois = 1;
   end
   else begin
   display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
   end
   end
   if random(0, 12) == (0 - tox) andAlso (((leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 )or ((rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128 ) andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 ) )then begin set_sfall_return(1);
      if user == dude_obj then display_msg(gland_gone_msg);
   end
   else begin set_sfall_return(0);
     if LHpois > 0 then begin
      display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,lhname));
     end
     if RHpois > 0 then begin
      display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,rhname));
     end
   end
  end
  if PoisonMod > 0 andAlso (objpid == PID_SMALL_SCORPION_TAIL or objpid == 92) then begin
   if (user_in_party or user == dude_obj) andAlso has_fake_perk_npc(user, (envenomed_msg + rhname)) > (10 + (5 * tox)) then begin
     set_fake_perk_npc(user, (envenomed_msg + rhname), 10 + (5 * tox), 23, envenomed_description_msg);
     display_msg(parse_str_2(modmsg(msg_wpn_poison_full), user_name,rhname));
   end
   if (user_in_party or user == dude_obj) andAlso has_fake_perk_npc(user, (envenomed_msg + lhname)) > (10 + (5 * tox)) then begin
     set_fake_perk_npc(user, (envenomed_msg + lhname), 10 + (5 * tox), 23, envenomed_description_msg);
     display_msg(parse_str_2(modmsg(msg_wpn_poison_full), user_name,lhname));
   end
  end
end

procedure USEOBJON begin
   variable target = get_sfall_arg;
   variable user = get_sfall_arg;
   variable obj = get_sfall_arg;
   variable objpid = obj_pid(obj);
   variable target_obj_type = obj_type(target);
   variable leftHand_obj = critter_inven_obj2(target, INVEN_TYPE_LEFT_HAND);
   variable rightHand_obj = critter_inven_obj2(target, INVEN_TYPE_RIGHT_HAND);
   variable leftHand;
   variable rightHand;
   variable leftHanddmgtype;
   variable rightHanddmgtype;
   variable leftHandanim;
   variable rightHandanim;
   variable LHpois = 0;
   variable RHpois = 0;
   variable injuryhealed = 0;
   variable SShphealed;
   variable HRhealcost = 0;
   variable SShpdmg = 0;
   variable tarHR;
   variable Tox;
   variable fast_meta = has_trait(TRAIT_TRAIT, real_dude_obj, TRAIT_fast_metabolism);
   variable STEAL_MOD = 0;
   variable target_pe;
   variable lhname;
   variable rhname;
   variable lhpoison;
   variable rhpoison;
   variable tar_name = obj_name(target);
   variable user_name = obj_name(user);
   variable party = party_member_list(0);
   variable user_in_party = is_in_array(user,party);
   variable target_in_party;
   variable tar_type;
   variable tar_fid;
   variable tar_cur_hp;
   variable tar_state;
   if target_obj_type == OBJ_TYPE_CRITTER then begin
      tar_cur_hp = get_critter_stat(target, STAT_current_hp);
      SShphealed = get_critter_stat(target, STAT_max_hit_points) - tar_cur_hp;
      tarHR = get_critter_stat(target, STAT_heal_rate);
      target_pe = get_critter_stat(target, STAT_pe);
      target_in_party = is_in_array(target, party);
      tar_type = metarule(METARULE_CRITTER_KILL_TYPE, target);
      tar_state = critter_state(target);
   end
   if user == dude_obj then Tox = has_fake_perk(perk_poison_mastery_name);
   if leftHand_obj then begin
     leftHand = obj_pid(critter_inven_obj2(target, INVEN_TYPE_LEFT_HAND));
     leftHanddmgtype = get_proto_data(leftHand, PROTO_WP_DMG_TYPE);
     leftHandanim = get_proto_data(leftHand, PROTO_WP_ANIM);
     lhname = proto_data(leftHand, 1);
     if (target_in_party or target == real_dude_obj) then lhpoison = has_fake_perk_npc(target, (envenomed_msg + lhname));
   end
   if rightHand_obj then begin
     rightHand = obj_pid(critter_inven_obj2(target, INVEN_TYPE_RIGHT_HAND));
     rightHanddmgtype = get_proto_data(rightHand, PROTO_WP_DMG_TYPE);
     rightHandanim = get_proto_data(rightHand, PROTO_WP_ANIM);
     rhname = proto_data(rightHand, 1);
     if (target_in_party or target == real_dude_obj) then rhpoison = has_fake_perk_npc(target, (envenomed_msg + rhname));
   end
   //divides the duration of drug by 4 (examle: from 1 min to 15 sec)
   //if UnsafeRegenModScripting != 0 andAlso sfall_unsafescripting != 0 then begin
      // return memory to normal if was modified
      if read_int(0x479BD4) != 280509755 then begin // return to normal memory adress stat
         write_int(0x479BD4, 280509755);
      end
      // return memory to normal if was modified
      if read_int(0x479BE8) != -288292236 then begin // return to normal memory adress stat
         write_int(0x479BE8, -288292236);
      end
      if tar_cur_hp > 0 andAlso tar_state != CRITTER_IS_DEAD then begin
         if objpid == PID_STIMPAK or objpid == PID_HEALING_POWDER then begin// only for stimpak and healing powder, other drugs unaffected (can be used for any drug item if needed)
            write_int(0x479BD4, read_int(0x479BEA)); // drug duration logical right shift by 1 ¹1
            write_int(0x479BE8, read_int(0x479BEA)); // drug duration logical right shift by 1 ¹2
         end
      end
   //end
   //if UnsafeRegenModScripting == 0 andAlso sfall_unsafescripting < 1 then begin
      // return memory to normal if was modified
      //if read_int(0x479BD4) != 280509755 then begin // return to normal memory adress stat
      //write_int(0x479BD4, 280509755);
      //end
      //if objpid == PID_STIMPAK or objpid == PID_HEALING_POWDER then begin// only for stimpak and healing powder, other drugs unaffected (can be used for any drug item if needed)
      //write_int(0x479BD4, read_int(0x479BEA)); // drug duration logical right shift by 1 ¹1 (duration divided by 2)
      //end
   //end
   //
  if objpid == PID_HYPO_POISON andAlso tar_cur_hp > 0 andAlso tar_state != CRITTER_IS_DEAD andAlso user_in_party andAlso target_obj_type == OBJ_TYPE_CRITTER andAlso not(target_in_party) then begin
    if obj_can_see_obj(target, user) andAlso (random(30, target_pe * 30) > random(0, (has_skill(user, SKILL_FIRST_AID) + has_skill(user, SKILL_DOCTOR) + has_skill(user, SKILL_SNEAK)))) andAlso get_proto_data(obj_pid(target), PROTO_CR_BODY_TYPE) != CR_BODY_ROBOTIC then begin
     tar_fid = critter_art_fid(target);
     //if using_skill(dude_obj, SKILL_SNEAK) then begin
        //display_msg(failed_sneak_use_msg);
     //end
     if random(0,1) andAlso not(combat_is_initialized) andAlso get_critter_stat(target, STAT_iq) > 3 andAlso get_proto_data(obj_pid(target), PROTO_CR_BODY_TYPE) == CR_BODY_BIPED andAlso tar_type != KILL_TYPE_children_kills andAlso tar_fid != FID_NFBRLP andAlso tar_fid != 16777336 andAlso tar_fid != 16777325 then begin
        float_msg(target, modmsg(random(msg_failedPoisoning1,msg_failedPoisoning4)), FLOAT_COLOR_AFRAID);
        set_sfall_return(0);
     end
     else begin
        //if get_poison(target) + Poison_amt * get_critter_stat(target, STAT_poison_resist) / 100 < 99 then begin
        display_msg(failed_sneak_use_msg);
        attack_setup(target,user);
        //set_self(target);
        //attack(user);
        //set_self(0);
        //end
     end
   end
  end
  // stimpak usage timer start
  if user == real_dude_obj andAlso target == real_dude_obj andAlso objpid == 40 then begin
   stimtimer = game_time;
  end
  // modified stimpak if dude hase fast_metabolism
  if RegenMod > 0 andAlso stimburn == 0 andAlso fast_meta >= 1 then begin
   if target == real_dude_obj then begin
     if UnsafeRegenModScripting > 0 andAlso sfall_unsafescripting > 0 then begin
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_A, -2);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_B, STAT_current_hp);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_C, STAT_heal_rate);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_A, stim_min_hp_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_B, stim_max_hp_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_C, stim_hr_increase_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_1, stim_duration_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_C, -stim_hr_decrease_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_2, stim_penalty_duration_fast_meta);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_C, (stim_hr_decrease_fast_meta - stim_hr_increase_fast_meta));
     end
     //if UnsafeRegenModScripting <= 0 then begin
     else begin
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_A, -2);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_B, 35);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_C, 14);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_A, 4);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_B, 6);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_C, 8);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_1, 1);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_C, -10);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_2, 1);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_C, 2);
     end
   end
   if target != real_dude_obj andAlso tar_cur_hp > 0 andAlso tar_state != CRITTER_IS_DEAD then begin
     call stimrestore();
   end
  end
  // superstimpak usage mechanics
   if RegenMod > 0 andAlso objpid == PID_SUPER_STIMPAK andAlso tar_cur_hp > 0 andAlso tar_state != CRITTER_IS_DEAD then begin
      if StimUninjure == 1 then begin
         if critter_state(target) BWAND DAM_CRIP_LEG_LEFT then begin
            injuryhealed += 5;
         end
         if critter_state(target) BWAND DAM_CRIP_LEG_RIGHT then begin
            injuryhealed += 5;
         end
         if critter_state(target) BWAND DAM_CRIP_ARM_LEFT then begin
            injuryhealed += 4;
         end
         if critter_state(target) BWAND DAM_CRIP_ARM_RIGHT then begin
            injuryhealed += 4;
         end
         if critter_state(target) BWAND DAM_BLIND then begin
            injuryhealed += 3;
         end
         critter_uninjure(target, (DAM_CRIP_LEG_LEFT BWOR DAM_CRIP_LEG_RIGHT BWOR DAM_CRIP_ARM_LEFT BWOR DAM_CRIP_ARM_RIGHT BWOR DAM_BLIND));
      end
      if Resurrection <= 0 then begin
         if SShphealed > 60 then begin
           SShphealed = 60;
         end
         HRhealcost = SShphealed / 3;
         if HRhealcost < 1 then begin
           HRhealcost = 0;
         end
         SShpdmg = (tarHR - (2 * HRhealcost + (injuryhealed / 4))) / 3;
         if SShpdmg > 0 then begin
           SShpdmg = 0;
         end
         if SShphealed == 0 then begin
           SShpdmg = 0;
         end
         if SShphealed < SShpdmg then begin
           SShpdmg = SShphealed;
         end
         // display_msg("SShpdmg=" + SShpdmg);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_A, STAT_current_hp);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_B, STAT_heal_rate);
         //set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, -1);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_A, SShphealed - injuryhealed);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_B, - (HRhealcost + (injuryhealed / 5)));
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, 0);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_DURATION_1, 2);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_A, SShpdmg);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_B, ceil((HRhealcost + (injuryhealed / 5)) / 2.00000));
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 0);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_DURATION_2, 480);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_B, floor2((HRhealcost + (injuryhealed / 5)) / 2.00000));
         set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
         if Sonora > 0 then begin
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, STAT_st);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, -1);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 1);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
         end
         else begin
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, -1);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, 0);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 0);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
         end
            // modified stimpak if dude hase fast_metabolism
         if fast_meta andAlso target == real_dude_obj then begin
            SShpdmg = (tarHR - (2 * HRhealcost + (injuryhealed / 6))) / 4;
            if SShpdmg > 0 then begin
              SShpdmg = 0;
            end
            HRhealcost = SShphealed / 4;
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_A, STAT_current_hp);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_B, STAT_heal_rate);
            //set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, -1);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_A, 10 + SShphealed - (injuryhealed / 2));
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_B, - (HRhealcost + (injuryhealed / 10)));
            //set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, 0);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_DURATION_1, 1);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_A, SShpdmg);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_B, ceil((HRhealcost + (injuryhealed / 10)) / 2.00000));
            //set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 0);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_DURATION_2, 220);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
            set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_B, floor2((HRhealcost + (injuryhealed / 10)) / 2.00000));
            //set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
            if Sonora > 0 then begin
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, STAT_st);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, -1);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 1);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
            end
            else begin
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_STAT_C, -1);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_1_C, 0);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_2_C, 0);
               set_proto_data(PID_SUPER_STIMPAK, PROTO_DR_AMOUNT_3_C, 0);
            end
         end
      end
   end
  // small radscorp tail
  if PoisonMod > 0 andAlso objpid == PID_SMALL_SCORPION_TAIL andAlso target_obj_type == OBJ_TYPE_CRITTER andAlso (target_in_party or target == real_dude_obj) andAlso user_in_party then begin
   //right hand act and wpn
   if rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
   if user == dude_obj then set_fake_perk_npc(target, (envenomed_msg + proto_data(rightHand, 1)), (rhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user != dude_obj then set_fake_perk_npc(target, (envenomed_msg + proto_data(rightHand, 1)), (rhpoison + 4 + (6 * tox)), 23, envenomed_description_msg);
      RHpois = 1;
   end
   //right hand act and left hand wpn
   if leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (rightHandanim != 1 or rightHanddmgtype != DMG_normal_dam )andAlso (rightHandanim != 4 or rightHand == 180 or rightHanddmgtype != DMG_normal_dam)  andAlso rightHand != 522 andAlso rightHand != 234 andAlso rightHand != 190 andAlso rightHand != 128 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
   if user == dude_obj then set_fake_perk_npc(target, (envenomed_msg + proto_data(leftHand, 1)), (lhpoison + 3 + (6 * tox)), 23, envenomed_description_msg);
   if user != dude_obj then  set_fake_perk_npc(target, (envenomed_msg + proto_data(leftHand, 1)), (lhpoison + 4 + (6 * tox)), 23, envenomed_description_msg);
   LHpois = 1;
   end
   if random(0, 6) == (0 - tox) andAlso (((leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 )or ((rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128 ) andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 ) )then begin
     set_sfall_return(1);
     if target != dude_obj andAlso user == dude_obj then begin
         display_msg(parse_str_2(modmsg(msg_gland_gone_npc), tar_name,0));
     end
     else begin
      if user == dude_obj then display_msg(gland_gone_msg);
     end
   end
   else begin set_sfall_return(0);
     if LHpois > 0 then begin
         if user == dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,lhname));
         if user != dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
     end
     if RHpois > 0 then begin
         if user == dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,rhname));
         if user != dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
     end
   end
  end
  // original radscorp tail
  if PoisonMod > 0 andAlso objpid == 92 andAlso target_obj_type == OBJ_TYPE_CRITTER andAlso (target_in_party or target == real_dude_obj) andAlso user_in_party then begin
   //right hand act and wpn
     if rightHand_obj andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 andAlso (rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128) then begin
        if user == dude_obj then set_fake_perk_npc(target, (envenomed_msg + rhname), (rhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
        if user != dude_obj then set_fake_perk_npc(target, (envenomed_msg + rhname), (rhpoison + 6 + (20 * tox)), 23, envenomed_description_msg);
        RHpois = 1;
     end
     //right hand act and left hand wpn
     if leftHand_obj andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 andAlso (rightHandanim != 1 or rightHanddmgtype != DMG_normal_dam )andAlso (rightHandanim != 4 or rightHand == 180 or rightHanddmgtype != DMG_normal_dam) andAlso rightHand != 522 andAlso rightHand != 234 andAlso rightHand != 190 andAlso rightHand != 128 andAlso (leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) then begin
        if user == dude_obj then set_fake_perk_npc(target, (envenomed_msg + lhname), (lhpoison + 4 + (20 * tox)), 23, envenomed_description_msg);
        if user != dude_obj then set_fake_perk_npc(target, (envenomed_msg + lhname), (lhpoison + 6 + (20 * tox)), 23, envenomed_description_msg);
        LHpois = 1;
     end
     if random(0, 12) == (0 - tox) andAlso (((leftHandanim == 1 or leftHandanim == 4 or leftHand == 522 or leftHand == 234 or leftHand == 190 or leftHand == 128) andAlso leftHanddmgtype == DMG_normal_dam andAlso leftHand != 180 )or ((rightHandanim == 1 or rightHandanim == 4 or rightHand == 522 or rightHand == 234 or rightHand == 190 or rightHand == 128 ) andAlso rightHanddmgtype == DMG_normal_dam andAlso rightHand != 180 ) )then begin
      set_sfall_return(1);
     if target != dude_obj andAlso user == dude_obj  then begin
     display_msg(parse_str_2(modmsg(msg_gland_gone_npc), tar_name,0));
     end
     else begin
      if user == dude_obj then display_msg(gland_gone_msg);
     end
   end
   else begin set_sfall_return(0);
     if LHpois > 0 then begin
         if user == dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,lhname));
         if user != dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,lhname));
     end
     if RHpois > 0 then begin
         if user == dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_player), user_name,rhname));
         if user != dude_obj then display_msg(parse_str_2(modmsg(msg_pois_appl_npc), user_name,rhname));
     end
   end
  end
  if PoisonMod > 0 andAlso (objpid == PID_SMALL_SCORPION_TAIL or objpid == 92) andAlso target_obj_type == OBJ_TYPE_CRITTER andAlso (target_in_party or target == real_dude_obj) andAlso user_in_party then begin
   if (target_in_party or target == dude_obj) andAlso has_fake_perk_npc(target, (envenomed_msg + rhname)) > (10 + (5 * tox)) then begin
     set_fake_perk_npc(target, (envenomed_msg + rhname), 10 + (5 * tox), 23, envenomed_description_msg);
     if user == dude_obj then display_msg(parse_str_2(modmsg(msg_wpn_poison_full), user_name,rhname));
   end
   if (target_in_party or target == dude_obj) andAlso has_fake_perk_npc(target, (envenomed_msg + lhname)) > (10 + (5 * tox)) then begin
     set_fake_perk_npc(target, (envenomed_msg + lhname), 10 + (5 * tox), 23, envenomed_description_msg);
     if user == dude_obj then display_msg(parse_str_2(modmsg(msg_wpn_poison_full), user_name,lhname));
   end
  end
end

procedure USESKIL begin
  variable user = get_sfall_arg;
  variable target = get_sfall_arg;
  variable skill = get_sfall_arg;
  variable skill_bonus = get_sfall_arg;
  dudehrcount = 0;
  healfromskill = 0;
  deadtarget = 0;
  if (RegenMod > 0  or PoisonMod > 0) andAlso (skill == SKILL_FIRST_AID or skill == SKILL_DOCTOR) andAlso get_critter_stat(target, STAT_current_hp) > 0 then begin
   healfromskill = target;
   call rest;
   if deadtarget > 0 then begin
   FadeOut(300);
   game_time_advance(5150);
   FadeIn(300);
   set_sfall_return(0);
   end
   if PoisonDecayDiv != 10 then begin
    call rest;
   end
   healfromskill = 0;
   game_time_advance(500);
  end
end

procedure map_exit_p_proc begin
  variable critwaspoisoned = 0;
  variable tardt = 0;
  variable critter;
  variable party = party_member_list(0);
  variable critter_in_party;
  variable critcurpoison;
  variable critcurhp;
  variable critmaxhp;
  variable dudehrexitmap;
  variable critter_body_type;
  variable has_antidote;
  variable has_super_antidote;
  variable antidote;
  map_exit = 1;
  if new_death > 0 then call show_death_msg;
  if game_ui_is_disabled then game_ui_enable;
  if get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
  RegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
  DudeRegenTickHP = RegenTickHP;
  end
  foreach critter in list_as_array(0) begin
   poisondeath = 0;
   PoisonTickDmg = 0;
   critter_in_party = is_in_array(critter, party);
   // regen if not poisoned (exept dude and party)
   if RegenMod > 0  andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp) andAlso get_poison(Critter) < 1 andAlso critter != real_dude_obj andAlso not(critter_in_party) then begin
     if (RegenMaxHPpercentMult < 1) then begin
      RegenMaxHPpercentMult = 1;
     end
     RegenTickHP = (round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * random(4, 8) * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
     if (RegenTickHP < 1) then begin
      RegenTickHP = 1;
     end
   critter_heal(critter, RegenTickHP);
   end

   // if poisoned (exept dude and party)
   while PoisonMod > 0 andAlso (get_critter_stat(critter, STAT_current_hp ) - PoisonTickDmg) > 0 andAlso get_poison(Critter) > 0 andAlso critter != real_dude_obj andAlso not(critter_in_party) andAlso get_critter_stat(critter, STAT_current_hp ) > 0 do begin
      critcurpoison = get_poison(Critter);
      critcurhp = get_critter_stat(critter, STAT_current_hp );
      critmaxhp = get_critter_stat(critter, STAT_max_hp );
      // npc use antidote oute of combat
      if PoisonMod > 0 andAlso Critter != real_dude_obj andAlso critcurpoison > 5 andAlso critcurhp > 0 andAlso not(is_dead(critter)) then begin
         //critter_cur_frm = get_object_data(critter, OBJ_DATA_CUR_FRM);
         critter_body_type = get_proto_data(obj_pid(critter), PROTO_CR_BODY_TYPE);
         if not(is_prone(critter)) andAlso critter_body_type == CR_BODY_BIPED then begin
            has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
            if Nevada > 0 then has_super_antidote = obj_is_carrying_obj_pid(Critter, 53);
            if (has_antidote > 0 or (Nevada > 0 andAlso has_super_antidote)) andAlso ((critter_in_party andAlso ((critcurpoison > 10 andAlso critcurhp < (critmaxhp / 4)) or critcurpoison > 25 or critcurhp < 14)) or (not(critter_in_party) andAlso ((random(10,50)) < critcurpoison or critcurhp <= 13 or critcurhp < (critmaxhp / 5))) ) then begin
               tail_used = 1;
               antidote = obj_carrying_pid_obj(critter, PID_ANTIDOTE);
               if Nevada > 0 andAlso has_super_antidote > 0 andAlso (critcurpoison > 25 or (has_antidote <= 0 andAlso critcurpoison > 15)) then antidote = obj_carrying_pid_obj(critter, 53);
               set_self(critter);
               set_self(critter);
               use_obj_on_obj(antidote, critter);
               set_self(0);
               if critter_in_party andAlso critcurpoison > 30 then poison(critter, -(get_poison(Critter) / 2));
               //display_msg(parse_str_2(modmsg(msg_npc_use_item), tar_name, proto_data(PID_ANTIDOTE, 1)));
            end
         end
      end
     poisondeath = 0;
     // regen while poisonedd
     if RegenMod > 0  andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 then begin
      if (RegenMaxHPpercentMult < 1) then begin
      RegenMaxHPpercentMult = 1;
      end
      RegenTickHP = round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * random(0, 1) * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
      if (RegenTickHP < 1) then begin
      RegenTickHP = 1;
      end
      critter_heal(critter, RegenTickHP);
     end
      //Poison dmg
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
     PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
      if PoisonTickDmg < min_poison_dmg then begin
        PoisonTickDmg = min_poison_dmg;
      end

     if PoisonTickDmg > 0 andAlso Critter != real_dude_obj then begin
      if (get_critter_stat(critter, STAT_current_hp ) - PoisonTickDmg) < 1 then begin
         poisondeath = 1;
      end
      else begin
      end
     end
     if poisondeath == 0 then begin
        poison(critter, - (min_poison_decay + (round(get_poison(Critter) * 0.10 ) * 10 / PoisonDecayDiv)));
        critter_heal(Critter, - PoisonTickDmg);
     end
     PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
      if PoisonTickDmg < min_poison_dmg then begin
        PoisonTickDmg = min_poison_dmg;
      end

   end
   // heal after poison is cleared (exept dude and party)
   if RegenMod > 0  andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp) andAlso get_poison(Critter) < 1 andAlso critter != real_dude_obj andAlso not(critter_in_party) then begin
     if (RegenMaxHPpercentMult < 1) then begin
     RegenMaxHPpercentMult = 1;
     end
     RegenTickHP = (round(get_critter_stat(critter, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * random(4, 8) * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
     if (RegenTickHP < 1) then begin
     RegenTickHP = 1;
     end
     critter_heal(critter, RegenTickHP);
   end
  end
  dudehrcount = ((660 - (game_time - stimtimer)) / 120);
  if (stimtimer < 1 or dudehrcount < 0) andAlso get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
  dudehrcount = 6;
  end
end

procedure rest begin
  variable gameticks = 0;
  variable eventtype = 0;
  variable critter_array = 0;
  variable theonecrit = 0;
  variable theonecrit2 = 0;
  variable lastdudehr = 0;
  variable i = 0;
  variable tarishealing = 0;
  variable tardt = 0;
  variable tardr = 0;
  variable tar_name = 0;
  variable critter_fid = 0;
  variable crit_pid = 0;
  variable critter;
  variable critcurpoison;
  variable critcurhp;
  //variable party = party_member_list(0);
  //variable critter_in_party;
  variable critter_team;
  variable critter_body_type;
  variable has_antidote;
  variable has_super_antidote;
  variable critmaxhp;
  variable antidote;
  RegenTickHP2 = 0;
  gameticks = get_sfall_arg;
  eventtype = get_sfall_arg;
  for (i = 0; i < 20; i++) begin
   foreach (critter in list_as_array(0)) begin
     poisondeath = 0;
     tar_name = obj_name(critter);
     //critter_in_party = is_in_array(critter, party);
     critter_team = has_trait(TRAIT_OBJECT, critter, OBJECT_TEAM_NUM);
     crit_pid = obj_pid(critter);
           // regen while resting/time skipping
              if RegenMod > 0  andAlso ((critter != real_dude_obj andAlso (get_poison(Critter) < 1 or  PoisonMod <= 0) ) or critter == real_dude_obj) andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso  get_critter_stat(critter, STAT_heal_rate) > 5 andAlso (get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp)) or (critcrippled(real_dude_obj) andAlso critter == real_dude_obj andAlso has_fake_perk(regen_perk_name) > 0) then begin
               if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
               RegenTickHP = ( round(get_critter_stat(critter, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
               if (RegenTickHP < 1) then begin RegenTickHP = 1; end

               if critter == real_dude_obj then begin
                 DudeRegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
                 if get_poison(real_dude_obj) < 1 then begin
                  if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter == real_dude_obj AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                    end
                    critter_heal(real_dude_obj, RegenTickHP);
                  end
                  if critter == real_dude_obj AndAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(real_dude_obj) then begin
                    call cripheal();
                  end
                 tarishealing = 1;
                 end
                 dudehrcount += 1;
               end
               else begin
                 tarishealing = 1;
                  if get_critter_stat(critter, STAT_current_hp ) + RegenTickHP >= get_critter_stat(critter, STAT_max_hp ) then begin
                    RegenTickHP = get_critter_stat(critter, STAT_max_hp ) - get_critter_stat(critter, STAT_current_hp );
                  end
                 if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
                    end
                 end
                  critter_heal(critter, RegenTickHP);
               end
              end
             // poison dmg while resting/time skipping
             if PoisonMod > 0 andAlso get_poison(Critter) > 0 andAlso get_critter_stat(critter, STAT_current_hp ) > 0 then begin
               critcurpoison = get_poison(Critter);
               critcurhp = get_critter_stat(critter, STAT_current_hp );
               critmaxhp = get_critter_stat(critter, STAT_max_hp );
               // npc use antidote oute of combat
               if PoisonMod > 0 andAlso Critter != real_dude_obj andAlso critcurpoison > 5 andAlso critcurhp > 0 andAlso not(is_dead(critter)) then begin
                  //critter_cur_frm = get_object_data(critter, OBJ_DATA_CUR_FRM);
                  critter_body_type = get_proto_data(obj_pid(critter), PROTO_CR_BODY_TYPE);
                  if not(is_prone(critter)) andAlso critter_body_type == CR_BODY_BIPED then begin
                     has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
                     if Nevada > 0 then has_super_antidote = obj_is_carrying_obj_pid(Critter, 53);
                     if (has_antidote > 0 or (Nevada > 0 andAlso has_super_antidote)) andAlso ((critter_team == TEAM_PLAYER andAlso ((critcurpoison > 10 andAlso critcurhp < (critmaxhp / 4)) or critcurpoison > 25 or critcurhp < 14)) or (critter_team != TEAM_PLAYER andAlso ((random(10,50)) < critcurpoison or critcurhp <= 13 or critcurhp < (critmaxhp / 5))) ) then begin
                        tail_used = 1;
                        antidote = obj_carrying_pid_obj(critter, PID_ANTIDOTE);
                        if Nevada > 0 andAlso has_super_antidote > 0 andAlso (critcurpoison > 25 or (has_antidote <= 0 andAlso critcurpoison > 15)) then antidote = obj_carrying_pid_obj(critter, 53);
                        set_self(critter);
                        set_self(critter);
                        use_obj_on_obj(antidote, critter);
                        set_self(0);
                        if critter_team == TEAM_PLAYER  andAlso critcurpoison > 30 then poison(critter, -(get_poison(Critter) / 2));
                        display_msg(parse_str_2(modmsg(msg_npc_use_item), tar_name, proto_data(PID_ANTIDOTE, 1)));
                     end
                  end
               end


              if RegenMod > 0  andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 then begin
               if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
               RegenTickHP = ( round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
               if (RegenTickHP < 1) then begin RegenTickHP = 1; end
               if get_critter_stat(critter, STAT_current_hp ) + RegenTickHP >= get_critter_stat(critter, STAT_max_hp ) then begin
                 RegenTickHP = get_critter_stat(critter, STAT_max_hp ) - get_critter_stat(critter, STAT_current_hp );
               end
                  if critter == real_dude_obj AndAlso has_fake_perk(regen_perk_name) != 0 andAlso critcrippled(real_dude_obj) then begin
                    call cripheal();
                  end
               tarishealing = 1;

               if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter == real_dude_obj AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                    end
               end
               if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
                    end
               end
               critter_heal(critter, RegenTickHP);
               if get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
               lastdudehr = get_critter_stat(real_dude_obj, STAT_heal_rate);
               end
              end
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if critter_team != TEAM_PLAYER andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
                 PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
                  if PoisonTickDmg < min_poison_dmg then begin
                    PoisonTickDmg = min_poison_dmg;
                  end
               //critter_heal(Critter, - PoisonTickDmg);
               if PoisonTickDmg > 0 andAlso ShowModMSG > 0 andAlso Critter == real_dude_obj then begin
                 display_msg(parse_str_2(modmsg(msg_player_poison_dmg), tar_name,PoisonTickDmg));
               end
               poison(critter, - (min_poison_decay + (round(get_poison(Critter) * 0.10 ) * 10 / PoisonDecayDiv)));
               if PoisonTickDmg > 0 andAlso Critter != real_dude_obj then begin
                 if get_critter_stat(critter, STAT_current_hp) <= PoisonTickDmg then begin
                  if critter == healfromskill then begin
                  deadtarget += 1;
                  end
                  if critter_team == TEAM_PLAYER then begin
                     poison(critter, -(get_poison(critter) + 1));
                     //reg_anim_clear(critter);

                     //party_remove(critter);
                     call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
                     poisondeath = 1;
                     //critter_heal(Critter, - 9999);
                     //display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), tar_name, PoisonTickDmg));
                  end
                  else begin
                     poison(critter, -(get_poison(critter) + 1));
                     //reg_anim_clear(critter);
                     //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
                     //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);
                     //poisondeath = 1;
                     //if HR_fog_of_war then set_outline(critter, OUTLINE_NEW_RED);
                     //set_target_knockback(critter, 0, 0);
                     //poison(critter, - 999);
                     //critter_heal(Critter, - (get_critter_stat(critter, STAT_current_hp) - 1));
                     //set_proto_data(crit_pid, CRITTER_PROTO_DT, 0);
                     //set_proto_data(crit_pid, CRITTER_PROTO_DR, 0);
                     //critter_dmg(critter, PoisonTickDmg, DMG_plasma);
                     call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
                     poisondeath = 1;
                     //set_proto_data(crit_pid, CRITTER_PROTO_DT, tardt);
                     //set_proto_data(crit_pid, CRITTER_PROTO_DR, tardr);
                     //critter_fid = critter_art_fid(Critter);
                     //if critter_fid != 16777322 andAlso crit_pid != 16777508 then begin
                     //give_xp((get_proto_data(crit_pid, PROTO_CR_KILL_EXP)));
                     //end
                  end
                 end
                 else begin
                  if ShowModMSG > 0 then begin
                     if Critter != real_dude_obj then
                        display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
                  end
                 end
               end
               if poisondeath == 0 then begin
               critter_heal(Critter, - PoisonTickDmg);
               end
              end
              //if target dies from poison during skill use triggers original poison script to dmg real_dude_obj
              if deadtarget != 0 andAlso i > 18 then begin
              healfromskill = 0;
              end
   end
   if tarishealing > 0 then begin
   game_time_advance(49);
   end
   tarishealing = 0;
  end
end

procedure worldMapTravel begin
  variable lastgamemode = get_sfall_arg_at(1);
  variable partypoisoncountdown = 0;
  variable critterishealing = 0;
  variable poisonedcrit = 0;
  variable tar_name = 0;
  variable critter;
  variable party = party_member_list(0);
  variable critter_in_party;
  variable critcurpoison;
  variable critcurhp;
  variable critmaxhp;
  variable dudehrexitmap;
  variable critter_body_type;
  variable has_antidote;
  variable has_super_antidote;
  variable antidote;
  variable tmp;
  if lastgamemode bwand OPTIONS then begin
     combat_diff = (combat_difficulty + 1);
  end
  gamemode = get_game_mode;
  RegenTickHP2 = 0;
  dudehrcount2 = 0;
  DudeRegenTickHP = 0;
  dudeishealing = 0;
  //regenperk activation
  if (lastgamemode bwor CHARSCREEN) or (gamemode bwor CHARSCREEN) then begin
   call newperks;
  end
  if new_death > 0 then begin
     mode_change_death = 1;
     call show_death_msg;
  end
  if critter_poison_overdose > 0 then begin
     call critter_inflict_poison_dmg(critter_poison_overdose, (get_critter_stat(critter_poison_overdose, STAT_max_hp) * 3),1);
     //if critter_poison_overdose == dude_obj then
        game_ui_enable;
     //critter_poison_overdose = 0;
  end
  if (lastgamemode == PCOMBAT andAlso gamemode == WORLDMAP) orElse (lastgamemode == DIALOG andAlso gamemode == WORLDMAP) orElse (lastgamemode == LOADGAME andAlso gamemode == WORLDMAP) orElse (lastgamemode == COMBAT andAlso gamemode == WORLDMAP) orElse (lastgamemode == 0 andAlso gamemode == WORLDMAP) then begin
  if get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
   dudeishealing = 1;
  end
      for (partypoisoncountdown = 0; partypoisoncountdown < 20 ; partypoisoncountdown++) begin
                     critterishealing = 0;
             foreach (critter in party) begin
                tar_name = obj_name(critter);
              // regen for party memebers and dude_obj
               if RegenMod > 0  andAlso get_poison(critter) < 1 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso (get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) or (critter == real_dude_obj andAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(critter))) then begin
               if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
               RegenTickHP = round(get_critter_stat(critter, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
               if RegenTickHP < 1 then begin RegenTickHP = 1; end
                  if get_critter_stat(critter, STAT_current_hp ) + RegenTickHP >= get_critter_stat(critter, STAT_max_hp ) then begin
                    RegenTickHP = get_critter_stat(critter, STAT_max_hp ) - get_critter_stat(critter, STAT_current_hp );
                  end
                  if critter == real_dude_obj AndAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(real_dude_obj) then begin
                    call cripheal();
                  end
                 critterishealing = 1;
                 poisonedcrit = 1;

                  if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter == real_dude_obj AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                    end
                  end
                  if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
                    end
                  end
                  critter_heal(critter, RegenTickHP);
               end
                      // Poison dmg for party memebers and real_dude_obj if dude is regenerating
                     critter_in_party = is_in_array(critter, party);
                     if critter_in_party andAlso (get_poison(real_dude_obj) <= 0 or get_critter_stat(real_dude_obj, STAT_heal_rate) > 5) then begin
                       if PoisonMod > 0 andAlso (critter != real_dude_obj orElse (RegenMod > 0  andAlso critter == real_dude_obj andAlso dudeishealing > 0) ) andAlso get_poison(Critter) > 0  andAlso get_critter_stat(critter, STAT_current_hp ) > 0then begin
                           critcurpoison = get_poison(Critter);
                           critcurhp = get_critter_stat(critter, STAT_current_hp );
                           critmaxhp = get_critter_stat(critter, STAT_max_hp );
                           // npc use antidote oute of combat
                           if PoisonMod > 0 andAlso Critter != real_dude_obj andAlso critcurpoison > 5 andAlso critcurhp > 0 andAlso not(is_dead(critter)) then begin
                              //critter_cur_frm = get_object_data(critter, OBJ_DATA_CUR_FRM);
                              critter_body_type = get_proto_data(obj_pid(critter), PROTO_CR_BODY_TYPE);
                              if not(is_prone(critter)) andAlso critter_body_type == CR_BODY_BIPED then begin
                                   has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
                                 if Nevada > 0 then has_super_antidote = obj_is_carrying_obj_pid(Critter, 53);
                                 if (has_antidote > 0 or (Nevada > 0 andAlso has_super_antidote)) andAlso ((critter_in_party andAlso ((critcurpoison > 10 andAlso critcurhp < (critmaxhp / 4)) or critcurpoison > 25 or critcurhp < 14)) or (not(critter_in_party) andAlso ((random(10,50)) < critcurpoison or critcurhp <= 13 or critcurhp < (critmaxhp / 5))) ) andAlso get_critter_stat(critter, STAT_current_hp ) > 0 then begin
                                    tail_used = 1;
                                    antidote = obj_carrying_pid_obj(critter, PID_ANTIDOTE);
                                    if Nevada > 0 andAlso has_super_antidote > 0 andAlso (critcurpoison > 25 or (has_antidote <= 0 andAlso critcurpoison > 15)) then antidote = obj_carrying_pid_obj(critter, 53);
                                    set_self(critter);
                                    set_self(critter);
                                    use_obj_on_obj(antidote, critter);
                                    set_self(0);
                                    tmp = rm_mult_objs_from_inven(critter, antidote, 1);
                                    if critter_in_party andAlso critcurpoison > 30 then poison(critter, -(get_poison(Critter) / 2));
                                    display_msg(parse_str_2(modmsg(msg_npc_use_item), tar_name, proto_data(PID_ANTIDOTE, 1)));
                                 end
                              end
                           end
                        if RegenMod > 0 andAlso get_critter_stat(critter, STAT_current_hp ) > 0 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso (get_critter_stat(critter, STAT_current_hp) < get_critter_stat(critter, STAT_max_hp) or (critter == real_dude_obj andAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(critter))) then begin
                        if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
                        RegenTickHP = round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
                        if (RegenTickHP < 1) then begin RegenTickHP = 1; end
                        if get_critter_stat(critter, STAT_current_hp ) + RegenTickHP >= get_critter_stat(critter, STAT_max_hp ) then begin
                          RegenTickHP = get_critter_stat(critter, STAT_max_hp ) - get_critter_stat(critter, STAT_current_hp );
                        end
                          if critter == real_dude_obj AndAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(real_dude_obj) then begin
                           call cripheal();
                          end
                        critterishealing = 1;
                        poisonedcrit = 1;

                          if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter == real_dude_obj AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                             if RegenTickHP == 1 then begin
                             display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                             end
                             else begin
                             display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                             end
                          end
                          if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) AndAlso get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp ) then begin
                             if RegenTickHP == 1 then begin
                             display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
                             end
                             else begin
                             display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
                             end
                          end
                           critter_heal(critter, RegenTickHP);
                        end
                        if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
                        if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
                        if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
                        PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.0 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
                           if PoisonTickDmg < min_poison_dmg then begin
                             PoisonTickDmg = min_poison_dmg;
                           end
                          if PoisonTickDmg > 0 andAlso Critter == real_dude_obj then begin
                           poisonedcrit = 1;
                           if ShowModMSG > 0 then begin
                              display_msg(parse_str_2(modmsg(msg_player_poison_dmg), tar_name,PoisonTickDmg));
                           end
                          end
                          if get_critter_stat(critter, STAT_current_hp ) <= PoisonTickDmg then begin
                             if critter_in_party then begin
                                if not(array_exists(party_member_remove_arr)) then begin
                                   party_member_remove = 1;
                                   party_member_remove_arr = create_array_map;
                                end
                                set_array(party_member_remove_arr, len_array(party_member_remove_arr), get_object_data(critter, OBJ_DATA_ID));
                             end
                             call critter_inflict_poison_dmg(critter, PoisonTickDmg, 1);
                          end
                          else begin
                             critter_heal(Critter, -PoisonTickDmg);
                          end
                          poison(critter, - (min_poison_decay + (round(get_poison(Critter) * 0.10 ) * 10 / PoisonDecayDiv)));
                          if PoisonTickDmg > 0 andAlso Critter != real_dude_obj then begin

                           //if get_critter_stat(critter, STAT_current_hp ) < 1 then begin
                             //poison(critter, -999);
                             //reg_anim_clear(critter);
                             //if ShowModMSG > 0 then begin
                             //display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), tar_name, PoisonTickDmg));
                             //end
                           //end
                           if get_critter_stat(critter, STAT_current_hp ) > 0 then begin
                             poisonedcrit = 1;
                             if ShowModMSG > 0 then begin
                             display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
                             end
                           end
                          end
                        end
                       end
                     end
           // time skip for heals
           if critterishealing > 0 andAlso poisonedcrit > 0 then begin
           RegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * (3 + 4 * not(UnsafeRegenModScripting)) * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
           game_time_advance(53);
           end
      end
  partypoisoncountdown = 0;
  critterishealing = 0;
  poisonedcrit = 0;
  end
end

procedure poisonInRealTime begin
   variable leftHand_obj;
   variable rightHand_obj;
   variable leftHand;
   variable rightHand;
   variable losblock;
   variable tardt = 0;
   variable tardr = 0;
   variable Tox = has_fake_perk(perk_poison_mastery_name);
   variable tar_name = 0;
   variable critter_fid = 0;
   variable game_mode = get_game_mode;
   variable crit_pid = 0;
   variable critter;
   variable party = party_member_list(0);
   variable critter_in_party;
   variable critcurpoison;
   variable critmaxhp;
   variable critcurhp;
   variable critter_cur_frm;
   variable critter_body_type;
   variable has_antidote;
   variable has_super_antidote;
   variable antidote;
   // weapon poisonBuff deacay for dude & party members
   foreach (critter in party) begin
      if PoisonMod > 0 andAlso (get_game_mode == 0 or get_game_mode == 1) andAlso random(0, 2) >= (2 * Tox) then begin
         leftHand_obj = critter_inven_obj2(critter, INVEN_TYPE_LEFT_HAND);
         rightHand_obj = critter_inven_obj2(critter, INVEN_TYPE_RIGHT_HAND);
         if leftHand_obj then leftHand = obj_pid(critter_inven_obj2(critter, INVEN_TYPE_LEFT_HAND));
         if rightHand_obj then rightHand = obj_pid(critter_inven_obj2(critter, INVEN_TYPE_RIGHT_HAND));
         //Fo2 weapons has_fake_perk_npc
         if leftHand != 4 andAlso rightHand != 4 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(4, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(4, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(4, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 7 andAlso rightHand != 7 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(7, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(7, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(7, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 45 andAlso rightHand != 45 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(45, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(45, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(45, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 116 andAlso rightHand != 116 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(116, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(116, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(116, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 234 andAlso rightHand != 234 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(234, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(234, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(234, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 236 andAlso rightHand != 236 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(236, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(236, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(236, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 280 andAlso rightHand != 280 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(280, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(280, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(280, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 319 andAlso rightHand != 319 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(319, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(319, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(319, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 320 andAlso rightHand != 320 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(320, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(320, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(320, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 383 andAlso rightHand != 383 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(383, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(383, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(383, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 517 andAlso rightHand != 517 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(517, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(517, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(517, 1))) - 1), 23, envenomed_description_msg);
         end
         if leftHand != 522 andAlso rightHand != 522 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(522, 1))) > 0 then begin
            set_fake_perk_npc(critter, (envenomed_msg + proto_data(522, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(522, 1))) - 1), 23, envenomed_description_msg);
         end
         //Nevada Weapons
         if Nevada > 0 then begin
            if leftHand != 112 andAlso rightHand != 112 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(112, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(112, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(112, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 365 andAlso rightHand != 365 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(365, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(365, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(365, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 420 andAlso rightHand != 420 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(420, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(420, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(420, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 573 andAlso rightHand != 573 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(573, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(573, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(573, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 575 andAlso rightHand != 575 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(575, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(575, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(575, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 654 andAlso rightHand != 654 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(654, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(654, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(654, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 667 andAlso rightHand != 667 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(667, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(667, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(667, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 668 andAlso rightHand != 668 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(668, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(668, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(668, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 677 andAlso rightHand != 677 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(677, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(677, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(677, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 678 andAlso rightHand != 678 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(678, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(678, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(678, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 738 andAlso rightHand != 738 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(738, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(738, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(738, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 739 andAlso rightHand != 739 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(739, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(739, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(739, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 762 andAlso rightHand != 762 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(762, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(762, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(762, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 763 andAlso rightHand != 763 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(763, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(763, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(763, 1))) - 1), 23, envenomed_description_msg);
            end
         end
         //Sonora Weapons
         if Sonora > 0 then begin
            if leftHand != 190 andAlso rightHand != 190 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(190, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(190, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(190, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 19 andAlso rightHand != 19 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(19, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(19, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(19, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 127 andAlso rightHand != 127 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(127, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(127, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(127, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 128 andAlso rightHand != 128 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(128, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(128, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(128, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 132 andAlso rightHand != 132 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(132, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(132, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(132, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 133 andAlso rightHand != 133 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(133, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(133, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(133, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 134 andAlso rightHand != 134 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(134, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(134, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(134, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 135 andAlso rightHand != 135 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(135, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(135, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(135, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 137 andAlso rightHand != 137 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(137, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(137, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(137, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 138 andAlso rightHand != 138 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(138, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(138, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(138, 1))) - 1), 23, envenomed_description_msg);
            end
            if leftHand != 174 andAlso rightHand != 174 andAlso has_fake_perk_npc(critter, (envenomed_msg + proto_data(174, 1))) > 0 then begin
               set_fake_perk_npc(critter, (envenomed_msg + proto_data(174, 1)), (has_fake_perk_npc(critter, (envenomed_msg + proto_data(174, 1))) - 1), 23, envenomed_description_msg);
            end
         end
      end
   end
   if PoisonMod > 0 andAlso  game_time > combatendtime + 20 then begin
      foreach (critter in list_as_array(0)) begin
         critcurpoison = get_poison(Critter);
         critcurhp = get_critter_stat(critter, STAT_current_hp );
         if critcurhp > 0 andAlso game_mode == 0 andAlso critcurpoison > 0 then begin
            tar_name = obj_name(Critter);
            critter_in_party = is_in_array(critter, party);
            critmaxhp = get_critter_stat(critter, STAT_max_hp );
            // npc use antidote out of combat
            if PoisonMod > 0 andAlso Critter != real_dude_obj andAlso critcurpoison > 5 andAlso critcurhp > 0 andAlso not(is_dead(critter)) then begin
               //critter_cur_frm = get_object_data(critter, OBJ_DATA_CUR_FRM);
               critter_body_type = get_proto_data(obj_pid(critter), PROTO_CR_BODY_TYPE);
               if not(is_prone(critter)) andAlso critter_body_type == CR_BODY_BIPED then begin
                  has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
                  if Nevada > 0 then has_super_antidote = obj_is_carrying_obj_pid(Critter, 53);
                  if (has_antidote > 0 or (Nevada > 0 andAlso has_super_antidote)) andAlso ((critter_in_party andAlso ((critcurpoison > 10 andAlso critcurhp < (critmaxhp / 4)) or critcurpoison > 25 or critcurhp < 14)) or (not(critter_in_party) andAlso ((random(10,50)) < critcurpoison or critcurhp <= 13 or critcurhp < (critmaxhp / 5))) ) then begin
                     tail_used = 1;
                     antidote = obj_carrying_pid_obj(critter, PID_ANTIDOTE);
                     if Nevada > 0 andAlso has_super_antidote > 0 andAlso (critcurpoison > 25 or (has_antidote <= 0 andAlso critcurpoison > 15)) then antidote = obj_carrying_pid_obj(critter, 53);
                     reg_anim_clear(critter);
                     reg_anim_begin();
                     reg_anim_animate(critter, ANIM_magic_hands_middle, -1);
                     reg_anim_animate(critter, ANIM_stand, -1);
                     reg_anim_end();
                     set_self(critter);
                     set_self(critter);
                     use_obj_on_obj(antidote, critter);
                     set_self(0);
                     if critter_in_party andAlso critcurpoison > 30 then poison(critter, -(get_poison(Critter) / 2));
                     display_msg(parse_str_2(modmsg(msg_npc_use_item), tar_name, proto_data(PID_ANTIDOTE, 1)));
                  end
               end
            end

            if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
            if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
            if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
            PoisonTickDmg = round(critmaxhp / 100.0 * PoisonMaxHPpercentMult * (get_poison(Critter) * PoisonLevelMult / PoisonLevelDiv));
            if PoisonTickDmg < min_poison_dmg then begin
               PoisonTickDmg = min_poison_dmg;
            end
            if PoisonTickDmg > 0 andAlso Critter == real_dude_obj andAlso ShowModMSG > 0 then begin
               display_msg(parse_str_2(modmsg(msg_player_poison_dmg), tar_name,PoisonTickDmg));
            end
            losblock = obj_blocking_line(real_dude_obj, tile_num(critter), BLOCKING_TYPE_SIGHT);
            if PoisonTickDmg > 0 then begin
               if get_critter_stat(critter, STAT_current_hp ) <= PoisonTickDmg then begin
                  //crit_pid = obj_pid(critter);
                  //reg_anim_clear(critter);
                  //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
                  //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);
                  //poisondeath = 1;
                  //set_target_knockback(critter, 0, 0);
                  //if HR_fog_of_war then set_outline(critter, OUTLINE_NEW_RED);
                  //critter_heal(Critter, - (get_critter_stat(critter, STAT_current_hp ) - 1));
                  //poison(critter, -999);
                  //set_proto_data(crit_pid, CRITTER_PROTO_DT, 0);
                  //set_proto_data(crit_pid, CRITTER_PROTO_DR, 0);
                  //critter_dmg(critter, PoisonTickDmg, DMG_plasma);
                  //poison(critter, -(get_poison(critter) + 1));
                  //party_remove(critter);
                  call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
                  poisondeath = 1;
                  //set_proto_data(crit_pid, CRITTER_PROTO_DT, tardt);
                  //set_proto_data(crit_pid, CRITTER_PROTO_DR, tardr);
                  //critter_fid = critter_art_fid(Critter);
                  //if not(critter_in_party) andAlso critter_fid != 16777322 andAlso crit_pid != 16777508 then begin
                     //give_xp((get_proto_data(crit_pid, PROTO_CR_KILL_EXP)));
                  //end
               end
               if (get_critter_stat(critter, STAT_current_hp ) - PoisonTickDmg) > 0 andAlso (not(losblock) or HR_fog_of_war == 0) andAlso ShowModMSG > 0 then begin
                  display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
               end
            end
               if poisondeath == 0 then begin
                  critter_heal(Critter, - PoisonTickDmg);
               end
            poison(critter, - (min_poison_decay + (round(get_poison(Critter) * 0.10 ) * 10 / PoisonDecayDiv)));
         end
      end
   end
end

procedure regenInRealTime begin
  variable losblock = 0;
  variable game_mode = get_game_mode;
  variable tar_name = 0;
  variable critter;
  if RegenMod > 0  andAlso game_time > combatendtime + 20 then begin
   foreach (critter in list_as_array(0)) begin
     tar_name = obj_name(critter);
     if get_critter_stat(critter, STAT_current_hp ) > 0 andAlso game_mode == 0 andAlso get_critter_stat(critter, STAT_heal_rate) > 5 andAlso (get_critter_stat(critter, STAT_current_hp ) < get_critter_stat(critter, STAT_max_hp) or (critter == real_dude_obj andAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(critter))) then begin
      if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
      RegenTickHP = round(get_critter_stat(critter, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(critter, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
      if (RegenTickHP < 1) then begin RegenTickHP = 1; end
                  if get_critter_stat(critter, STAT_current_hp ) + RegenTickHP >= get_critter_stat(critter, STAT_max_hp ) then begin
                    RegenTickHP = get_critter_stat(critter, STAT_max_hp ) - get_critter_stat(critter, STAT_current_hp );
                  end
      critter_heal(critter, RegenTickHP);
      if critter == real_dude_obj then begin
        if has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(real_dude_obj) then begin
         call cripheal();
        end
      DudeRegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
      end
      if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter == real_dude_obj then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                    end

      end
      losblock = obj_blocking_line(real_dude_obj, tile_num(critter), BLOCKING_TYPE_SIGHT);
      if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) andAlso (not(losblock) or HR_fog_of_war == 0) then begin
        if RegenTickHP == 1 then begin
        display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
        end
        else begin
        display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
        end
      end
     end
   end
  end
end

procedure ModInTurnBased begin
   variable CritterTurnStatus = get_sfall_arg;
   variable Critter = get_sfall_arg;
   variable party = party_member_list(0);
   variable critter_in_party = is_in_array(critter, party);
   variable critmaxhp = get_critter_stat(critter, STAT_max_hp);
   variable critcurhp = get_critter_stat(Critter, STAT_current_hp);
   variable crithr = get_critter_stat(critter, STAT_heal_rate);
   variable critcurpoison = get_poison(Critter);
   variable losblock = 0;
   variable tardt = 0;
   variable tardr = 0;
   variable tar_name = obj_name(critter);
   variable crit_pid = obj_pid(Critter);
   variable critter_int;
   variable radscrop_tail;
   variable antidote;
   variable tmp;
   variable rnd;
   variable has_scorp_tail;
   variable has_small_scorp_tail;
   variable has_antidote;
   variable has_super_antidote;
   variable critter_body_type;
   variable wpn;
   variable wpnpid;
   variable wpnname;
   variable wpnanim = -5;
   variable wpndmgtype = -5;
   variable lhpoison;
   variable rhpoison;
   variable critter_cur_frm;
   variable dude_hp = get_critter_stat(real_dude_obj, STAT_current_hp);
   tail_used = 0;
   dude_turn = 0;
   if Critter == dude_obj then begin
      if CritterTurnStatus == 1 andAlso dude_turn_critter_dies > 0 then begin
         dude_turn = 1;
         set_global_script_type(3);
         set_global_script_repeat(1);
      end
   end

   if RegenMod > 0 andAlso critcurhp > 0 andAlso dude_hp > 0 then begin
   if RegenMaxHPpercentMult < 1 then begin RegenMaxHPpercentMult = 1; end
     RegenTickHP = round(critmaxhp / 100.0 * RegenMaxHPpercentMult * (crithr * HealingRateMult / HealingRateDiv));
     if RegenTickHP < 1 then begin RegenTickHP = 1; end
     if ((CritterTurnStatus == 0) andAlso (crithr > 5)) andAlso ((critcurhp < critmaxhp) or (critter == real_dude_obj andAlso has_fake_perk(regen_perk_name) > 0 andAlso critcrippled(critter)))then begin
       if critcurhp + RegenTickHP >= critmaxhp then begin
         RegenTickHP = critmaxhp - critcurhp;
       end
     critter_heal(Critter, RegenTickHP);
     losblock = obj_blocking_line(real_dude_obj, tile_num(critter), BLOCKING_TYPE_SIGHT);
     if ShowFloatMSG > 0 andAlso get_poison(critter) < 1 andAlso RegenTickHP > 0 and (not(losblock) or HR_fog_of_war == 0) then begin
     float_msg(critter, "+" + RegenTickHP, FLOAT_MSG_GREEN);
     end
     if critter == real_dude_obj then begin
      if has_fake_perk(regen_perk_name) != 0 andAlso critcrippled(real_dude_obj) then begin
        call cripheal();
      end
         DudeRegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.0 * RegenMaxHPpercentMult * (get_critter_stat(real_dude_obj, STAT_heal_rate) * HealingRateMult / HealingRateDiv));
         end
     if Critter == real_dude_obj andAlso RegenTickHP > 0 andAlso ShowModMSG > 0 then begin
                    if RegenTickHP == 1 then begin
                    display_msg(parse_str_2(modmsg(msg_player_1_hp_healed), tar_name,RegenTickHP));
                    end
                    else begin
                    display_msg(parse_str_2(modmsg(msg_player_many_hp_healed), tar_name,RegenTickHP));
                    end
     end
      if ShowModMSG > 0 andAlso RegenTickHP > 0 andAlso critter != real_dude_obj andAlso not(is_dead(critter)) then begin
           if RegenTickHP == 1 then begin
           display_msg(parse_str_2(modmsg(msg_npc_1_hp_healed), tar_name,RegenTickHP));
           end
           else begin
           display_msg(parse_str_2(modmsg(msg_npc_many_hp_healed), tar_name,RegenTickHP));
           end
      end
     end
   end
   if PoisonMod > 0 andAlso critcurhp > 0 andAlso dude_hp > 0 then begin
     wpn = critter_inven_obj(critter, INVEN_TYPE_RIGHT_HAND);
     if wpn then wpnpid = obj_pid(wpn);
     if wpnpid > 0 then wpnname = obj_name(wpn);
     if wpnpid > 0 then wpnanim = get_proto_data(wpnpid, PROTO_WP_ANIM);
     if wpnpid > 0 then wpndmgtype = get_proto_data(wpnpid, PROTO_WP_DMG_TYPE);
     critter_int = get_critter_stat(critter, STAT_iq);
     critter_body_type = get_proto_data(obj_pid(critter), PROTO_CR_BODY_TYPE);
     critter_cur_frm = get_object_data(critter, OBJ_DATA_CUR_FRM);
     //npc use antidote if poisoned (if not direct control enabled)
     if PoisonMod > 0 andAlso combat_direct_controll != 1 andAlso critcurpoison > 5 andAlso tail_used <= 0 andAlso critcurhp > 0 andAlso combat_med_tool_used <= 0 andAlso critter_cur_frm == 0 andAlso  not(is_dead(critter)) andAlso critcurhp > 0 andAlso Critter != real_dude_obj andAlso critter_body_type == CR_BODY_BIPED andAlso CritterTurnStatus == 1 then begin
         has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
         if Nevada > 0 then has_super_antidote = obj_is_carrying_obj_pid(Critter, 53);
         if (has_antidote > 0 or (Nevada > 0 andAlso has_super_antidote)) andAlso ((critter_in_party andAlso ((critcurpoison > 9 andAlso critcurhp < (critmaxhp / 2)) or critcurpoison > 15)) or (not(critter_in_party) andAlso (random(20,50) - critter_int) < critcurpoison) or not(random(0,2))) then begin
            tail_used = 1;
            antidote = obj_carrying_pid_obj(critter, PID_ANTIDOTE);
            if Nevada > 0 andAlso has_super_antidote > 0 andAlso (critcurpoison > 25 or (has_antidote <= 0 andAlso critcurpoison > 9)) then antidote = obj_carrying_pid_obj(critter, 53);
            anim(critter, ANIM_magic_hands_middle, 1);
            set_self(critter);
            set_self(critter);
            use_obj_on_obj(antidote, critter);
            set_self(0);
            if critter_in_party andAlso critcurpoison > 30 then poison(critter, -(get_poison(Critter) / 2));
            display_msg(parse_str_2(modmsg(msg_npc_use_item), tar_name, proto_data(PID_ANTIDOTE, 1)));
         end
     end
     // enemy npc radscorpion tail if not crippled and not fleeing
     if NPCsUsePoisonTails != 0 andAlso combat_direct_controll != 1 andAlso tail_used <= 0 andAlso combat_med_tool_used <= 0 andAlso not(critter_in_party) andAlso critter_cur_frm == 0 andAlso not(is_dead(critter)) andAlso critcurhp > 0 andAlso Critter != dude_obj andAlso not(critcrippled(critter)) andAlso not(critter_is_fleeing(critter)) andAlso critter_body_type == CR_BODY_BIPED andAlso (wpnanim == 1 or wpnanim == 4) andAlso CritterTurnStatus == 1 andAlso wpndmgtype == DMG_normal_dam then begin
        has_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SCORPION_TAIL);
        if PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data (PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 then has_small_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SMALL_SCORPION_TAIL);
        if has_scorp_tail >= 2 then begin
            tail_used = 1;
            radscrop_tail = obj_carrying_pid_obj(critter, PID_SCORPION_TAIL);
            anim(critter, ANIM_magic_hands_middle, 1);
            display_msg(parse_str_2(modmsg(msg_pois_appl_npc), tar_name,obj_name(wpn)));
            tmp = rm_mult_objs_from_inven(critter, radscrop_tail, has_scorp_tail - 1);
        end
        if has_small_scorp_tail >= 2 andAlso has_scorp_tail <= 0 then begin
            tail_used = 1;
            radscrop_tail = obj_carrying_pid_obj(critter, PID_SMALL_SCORPION_TAIL);
            anim(critter, ANIM_magic_hands_middle, 1);
            display_msg(parse_str_2(modmsg(msg_pois_appl_npc), tar_name,obj_name(wpn)));
            tmp = rm_mult_objs_from_inven(critter, radscrop_tail, has_small_scorp_tail - 1);
        end
     end
       // companion npc use radscorpion tail if not crippled and not fleeing
     if NPCsUsePoisonTails >= 2 andAlso (combat_direct_controll != 1 andAlso combat_direct_controll != 2) andAlso combat_med_tool_used <= 0 andAlso tail_used <= 0 andAlso critter_in_party andAlso critter_cur_frm == 0 andAlso  not(is_dead(critter)) andAlso critcurhp > 0 andAlso Critter != dude_obj andAlso not(critcrippled(critter)) andAlso not(critter_is_fleeing(critter)) andAlso critter_body_type == CR_BODY_BIPED andAlso (wpnanim == 1 or wpnanim == 4) andAlso CritterTurnStatus == 1 andAlso wpndmgtype == DMG_normal_dam then begin
        rhpoison = has_fake_perk_npc(Critter, (envenomed_msg + wpnname));
        has_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SCORPION_TAIL);
        if PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data (PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 then has_small_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SMALL_SCORPION_TAIL);
        rnd = random (0, 100);
        if has_scorp_tail > 0 andAlso has_small_scorp_tail < 1 andAlso rnd - (30 - critter_int * 3) * 4 > rhpoison * 14 then begin
         tail_used = 1;
         radscrop_tail = obj_carrying_pid_obj(critter, PID_SCORPION_TAIL);
         anim(critter, ANIM_magic_hands_middle, 1);
         set_self(critter);
         set_self(critter);
         use_obj_on_obj(radscrop_tail, critter);
         set_self(0);
        end
        if has_small_scorp_tail > 0 andAlso rnd - (30 - critter_int * 3) * 4 > rhpoison * 14 then begin
         tail_used = 1;
         radscrop_tail = obj_carrying_pid_obj(critter, PID_SMALL_SCORPION_TAIL);
         anim(critter, ANIM_magic_hands_middle, 1);
         set_self(critter);
         set_self(critter);
         use_obj_on_obj(radscrop_tail, critter);
         set_self(0);
        end
     end
      if CritterTurnStatus == 0 andAlso CritterTurnStatus != -2 andAlso CritterTurnStatus != -1 andAlso (critcurpoison > 0) andAlso critcurhp > 0 then begin
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
          PoisonTickDmg = round(critmaxhp / 100.0 * PoisonMaxHPpercentMult * (critcurpoison * PoisonLevelMult / PoisonLevelDiv));
         if PoisonTickDmg < min_poison_dmg then begin
           PoisonTickDmg = min_poison_dmg;
         end
         losblock = obj_blocking_line(real_dude_obj, tile_num(critter), BLOCKING_TYPE_SIGHT);
         if ShowFloatMSG > 0 andAlso (not(losblock) or HR_fog_of_war == 0) then begin
           if PoisonTickDmg > 0 andAlso RegenMod > 0  then begin
            if RegenMod > 0  andAlso PoisonTickDmg > 0 andAlso crithr > 5 then begin
              if PoisonTickDmg > RegenTickHP then begin
              float_msg(critter, "-" + (PoisonTickDmg - RegenTickHP), FLOAT_MSG_BLUE);
              end
              if PoisonTickDmg == RegenTickHP then begin
              float_msg(critter, "" + (PoisonTickDmg - RegenTickHP), FLOAT_MSG_BLUE);
              end
              if PoisonTickDmg < RegenTickHP then begin
              float_msg(critter, "+" + (RegenTickHP - PoisonTickDmg), FLOAT_MSG_BLUE);
              end
            end
            if PoisonTickDmg > 0 andAlso crithr < 6 then begin
            float_msg(critter, "-" + PoisonTickDmg, FLOAT_COLOR_AFRAID);
            end
           end
           if PoisonTickDmg > 0 andAlso RegenMod == 0 then begin
            float_msg(critter, "-" + PoisonTickDmg, FLOAT_COLOR_AFRAID);
           end
         end
         if PoisonTickDmg > 0 andAlso Critter == real_dude_obj then begin
           display_msg(parse_str_2(modmsg(msg_player_poison_dmg), tar_name,PoisonTickDmg));
         end
         if PoisonTickDmg > 0 then begin
              if get_critter_stat(Critter, STAT_current_hp) <= PoisonTickDmg then begin
               if critter_in_party then begin
                  //poisondeath = 1;
                  //party_remove(critter);
                  call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
                  dude_turn_critter_dies = critter;
                  poisondeath = 1;
                 //critter_heal(Critter, - PoisonTickDmg * 2);
                 //if ShowModMSG > 0 then begin
                 //display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), tar_name, PoisonTickDmg));
                 //end
               end
               else begin
               //if HR_fog_of_war then set_outline(critter, OUTLINE_NEW_RED);
               //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
               //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);
               //poisondeath = 1;
               //set_target_knockback(critter, 0, 0);
               //party_remove(critter);
               //poison(critter, - 999);
               //critter_heal(Critter, - (get_critter_stat(Critter, STAT_current_hp) - 1));
               //set_proto_data(crit_pid, CRITTER_PROTO_DT, 0);
               //set_proto_data(crit_pid, CRITTER_PROTO_DR, 0);
               //critter_dmg(critter, PoisonTickDmg, DMG_plasma);
               call critter_inflict_poison_dmg(critter, PoisonTickDmg,1);
               dude_turn_critter_dies = critter;
               poisondeath = 1;
               //set_proto_data(crit_pid, CRITTER_PROTO_DT, tardt);
               //set_proto_data(crit_pid, CRITTER_PROTO_DR, tardr);
               end
              end
              else begin
                  if ShowModMSG > 0 then begin
                     if Critter != real_dude_obj then
                        display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
                  end
              end
         end

         poison(critter, - (min_poison_decay + (round(critcurpoison * 0.10 ) * 10 / PoisonDecayDiv)));
         if get_critter_stat(Critter, STAT_current_hp) > PoisonTickDmg then begin
            critter_heal(Critter, - PoisonTickDmg);
         end
      end
   end
   if CritterTurnStatus <= 0 andAlso dude_hp > 0 then begin
      if CritterTurnStatus == -2 then
         combatendtime = game_time;

      if dude_turn_critter_dies > 0 then begin
         set_global_script_type(3);
         set_global_script_repeat(1);
      end
   end
   if dude_hp > 0 andAlso (get_poison(real_dude_obj) > 0 andAlso CritterTurnStatus < 0) or (get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 andAlso CritterTurnStatus < 0) then begin
      float_msg(real_dude_obj, 0, 0);
   end
   poisondeath = 0;
end

procedure ADJUSTPOISON begin
  variable Critter = 0;
  variable companion = 0;
  variable OriginalPoisonDecay = 0;
  variable OriginalPoisonDMG = 0;
  variable newpoisondmg = 0;
  variable PoisonTickDmg = 0;
  variable PoisonEcxessLevel = 0;
  variable pseudoPoisonLevel = 0;
  variable pseudoCurrentHP = 0;
  variable poisonres = 0;
  variable repeat = 0;
  variable crit_pid= 0;
  variable tardt = 0;
  variable tardr = 0;
  variable tar_name = 0;
  variable kill_type = -1;
  variable party;
  variable critter_in_party;
  variable companion_in_party;
  if PoisonMod > 0 then begin
  Critter = get_sfall_arg;
  originalPoisonDecay = get_sfall_arg;
  originalPoisonDMG = get_sfall_arg;
  if Critter > 0 then begin
     poisonres = get_critter_stat(critter, STAT_poison_resist );
     if poisonres <= 0 then poisonres = 1;
     pseudoPoisonLevel = get_poison(critter);
     pseudoCurrentHP = get_critter_stat(critter, STAT_current_hp );
     party = party_member_list(0);
     critter_in_party = is_in_array(critter, party);
     tar_name = obj_name(Critter);
     kill_type = critter_kill_type(critter);
  end
  // preventing robots from getting poison level
  if kill_type == KILL_TYPE_robot_kills then begin
      if originalPoisonDecay > 0 then begin
         set_sfall_return(0);
         set_sfall_arg(0, 1);
      end
      return;
  end
  else if (critter_in_party) then begin
     if originalPoisonDecay > 0 then begin
        if critter != dude_obj then begin
           newpoisondmg = ((3 * originalPoisonDecay * (100 - poisonres)) / 400);
           if newpoisondmg <= 0 then newpoisondmg = 1;
           set_sfall_return(newpoisondmg);
           set_sfall_arg(newpoisondmg, 1);
        end
        //dude poison
        else begin
            if ((originalPoisonDecay * poisonres) / 100) >= 100 then begin
               set_sfall_return(99);
               set_sfall_arg(99, 1);
            end
        end
     end
  end
  if (critter == real_dude_obj) andAlso pseudoCurrentHP > 0 andAlso ( ((get_poison(critter) + originalPoisonDecay * poisonres / 100 ) >= 100 andAlso critter == real_dude_obj) or ((get_poison(critter) + originalPoisonDecay * poisonres / 100) >= 100 andAlso critter != real_dude_obj) or (originalPoisonDecay * poisonres / 100) >= 100) then begin
   display_msg(parse_str_2(modmsg(msg_npc_reach_poison_lethal_value), tar_name, pseudoPoisonLevel));
   if critter_in_party andAlso not(combat_is_initialized) then begin
      if critter == real_dude_obj then begin
         if get_game_mode bwand INVENTORY then begin
            if critter == dude_obj then begin
               critter_poison_overdose = dude_obj;
               tap_key(1);
            end
            else begin
               critter_heal(Critter, -9999);
            end
         end
         else begin
            //poison(critter, (25 - get_poison(critter)));
            call critter_inflict_poison_dmg(critter, (get_critter_stat(critter, STAT_max_hp) * 3),1);
         end
      end
      else begin
         //poison(critter, (25 - get_poison(critter)));
         call critter_inflict_poison_dmg(critter, (get_critter_stat(critter, STAT_max_hp) * 3),1);
         //critter_heal(Critter, - pseudoCurrentHP * 2);
      end
   end
   else begin
      if critter == real_dude_obj then begin
         if get_game_mode bwand INVENTORY then begin
            if critter == dude_obj then begin
               critter_poison_overdose = dude_obj;
               tap_key(1);
            end
            else begin
               critter_heal(Critter, -9999);
            end
         end
         else begin
            //poison(critter, (25 - get_poison(critter)));
            call critter_inflict_poison_dmg(critter, (get_critter_stat(critter, STAT_max_hp) * 3),1);
         end
      end
      else begin
         //crit_pid = obj_pid(Critter);
         //tardt = get_proto_data(crit_pid, CRITTER_PROTO_DT);
         //tardr = get_proto_data(crit_pid, CRITTER_PROTO_DR);
         //poisondeath = 1;
         //if HR_fog_of_war then set_outline(critter, OUTLINE_NEW_RED);
         //set_target_knockback(critter, 0, 0);
         //party_remove(critter);
         //poison(critter, - 999);
         //critter_heal(Critter, - (pseudoCurrentHP - 1));
         //set_proto_data(crit_pid, CRITTER_PROTO_DT, 0);
         //set_proto_data(crit_pid, CRITTER_PROTO_DR, 0);
         //critter_dmg(critter, pseudoCurrentHP, DMG_plasma);

         //if get_game_mode bwand WORLDMAP then begin
            //critter_heal(critter, - (get_critter_stat(critter, STAT_max_hp) * 2));
         //end
         //else begin
         //poison(critter, -get_poison(critter));
         call critter_inflict_poison_dmg(critter, (get_critter_stat(critter, STAT_max_hp) * 2),1);
         poisondeath = 1;
         //end
         //set_proto_data(crit_pid, CRITTER_PROTO_DT, tardt);
         //set_proto_data(crit_pid, CRITTER_PROTO_DR, tardr);
      end
   end

  end
  if originalPoisonDecay == -2 andAlso OriginalPoisonDMG == -1 andAlso not(combat_is_initialized) then begin
   // Poison dmg for party memebers (exept real_dude_obj) start
   foreach (companion in party) begin
    companion_in_party = is_in_array(companion, party);
    tar_name = obj_name(companion);
    if companion_in_party then begin
     while PoisonMod > 0 andAlso companion != real_dude_obj andAlso get_poison(companion) > 0  andAlso get_critter_stat(companion, STAT_current_hp ) > 0 do begin
      if RegenMod > 0  andAlso get_critter_stat(companion, STAT_current_hp ) > 0 andAlso get_critter_stat(companion, STAT_heal_rate) > 5 then begin
      if (RegenMaxHPpercentMult < 1) then begin RegenMaxHPpercentMult = 1; end
      RegenTickHP = (1 * round(get_critter_stat(companion, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (get_critter_stat(companion, STAT_heal_rate) * HealingRateMult / HealingRateDiv)));
      if (RegenTickHP < 1) then begin RegenTickHP = 1; end
      critter_heal(companion, RegenTickHP);
      end
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
      PoisonTickDmg = round(get_critter_stat(companion, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (get_poison(companion) * PoisonLevelMult / PoisonLevelDiv));
         if PoisonTickDmg < min_poison_dmg then begin
           PoisonTickDmg = min_poison_dmg;
         end
        poison(companion, - (min_poison_decay + (round(get_poison(companion) * 0.10 ) * 10 / PoisonDecayDiv)));
        if PoisonTickDmg > 0 andAlso companion != real_dude_obj then begin
         if (get_critter_stat(companion, STAT_current_hp ) <= PoisonTickDmg) then begin
           poison(companion, - 999);
           reg_anim_clear(companion);
           critter_heal(companion, - 9999);
           if ShowModMSG > 0 then begin
           display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), tar_name, PoisonTickDmg));
           end
         end
         else begin
           display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
         end
        end
        if poisondeath == 0 then begin
         critter_heal(companion, - PoisonTickDmg);
        end
      end
     end
   end
   // Poison dmg for party memebers (exept real_dude_obj) end
   while pseudoPoisonLevel > 0 do begin
      if combat_diff <= 2 then PoisonMaxHPpercentMult = (0.5 * PoisonMaxHPpercentMult2) * combat_diff;
      if combat_diff > 2 then PoisonMaxHPpercentMult = (1.25 * PoisonMaxHPpercentMult2);
      if not(critter_in_party) andAlso critter!= real_dude_obj andAlso (PoisonMaxHPpercentMult < PoisonMaxHPpercentMult2 * EnemyPoisonMult) then PoisonMaxHPpercentMult = PoisonMaxHPpercentMult2 * EnemyPoisonMult;
        PoisonTickDmg = round(get_critter_stat(Critter, STAT_max_hp) / 100.00000 * PoisonMaxHPpercentMult * (pseudoPoisonLevel * PoisonLevelMult / PoisonLevelDiv));
            if PoisonTickDmg < min_poison_dmg then begin
              PoisonTickDmg = min_poison_dmg;
            end
           pseudoPoisonLevel = pseudoPoisonLevel - (min_poison_decay + round((pseudoPoisonLevel * 0.10 ) * 10 / PoisonDecayDiv));
           if PoisonTickDmg > 0 andAlso Critter == real_dude_obj then begin
            display_msg(parse_str_2(modmsg(msg_player_poison_dmg), tar_name,PoisonTickDmg));
           end
           if PoisonTickDmg > 0 andAlso Critter != real_dude_obj then begin
            if (pseudoCurrentHP - PoisonTickDmg) < 1 then begin
              poison(critter, - 999);
              reg_anim_clear(critter);
              if ShowModMSG > 0 then begin
              display_msg(parse_str_2(modmsg(msg_npc_poison_dmg_deadly), tar_name, PoisonTickDmg));
              end
            end
            else begin
              if ShowModMSG > 0 then begin
              display_msg(parse_str_2(modmsg(msg_npc_poison_dmg), tar_name, PoisonTickDmg));
              end
            end
           end
     while get_critter_stat(critter, STAT_heal_rate) > 5 and repeat < ANIM_magic_hands_middle do begin
      repeat += 1;
      game_time_advance(100);
     end
     pseudoCurrentHP = pseudoCurrentHP - PoisonTickDmg;
   end
   if dudehrexitmap > 5 then begin
   RegenTickHP = round(get_critter_stat(real_dude_obj, STAT_max_hp) / 100.00000 * RegenMaxHPpercentMult * (dudehrexitmap * HealingRateMult / HealingRateDiv));
   DudeRegenTickHP = RegenTickHP;
   end
   dudehrcount = MAX(dudehrcount2, dudehrcount);
   if dudehrcount < 0 then begin
     dudehrcount = 0;
   end
   if dudehrcount > 6 then begin
   dudehrcount = (dudehrcount - 1) / 2;
   end
   if dudehrcount == 5 then begin
   dudehrcount = dudehrcount - 1;
   end
   if get_critter_stat(real_dude_obj, STAT_heal_rate) > 5 then begin
     dudehrcount = 6;
   end
   set_sfall_return( - get_poison(critter));
   set_sfall_arg(1, - get_poison(critter));
   set_sfall_return( - (get_critter_stat(critter, STAT_current_hp ) - pseudoCurrentHP));
   set_sfall_arg(2, - (get_critter_stat(critter, STAT_current_hp ) - pseudoCurrentHP));
   dudehrcount = 0;
   dudehrcount2 = 0;
   DudeRegenTickHP = 0;
   end
  end
  if PoisonMod > 0 andAlso critter == real_dude_obj andAlso get_poison(critter) < 1 andAlso OriginalPoisonDMG == -1 then begin
   display_msg(parse_str_2(modmsg(msg_player_after_poison_effect), tar_name, OriginalPoisonDMG));
   critter_heal(critter, random(-1, 1));
  end
  RegenTickHP = 0;
  repeat = 0;
end

procedure map_enter_p_proc begin
   variable critter;
   variable critter_cur_hp;
   variable critter_int;
   variable critter_outdoorsman;
   variable critter_type;
   variable critter_body_type;
   variable rnd;
   variable critter_pid;
   variable has_scorp_tail;
   variable has_small_scorp_tail = -1;
   variable has_antidote;
   variable antidote;
   variable radscrop_tail;
   variable wpn;
   variable wpnpid;
   variable wpnname;
   variable wpnanim = -5;
   variable wpndmgtype = -5;
   variable has_stim;
   variable stim;
   variable invenArr;
   variable count;
   variable i;
   variable item;
   variable new_wpn = 1;
   variable party;
   variable critter_in_party;
   map_exit = 0;
   dudehrexitmap = 0;
   dudehrcount = 0;
   if PoisonMod > 0 then begin
      if game_ui_is_disabled then game_ui_enable;
      if party_member_remove > 0 then begin
         party = party_member_list(1);
         foreach critter in party begin
            if is_in_array(get_object_data(critter, OBJ_DATA_ID),party_member_remove_arr) then begin
               kill_critter(critter, get_object_data(critter, OBJ_DATA_CUR_FRM));
            end
         end
         clear_array(party_member_remove_arr);
         party_member_remove = 0;
      end
      //add radscorpion tail to npc at first map loading
      if ((PoisonMod > 0 andAlso NPCsUsePoisonTails > 0) or RegenMod > 0 ) andAlso (metarule(METARULE_TEST_FIRSTRUN,0) or days_since_visited > 50) then begin
         party = party_member_list(0);
         foreach (critter in list_as_array(LIST_CRITTERS)) begin
               critter_in_party = is_in_array(critter, party);
               critter_cur_hp = get_critter_stat(critter, STAT_current_hp );
               critter_pid = obj_pid(critter);
               critter_body_type = get_proto_data(critter_pid, PROTO_CR_BODY_TYPE);
               critter_type = critter_kill_type(critter);
            if obj_is_visible_flag(critter) andAlso not(is_dead(critter)) andAlso critter_cur_hp > 0 andAlso critter != real_dude_obj andAlso not(critter_in_party) andAlso critter_body_type == CR_BODY_BIPED andAlso critter_type != KILL_TYPE_children_kills andAlso critter_type != KILL_TYPE_robot_kills then begin
               has_stim = obj_is_carrying_obj_pid(Critter, PID_STIMPAK);
               if RegenMod > 0  andAlso has_stim <= 0 then begin
                   rnd = random(0, 1000);
                  if (rnd < critter_cur_hp - 50) or (military_fid(critter) andAlso rnd < 75) then begin
                     stim = create_object_sid(PID_STIMPAK, 0, 0, -1);
                     if Sonora <= 0 andAlso military_fid(critter) then begin
                        add_mult_objs_to_inven(critter, stim, random(1,3));
                        stim = create_object_sid(PID_PLASMA_GRENADE, 0, 0, -1);
                        add_mult_objs_to_inven(critter, stim, random(0,2));
                     end
                     else begin
                        add_mult_objs_to_inven(critter, stim, 1);
                     end
                     if critter_pid == PID_END_BOSS then begin
                        add_mult_objs_to_inven(critter, stim, 1);
                        stim = create_object_sid(PID_PLASMA_GRENADE, 0, 0, -1);
                        add_mult_objs_to_inven(critter, stim, 7);
                        stim = create_object_sid(PID_MICRO_FUSION_CELL, 0, 0, -1);
                        add_mult_objs_to_inven(critter, stim, 2);
                        stim = create_object_sid(PID_PSYCHO, 0, 0, -1);
                        add_mult_objs_to_inven(critter, stim, 1);
                     end
                  end
               end
               if game_time > ONE_GAME_DAY * 19 then begin
                  has_antidote = obj_is_carrying_obj_pid(Critter, PID_ANTIDOTE);
                  if PoisonMod > 0 andAlso has_antidote <= 0 then begin
                      rnd = random(0,120);
                     if rnd < 1 then begin
                        antidote = create_object_sid(PID_ANTIDOTE, 0, 0, -1);
                        add_mult_objs_to_inven(critter, antidote, random(1,3));
                     end
                  end
               end
               has_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SCORPION_TAIL);
               if PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data (PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 then has_small_scorp_tail = obj_is_carrying_obj_pid(Critter, PID_SMALL_SCORPION_TAIL);
               critter_int = get_critter_stat(critter, STAT_iq);
               wpn = critter_inven_obj2(critter, INVEN_TYPE_RIGHT_HAND);
               //if the weapon is not equipped, try to find it in the inventory
               if wpn <= 0 then begin
               count = inven_count(critter);
               invenArr = temp_array_list(count);
                  for (i = 0; i < count; i++) begin
                     invenArr[i] = inven_ptr(critter, i);
                  end
                  foreach (item in invenArr) begin
                     if obj_item_subtype(item) == item_type_weapon then begin
                        wpnpid = obj_pid(item);
                        wpnanim = get_proto_data(wpnpid, PROTO_WP_ANIM);
                        wpndmgtype = get_proto_data(wpnpid, PROTO_WP_DMG_TYPE);
                        if (wpnanim == WPN_ANIM_KNIFE or wpnanim == WPN_ANIM_SPEAR) andAlso wpndmgtype == DMG_normal_dam then begin
                           wpn = item;
                            new_wpn = 3;
                           break;
                        end
                     end
                  end
               end
               if wpn then begin
                  wpnpid = obj_pid(wpn);
                  wpnname = obj_name(wpn);
               end
               if wpnpid then begin
                  wpnanim = get_proto_data(wpnpid, PROTO_WP_ANIM);
                  wpndmgtype = get_proto_data(wpnpid, PROTO_WP_DMG_TYPE);
               end
                // add npc radscorpion tail
               if NPCsUsePoisonTails > 0 andAlso has_scorp_tail <= 1 andAlso has_small_scorp_tail <= 1 then begin
                  critter_outdoorsman = has_skill(critter, SKILL_OUTDOORSMAN);
                  if critter_outdoorsman < 40 then critter_outdoorsman = 40;
                  critter_outdoorsman = critter_outdoorsman / new_wpn;
                  rnd = random(0, 80);
                  if (rnd <= critter_outdoorsman andAlso (wpnanim == WPN_ANIM_KNIFE or wpnanim == WPN_ANIM_SPEAR) andAlso wpndmgtype == DMG_normal_dam) then begin
                     if Sonora <= 0 andAlso PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 andAlso has_small_scorp_tail >= has_scorp_tail then begin
                        radscrop_tail = create_object_sid(PID_SMALL_SCORPION_TAIL, 0, 0, -1);
                        add_mult_objs_to_inven(critter, radscrop_tail, random(2,3) - has_small_scorp_tail);
                     end
                     if (PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) != 117440914) or has_small_scorp_tail < has_scorp_tail then begin
                        radscrop_tail = create_object_sid(PID_SCORPION_TAIL, 0, 0, -1);
                        add_mult_objs_to_inven(critter, radscrop_tail, random(2,3) - has_scorp_tail);
                     end
                  end
               end
            end
         end
      end


   //radscorpion tail add use ablility
   if (get_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS) bwand ITEM_ACTION_USEON) != ITEM_ACTION_USEON then begin
   set_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS, (get_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS) bwor ITEM_ACTION_USEON));
   end
   if (get_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS) bwand ITEM_ACTION_USE) != ITEM_ACTION_USE then begin
   set_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS, (get_proto_data(PID_SCORPION_TAIL, PROTO_IT_FLAGS) bwor ITEM_ACTION_USE));
   end
   if PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 andAlso (get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS) bwand ITEM_ACTION_USEON) != ITEM_ACTION_USEON then begin
   set_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS, (get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS) bwor ITEM_ACTION_USEON));
   end
   if PID_SMALL_SCORPION_TAIL > 0 andAlso get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_INV_FID) == 117440914 andAlso (get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS) bwand ITEM_ACTION_USE) != ITEM_ACTION_USE then begin
   set_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS, (get_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_FLAGS) bwor ITEM_ACTION_USE));
   end
   //radscorpion tail weight modifying
   set_proto_data(PID_SCORPION_TAIL, PROTO_IT_WEIGHT, 4);
   if PID_SMALL_SCORPION_TAIL > 0 then set_proto_data(PID_SMALL_SCORPION_TAIL, PROTO_IT_WEIGHT, 2);
   // poison injection moddification
   if Sonora <= 0 then begin
      set_proto_data(PID_HYPO_POISON, PROTO_DR_STAT_A, STAT_current_hp);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_STAT_B, STAT_current_poison);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_STAT_C, STAT_ag);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_1_A, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_1_B, Poison_amt);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_1_C, -2);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_DURATION_1, 30);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_2_C, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_DURATION_2, 60);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_AMOUNT_3_C, 2);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_ADDICT_CHANCE, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_ADDICT_PERK, 0);
      set_proto_data(PID_HYPO_POISON, PROTO_DR_ADDICT_DELAY, 0);

   // antidot moddification
      set_proto_data(PID_ANTIDOTE, PROTO_DR_STAT_A, -2);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_STAT_B, STAT_current_poison);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_STAT_C, STAT_poison_resist);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_1_A, -28);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_1_B, -18);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_1_C, 20);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_DURATION_1, 10);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_2_C, -20);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_DURATION_2, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_AMOUNT_3_C, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_ADDICT_CHANCE, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_ADDICT_PERK, 0);
      set_proto_data(PID_ANTIDOTE, PROTO_DR_ADDICT_DELAY, 0);
   end
  end
  if RegenMod > 0 then begin
   if UnsafeRegenModScripting > 0 andAlso sfall_unsafescripting > 0 then begin
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_A, -2);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_B, STAT_current_hp);
      set_proto_data(PID_STIMPAK, PROTO_DR_STAT_C, STAT_heal_rate);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_A, stim_min_hp);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_B, stim_max_hp);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_C, stim_hr_increase);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_1, stim_duration);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_C, -stim_hr_decrease);
      set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_2, stim_penalty_duration);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_C, (stim_hr_decrease - stim_hr_increase));
   end
   //if UnsafeRegenModScripting <= 0 then begin
   else begin
     set_proto_data(PID_STIMPAK, PROTO_DR_STAT_A, -2);
     set_proto_data(PID_STIMPAK, PROTO_DR_STAT_B, STAT_current_hp);
     set_proto_data(PID_STIMPAK, PROTO_DR_STAT_C, STAT_heal_rate);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_A, 2);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_B, 4);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_1_C, 6);
     set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_1, 1);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_A, 0);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_B, 0);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_2_C, -8);
     set_proto_data(PID_STIMPAK, PROTO_DR_DURATION_2, 60);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_A, 0);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_B, 0);
     set_proto_data(PID_STIMPAK, PROTO_DR_AMOUNT_3_C, 2);
   end

   if Sonora <= 0 then begin
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_STAT_A, -2);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_STAT_B, STAT_current_hp);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_STAT_C, STAT_pe);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_1_A, 2);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_1_B, 4);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_1_C, -1);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_DURATION_1, 1);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_2_A, 3);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_2_B, 5);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_2_C, 0);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_DURATION_2, 2);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_3_A, 2);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_3_B, 4);
      set_proto_data(PID_HEALING_POWDER, PROTO_DR_AMOUNT_3_C, 1);
      set_proto_data(16777458, 232, get_ini_setting("mods\\F2MechanicsMiniRework.ini|CRITTER|WAHR"));
      set_proto_data(16777459, 232, get_ini_setting("mods\\F2MechanicsMiniRework.ini|CRITTER|TWAHR"));
      if  ET_TU <= 0 then set_proto_data(16777570, 232, get_ini_setting("mods\\F2MechanicsMiniRework.ini|CRITTER|WAQHR"));
      set_proto_data(16777464, 232, get_ini_setting("mods\\F2MechanicsMiniRework.ini|CRITTER|CENHR"));
      set_proto_data(16777465, 232, get_ini_setting("mods\\F2MechanicsMiniRework.ini|CRITTER|MCENHR"));
      if Nevada <= 0 andAlso ET_TU <= 0 andAlso Resurrection <= 0 then begin
         set_proto_data(PID_END_BOSS, 304, 30); // set Frank Horrigan poison res to 80%(base 50 + bonus 30%)
         set_proto_data(PID_END_BOSS, PROTO_CR_BONUS_DR(DMG_laser), 65); // set Frank Horrigan laser res to 65 %
         set_proto_data(PID_END_BOSS, PROTO_CR_BONUS_DR(DMG_electrical), 45); // set Frank Horrigan elec res to 66 %
      end
   end

   // Nevada food edition
   if Nevada > 0 then begin
     // mutafruit heal
     set_proto_data(PID_MUTATED_FRUIT, PROTO_DR_STAT_A, -2);
     set_proto_data(PID_MUTATED_FRUIT, PROTO_DR_STAT_B, STAT_current_hp);
     set_proto_data(PID_MUTATED_FRUIT, PROTO_DR_AMOUNT_1_A, 0);
     set_proto_data(PID_MUTATED_FRUIT, PROTO_DR_AMOUNT_1_B, 1);
     // iguana
     set_proto_data(PID_IGUANA_ON_A_STICK, PROTO_DR_STAT_C, STAT_poison_resist);
     set_proto_data(PID_IGUANA_ON_A_STICK, PROTO_DR_AMOUNT_1_C, 2);
     set_proto_data(PID_IGUANA_ON_A_STICK, PROTO_DR_AMOUNT_2_C , -2);
     set_proto_data(PID_IGUANA_ON_A_STICK, PROTO_DR_AMOUNT_3_C , 0);
     // pretty & glamour care kit
     set_proto_data(90, PROTO_DR_STAT_C, STAT_poison_resist);
     set_proto_data(90, PROTO_DR_AMOUNT_1_C, 15);
     // iguana bits
     set_proto_data(103, PROTO_DR_STAT_C, STAT_poison_resist);
     set_proto_data(103, PROTO_DR_AMOUNT_1_C, 5);
     set_proto_data(103, PROTO_DR_AMOUNT_2_C , -5);
     // nuka heal
     set_proto_data(106, PROTO_DR_AMOUNT_1_A, 1);
     // water
      set_proto_data(126, PROTO_DR_STAT_A, STAT_current_hp);
      set_proto_data(126, PROTO_DR_STAT_B, STAT_current_poison);
      set_proto_data(126, PROTO_DR_STAT_C, STAT_current_rad);
      set_proto_data(126, PROTO_DR_AMOUNT_1_A, 1);
      set_proto_data(126, PROTO_DR_AMOUNT_1_B, -2);
      set_proto_data(126, PROTO_DR_AMOUNT_1_C, -1);
      set_proto_data(126, PROTO_DR_AMOUNT_1_A, 2);
      //clear water  8
      set_proto_data(212, PROTO_DR_STAT_A, STAT_current_hp);
      set_proto_data(212, PROTO_DR_STAT_B, STAT_current_poison);
      set_proto_data(212, PROTO_DR_STAT_C, STAT_current_rad);
      set_proto_data(212, PROTO_DR_AMOUNT_1_A, 2);
      set_proto_data(212, PROTO_DR_AMOUNT_1_B, -5);
      set_proto_data(212, PROTO_DR_AMOUNT_1_C, -5);
     // the ashes of the forefather poison for 6, not 25
     set_proto_data(218, PROTO_DR_AMOUNT_1_A, 6);
     //meat jerky
     set_proto_data(PID_MEAT_JERKY, PROTO_DR_STAT_B, STAT_current_hp);
     set_proto_data(PID_MEAT_JERKY, PROTO_DR_AMOUNT_1_B, 1);
     set_proto_data(PID_MEAT_JERKY, PROTO_DR_AMOUNT_2_B, 0);
     set_proto_data(PID_MEAT_JERKY, PROTO_DR_AMOUNT_3_B, 0);
     //pirog max hp + ac instead of hr
      set_proto_data(343, PROTO_DR_STAT_A, STAT_max_hp);
      set_proto_data(343, PROTO_DR_STAT_B, STAT_current_hp);
      set_proto_data(343, PROTO_DR_STAT_C, STAT_ac);
      set_proto_data(343, PROTO_DR_AMOUNT_1_A, 4);
      set_proto_data(343, PROTO_DR_AMOUNT_1_B, 4);
      set_proto_data(343, PROTO_DR_AMOUNT_1_C, 3);
      set_proto_data(343, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(343, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(343, PROTO_DR_AMOUNT_2_C, -3);
     //mantis
     set_proto_data(419, PROTO_DR_STAT_A, STAT_current_hp);
     set_proto_data(419, PROTO_DR_STAT_B, STAT_crit_chance);
     set_proto_data(419, PROTO_DR_STAT_C, 0);
     set_proto_data(419, PROTO_DR_AMOUNT_1_A, 3);
     set_proto_data(419, PROTO_DR_AMOUNT_1_B, 1);
     set_proto_data(419, PROTO_DR_AMOUNT_1_C, 0);
     set_proto_data(419, PROTO_DR_DURATION_1, 15);
     set_proto_data(419, PROTO_DR_AMOUNT_2_A, 0);
     set_proto_data(419, PROTO_DR_AMOUNT_2_B, -1);
     set_proto_data(419, PROTO_DR_AMOUNT_2_C, 0);
     set_proto_data(419, PROTO_DR_DURATION_2, 0);
     set_proto_data(419, PROTO_DR_AMOUNT_3_A, 0);
     set_proto_data(419, PROTO_DR_AMOUNT_3_B, 0);
     set_proto_data(419, PROTO_DR_AMOUNT_3_C, 0);
     //rootbeer
     set_proto_data(423, PROTO_DR_AMOUNT_1_A, 3);
     //milk
     set_proto_data(440, PROTO_DR_STAT_B, STAT_current_hp);
     set_proto_data(440, PROTO_DR_STAT_C, STAT_current_poison);
     set_proto_data(440, PROTO_DR_AMOUNT_1_B, 2);
     set_proto_data(440, PROTO_DR_AMOUNT_1_C, -4);
     set_proto_data(440, PROTO_DR_AMOUNT_2_B, 0);
     set_proto_data(440, PROTO_DR_AMOUNT_2_C, 0);
     //burger
     set_proto_data(468, PROTO_DR_STAT_A, STAT_current_hp);
     set_proto_data(468, PROTO_DR_STAT_C, STAT_carry_amt);
     set_proto_data(468, PROTO_DR_AMOUNT_1_A, 2);
     set_proto_data(468, PROTO_DR_AMOUNT_1_C, 3);
     set_proto_data(468, PROTO_DR_DURATION_1, 930);
     set_proto_data(468, PROTO_DR_AMOUNT_2_A, 0);
     set_proto_data(468, PROTO_DR_AMOUNT_2_C, -3);
     set_proto_data(468, PROTO_DR_DURATION_2, 0);
     set_proto_data(468, PROTO_DR_AMOUNT_3_A, 0);
     set_proto_data(468, PROTO_DR_AMOUNT_3_B, 0);
     set_proto_data(468, PROTO_DR_AMOUNT_3_C, 0);
     //pizza max hp instead of hr
     set_proto_data(581, PROTO_DR_AMOUNT_1_A, 2);
     set_proto_data(581, PROTO_DR_STAT_B, STAT_max_hp);
     set_proto_data(581, PROTO_DR_STAT_C, STAT_melee_dmg);
     set_proto_data(581, PROTO_DR_AMOUNT_1_B, 2);
     set_proto_data(581, PROTO_DR_AMOUNT_2_B, -2);
     set_proto_data(581, PROTO_DR_AMOUNT_1_C, 1);
     set_proto_data(581, PROTO_DR_AMOUNT_2_C, -1);
     //cola heal hp instead of hr
     set_proto_data(583, PROTO_DR_STAT_A, STAT_current_hp);
     set_proto_data(583, PROTO_DR_AMOUNT_1_A, 3);
     set_proto_data(583, PROTO_DR_AMOUNT_2_A, 0);
     //îáåä êÎðÎâàíùèêà
     set_proto_data(672, PROTO_DR_STAT_A, STAT_max_hp);
     set_proto_data(672, PROTO_DR_STAT_B, STAT_carry_amt);
     set_proto_data(672, PROTO_DR_AMOUNT_1_A, 10);
     set_proto_data(672, PROTO_DR_AMOUNT_1_B, 15);
     set_proto_data(672, PROTO_DR_DURATION_1, 1440);
     set_proto_data(672, PROTO_DR_AMOUNT_2_A, -10);
     set_proto_data(672, PROTO_DR_AMOUNT_2_B, -15);
     //potroh heal hp instead of hr
     set_proto_data(708, PROTO_DR_STAT_A, STAT_current_hp);
     set_proto_data(708, PROTO_DR_AMOUNT_1_A, 4);
     set_proto_data(708, PROTO_DR_AMOUNT_2_A, 0);
     //drgn meat crit instead of hr
     set_proto_data(743, PROTO_DR_STAT_A, STAT_crit_chance);
     set_proto_data(743, PROTO_DR_STAT_B, STAT_current_hp);
     set_proto_data(743, PROTO_DR_AMOUNT_1_A, 2);
     set_proto_data(743, PROTO_DR_AMOUNT_1_B, 10);
     set_proto_data(743, PROTO_DR_AMOUNT_2_A, -2);
     set_proto_data(743, PROTO_DR_AMOUNT_2_B, 0);
     set_proto_data(743, PROTO_DR_AMOUNT_3_A, 0);
     set_proto_data(743, PROTO_DR_AMOUNT_3_B, 0);
   end
   // Sonora food edition
   if Sonora > 0 then begin
     // noodles heal
     //set_proto_data(63, PROTO_DR_AMOUNT_1_A, 4);
     // tele diner max hp instead of hr
     //set_proto_data(64, PROTO_DR_AMOUNT_1_A, 5);
      set_proto_data(64, PROTO_DR_STAT_A, STAT_current_hp);
      set_proto_data(64, PROTO_DR_STAT_B, STAT_max_hp);
      set_proto_data(64, PROTO_DR_STAT_C, -1);
      set_proto_data(64, PROTO_DR_AMOUNT_1_A, 10);
      set_proto_data(64, PROTO_DR_AMOUNT_1_B, 2);
      set_proto_data(64, PROTO_DR_AMOUNT_1_C, 0);
      set_proto_data(64, PROTO_DR_DURATION_1, 1440);
      set_proto_data(64, PROTO_DR_AMOUNT_2_A, 0);
      set_proto_data(64, PROTO_DR_AMOUNT_2_B, -2);
      set_proto_data(64, PROTO_DR_AMOUNT_2_C, 0);
      set_proto_data(64, PROTO_DR_DURATION_2, 0);
      set_proto_data(64, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(64, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(64, PROTO_DR_AMOUNT_3_C, 0);
      set_proto_data(64, PROTO_DR_ADDICT_CHANCE, 0);
      set_proto_data(64, PROTO_DR_ADDICT_PERK, 0);
      set_proto_data(64, PROTO_DR_ADDICT_DELAY, 0);

      //MRE
      set_proto_data(68, PROTO_DR_STAT_A, STAT_max_hp);
      set_proto_data(68, PROTO_DR_STAT_B, STAT_current_poison);
      set_proto_data(68, PROTO_DR_STAT_C, STAT_current_hp);
      set_proto_data(68, PROTO_DR_AMOUNT_1_A, 5);
      set_proto_data(68, PROTO_DR_AMOUNT_1_B, -10);
      set_proto_data(68, PROTO_DR_AMOUNT_1_C, 12);
      set_proto_data(68, PROTO_DR_DURATION_1, 2880);
      set_proto_data(68, PROTO_DR_AMOUNT_2_A, -5);
      set_proto_data(68, PROTO_DR_AMOUNT_2_B, 0);
      set_proto_data(68, PROTO_DR_AMOUNT_2_C, 0);
      set_proto_data(68, PROTO_DR_DURATION_2, 0);
      set_proto_data(68, PROTO_DR_AMOUNT_3_A, 0);
      set_proto_data(68, PROTO_DR_AMOUNT_3_B, 0);
      set_proto_data(68, PROTO_DR_AMOUNT_3_C, 0);
      set_proto_data(68, PROTO_DR_ADDICT_CHANCE, 0);
      set_proto_data(68, PROTO_DR_ADDICT_PERK, 0);
      set_proto_data(68, PROTO_DR_ADDICT_DELAY, 0);
     // chips heal
     //set_proto_data(71, PROTO_DR_AMOUNT_1_A, 4);
     // nuka
     //set_proto_data(106, PROTO_DR_AMOUNT_1_A, 5);
     //set_proto_data(106, PROTO_DR_AMOUNT_1_B, 1);
     // irradiated nuka
     //set_proto_data(107, PROTO_DR_AMOUNT_1_A, 5);
     //set_proto_data(107, PROTO_DR_AMOUNT_1_B, 1);
     // water
     //set_proto_data(108, PROTO_DR_AMOUNT_1_A, 5);
     //set_proto_data(108, PROTO_DR_AMOUNT_1_B, 1);
   end
  end
end