{1}{}{This item can only be used from the interface panel during combat.}
{2}{}{You heal the }
{3}{}{crippled right arm.}
{4}{}{crippled left arm.}
{5}{}{crippled right leg.}
{6}{}{crippled left leg.}
{7}{}{damaged eye.}
{8}{}{You look healthy already.}
{9}{}{%1% looks healthy already.}
{10}{}{%1% uses %2%.}
{11}{}{Failed to heal disabilities.}
{12}{}{You healed %1% hit points.}
{13}{}{You aren't skilled enough to use %1%.}
{14}{}{You failed to do any healing.}
{15}{}{The supplies in the %1% run out.}
{16}{}{}
{17}{}{}
{18}{}{That does nothing.}
{19}{}{It's dead, get over it.}
{20}{}{You can't heal the dead.}
{21}{}{You aren't skilled enough to heal crippling injuries.}
{22}{}{You aren't skilled enough to heal crippling injuries during combat.}
{23}{}{%1% is not suitable for healing crippling injuries.}
{24}{}{You receive %1% experience for the successful use of the Doctor skill.}
{25}{}{Your inept handling only made things worse.}
{26}{}{Due to your inept handling, %1% takes %2% damage.}

{80}{}{Incompatible Medical Tools Mods detected:}
{81}{}{EcCo and F2MMR}
{82}{}{YES: Use F2MMR (disable EcCo).}
{83}{}{  NO: Use EcCo (disable F2MMR).}
{84}{}{Game will exit. Restart the game.}

{310}{}{ It has supplies for %d/%d uses.}

{1001}{}{This tool can only be used from the interface panel during combat.}
{1002}{}{You repair the }
{1003}{}{damaged right manipulator.}
{1004}{}{damaged left manipulator.}
{1005}{}{damaged right locomotion system.}
{1006}{}{damaged left locomotion system.}
{1007}{}{damaged sensors.}
{1008}{}{You look fully operational.}
{1009}{}{%1% looks fully operational.}
{1010}{}{%1% uses the %2%.}
{1011}{}{You fail to repair the damage.}
{1012}{}{You restored %1% integrity.}
{1013}{}{You aren't skilled enough to use the %1%.}
{1014}{}{You fail to do any repairs.}
{1015}{}{%1%: supplies run out.}
{1018}{}{That does nothing.}
{1019}{}{It's beyond repair, get over it.}
{1020}{}{You can't repair what is destroyed.}
{1021}{}{You aren't skilled enough to repair damaged systems.}
{1022}{}{You aren't skilled enough to repair damaged systems during combat.}
{1023}{}{%1% is not suitable for repairing damaged systems.}
{1024}{}{You receive %1% experience for the successful use of your skills.}
{1025}{}{Due to your inept handling, you take %2% damage.}
{1026}{}{Due to your inept handling, %1% takes %2% damage.}
{1027}{}{%1% repairs itself.}
{1028}{}{%1% repairs %2%.}
{1310}{}{It has supplies for %d/%d uses.}