{1}{}{Regeneration} //Regeneration perk name
{2}{}{Toxicologist}
{3}{}{You are regenerating!}
{4}{}{You are lucky to have gained an incredible mutation! Your metabolism is so high that even severed limbs can grow back.}
{5}{}{Your knowledge of Radscorpion venom allows you to preserve it longer and use it more effectively, as well as fill all your injector ammo with it.}
{6}{}{Your right hand has healed.}
{7}{}{Your right leg has healed.}
{8}{}{Your left hand has healed.}
{9}{}{Your left leg has healed.}
{10}{}{Your eyesight has returned.}
{11}{}{Poisoned }
{12}{}{You have applied Radscorpion venom to your weapon. Each successful strike now poisons the target.}
{13}{}{%1% applies poison to the %2%.} //%1% = npc_name, %2% - weapon name
{14}{}{You apply poison to the %2%.}
{15}{}{You apply the last drops of poison to the %2% and discard the useless remains of the poison gland.}
{16}{}{Poison from the weapon starts dripping onto the ground. Applying even more poison to the %2% isn't possible.}
{17}{}{You apply the last drops of poison to the weapon %1% holds and discard the useless remnants of the poison gland.}
{18}{}{You failed to poison your target undetected.}
{19}{}{You heal %2% hit point.} //player if 1 hp
{20}{}{You heal %2% hit points.} //player if > than 1 hp
{21}{}{%1% regenerates %2% hit point.} //npc if 1 hp
{22}{}{%1% regenerates %2% hit points.} //npc if > than 1 hp
{23}{}{You take %2% damage from poison.}
{24}{}{%1% takes %2% damage from poison.}
{25}{}{%1% takes %2% damage from poison and dies.}
{26}{}{%1%: Poison level has reached a lethal value!}
{27}{}{You feel the aftereffects of poisoning.}
{28}{}{MechanicsMiniRework: To work correctly, you must activate the "AllowUnsafeScripting" parameter in "ddraw.ini".}
{29}{}{I don't think we know each other *that* well.}
{30}{}{Get it away from me!}
{31}{}{Hands off!}
{32}{}{Hey! Back off.}
{33}{}{%1% uses the %2%.}
{34}{}{%1% applies the last drops of poison to the %2% and discards the useless remains of the poison gland.} //%1% = NPC name, %2% = weapon name
{35}{}{ Poison from the weapon starts dripping onto the ground. You can't apply more poison to the %2%.}
{36}{}{Poison is already dripping from the weapon. You can't apply more poison to the %2%.}

{38}{}{Your body stops healing.}
{39}{}{Your body starts healing.}
{40}{}{Your poison level has reached a lethal value!}
{41}{}{You take %2% damage from poison and die.}

{75}{}{Incompatible Healing Drugs Mods detected:}
{76}{}{EcCo and F2MMR}
{77}{}{YES: Use F2MMR (disable EcCo).}
{78}{}{  NO: Use EcCo (disable F2MMR).}
{79}{}{Game will exit. Restart the game.}


{80}{}{Effects:}
{81}{}{SCORCHED}
{82}{}{Thermal Burn}
{83}{}{Your character has sustained a thermal burn. This reduces your health regeneration speed. The more severe the injury, the worse it is for your body, and the burns will require more time to heal.}
{84}{}{HEALING}

{100}{}{Your }
{101}{}{ has reached its maximum value.}
{102}{}{ has reached its maximum value.}

{1000}{}{MechanicsMiniRework: Requires sfall 4.4.4 or later.}
{1001}{}{MechanicsMiniRework: Requires sfall 5.0.8.5 or later.}


{2000}{}{Poison Mastery} //Poison mastery perk name old
{2001}{}{Envenomed } //Poison mastery perk name old