{1}{}{To use this item during combat, you must equip it.}
{2}{}{You heal the }
{3}{}{crippled right arm.}
{4}{}{crippled left arm.}
{5}{}{crippled right leg.}
{6}{}{crippled left leg.}
{7}{}{damaged eye.}
{8}{}{You look healthy already.}
{9}{}{%1% looks healthy already.}
{10}{}{%1% uses %2%.}
{11}{}{Failed to heal disabilities.}
{12}{}{You healed %1% hit points.}
{13}{}{You aren't skilled enough to use %1%.}
{14}{}{You failed to do any healing.}
{15}{}{The supplies in the %1% run out.}
{16}{}{}
{17}{}{}
{18}{}{That does nothing.}
{19}{}{It's dead, get over it.}
{20}{}{You can't heal the dead.}
{21}{}{You aren't skilled enough to heal crippling injuries.}
{22}{}{You aren't skilled enough to heal crippling injuries during combat.}
{23}{}{%1% is not suitable for healing crippling injuries.}
{24}{}{You receive %1% experience for the successful use of the Doctor skill.}
{25}{}{Due to your inept handling, you take %2% damage.}
{26}{}{Due to your inept handling, %1% takes %2% damage.}


{310}{}{ It has supplies for %d/%d uses.}