{1}{}{You cannot do that in combat.}
{2}{}{Only party members can read your books.} 
{3}{}{None of you learned anything new.} 
{4}{}{ learns nothing new.}
{5}{}{You learn nothing new.}
{6}{}{You learn something new.}
{7}{}{ learns something new.}
{8}{}{ read the book.}
{9}{}{ read the book out loud.}
{10}{}{You read the book out loud.}
{11}{}{You are not intelligent enough to learn anything new from this book.}
{12}{}{ is not intelligent enough to learn anything new from this book.}
{13}{}{+10% to Energy Weapon.}
{14}{}{ has learned some valuable tips on how to use energy weapons.}
{15}{}{Perfection.}
{16}{}{The book contains TONS of inside information on Fallout 2, more than enough to modify your friends for the better.}
{17}{}{You have improved your skills by reading this book.}
{18}{}{After reading the book, }
{19}{}{ now looks at the phenomenon of the game and the fate of mankind differently.}
{20}{}{ has already learned everything in this book.}
{21}{}{The book gave you a new perspective on the place of the game phenomenon in your life and the fate of humanity, which improved some of your skills.}
{22}{}{You learn the secrets of practical human and animal anatomy. This will help you with both healing and combat.}
{23}{}{ is not smart enough to read highly scientific literature.}
{24}{}{This monograph is for established medical professionals. }
{25}{}{ cannot understand anything about it.}
{26}{}{ does not have enough scientific knowledge to study this monograph.}
{27}{}{ learns nothing new about medical practice.}
{28}{}{ learns a lot about medical practice.}
{29}{}{ learns a lot about practical human and animal anatomy.}
{30}{}{You pay much closer attention to the smaller details when reading. Your skill points and their gain limit when reading books are increased by 50%.}
{31}{}{You pay much closer attention to the smaller details when reading. Your skill points gained from reading and the maximum number of skill books you can read have been increased by 50%.}
{802}{}{You learn new scientific knowledge.}
{803}{}{You learn new repair knowledge.}
{804}{}{You learn how best to treat various injuries.}
{805}{}{You learn a lot about the practical use of firearms.}
{806}{}{You gain new knowledge about survival in the wasteland.}
{807}{}{You learn how to plant and disarm traps better.}
{808}{}{You learn a lot about economics.}
{809}{}{You learn a lot about medicine and biology.}
{810}{}{You learn how to use energy weapons better.}
{811}{}{You gain new knowledge about stealth.}
{812}{}{You learn a lot about the practical application of hand-to-hand combat.}
{813}{}{You gain new knowledge about lock design and intricacies.}
{814}{}{You gain new knowledge about traps and stealth.}
{902}{}{ learns new scientific information.}
{903}{}{ learns a lot about repairing broken electronics.}
{904}{}{ learns new ways to heal injuries.}
{905}{}{ learns how to handle guns better.}
{906}{}{ learns a lot about survival in the wasteland.}
{907}{}{ learns how to plant and disarm traps better.}
{908}{}{ learns a lot about economics.}
{909}{}{ learns a lot about medicine and biology.}
{910}{}{ learns a lot about how to use energy weapons.}
{911}{}{ learns to move more imperceptibly.}
{912}{}{ learns about the practical application of hand-to-hand combat techniques.}
{913}{}{ gains new knowledge about the design and intricacies of locks.}
{914}{}{ gains new knowledge about traps and stealth.}