{1}{}{You cannot do that in combat.}
{2}{}{Only party members can read your books.} 
{3}{}{None of you learned anything new.} 
{4}{}{ learns nothing new.}
{5}{}{You learn nothing new.}
{6}{}{You learn something new.}
{7}{}{ learns something new.}
{8}{}{ read the book.}
{9}{}{ read the book out loud.}
{10}{}{You read the book out loud.}
{11}{}{You are not intelligent enough to learn anything new from this book.}
{12}{}{ is not intelligent enough to learn anything new from this book.}
{13}{}{+10% to Energy Weapon.}
{14}{}{ has learned some valuable tips on how to use energy weapons.}
{15}{}{Perfection.}
{16}{}{The book contains TONS of inside information on Fallout 2, more than enough to modify your friends for the better.}
{18}{}{After reading the book, }
{19}{}{ now looks at the phenomenon of the game and the fate of mankind differently.}
{20}{}{ has already learned everything in this book.}
{21}{}{The book gave you a new perspective on the place of the game phenomenon in your life and the fate of humanity, which improved some of your skills..}
{22}{}{You learn the secrets of practical human and animal anatomy. This will help you with both healing and combat.}
{23}{}{  is not smart enough to read highly scientific literature.}
{24}{}{This monograph is for established medical professionals. }
{25}{}{ cannot understand anything about it.}
{26}{}{ does not have enough scientific knowledge to study this monograph.}
{27}{}{ learns nothing new about medical practice.}
{28}{}{ learns a lot about medical practice.}
{29}{}{ learns a lot about practical human and animal anatomy.}
{807}{}{You learn how to plant and disarm traps better.}
{808}{}{You learn a lot about economics.}
{809}{}{You learn a lot about medicine and biology.}
{902}{}{ learns new science information.}
{903}{}{ learns a lot about repairing broken electronics.}
{904}{}{ learns new ways to heal injuries.}
{905}{}{ learns how to handle your guns better.}
{906}{}{ learns a lot about wilderness survival.}
{907}{}{ learns how to plant and disarm traps better.}
{908}{}{ learns a lot about economics.}
{909}{}{ learns a lot about medicine and biology.}
