{1}{}{Regeneration} //Regeneration perk name
{2}{}{Poison Mastery}
{3}{}{You are regenerating!}
{4}{}{You are lucky to get an incredible mutation! Your metabolism is so high that even severed limbs can grow back.}
{5}{}{Your knowledge of Radscorpion venom allows you to preserve it longer and use it more effectively, and also fill all your injector ammo with it.}
{6}{}{Your right hand healed.}
{7}{}{Your right leg healed.}
{8}{}{Your left hand healed.}
{9}{}{Your left leg healed.}
{10}{}{Your eyesight has returned.}
{11}{}{Envenomed }
{12}{}{You applied the venom of a radscorpion to a weapon, now every successful attack poisons the enemy.}
{13}{}{%1% applies poison to %2%.} //%1% = npc_name, %2% - weapon name
{14}{}{You apply poison to %2%.}
{15}{}{You apply the last drops of poison to your weapon and discard the useless remnants of the poison gland.}
{16}{}{Poison from the weapon starts to drip on the ground, apply even more poison to the %2% isn't possible.}
{17}{}{You apply the last drops of poison to the weapon %1% holds, and discard the useless remnants of the poison gland.}
{18}{}{You failed to poison your target undetected.}
{19}{}{You heal %2% hit point.} //player if 1 hp
{20}{}{You heal %2% hit points.} //player if > than 1 hp
{21}{}{%1% regenerates %2% hit point.} //npc if 1 hp
{22}{}{%1% regenerates %2% hit points.} //npc if > than 1 hp
{23}{}{You take %2% damage from poison.}
{24}{}{%1% takes %2% damage from poison.}
{25}{}{%1% takes %2% damage from poison and dies.}
{26}{}{%1%: Poison level has reached a lethal value!}
{27}{}{You feel the aftereffect of poisoning.}
{28}{}{Regeneration: To enable alternative stimpack mechanics in ddraw.ini the "AllowUnsafeScripting" option must be enabled.}
{29}{}{I don't think we know each other *that* well.}
{30}{}{Get it away from me!}
{31}{}{Hands off!}
{32}{}{Hey! Back off.}