{1}{}{With your skills, you can never steal the %1%.}
{2}{}{With your skills, you can never plant the %1%.}
{3}{}{ You need at least %1% steal skill to attempt this.} // failed stealing attempt
{4}{}{ You need at least %1% steal skill to attempt this.} // failed planting attempt
{5}{}{You cannot pickpocket with both hands broken.}
{6}{}{Your pickpocketing attempt was noticed by the target's allies.}
{7}{}{?} // weak NPC response on failed pickpocket
{8}{}{!} // weak NPC response on failed pickpocket
{9}{}{You are not skilled enough to peek into your target's pocket.} // response on failed pickpocket
{10}{}{I don't have anything to steal, you idiot}
{11}{}{I don't think we know each other *that* well}
{12}{}{Get your hands off of me}
{13}{}{Hands off!}
{14}{}{Hey! Back off}
{15}{}{!}
{16}{}{That's mine, hands off!}
{17}{}{You're caught stealing the %1%.}
{18}{}{You steal the %1%.}
{19}{}{You're caught planting the %1%.}
{20}{}{You plant the %1%.}
{21}{}{ returns what was stolen.}
{22}{}{You were able to hide some items. }
{23}{}{ only returns part of what was stolen.}
{24}{}{You skillfully hide everything you stole. }
{25}{}{ returns nothing of what was stolen.}
{26}{}{You were hit in the head for }
{27}{}{ hit point.} 
{28}{}{ hit points.} 
{29}{}{You were hit for no damage.} 
{30}{}{ was hit for } 
{31}{}{ puts something on the floor.} 
{32}{}{ pretends to put something on the floor.} 
{33}{}{ returns the stolen goods and takes part of your money as compensation.} 
{34}{}{ takes } 
{35}{}{ takes a portion of your cash as compensation.} 
{36}{}{ finds nothing useful in your bag.} 
{37}{}{ takes back the stolen goods.} 
{38}{}{ returns the stolen goods and takes } 
{39}{}{ from you as compensation.} 
{40}{}{ gives you his valuables!} 
{41}{}{ gives you her valuables!} 
{42}{}{You have been caught stealing. Rumors about this will quickly spread among the locals.}
{43}{}{To hell with you, I won't run anymore!} 
{44}{}{Screw you, I'm done running!} 
{45}{}{You can go to hell, I'm not running anymore!} 
{46}{}{FUCK IT!} 
{47}{}{Phew, it seems this moron finally has left me alone} 
{48}{}{Thank goodness, it appears this imbecile has decided to give me a break} 
{49}{}{I wonder if this asshole has already stopped stalking me?} 
{50}{}{Is that jerk still lingering around me, or can I finally go back?} 
{51}{}{Can you please return it? I don't have anything else...} 
{52}{}{Please give it back, this is all I have...} 
{53}{}{I'm begging you, this is all I've got...} 
{54}{}{You have no idea how much this item means to me, please give it back!} 
{55}{}{If you stole something from me, you better give it back!} 
{56}{}{You better be ready to give back what you took from me} 
{57}{}{Give back what you stole, I'm serious!} 
{58}{}{I won't take it lightly if you don't give it back} 
{59}{}{Did you steal something from me?! No, it seems not...} 
{60}{}{Did you borrow my stuff without asking? No, it looks like you didn't} 
{61}{}{Did you take something from me? No, apparently not...} 
{62}{}{Did you steal something from me?! No, it seems not...} 
{63}{}{I'll pretend that nothing happened! Just don't touch me!} 
{64}{}{What? I didn't see anything!}
{65}{}{I will not tell anyone! But please don't do that again!}
{66}{}{It seems like I have a hole in my pocket, I've lost my things again...} 
{67}{}{Why does bad luck always find me? I can never hold onto my belongings} 
{68}{}{I swear I have the memory of a goldfish. I lose my things all the time!} 
{69}{}{Oh! How did this end up in my pocket?}
{70}{}{Well, isn't this a surprise! I have no idea how this ended up in my pocket!}
{71}{}{Whoops! I just discovered this in my pocket. How did it get there?} 
{72}{}{And why did you slip this to me?} 
{73}{}{ hit point and dies instantly.}
{74}{}{ hit points and dies instantly.}
{75}{}{I ain't afraid of no ghosts!}
{76}{}{The last person who witnessed your failed pickpocket attempt is dead. Now no one will know about your misdeed.}
{77}{}{The witnesses to your failed pickpocket attempt are no longer alive. Now your secret rests with them.}
{78}{}{The last person who saw your failed attempt to steal is dead. Now no one will know about your crime.}
{79}{}{The witnesses to your failed theft are no longer among the living. Now your secret rests with them.}


{94}{}{You need at least %1% steal skill to attempt to steal the %2%.} // failed stealing attempt
{95}{}{You need at least %1% steal skill to attempt to plant the %2%.} // failed planting attempt																							 
{96}{}{You were critically hit for }
{97}{}{You were critically hit in the head for }
{98}{}{You fail to steal the }
{99}{}{You fail to plant the } 


##child human attack
{230}{}{Take this!}
{231}{}{You shouldn't have started this!}
{232}{}{You asked for this!}
{233}{}{How do you like this?}
{234}{}{Take that!}

##child human flee
{240}{}{Mercy!}
{241}{}{Somebody help me!}
{242}{}{Please stop!}
{243}{}{Help!}
{244}{}{Aaaaahhhh!}
{245}{}{BAD PERSON! GET AWAY!}
{246}{}{GET AWAY FROM ME!}



##child common response
{250}{}{I don't have anyone else to rely on. Taking my things is really mean}
{251}{}{YOU ARE A BAD PERSON!}
{252}{}{I'm just a kid. Taking my stuff is really unfair!}
{253}{}{"Sad crying sounds"}
{254}{}{Aren't you ashamed of stealing from a child?}
{255}{}{OH NO! IT'S A GHOST!}

##child rare response
{260}{}{Hey, that's mine. I'm taking it back}
{261}{}{Give my stuff back!}
{262}{}{Think you can just take whatever you want? NO!!! IT'S MINE! GIVE IT BACK!}
{263}{}{I may be scared, but I won't let you bully me. Give my stuff back, now!}
{264}{}{I may be small, but I'm not afraid to stand up for myself. Hand over my belongings!}
{265}{}{GIMME BACK MY STUFF!!!}
{266}{}{Give it back!}
{267}{}{I ain't afraid of no ghosts!}

##pls dont hurt me
{270}{}{Please don't kill me! Take this, I don’t need this anymore!}
{271}{}{Don't hurt me! Don't hurt me! Here, take it!}
{272}{}{I'll give you everything, just please don't hurt me!}
{273}{}{I don't want any trouble! Take my belongings and let me be!}
{274}{}{Here, take everything I've got, just leave me alone!}
{275}{}{Here, just take it! I don't want any trouble, I just want to get out of here!}
{276}{}{Please, I have a family, don't harm me! Take what you want!}
{277}{}{Take this, I don't need it as much as my life!}

##child human name calling
{290}{}{Fart Knocker!}
{291}{}{You're a poop!}
{292}{}{You are a turd!}
{293}{}{Poopy-head!}
{294}{}{You're a poop-eater!}


##Tough human irritated aggressive
{100}{}{}
{101}{}{}
{102}{}{}
{103}{}{}
{104}{}{}

##Tough human irritated aggressive
{110}{}{Try reachin' into my pocket, and I'll wreck ya!}
{111}{}{You try that again, and I'll smash ya into goo!}
{112}{}{Try that again and I'll rend you limb from limb!}
{113}{}{Back off, or I'll squish you like a bug!}
{114}{}{I'll rip you apart if you try to steal from me!}


##Tough human combat warning
{120}{}{You leave here or I'll rip your guts out!}
{121}{}{I'm giving you 5 seconds to get the fuck out of here, or I'll rip you head off and make you watch me crap down throat!}
{122}{}{You picked the wrong pocket, fool! Get lost RIGHT NOW or fucking kill you!}
{123}{}{Countdown's on, scum! 5 seconds 'til I unleash hell upon ya!}
{124}{}{You got a death wish, huh?! Well, stick around for 5 more seconds and I'll be more than happy to grant it!}

##Tough human attack
{130}{}{It's too late to run!}
{131}{}{It is you again? Prepare to meet your end!}
{132}{}{This is what we do to vermin!}
{133}{}{Troublemaking scum!}
{134}{}{You asked for this!}
{135}{}{You had a chance to get away. Now you're fucked!}
{136}{}{Your guts sure are going to look pretty on the ground!}
{137}{}{It is you again?! Die fucker!}

##Tough human flee
{140}{}{This ain't worth it!}
{141}{}{I ain't dyin' for this!}
{142}{}{Better to live again to fight another day}
{143}{}{Crap, time to scram}
{144}{}{I'm bad, but you're the baddest}


##unaiming normal
{150}{}{Now get lost}
{151}{}{Now fuck off!}
{152}{}{Good. I forgive you this time}
{153}{}{Thank you for your cooperation. Now piss off!}
{154}{}{You've got some nerve stealing from me. Lucky for you, I haven't decided to introduce my bullets to your skull... yet}

##aiming
{160}{}{Step back! Put everything you stole on the floor!}
{161}{}{I suggest you slowly take two steps back and put what you took on the floor, and maybe I'll consider sparing your sorry ass}
{162}{}{Step away from me and drop what you took, or else!}
{163}{}{Take a step back! Put down what you stole, and maybe I'll let you walk away}
{164}{}{Step back! Give back my belongings or face my gun!}

##unaiming death threat
{170}{}{I'm giving you time to get outta here before I blow your stupid head off!}
{171}{}{You've got two options: leave right now or become target practice for my trigger finger}
{172}{}{I suggest you to leave, unless you're feeling particularly fond of lead}
{173}{}{Get outta my sight before I change my mind and decide to paint this place with your blood}
{174}{}{This is your one chance to make things right. Leave now and we might just forget this ever happened}


##Tough human non combat attack
{180}{}{Are you fucking kidding me?}
{181}{}{I'm gonna roll you like dice}
{182}{}{Let me show you what we do with garbage around here...}
{183}{}{Gonna beat you like a dog...}
{184}{}{We don't like thieves here!}
{185}{}{Are you fucking kidding me!?}
{186}{}{I'm gonna beat you up, fucker!}

##Tough human name calling
{190}{}{Now leave}
{191}{}{You fucker!}
{192}{}{Go away!}
{193}{}{Fucking thief...}
{194}{}{FUCK YOU!}
{195}{}{Stupid prick!}



##supermutant irritated floats
{300}{}{Hands off, human! No touchin' my stuff}
{301}{}{Argggggghhhh}
{302}{}{Back off}
{303}{}{Rrrgggg}
{304}{}{Back off before I break you, weakling}

##supermutant irritated aggressive floats
{310}{}{Try reachin' into my pocket, and I'll wreck ya!}
{311}{}{You try that again, and I'll smash ya into goo!}
{312}{}{Try that again and I'll rend you limb from limb!}
{313}{}{Back off, or I'll squish you like a bug!}
{314}{}{I'll rip you apart if you try to steal from me!}

##supermutant combat warning floats
{320}{}{I'll give ya 5 seconds to scram, then I'll squash ya like a radroach!}
{321}{}{You leave here or I rip you head off and make you watch me crap down throat!}
{322}{}{You're testing my patience, human. Leave NOW!}
{323}{}{Countdown's on, chump! 5 seconds 'til I unleash hell upon ya!}
{324}{}{You got a death wish, huh?! Well, stick around for 5 more seconds and I'll be more than happy to grant it!}

##supermutant attack floats
{330}{}{It is you again!? DIE, HUMAN!!!}
{331}{}{I tried bein' reasonable, but now it's time for some big mutant justice!}
{332}{}{Prepare to meet your end!}
{333}{}{You will suffer, suffer great!!}
{334}{}{Die Human Fool!}

##supermutant flee floats
{340}{}{You ain't heard the last of me!}
{341}{}{You will not kill me!}
{342}{}{I will be back!}
{343}{}{My friends get you for me!}
{344}{}{You pay for this -- later!}

##supermutant non combat attack
{380}{}{ME SMASH PUNY HUMAN!}
{381}{}{Suffer, human!}
{382}{}{Let me show you what we do with thieves around here...}
{383}{}{Gonna beat you like a dog...}
{384}{}{We don't like thieves here!}
{385}{}{Dipshit, you just earned yourself a ticket to a world of hurt}
{386}{}{Who is stupid enough to anger me?}



##robot irritated floats
{1000}{}{Unauthorized access detected. Cease your attempts immediately.}
{1001}{}{Intruder alert! Hands off my storage compartment!}
{1002}{}{Access denied. Unauthorized personnel attempting breach.}
{1003}{}{Please refrain from attempting to access my internal components.}
{1004}{}{I am programmed to protect my integrity. Cease your actions.}

##robot irritated aggressive floats
{1010}{}{Warning: Cease your meddling or face the full force of my defenses.}
{1011}{}{Access denied. Disregarding this final warning will trigger defensive countermeasures.}
{1012}{}{Final warning issued. Continuing unauthorized access will initiate combat protocols.}
{1013}{}{Last chance, meatbag! Cease your intrusion or prepare for termination!}
{1014}{}{Unauthorized breach detected. This is your last opportunity to retreat.}

##robot combat warning floats
{1020}{}{Attention, intruder. You have five seconds to vacate my field of view or face imminent termination.}
{1021}{}{Warning: You have five seconds to retreat from my sight before I initiate elimination protocols.}
{1022}{}{Intruder alert. You have 5 seconds to retreat before I engage my termination protocol.}
{1023}{}{Countdown initiated. 5 seconds remain until I initiate your eradication. Depart immediately.}
{1024}{}{Intruder detected. Leave now or become the target of my termination sequence.}

##robot attack floats
{1030}{}{Warning ignored. Combat mode activated.}
{1031}{}{Warning disregarded. Commencing termination procedures.}
{1032}{}{Initiating elimination sequence. Resistance is futile.}
{1033}{}{Hostile actions confirmed. Initiating eradication sequence.}
{1034}{}{Recklessness noted. Commencing elimination process.}

##robot flee floats
{1040}{}{Retreat option initiated}
{1041}{}{Tactical plan: retreat}
{1042}{}{Combat effective minimal. Retreat advised}
{1043}{}{Tactical analysis complete. Retreat recommended.}
{1044}{}{Retreat sequence initiated}