{1}{}{%1% was hit for %2% hit points.}
{2}{}{%1% was hit for %2% hit points}
{3}{}{%1% was critically hit for %2% hit points.}
{4}{}{%1% was critically hit for %2% hit points}
{5}{}{ and fell to the ground.}
{6}{}{ and fell to the ground in pain.}
{7}{}{ with no armor defenses and fell to the ground in pain.}
{8}{}{. The impact knocks your target down.}
{9}{}{. A hit to a vital organ sends the opponent to a knockout..}
{10}{}{ and dies.}
{11}{}{ and passes away.}
{12}{}{ and was killed.}
{13}{}{ and ceases to exist.}
{14}{}{ and dies instantly.}
{15}{}{ and instantly stops living.}
{16}{}{%1% doesn't take damage.}
{17}{}{You receive }
{18}{}{ experience points.}
{19}{}{%1% was hit for 1 hit point.}
{20}{}{%1% was hit for 1 hit point}
{21}{}{%1% was critically hit for 1 hit point.}
{22}{}{%1% was critically hit for 1 hit points}

# part copied from the original fallout
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first %s will be replaced by the value of line 506, which
#          should be the language's equivalent to 2nd person male singular,
#          which is "You" in English. The first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 509
#          where the second %s is the name of another creature
{506}{}{You}
{509}{}{Oops! %s were hit instead of %s!}
{511}{}{%s were critically hit in %s for %d hit points}
{512}{}{%s were hit in %s for %d hit points}
{513}{}{%s were hit for %d hit points}
{514}{}{%s critically missed}
{515}{}{%s missed}
{520}{}{%s were critically hit for %d hit points}
{521}{}{%s were critically hit in %s for 1 hit point}
{522}{}{%s were hit in %s for 1 hit point}
{523}{}{%s were hit for 1 hit point}
{524}{}{%s were critically hit for 1 hit point}
{525}{}{%s were critically hit in %s for no damage}
{526}{}{%s were hit in %s for no damage}
{527}{}{%s were hit for no damage}
{528}{}{%s were critically hit for no damage}
{533}{}{%s critically missed and took 1 hit point}
{534}{}{%s critically missed and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first %s will be replaced by the value of line 556, which
#          should be the language's equivalent to 2nd person female singular,
#          which is "You" in English. The first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 559
#          where the second %s is the name of another creature
{556}{}{You}
{559}{}{Oops! %s were hit instead of %s!}
{561}{}{%s were critically hit in %s for %d hit points}
{562}{}{%s were hit in %s for %d hit points}
{563}{}{%s were hit for %d hit points}
{564}{}{%s critically missed}
{565}{}{%s missed}
{570}{}{%s were critically hit for %d hit points}
{571}{}{%s were critically hit in %s for 1 hit point}
{572}{}{%s were hit in %s for 1 hit point}
{573}{}{%s were hit for 1 hit point}
{574}{}{%s were critically hit for 1 hit point}
{575}{}{%s were critically hit in %s for no damage}
{576}{}{%s were hit in %s for no damage}
{577}{}{%s were hit for no damage}
{578}{}{%s were critically hit for no damage}
{583}{}{%s critically missed and took 1 hit point}
{584}{}{%s critically missed and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first %s is the name of the male creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 609
#          where the second %s is the name of another creature
#
{608}{}{Oops! %s was hit instead of you!}
{609}{}{Oops! %s was hit instead of %s!}
{611}{}{%s was critically hit in %s for %d hit points}
{612}{}{%s was hit in %s for %d hit points}
{613}{}{%s was hit for %d hit points}
{614}{}{%s critically missed}
{615}{}{%s missed}
{620}{}{%s was critically hit for %d hit points}
{621}{}{%s was critically hit in %s for 1 hit point}
{622}{}{%s was hit in %s for 1 hit point}
{623}{}{%s was hit for 1 hit point}
{624}{}{%s was critically hit for 1 hit point}
{625}{}{%s was critically hit in %s for no damage}
{626}{}{%s was hit in %s for no damage}
{627}{}{%s was hit for no damage}
{628}{}{%s was critically hit for no damage}
{633}{}{%s critically missed and took 1 hit point}
{634}{}{%s critically missed and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first %s is the name of the female creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 709
#          where the second %s is the name of another creature
#
{708}{}{Oops! %s was hit instead of you!}
{709}{}{Oops! %s was hit instead of %s!}
{711}{}{%s was critically hit in %s for %d hit points}
{712}{}{%s was hit in %s for %d hit points}
{713}{}{%s was hit for %d hit points}
{714}{}{%s critically missed}
{715}{}{%s missed}
{720}{}{%s was critically hit for %d hit points}
{721}{}{%s was critically hit in %s for 1 hit point}
{722}{}{%s was hit in %s for 1 hit point}
{723}{}{%s was hit for 1 hit point}
{724}{}{%s was critically hit for 1 hit point}
{725}{}{%s was critically hit in %s for no damage}
{726}{}{%s was hit in %s for no damage}
{727}{}{%s was hit for no damage}
{728}{}{%s was critically hit for no damage}
{733}{}{%s critically missed and took 1 hit point}
{734}{}{%s critically missed and took %d hit points}