{1}{}{With your skills you can never steal %1%.}
{2}{}{With your skills you can never plant %1%.}
{3}{}{ You need at least %1% steal skill to do it.} // failed stealing attempt
{4}{}{ You need at least %1% steal skill to do it.} // failed planting attempt
{5}{}{You cannot pickpocket with both hands broken.}
{6}{}{Your pickpocketing attempt was noticed by target's allies.}
{7}{}{?} // weak NPC response on failed pickpocket
{8}{}{!} // weak NPC response on failed pickpocket
{9}{}{You are not skilled enough to peek into your target's pocket.} // response on failed pickpocket