{1}{}{%1% was hit for %2% hit points.}
{2}{}{%1% was hit for %2% hit points}
{3}{}{%1% was critically hit for %2% hit points.}
{4}{}{%1% was critically hit for %2% hit points}
{5}{}{ and fell to the ground.}
{6}{}{ and fell to the ground in pain.}
{7}{}{ with no armor defenses and fell to the ground in pain.}
{8}{}{. The impact knocks your target down.}
{9}{}{. The attack to a vital organs knocks the loser over.}
{10}{}{ and dies.}
{11}{}{ and passes away.}
{12}{}{ and finaly gave up the ghost.}
{13}{}{ and ceases to exist.}
{14}{}{ and dies instantly.}
{15}{}{ and instantly stops living.}
{16}{}{%1% doesn't take damage.}
{17}{}{You receive }
{18}{}{ experience points.}
{19}{}{%1% was hit for 1 hit point.}
{20}{}{%1% was hit for 1 hit point}
{21}{}{%1% was critically hit for 1 hit point.}
{22}{}{%1% was critically hit for 1 hit points}