{1}{}{Traits updated. }
{2}{}{Restart the game!}


#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Fast Metabolism}
{101}{}{Bruiser}
{102}{}{Small Frame}
{103}{}{One Hander}
{104}{}{Finesse}
{105}{}{Kamikaze}
{106}{}{Heavy Handed}
{107}{}{Fast Shot}
{108}{}{Bloody Mess}
{109}{}{Jinxed}
{110}{}{Good Natured}
{111}{}{Chem Reliant}
{112}{}{Chem Resistant}
{113}{}{Sex Appeal}
{114}{}{Skilled}
{115}{}{Gifted}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{Your metabolic rate is twice normal. This means you are less resistant to radiation and poison, and chems only affect you half as long as normal. However, your body heals faster, and chems are  one-third more effective at healing and detoxifying.}
{201}{}{A little slower, but a little bigger. You may not hit as often, but they will feel it when you do! Your total action points are lowered, but your Strength is increased, and each close combat and thrown attack can deal up to double the damage.}
{202}{}{You are not quite as big as other people, but that never slowed you down. You can't carry as much, but you are more agile, stealthier, and harder to hit.}
{203}{}{One of your hands is very dominant.        You excel with single-handed attacks, even if both arms are crippled. One-handed critical hits are slightly more devastating, but two-handed weapons cause a problem.}
{204}{}{Your attacks show a lot of finesse.       You don't do as much damage, but you cause more critical hits. Additionally, your burst and explosive attacks can penetrate armor and knock down opponents.}
{205}{}{By not paying attention to any threats, you can act a lot faster. This sets natural AC to zero and reduces chance to hit with each step, but increases sequence and reduces AP cost of attacks after movement.}
{206}{}{You swing harder, not better. Your attacks are very brutal, but lack finesse. You rarely cause a good critical hit, but you always do more melee damage, and you have a chance to knock down your target with each close combat and thrown attack.}
{207}{}{You don't have time to aim for a targeted attack, because you attack faster than normal people. It costs you one less action point for guns and thrown weapons.}
{208}{}{By some strange twist of fate, critical failures become more dangerous, and everyone dies in the worst way possible. Yet, there's a bright side - each life you extinguish restores some of your action points.}
{209}{}{The good thing is that everyone around you has more misses and critical failures in combat. The bad thing is, so do you!}
{210}{}{You studied less-combative skills as you were growing up. Your combat skills start at a lower level, but First Aid, Doctor, Speech and Barter are substantially improved.}
{211}{}{Your chance to be addicted by chem use is twice normal, and most of their effects on you are increased by 50%. However, you recover faster from withdrawal effects.}
{212}{}{Chems no longer cause negative side effects or addiction, allowing for higher doses. However, their duration and potency are reduced by half, with the exception of their healing and detoxifying effects.}
{213}{}{You've got the "right" stuff. Members of the opposite sex are attracted to you, but those of the same sex tend to become quite jealous.}
{214}{}{Since you spent more time improving your skills than a normal person, you gain an increased maximum hit chance and 5 additional skill points per level. Stronger perks become available earlier, but you gain a perk every four levels.}
{215}{}{You have more innate abilities than most, so you have not spent as much time honing your skills. Your primary statistics are each +1, but you lose -10% on all skills to start, and receive 5 less skill points per level.}
#
#   SONORA
#
{1008}{}{Hot Blood}
{2008}{}{By some strange twist of fate, critical failures become more dangerous, and everyone dies in the worst way possible. But at least you know Spanish, and each kill restores some of your AP.}