; Allows to reassign books to different object PIDs, text messages.
; Maximum 30 books are allowed (25 if overrideVanilla is 0)
; This file is for Fallout: Nevada with F2MechanicsMiniRework Skill2 support

[main]
; total number of books in this file
count=8

; set to 1 to override all vanilla books, so you will have to define ALL books in this file;
; otherwise only new books are defined here
overrideVanilla=0

; ============================================
; FALLOUT: NEVADA BOOKS
; ============================================

[1]
; Big Book of Science
PID=73
TextID=802
; Science 
Skill=12

[2]
; Dean's Electronics
PID=76
TextID=803
; Repair
Skill=13

[3]
; First Aid Book
PID=80
TextID=804
; First Aid
Skill=6
; Doctor
Skill2=7

[4]
; Guns and Bullets
PID=102
TextID=805
; Small Guns 
Skill=0
; Big Guns
Skill2=1

[5]
; Scout Handbook
PID=86
TextID=806
; Outdoorsman 
Skill=17
; Sneak
Skill2=8

[6]
; Super-science magazine (Energy Weapons)
PID=331
TextID=810
; Energy Weapons
Skill=2
; Repair
Skill2=13

[7]
; "Trade" magazine (Barter)
PID=523
TextID=808
; Barter
Skill=15
; Speech
Skill2=14

[8]
; Saboteur's Casebook (Traps)
PID=444
TextID=807
; Traps
Skill=11
; Throwing
Skill2=5